### ISSUE TITLE
macOS menu bar icon with extra text?

### ISSUE THREAD

**Issue by brian163** [yakyak/yakyak#1000]
Looking around these discussion threads, I don't know if this started with the "re-released" version of 1.5.2 for macOS because I went straight to the "v1.5.3-beta-rolling" version. While that corrected the connection issue for me,  the menu bar icon is now the Yak Yak "Y" icon followed by the text "YakYak - Hangouts Client". 

That is taking up far too much limited (and precious ;-) ) menu bar space and I could not figure out any way to toggle the text off (assuming it was something I perhaps toggled on).

I suspect this was a change baked into the beta and would like to ask it be changed back to just an icon PLEASE.

**Comment by brian163** [comment]
(Side note) As I reported back to a different thread, I just wanted to clarify that the release did not permanently correct the connection issue.

**Comment by stoppablemurph** [comment]
Congrats on making issue number 1000! :D

**Comment by averissimo** [comment]
duplicate of #990 hopefully the fix will be available in v1.5.4 *(beta-rolling first)*
