### ISSUE TITLE
2-Factor Authentication

### ISSUE THREAD

**Issue by drewpayment** [yakyak/yakyak#1007]
Cannot login with Google Titan Key, just stays at "Connecting...". I'm not sure exactly why it can't get go through this process since it seems to run Chromium under the hood? 

Maybe I'm just doing something wrong? I've uninstalled, reinstalled, wiped out the app data. 

macOS Mojave 10.14.1

**Comment by delta-one** [comment]
Are you sure it is because of the Google Titan Key ? It seems like run've run into this issue: https://github.com/yakyak/yakyak/issues/999

The solution is decribed there (https://github.com/yakyak/yakyak/issues/999#issuecomment-434873957):
```
Please go to the following file in the YakYak directory

yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/init.js

And make the change:

ds:20 to ds:19

Under BOTH the self_entity and conv_states.
```

**Comment by drewpayment** [comment]
I uninstalled and reinstalled this morning before posting the issue.

**Comment by averissimo** [comment]
The new version is 1hour old.

stable v1.5.3 (not the beta-rolling release)

**Comment by drewpayment** [comment]
Sorry, I missed that. I was able to install 1.5.3 and now it is working! :)
