### ISSUE TITLE
Feature Requst: Set urgency hints in Linux when there are unread messages

### ISSUE THREAD

**Issue by jcbahr** [yakyak/yakyak#101]
I'm using dwm and it would be nice to have yakyak set the urgency hint flag so that I can see that I have unread messages just by looking at my statusbar.

**Comment by yermulnik** [comment]
+1

**Comment by algesten** [comment]
i don't know what urgency hints are. but PR:s are welcome.

**Comment by alextpedro** [comment]
Urgency hints tell the window manager that the window requires the user's attention. Think the hangouts bar going green when there's a new message.

**Comment by ctcpip** [comment]
+1

**Comment by ctcpip** [comment]
I really want to address this, and am happy to help, but I'm just not sure how to go about it.  The [notification spec](https://developer.gnome.org/notification-spec/) has a property for urgency, but setting this in the notification code in yakyak simply breaks notifications (at least in regard to libnotify functionality).  I'm open to ideas!

**Comment by yermulnik** [comment]
I had tried v1.3.0 yesterday and moved back to https://github.com/arnriu/yakyak

**Comment by ctcpip** [comment]
https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.2.4

and...

https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-hints.html

This is lower level functionality.  Not sure how to accomplish this.

**Comment by ctcpip** [comment]
Electron uses libnotify on Linux, so it seems there is no straightforward way to do this.  This may only be possible by modifying Electron.  It might be a good idea to submit a feature request to that project.

http://electron.atom.io/docs/tutorial/desktop-environment-integration/

**Comment by ctcpip** [comment]
Well, some good news is that Electron uses GTK.  And GTK has the method gtk_window_set_urgency_hint() which I believe should do what we want.  I'm just poking around right now though... been a long time since I wrote any C++

**Comment by davibe** [comment]
Mayve tou should fill in a feature request to electron

**Comment by ctcpip** [comment]
Got it.  Electron has method win.flashFrame(flag)

http://electron.atom.io/docs/api/browser-window/

PR to follow

**Comment by davibe** [comment]
💃

**Comment by ctcpip** [comment]
If anyone is curious about technical details, Electron calls a method from Chromium: `FlashFrame()` , which is implemented per OS / windowing system.

Code references here:

https://cs.chromium.org/search/?q=file:.cc+function:FlashFrame&m=100&sq=package:chromium&type=cs

Here is the implementation for X11, demonstrating the setting of the urgency hint:

```
806	void DesktopWindowTreeHostX11::FlashFrame(bool flash_frame) {
807	  if (urgency_hint_set_ == flash_frame)
808	    return;
809	
810	  XWMHints* hints = XGetWMHints(xdisplay_, xwindow_);
811	  if (!hints) {
812	    // The window hasn't had its hints set yet.
813	    hints = XAllocWMHints();
814	  }
815	
816	  if (flash_frame)
817	    hints->flags |= XUrgencyHint;
818	  else
819	    hints->flags &= ~XUrgencyHint;
820	
821	  XSetWMHints(xdisplay_, xwindow_, hints);
822	  XFree(hints);
823	
824	  urgency_hint_set_ = flash_frame;
825	}
```

**Comment by kmfdm303** [comment]
working on windows 7 professional

**Comment by jcbahr** [comment]
I ftf
