### ISSUE TITLE
Show unread msgs notifications in tray

### ISSUE THREAD

**Issue by yermulnik** [yakyak/yakyak#102]
Please add just a mark of unread messages presence or a count of them. Thanx.

**Comment by ArchieT** [comment]
Yeah. Notifications just disappear after a few seconds or are closed if in a hurry.

**Comment by davibe** [comment]
we should have unread count if we did not loose it in some release. Can you confirm ?
We don't have a marker of the last read message.

**Comment by yermulnik** [comment]
Unread count is shown in the app window, but not in tray icon.

**Comment by davibe** [comment]
also in the dock i think (OS X). Which os do you use ?

**Comment by yermulnik** [comment]
Linux Mint Rebecca

**Comment by Jimi-James** [comment]
Well, that means you could turn the tray icon off and use alltray to get a tray icon with an unread count. That's what I'll do for now, but I'd rather have an official tray icon with an unread count (that I can minimize the program to when I close the window, but that's another issue).

**Comment by Jimi-James** [comment]
I took a while to get back to this, but the app window definitely does not display an unread count for me. I'm on Linux (Arch Linux, x64, XFCE). So, I'd like to get an unread count on the tray icon so that I can miss notifications while away from the computer without missing the actual messages.

**Comment by algesten** [comment]
@davibe is this still and issue or close?

**Comment by Jimi-James** [comment]
I'm getting a different icon for unread messages, so I'm happy.

**Comment by algesten** [comment]
great
