### ISSUE TITLE
first open, sign-in window self-replicates non-stop

### ISSUE THREAD

**Issue by jngnyc** [yakyak/yakyak#1023]
When I open YakYak for the first time, the sign-in window appears (that's expected...), about a second later a second one appears over it, then a third, then a fourth... etc

See screen capture of the issue here: https://www.useloom.com/share/a9ab01bc192845f2a9dfe4af1d8440e0

I'm running macOS Mojave Version 10.14.2 (18C54) - MacBook Pro (13-inch, Late 2016)
I installed YakYak via homebrew (https://github.com/yakyak/yakyak/wiki#mac-os-x-alternative)

I'll see if I can replicate this issue on my home macbook and update this thread.

**Comment by ganthore** [comment]
I have observed the same behavior while attempting to login via a company oauth2 interface using older 1.2 versions of the software as well as 6f178a1.

The app accepts the credentials, then constantly loops. The runtime log shows:

```
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
asking for login credentials
login: did-finish-load https://blah
login: programmatic auth
2019-01-09 8:49:28 WARN no SAPISID cookie
2019-01-09 8:49:28 WARN no SAPISID cookie
2019-01-09 8:49:28 WARN no SAPISID cookie
2019-01-09 8:49:28 WARN no SAPISID cookie
2019-01-09 8:49:28 INFO removing refresh token
2019-01-09 8:49:28 INFO removing cookie store
```
