### ISSUE TITLE
yakyak Do you support Android, do you have an Android client?

### ISSUE THREAD

**Issue by fuckchinaOK** [yakyak/yakyak#1026]
I don't want to use the official "hangouts" client, so I want to have a third-party client. 

Can I provide a download of the APK version of Yakyak?

Thank. 

Or do you know that there are similar other clients that I can use on Android?

**Comment by cron410** [comment]
Google will be ending Hangouts sometime in 2020, doubt anyone will be working on a 3rd party android app if it doesn't already exist elsewhere.

**Comment by Rudloff** [comment]
I am working on an Hangups port for Android: https://github.com/Rudloff/hangupsdroid
But it is not very polished.
