### ISSUE TITLE
YakYak wont open on Windows

### ISSUE THREAD

**Issue by Neuroxiide** [yakyak/yakyak#1028]
Keep getting this error when trying to open yakyak on windows 64 bit. tried deleting and reinstalling no dice. can anyone assist? 

![capture](https://user-images.githubusercontent.com/44472684/50172983-440c1980-02c4-11e9-895c-79d8e579f887.PNG)

**Comment by fancypantalons** [comment]
Your message wasn't clear: have you tried moving/deleting the AppData folder (C:\Users\neuro\AppData\Roaming\yakyak)?

**Comment by Neuroxiide** [comment]
Oh, my words THANK YOU. That worked! I use this for work so I've been struggling since yesterday. VERY MUCH appreciated!

**Comment by fancypantalons** [comment]
> Oh, my words THANK YOU. That worked! I use this for work so I've been struggling since yesterday. VERY MUCH appreciated!

Just a bit of background, in case it's helpful in the future!  That folder (and there are many like it for various software on your computer) is a place where Yakyak can store information that's specific to your user on your machine.  That'd be things like configuration settings and so forth.

That folder is NOT deleted when you uninstall Yakyak!  This is a good thing, as it means you can upgrade Yakyak without destroying those settings!

Unfortunately, for some reason, for you, one of those configuration files (cookies.json) broke.  I can't begin to guess why (likely a software bug, but there could be many reasons, including cosmic rays... no, I'm not kidding), but the error you see, there, indicates that Yakyak had a problem reading that file.

So the simplest solution was just to delete or move that whole folder.

A more targeted solution (which would have preserved all your other settings) would have been to just delete that one offending file.

**Comment by cron410** [comment]
I'm having the same issue on 1.5.3 and deleting the 3 cookies files in that folder fixed it for me. Although I have to sign in again. Not sure if deleting just one will fix as I've only had this problem twice.

**Comment by Anssett** [comment]
This seems to be triggered by the machine powering off unexpectedly. I've had it happen twice now in about a month (building-wide power outage), and renaming %appdata%\yakyak\cookies.json (or deleting the file) corrects the issue.

**Comment by MostHated** [comment]
I keep getting cookie.json messing up every few days it seems
