### ISSUE TITLE
Rooms Missing in Google Hangouts Chat

### ISSUE THREAD

**Issue by LeeGDavis** [yakyak/yakyak#1037]
Hopefully this is a stupid question, but does this client support "rooms" as seen in the google hangouts chat client?  None of them seem to show up.  Not sure if this is a configuration or limitation of YakYak.

OS: Win 10 x64
YakYak: v1.5.4 Beta rolling

**Comment by Handspiker2** [comment]
Google Hangouts and Google Chat are different products.  Rooms is a Google Chat feature that isn't in Hangouts.

Google has just made it confusing by displaying one-on-one messages in both systems.

**Comment by LeeGDavis** [comment]
@Handspiker2, Thanks for the clarity!  I'll stick with the eye-searing google chat client for now.  YakYak looks so nice!

**Comment by LeeGDavis** [comment]
Out of curiosity, is this something on YakYak's road map or are to the two systems (hangout and chat) vastly different to support?

**Comment by pjz** [comment]
Working at a company with Gsuite, I'd love to have support for chat.google.com as well, please!

**Comment by floeschie** [comment]
It seems Hangouts Classic is going to be faded out in 2020:

https://9to5google.com/2018/12/01/hangouts-chat-meet-consumers/

I also would like to know if there are plans to migrate to Google Chat?

**Comment by festum** [comment]
Any good apps for the desktop version of Google Chat?

**Comment by floeschie** [comment]
@festum I use https://meetfranz.com/

**Comment by odyssey4me** [comment]
I'd like rooms support too, and am specifically looking for support on a linux desktop environment.

**Comment by festum** [comment]
@floeschie Franz seems like a browser wrapper. Duplicate memory resources with Chromium. ;(

**Comment by BopItFreak** [comment]
I'd really like to be able to make selfbots in google chat, like with hangupsjs.

**Comment by alpizano** [comment]
I installed yakyak on Ubuntu20.04. 

Is there  a way to get the Google hangout **ROOMS** on yakyak or how can I actually get this feature back? Do I need to install a different app?

**Comment by averissimo** [comment]
We would welcome developers that would add support google chat.

I'm currently only in caretaker mode merging pull requests and keeping packages updated.
