### ISSUE TITLE
SSO support

### ISSUE THREAD

**Issue by wheelerlaw** [yakyak/yakyak#1039]
When I type in my work email, a new window pops up and properly prompts me for my work credentials. However, Yakyak then enters this loop with the windows with the green Yakyak logo keeps on opening and closing (and repeats forever until I close the app):

([video](https://drive.google.com/file/d/1d83_bHUla8UhvRbGNsABWxm2CRnbbqiH/view?usp=sharing))

Logging into Hangouts Chat works fine

**Comment by worsco** [comment]
Same issue here (SSO, perpetiual loop), tried with yakyak-1.5.4-linux-x86_64.rpm

**Comment by ganthore** [comment]
Same issue when trying to connect to the company service. After SSO credentials are entered, the app goes into a perpetual loop.

**Comment by mveiga** [comment]
Same issue happening with me.

**Comment by kharyam** [comment]
Seeing the same behavior as well

**Comment by wheelerlaw** [comment]
In the mean time, I made this small Electron app that basically does the same thing. **Note:** it's very rough around the edges, as I'm currently working on it. But it pretty much does the basics. 

https://github.com/wheelerlaw/hangouts-chat-linux/

**Comment by devepone** [comment]
Same issue - Windows 10 x64.

**Comment by wheelerlaw** [comment]
Bumping so the issue is not closed since it is still unresolved.

**Comment by ganthore** [comment]
Yes, let's keep this active. This needs a bit more priority simply due to the number of orgs that are adopting Google's suite for business-related activities.

**Comment by Victoremepunto** [comment]
Bumping so the issue is not closed
