### ISSUE TITLE
Profile links go to Google+ but its shut down

### ISSUE THREAD

**Issue by neclimdul** [yakyak/yakyak#1056]
When I click on a profile photo in yakyak a browser window opens the users old Google+ profile. But its just a "Google+" is shut down message.

**Comment by jlyons210** [comment]
In the Gmail chat - the profile pics aren't linked. Is that the desired behavior? Are there links anywhere else?

**Comment by atomicwrites** [comment]
The same thing happens if you click on a picture someone sent, so theres no way to expand it.
