### ISSUE TITLE
"A JavaScript error occured in the main process"

### ISSUE THREAD

**Issue by SoulReaver-SS** [yakyak/yakyak#1060]
I've started getting this error all of a sudden:
I've tried a clean unzipping but the error persists.
![image](https://user-images.githubusercontent.com/5673736/57587709-1d8e8b00-74be-11e9-9d9b-7f4c88563cb9.png)

**Comment by stkaplan** [comment]
I had the same problem after a power outage, here's a fix: https://github.com/yakyak/yakyak/issues/1028
