### ISSUE TITLE
Text on Tray Icon for Mac

### ISSUE THREAD

**Issue by vv88cc77** [yakyak/yakyak#1067]
Is there a way to make it so that the tray only have the YakYak icon and none of the text. If there is, could you guys give me the instructions on how to remove them, step by step preferably please. I'm still very new to the OS.

**Comment by prediscover** [comment]
I have this issue too, this is what I see 
![Screen Shot 2019-06-24 at 9 44 16 AM](https://user-images.githubusercontent.com/10902462/60037628-eb4c7d80-9666-11e9-8fe7-ec861c17cca8.png)
Wish it was just the icon itself. I'm settling with just hiding the icon completely.

**Comment by mkolassa** [comment]
I would also like to see this feature.

**Comment by lemoran** [comment]
+1 For a way to hide the text (it's not so cool when tray is crowded)

**Comment by plinkowski** [comment]
I found that this worked. 
Here is the link to issue #990 [https://github.com/yakyak/yakyak/issues/990]

EDIT: quick hack is to edit this file:

/Applications/YakYak.app/Contents/Resources/app/ui/views/trayicon.js

Comment out line 51

tray.setTitle(i18n.__('title:YakYak - Hangouts Client'));

and restart YakYak.
