### ISSUE TITLE
Duplicate Notifications Windows 10

### ISSUE THREAD

**Issue by Riversiderepeat** [yakyak/yakyak#1070]
Just started seeing duplicate notifications for every incoming post on Windows 10. No idea how long it's actually been happening. I just noticed it now.

EDIT: Never mind. Restarting the app cleared it up. Weird.

**Comment by JPocalyko-REISys** [comment]
I get duplicate notifications too, but on Linux (Debian stable). They occur if I leave application running while going into S3 suspend. Upon wake I get duplicate notifications for new messages. Subsequent suspend/wake cycles add another notification each time. Restarting the app fixes it.

I'm guessing it's registering multiple times with the notification hook, but if it's occurring across platforms then it's not the OS fault, it's the app not checking to see if it's already registered.

**Comment by Riversiderepeat** [comment]
Yes. Actually I am still getting them even when the app is open in active conversations. Really shouldn't get any at all with the app open.
