### ISSUE TITLE
Browser Support Error

### ISSUE THREAD

**Issue by marsupilami09** [yakyak/yakyak#1073]
Hello! Today I got this error although I have enabled less secure apps in google account:

"You're using a browser that Google doesn't recognize or that's set up in a way we don't support."

**Comment by nokiajavi** [comment]
Same error

**Comment by jeffguevin** [comment]
I'm having the same issue, using Windows 10.

**Comment by sp823** [comment]
For the past week the client has been hanging at launch - maybe this is a different manifestation of the same error?

**Comment by elmateo487** [comment]
This is still a problem, unable to sign in on Windows 10 after a google password change.

**Comment by rajlego** [comment]
I'm also still having this issue

**Comment by mminer237** [comment]
This issue still exists.

**Comment by averissimo** [comment]
I believe this was solved in one of the previous version. Closing it.

Please open a new one if it still persists. Better yet would be a pull request.
