### ISSUE TITLE
[Feature Request] Hide conversation sidebar or standalone conversations

### ISSUE THREAD

**Issue by gtjones97** [yakyak/yakyak#1078]
I like using yakyak at work, where my screen space is valuable. I would like to see a feature where the sidebar could be hidden or being able to double click a specific conversation to open it in a new window. I only talk to one or two people on the app, it would be nice for me to reclaim some of the wasted space in my sidebar.

**Comment by atomicwrites** [comment]
It's very kludgy  but you can go to menu, yakyak, open inspector, and delete the entire left element. You cant get it back without restarting the entire app though, but it might help (I'm not a yakyak developer, just a user that happened to look at the issues).

**Comment by gtjones97** [comment]
Just as I wanted. Thank you kindly

**Comment by atomicwrites** [comment]
This works on websites too btw, and you can make it permanent by blocking things with your ad blocker even if its not actually an add.
