### ISSUE TITLE
Feature request: Google Voice specific variant?

### ISSUE THREAD

**Issue by aia832003** [yakyak/yakyak#1079]
Any chance the dev team here would consider a new application just for Google Voice? There really is no real desktop solution for Voice much like YakYak covers with Hangouts as a cross-platform option.

Could also offer an SMS alternative with the future of Hangouts being somewhat bleak for those using that. Just a suggestion but already appreciate the great app you've provided with YakYak.

**Comment by davibe** [comment]
we're very barely maintaining yakyak and not interested in google voice, not me at least.
