### ISSUE TITLE
No notifications in Gnome 3.30 notifications area

### ISSUE THREAD

**Issue by vash83a** [yakyak/yakyak#1091]
Hi,
notification popups appear, but I can't find any notification in Gnome notification area.
Thus, if I'm away I won't come to know having a new message.

`--> lsb_release -a      
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster`

Gnome 3.30
Yakyak 1.5.4

**Comment by averissimo** [comment]
Try v1.5.5 beta release or the new v1.5.4 that has significant changes since you last downloaded it
