### ISSUE TITLE
[Feature Request] Keyboard Shortcut for switching Tabs

### ISSUE THREAD

**Issue by duttaditya18** [yakyak/yakyak#1093]
The Chrome Hangouts Extension has the feature where you can switch Tabs of conversation with <kbd>Ctrl</kbd>+ <kbd>Tab</kbd>.

It would be amazing if this could be implemented in YakYak.

**Comment by mkellerman** [comment]
If this is for macOS, #1042

**Comment by duttaditya18** [comment]
<kbd>Ctrl</kbd>+ <kbd>Tab</kbd> and <kbd>Ctrl</kbd>+ <kbd>Shift</kbd> + <kbd>Tab</kbd> doesn't seem to work on Windows.

**Comment by duttaditya18** [comment]
It turns out we can use <kbd>Ctrl</kbd>+ <kbd>K</kbd> and <kbd>Ctrl</kbd>+ <kbd>J</kbd> or <kbd>Ctrl</kbd>+ <kbd>↑</kbd> and <kbd>Ctrl</kbd>+ <kbd>↓</kbd> to change tabs.

Seems to work fine.
