### ISSUE TITLE
No new releases?

### ISSUE THREAD

**Issue by mkellerman** [yakyak/yakyak#1095]
Seems like the last release dates of Nov 8, 2018. What is the status on this project? PR's are pilling up. Is this project dead?

**Comment by joshlewis** [comment]
As of today, the app (or Google?) forced me to sign out of YakYak, and I can't sign back in because the built-in "browser" is considered to be insecure by Google. So I can't use the app anymore. 👎

**Comment by mkellerman** [comment]
> As of today, the app (or Google?) forced me to sign out of YakYak, and I can't sign back in because the built-in "browser" is considered to be insecure by Google. So I can't use the app anymore. 👎

Check for a fix here: https://github.com/yakyak/yakyak/issues/1087#issuecomment-565170640

Hence why a new release would be nice, that includes the fix...

**Comment by joshuacant** [comment]
Seems like the maintainer has moved on, it happens. Has anyone forked this yet and incorporated all the changes from the last couple years into a new build?

**Comment by mkellerman** [comment]
I can help setup a new fork, and create a build in Azure and such.. but I’m no dev. I would be useless to approve/comment on PRs.

Would be nice if the maintainer could give us a status update. I’ve seen recent commits being done, but no releases.

**Comment by joshuacant** [comment]
The most recent commits are from Jan/Feb of 2019, which is basically a year ago, so it has been quite a while since there was activity. I don't mean any of this as an attack on the current maintainer. Things happen, interests change, time moves on. It probably didn't help motivation any when Google cancelled and then un-cancelled Hangouts in 2019.

I think someone taking the project on would need to be able to manage incoming PRs and doing builds for MacOS, Linux, and Windows. Either that, or split the duties between a couple people.

**Comment by atomicwrites** [comment]
I thought it said he had stopped, maintaining it since hangouts was deprecated, but i don't see it now.

**Comment by averissimo** [comment]
Sorry about that, but I'm no longer actively maintaining yakyak.

Both me and the previous developer stopped using hangouts and if someone wants to step up I gladly give him permissions.. *(or ask the previous dev to give it)*

I'm merging pending PR requests and will be updating the internal packages it uses.

I'm hoping to release a new version today.

This is all I can do.

**Comment by averissimo** [comment]
New release is available at [v1.5.4-beta-rolling](https://github.com/yakyak/yakyak/releases/tag/v1.5.4-beta-rolling)

I'd like if someone could test it for a bit to see if everything works fine.

I'll wait until users in Windows and Mac say that it's working for them.

What to look for:

* Notification problems
* Window problems *(electron, the framework used under yakyak was updated to a much more recent one)*

If I have the ok, this will be "officially" released.. maybe #1096 can also be included

**Comment by mkellerman** [comment]
I downloaded and installed on macOS. Seems fine. Is there a special list of features to test?

**Comment by averissimo** [comment]
There's a new message menu entry from pull request #1043 which is the only new feature if I'm not mistaken *(besides translations)*

Check if your normal workflow has any problems and keep an eye on notifications for anything different.

There were some updates to external packages that were quite big, unfortunately we don't have a testing framework in place to reliably check for problems.

**Comment by averissimo** [comment]
Btw, as a Mac user you can give feedback to this pull request from a while ago #1042 

Seems like there could be a conflict on the change... if you care to share your opinion please comment there. That's the sort of change I can do for this release.

**Comment by joshuacant** [comment]
Thank you for the new build, André. It's above and beyond given the status of the project, and definitely appreciated. I've upgraded and will report back after a couple days of normal use.

**Comment by mkellerman** [comment]
> Btw, as a Mac user you can give feedback to this pull request from a while ago #1042
> 
> Seems like there could be a conflict on the change... if you care to share your opinion please comment there. That's the sort of change I can do for this release.

Just commented on the issue. We should use the macOS standard way.

**Comment by mkellerman** [comment]
I second @joshuacant, Thanks!

**Comment by survivor303** [comment]
so the 1.5.4 code is new? release date is still from 2018, so little bit confusion there ;)

**Comment by atomicwrites** [comment]
@survivor303  The way I understand it's that is not the 1.5.4 release, but the permanently updated "master branch" code that would eventually be 1.5.4. The release was made in 2018 but the files are updated each time there is a change. At least that's what I understand.

**Comment by averissimo** [comment]
Yup, that was the idea under naming rolling release, instead of having multiple "beta" releases polluting the page.

Just pushed a new version with some of my old pull requests that I was hoping someone would review them

* Hides archived conversations
* Corrects a problem when deleting conversations

**Comment by joshuacant** [comment]
Hiding archived conversations works here. I've been wanting that feature for ages!

**Comment by averissimo** [comment]
Bunch on new code that cleans work from previous pull requests that were "merge-able". I couldn't get in deep on the on_the_record / off_the_record :(

Notable changes:

* Underlying fix for "Google Couldn't sign you in Yakyak"
* Hides archived conversations
* Add 'Show image preview' (feature #620) -- pull request #1096
    * only for previewing sent links *(not for images shared via hangouts)*
* Corrects a problem when deleting conversations
* New conversation menu
* When adding users to a conversation it shows the email when hovering the avatar
* Should correct a notification problem in Windows 10
* Should correct an auto-launch bug on macOS
* Bunch on updates on packages that will provide with better security and hopefully same functionality
* Fix mapping to :hankey: 
* Adds languages
    * Telugu
    * Breton
    * Simplified chinese
    * Remaning Czech string
* Moved my name to the "Main authors", because of Ego

Maybe some others... Didn't track everything ¯\\\_(ツ)_/¯
 
I ask the very patient community to please report if there are any problems. Plan on releasing the v1.5.4 in 24h from this comment.

**Comment by mkellerman** [comment]
Is there a way for me to send you a donation for your work? Buy you a beer or something? I/we really appreciate this!

**Comment by averissimo** [comment]
I may get the visibility, but the majority of the work goes to the still existing community

@AlessSala @signedbit @Jhall1990 @michaelherold @adrienlucas plus others with translations *(counting only for this release)*.

If you are keen on donating that beer please consider one of them or you favorite charity :smile:

**Comment by ryantiger658** [comment]
@averissimo, thanks so much for merging these PR's and doing a release!  I appreciate your temporarily coming out of retirement for this. 

I am a DevOps engineer and not a JavaScript developer, but I am happy to volunteer to be an interim maintainer until I can hand it off to a no-kidding JS developer. I am currently maintaining a couple of other OS projects.

I would be able  to setup some CI/CD pipeline for some automated releases, testing, and such. And I know enough JS to do code reviews.

I just figured I would offer so that you can officially retire and not have to get dragged back in! :)

**Comment by survivor303** [comment]
If we can get 24h timeformat available for what ever region user might be.

**Comment by ryantiger658** [comment]
1.5.4-beta is not working on Ubuntu 64bit. Trying to dig up a log file. Basically It keeps opening new windows without actually displaying anything.

**Comment by Jhall1990** [comment]
> 1.5.4-beta is not working on Ubuntu 64bit. Trying to dig up a log file. Basically It keeps opening new windows without actually displaying anything.

Seeing the same thing on MacOS. It was working until I signed out and tried to sign back in. Then I saw the above behavior.

**Comment by ryantiger658** [comment]
Getting a whole bunch of "AGENT is not defined"

`ryantiger658@Unknown:~/Projects/yakyak$ npm run dev

> yakyak@1.5.4 dev /home/ryantiger658/Projects/yakyak
> electron app --debug

Installing Devtron from /home/ryantiger658/Projects/yakyak/app/node_modules/devtron
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2020-01-27 11:51:41 DEBUG emit connecting 
DEBUG: Received event connecting
2020-01-27 11:51:41 DEBUG getting auth...
2020-01-27 11:51:41 DEBUG proceeding to login
asking for login credentials
2020-01-27 11:51:41 DEBUG request auth code from user
2020-01-27 11:51:41 ERROR getAuth failed ReferenceError: AGENT is not defined
    at /home/ryantiger658/Projects/yakyak/app/login.js:43:22
    at Function.promise (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:702:9)
    at module.exports (/home/ryantiger658/Projects/yakyak/app/login.js:16:14)
    at Auth.creds (/home/ryantiger658/Projects/yakyak/app/main.js:274:14)
    at /home/ryantiger658/Projects/yakyak/app/node_modules/hangupsjs/lib/auth.js:129:24
    at _fulfilled (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:854:54)
    at /home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:816:13)
    at /home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:877:14
    at runSingle (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:137:13)
2020-01-27 11:51:41 DEBUG emit connect_failed ReferenceError: AGENT is not defined
    at /home/ryantiger658/Projects/yakyak/app/login.js:43:22
    at Function.promise (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:702:9)
    at module.exports (/home/ryantiger658/Projects/yakyak/app/login.js:16:14)
    at Auth.creds (/home/ryantiger658/Projects/yakyak/app/main.js:274:14)
    at /home/ryantiger658/Projects/yakyak/app/node_modules/hangupsjs/lib/auth.js:129:24
    at _fulfilled (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:854:54)
    at /home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:816:13)
    at /home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:877:14
    at runSingle (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:137:13)
connect_failed ReferenceError: AGENT is not defined
    at /home/ryantiger658/Projects/yakyak/app/login.js:43:22
    at Function.promise (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:702:9)
    at module.exports (/home/ryantiger658/Projects/yakyak/app/login.js:16:14)
    at Auth.creds (/home/ryantiger658/Projects/yakyak/app/main.js:274:14)
    at /home/ryantiger658/Projects/yakyak/app/node_modules/hangupsjs/lib/auth.js:129:24
    at _fulfilled (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:854:54)
    at /home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:816:13)
    at /home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:877:14
    at runSingle (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:137:13)
DEBUG: Received event connect_failed
error connecting ReferenceError: AGENT is not defined
    at /home/ryantiger658/Projects/yakyak/app/login.js:43:22
    at Function.promise (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:702:9)
    at module.exports (/home/ryantiger658/Projects/yakyak/app/login.js:16:14)
    at Auth.creds (/home/ryantiger658/Projects/yakyak/app/main.js:274:14)
    at /home/ryantiger658/Projects/yakyak/app/node_modules/hangupsjs/lib/auth.js:129:24
    at _fulfilled (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:854:54)
    at /home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:816:13)
    at /home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:877:14
    at runSingle (/home/ryantiger658/Projects/yakyak/app/node_modules/q/q.js:137:13)`

**Comment by ryantiger658** [comment]
It looks like one of the additional PR's conflicted out a couple of lines from #1092. I can submit a PR with the fixed code. 

```# Hack the user agent so this works again
# Credit to https://github.com/yakyak/yakyak/issues/1087#issuecomment-565170640
AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/80.0.3904.70 Safari/537.36"
```

**Comment by joshuacant** [comment]
There may be something weird going on with the bubble showing unread message count. I've been seeing weird values all day, but here's just one example. It says "20+" but there was only 1 unread message, because it's a conversation I've been active in all morning.

![notif](https://user-images.githubusercontent.com/1975723/73196347-71e5a380-40fd-11ea-8063-82fdbbaa5a0b.png)

**Comment by ryantiger658** [comment]
So in local testing updating the login.js file fixed the startup issue. However, now once I login I hang on a "One moment please..." message with no obvious errors in the log

```login: did-finish-load https://accounts.google.com/o/oauth2/programmatic_auth?hl=en&scope=https://www.google.com/accounts/OAuthLogin+https://www.googleapis.com/auth/userinfo.email
login: programmatic auth``` (redacted what I assume are some secrets)

**Comment by averissimo** [comment]
@ryantiger658 and @Jhall1990 Oopsie... problem resolved in a less static way by replacing "Chrome" with "Chromium" in the default user agent. Even with Electron 8.0.0-beta.6 it still shows the same -_- I guess not even Chrome 80.* is safe

Hopefully in the medium term this *"fix"* can be removed.

@joshuacant I can't replicate this issue. Does it show immediately or just when the conversation is being ghosted for a while?

@survivor303 does the option "Edit" -> "Use system date format" works? 

![image](https://user-images.githubusercontent.com/211358/73288862-a89de580-41f3-11ea-8701-66c3f195b7c2.png)

**Comment by averissimo** [comment]
in my system -- Ubuntu -- I have 24h defined in the calendar and it shows like the image.. Otherwise it says 5:18PM

**Comment by joshuacant** [comment]
If that notification count glitch is only happening to me, I'll try wiping my settings folder and logging in fresh. That might fix it, or if not I can live with it. It's a very minor issue.

**Comment by billchase2** [comment]
I just came across this project and am thrilled to see that there have been some recent updates. Thank you! It's just what I've been looking for on my Mac. Working great, so far.

**Comment by averissimo** [comment]
@joshuacant it's not only happening to you, check out #1109
