### ISSUE TITLE
Multiple notifications on Windows 10

### ISSUE THREAD

**Issue by Riversiderepeat** [yakyak/yakyak#1098]
Getting a ridiculous number of notifications for each and every incoming text. Every time I dismiss one, another for the same text pops up. Number of times is random. Up to ten for the last two texts. Sometimes as few as four. Happens whether YakYak is open or not. Also YakYak has never opened when the notifications are clicked.

**Comment by averissimo** [comment]
may be fixed in v1.5.4-beta-rolling that was just updated
