### ISSUE TITLE
new message notification on windows

### ISSUE THREAD

**Issue by davibe** [yakyak/yakyak#11]
Apparently windows user do not like the balloon coming from the system tray. They are more used to having the application BLINK in the task bar. The actual behaviour is that the app blinks a couple of times then it stops but keeps a "hi lighted" color. Need to investigate how to do this on electron

**Comment by ctcpip** [comment]
Help me understand what is being asked for here.  I implemented the blinking in the taskbar, and it works as expected on Windows + GNU/Linux.  What is the request?

**Comment by davibe** [comment]
should probably have been closed indeed
