### ISSUE TITLE
stuck in loop?

### ISSUE THREAD

**Issue by DevinCharles** [yakyak/yakyak#110]
Running on binary v1.1.1 on Windows 7 x64 (tried both x86 and x64 versions). After entering username and password and 2 step auth, the program loops, trying to connect or sign in. I do connect through a proxy, not sure if this is causing the problem. If I try to open any menu items a I get this error.
![yakyak](https://cloud.githubusercontent.com/assets/2947096/12309194/55e50aa2-ba17-11e5-8f42-d99e068caecd.png)

**Comment by davibe** [comment]
I changed the login mechanism to be more robust. I will publish version 1.1.3 soon. Please reopen if the bug is still there
