### ISSUE TITLE
Incorrect Unread Message Count Indicator

### ISSUE THREAD

**Issue by monreric** [yakyak/yakyak#1109]
With the release from 2020-01-29, the unread message count is always displaying 20+.

![2020-01-29 12_24_20](https://user-images.githubusercontent.com/2573668/73385228-67a8de00-4292-11ea-883c-64b2ba7ac44c.png)

**Comment by averissimo** [comment]
Does it happen when you get a new message, more than 1? 

Or just when it's left with unread messages for a while? *(like ghosting)*

**Comment by monreric** [comment]
Happens with a single new message.

**Comment by aPoCoMiLogin** [comment]
same goes for me, but its 12+; also there is strange behaviour when window is "hidden" in mac osx (CMD + H), it popsup for second and minimizes itsefl.

**Comment by monreric** [comment]
Looks like for a single contact it shows 12+, but for a group it shows 20+.

**Comment by joshuacant** [comment]
I see "20+" most often, but I also occasionally see other random numbers in the high teens. Haven't figured out a pattern for that. 

The only unusual thing about the Google account I'm using is that it's part of a free G Suite domain. That's probably not relevant unless everyone else with the issue is set up the same way.

**Comment by averissimo** [comment]
It seems that after a bit, the counter looks into the number of existing messages in the conversation instead of the unread messages.

When it sees more than 20, then it shows 20+

Looking into it.

**Comment by averissimo** [comment]
This issue should be solved on v1.5.5-beta-rolling in the [releases page](https://github.com/yakyak/yakyak/releases/tag/v1.5.5-beta-rolling)

Please confirm or report any problems you have

**Comment by joshuacant** [comment]
This seems to be fixed for me with the new build. I've only tested a handful of messages so far, but they all showed "1" in the bubble and not "20+".

**Comment by markbaird** [comment]
This is still a bug in MacOS, even in version 1.5.6.

**Comment by averissimo** [comment]
We welcome a pull request with the fix
