### ISSUE TITLE
Stuck in "Reconnecting" Loop

### ISSUE THREAD

**Issue by alexholliz** [yakyak/yakyak#111]
I noticed that YakYak was stuck a loop of "Not Connected" and "Reconnecting". I cleared out my login cookie and logged in again, but no dice. If it helps, I am on win10 and the 64 bit client.

**Comment by kethinov** [comment]
Pretty sure this is happening to everyone. I know of at least two other people in different parts of the world experiencing the same problem.

I would suspect Google changed something about how to connect to the hangouts service and hangups needs to be updated...

**Comment by rnmp** [comment]
This is happening to me as well. I love your app guys please fix it so I can continue using it!

**Comment by manuelgrabowski** [comment]
Same here. :cry:

**Comment by averrin** [comment]
yeah=(((

**Comment by tonivade** [comment]
Same here

**Comment by Leeds-eBooks** [comment]
+1 on Mac

**Comment by yermulnik** [comment]
+1 here. console log shows:
```
2016-01-14 14:17:34 WARN init failed 404 Not Found
connect_failed
```

**Comment by mhogerheijde** [comment]
For me too. Latest version of hangupsjs is in use already, so I was unable to try a build with a newer version to see if that helped.

**Comment by larstobi** [comment]
Same here on Mac Yosemite.

**Comment by mhogerheijde** [comment]
Indeed, the URL ('https://talkgadget.google.com/u/0/talkgadget/_/chat') hangupsjs uses to connect to Hangouts, does not exist anymore.

**Comment by mhogerheijde** [comment]
A bug has been reported (already) against hangupsjs: https://github.com/algesten/hangupsjs/issues/39

**Comment by gustavoriveray** [comment]
Same here Mac OSX "El Capitan" is there a workaround in the mean time to make it usable?

**Comment by mhogerheijde** [comment]
I'm trying to find if Hangups (the python original hangupsjs is a port from) has the same issue, and if not, what URL they are using to see if it is a simple issue.

If Google changed the API, it's probably not a simple workaround... :(

**Comment by martin-g** [comment]
As explained earlier the endpoint at google.com has been removed. So it doesn't matter what your OS is!
Please wait until the developer find what the new endpoint is.

**Comment by mhogerheijde** [comment]
The python version still works, but it isn't clear to me which endpoint they use :-)

**Comment by 127001** [comment]
Mentioned in https://github.com/algesten/hangupsjs/issues/39#issuecomment-171648277:

> https://github.com/tdryer/hangups still works, so they have the correct endpoint :)

**Comment by iraszl** [comment]
+1 on Mac OSX

**Comment by troyxmccall** [comment]
+1 on OSX 10.11.2

**Comment by skrewz** [comment]
Working in 1.1.2 -- thanks! :)

**Comment by davibe** [comment]
gooooood!!

**Comment by kwrobel** [comment]
Whatever it is, but we are now in Dec 2016 and what is being described here in this thread is happening again. I can't use YakYak anymore. Same Not Connected, Reconnecting loop. I am on macOS Sierra and YakYak was working up until today.

**Comment by tonivade** [comment]
Try version 1.4.0-beta4, it works for me!

Kind Regards!

Antonio “Toni” Muñoz

Sent from
https://polymail.io/?utm_source=polymail&utm_medium=referral&utm_campaign=signature

On Thu, 01 Dec 2016 at 16:28 Kay Wrobel

<
mailto:Kay Wrobel <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Whatever it is, but we are now in Dec 2016 and what is being described here in this thread is happening again. I can't use YakYak anymore. Same Not Connected, Reconnecting loop. I am on macOS Sierra and YakYak was working up until today.

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/yakyak/yakyak/issues/111#issuecomment-264202998
, or

**Comment by PratapNaik** [comment]
yep...the new beta version fixes it...

<img width="926" alt="screen shot 2016-12-02 at 12 21 59 am" src="https://cloud.githubusercontent.com/assets/22319227/20807585/968ef894-b825-11e6-9f7d-57ba3d869bcc.png">

**Comment by jskovtoo** [comment]
How do you install 1.4.0 release version on mac?  It doesn't have a link for osx

**Comment by averissimo** [comment]
an official version has been released

see here https://github.com/yakyak/yakyak/releases/tag/v1.4.0

**Comment by jskovtoo** [comment]
Thanks @averissimo - saw that, but didn't see the osx version - is there a simple way for me to use one of the others - or do they need a conversion of some sort?  I noticed past releases had an osx version.

Thanks

**Comment by kwrobel** [comment]
@jskovtoo You would have to build it yourself. I just went through the same because 1.4.0 for OSX was not immediately available. You'd need to install npm on your Mac. I installed it through MacPorts (port install npm4). Then follow the build instructions. I'd say be carefor with the last step (deploy) because it will build versions for all platforms. So you'd want to deploy for darwin-x64.

**Comment by jskovtoo** [comment]
thanks @kwrobel - I'm not super keen on that, since I'm not real technical and wouldn't want to mess things up - is it something where you can pass over the version you built, or I would need to re-do and build my own?  Thx for the help

**Comment by kwrobel** [comment]
@jskovtoo In that case I'd just stick to the binaries that are being released. I was impatient and wanted to get YakYak working again after my older version went into a reconnect loop. It was suggested to use 1.4.0, but no binary was available. So I built it and it works. Of course, with a little patience (as in a day or so), I could have just downloaded the binary when it was released for macOS.

**Comment by martin-g** [comment]
Since a while I download the binaries from https://github.com/saenzramiro/rambox/releases.

**Comment by klonamy** [comment]
I have the same trouble.

On the first login it is stuck at loading contacts.
On second start it is stuck at Connecting or says it can't connect and switching with connecting.

**OS:**
Windows 10 (64bit)

**Program-Version:**
yakyak 1.4.0 x64
yakyak 1.4.1 x64
yakyak 1.4.2 x64 *and* ia32

**Comment by averissimo** [comment]
@klonamy can you please open a new issue with that information?
