### ISSUE TITLE
YakYak v1.5.5 / Hide Window Popping Bug

### ISSUE THREAD

**Issue by CdyVnd** [yakyak/yakyak#1115]
Hey YakYak team – thanks for all that you do.

I wanted to report a small bug in v1.5.5 ... or at least I think it's a bug, because I don't recall this happening in older versions.

On Mac OS, when you hide the chat window (and cannot see the window, nor a thumbnail in the dock), it strangely pops back up and then minimizes when someone messages you.

Please see the attached zipped .mov for reference.

Is there any way to fix this? It's a little annoying when you're purposefully hiding a window, only for it to pop back up.

Thank you again!
Cody

[Pop_Bug_013020.zip](https://github.com/yakyak/yakyak/files/4136827/Pop_Bug_013020.zip)

**Comment by averissimo** [comment]
Check out new v1.5.5 beta

**Comment by averissimo** [comment]
I believe it will solve this

**Comment by CdyVnd** [comment]
Hi André,

Confirming that I have downloaded the very latest v1.5.5 Beta, and it does not solve this issue.

Thank you for all that you do!
Cody

**Comment by averissimo** [comment]
Tried a different bit of code, when you can, please verify if it works.

If it doesn't we'll need a macOS developer to work on this a submit a pull request.

**Comment by CdyVnd** [comment]
So sorry, André, does this mean I should download the same Beta again? I'm not very experienced with this process, unfortunately. Or do I update the code somehow?

**Comment by drootang** [comment]
Can confirm 1.5.5 beta fixes this issue (and the unread message count)

**Comment by averissimo** [comment]
@CdyVnd You have to download again. Unfortunately, it doesn't update on its own.

**Comment by averissimo** [comment]
@drootang It's great to hear that

**Comment by ottopic** [comment]
I confirm that popping is fixed for me too.

**Comment by CdyVnd** [comment]
Confirming that this worked for me as well – thank you!
