### ISSUE TITLE
1.5.4 installed via amd64 .deb fails to run on Debian buster

### ISSUE THREAD

**Issue by PinkFreud** [yakyak/yakyak#1119]
Running from a terminal window reveals why:
"[16268:0203/212859.867721:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/yakyak/chrome-sandbox is owned by root and has mode 4755."

-rwxr-xr-x 1 root root 5581136 Jan 22 15:25 /opt/yakyak/chrome-sandbox

Why do we require a suid-root sandbox to run yakyak 1.5.4 now?  What changed here?

**Comment by averissimo** [comment]
From our part nothing. 

This should be a change from an update to electron (or for our deb package [fpm](https://github.com/jordansissel/fpm))

Probably electron: https://github.com/electron/electron/search?q=suid&type=Issues

**Comment by PinkFreud** [comment]
Wouldn't that be an issue to fix in the yakyak deb, then, given that electron is installed with yakyak?

Even so, I'm finding myself slightly skeeved out by electron requiring root.

**Comment by averissimo** [comment]
Please check the code itself, but as far as I know there is no requirement of any root command for yakyak

Seems it's for this: https://blog.chromium.org/2008/10/new-approach-to-browser-security-google.html

Maybe we should use a electron-specific packager for debian and rpm such as https://github.com/electron-userland/electron-installer-debian

**Comment by rvandegrift** [comment]
I was able to use `chrome-sandbox` from the `chromium-sandbox` package like this:
```
sudo dpkg-divert --divert /opt/yakyak/chrome-sandbox.disabled --rename /opt/yakyak/chrome-sandbox
sudo dpkg -i yakyak-1.5.5-linux-amd64.deb
sudo ln -s /usr/lib/chromium/chrome-sandbox /opt/yakyak/
```

**Comment by Rudloff** [comment]
As the error suggests, this fixed the issue for me:
```bash
sudo chmod 4755 /opt/yakyak/chrome-sandbox
```

**Comment by PinkFreud** [comment]
Thanks, everyone.  Yes, setting chrome-sandbox u+s works, but the original question was two parts (I apologize for not making this clear when I originally asked!): A. why is this necessary and B. why isn't the yakyak package setting appropriate permissions, as this now appears to be a requirement?

The first part of the question was answered in https://github.com/yakyak/yakyak/issues/1119#issuecomment-585371864 (thanks @averissimo !), but the second part remains unresolved - installing the 1.5.7 deb resulted in the same issue, so the package is still not setting correct perms on the chrome-sandbox binary, leaving it up to the user to do by hand.

Alternatively, as @rvandegrift suggests in https://github.com/yakyak/yakyak/issues/1119#issuecomment-593615919, we can add the chromium-sandbox package as a dependency to yakyak, and not have to include a separate sandbox binary.  Either of these should fix this issue, though I think I'd prefer to see yakyak use the existing package, rather than packaging it's own suid-root binary.

**Comment by averissimo** [comment]
Using a deb-specific packager now.

This shouldn't be an issue anymore. `v1.5.10-beta` deb uses a different method to package it. _(it should be available 20minutes from this comment)_
