### ISSUE TITLE
1.5.4 displaying incorrect number of unread messages

### ISSUE THREAD

**Issue by zanthorn** [yakyak/yakyak#1123]

**Comment by averissimo** [comment]
I believe it's now incorrect in all previous versions as this was a result of a protocol change from Google.

It's accurate again on 1.5.5 (beta)

**Comment by markbaird** [comment]
I just upgraded to the latest 1.5.5 (beta) release, and I'm still seeing this issue.

**Comment by LEAPgoods** [comment]
I am also seeing this issue.

**Comment by Guillealbr** [comment]
me too

**Comment by markbaird** [comment]
This issue is still present in the latest version. Please don't close the issue until it is fixed.

**Comment by markbaird** [comment]
This issue is still present in the latest version. I just installed the latest beta and tested it. It still shows `9` unread messages when I have `0`, `10` unread messages when I have `1`, etc. Please don't close the issue until it is fixed.

**Comment by averissimo** [comment]
I've pinned it so that the bot doesn't try to close it

**Comment by HomerSp** [comment]
Is this still happening in the latest release (1.5.11 or 1.5.12 beta)?
