### ISSUE TITLE
Displaying incorrect number of unread messages wrt older release

### ISSUE THREAD

**Issue by mojothejojo** [yakyak/yakyak#1124]
When checking on 1.5.4 the number of messages was More
With same number of unread messages - in the older release 1.5.3 shows less number of messages.
- With 1.5.4 Release
<img width="88" alt="Screenshot 2020-02-13 at 10 31 56 AM" src="https://user-images.githubusercontent.com/16579106/74403192-75db2a80-4e4c-11ea-86fe-403483e9b0aa.png">

- With 1.5.3 Release
<img width="107" alt="Screenshot 2020-02-13 at 10 32 27 AM" src="https://user-images.githubusercontent.com/16579106/74403226-8ab7be00-4e4c-11ea-9529-7e1125bad30f.png">

**Comment by averissimo** [comment]
duplicate #1123
