### ISSUE TITLE
Window tries to maximize and then minimize on each incoming notification

### ISSUE THREAD

**Issue by mojothejojo** [yakyak/yakyak#1125]
- When a new message is received - the window maximizes and then immediately minimizes with each incoming notification.
- this was not the case in the 1.5.3 Release - the notification was received without any window maximize - minimize circus.

**Comment by averissimo** [comment]
This is solved on the next release, you can try it by using the v1.5.5 rolling-beta

**Comment by averissimo** [comment]
Keeping issue open until release

**Comment by LEAPgoods** [comment]
I was just coming here to report the same issue. Glad it's being addressed. Thank you!
