### ISSUE TITLE
Can't send messages when Conversation History is turned off

### ISSUE THREAD

**Issue by ctcochran3** [yakyak/yakyak#1134]
My organization recently turned off Conversation History for Google Hangout:

> Conversation history:  This setting cannot be changed because of an organization policy set by your administrator.

Since this change has been instituted, I can receive messages/notifications via YakYak, but I cannot send messages via YakYak.  Any messages I send appear in the conversation window, but are grayed out and the recipient does not receive them.  If I send a Hangout message using Chrome or Pidgin, the message is received and the sent message will appear in my YakYak conversation window and it is not greyed out.  Some additional information:

Windows Version:  Microsoft Windows 10 Pro, 10.0.18363 N/A Build 18363
YakYak Version:  v1.5.4
Chrome Version:  80.0.3987.132 (Official Build) (64-bit)
Pidgin Version:  2.13.0 (libpurple 2.13.0)

**Comment by KBassford** [comment]
Ditto (conversation history is on!).  If using web client with YakYak turned off, those conversations appear on the (Chrome) web client, but not on YakYak when it is opened.  Looks like the work-a-round is broken.
YakYak: 1.5.4 amd64
OS: Parrot GNU/Linux 4.8
Chrome Browser: 80.0.3987.122-1 amd64

**Comment by KBassford** [comment]
UPDATE: Not all outgoing messages show up in YakYak.
