### ISSUE TITLE
No notifications in Kubuntu 18.04 (Plasma 5)?

### ISSUE THREAD

**Issue by pmsobrado** [yakyak/yakyak#1135]
Hi, notifications are not showing when I get new messages, but oddly enough executing this on the yakyak console DOES generate a desktop notification:

`require('node-notifier').notify('hello world')`

Any clues? Bug?

Thanks.

**Comment by garnus** [comment]
I have on KDE Neon the same problem.

**Comment by pmsobrado** [comment]
OK, last update seems to have fixed something, or at least for my case. The desktop notifications are working now, but NOT the sound, with normal conversation or  `require('node-notifier').notify('hello world')`, no sound.

**Comment by pmsobrado** [comment]
Sound seems to work with beta 1.5.8, thanks! Is there a way to change the sound?

**Comment by garnus** [comment]
Installed version 1.5.9 - sound is working but still no desktop notifications.
