### ISSUE TITLE
YakYak window popups up with a new notification

### ISSUE THREAD

**Issue by rakesh-intelligaia** [yakyak/yakyak#1140]
Entire window popups up with the new notification instead of a banner on top right of the screen.

MacBook Pro 15inch - late 2017
OS: Catalina (10.15.3)

Let me know if you need screenshots or anything for this.

**Comment by draydah** [comment]
Sounds like a similar issue to https://github.com/yakyak/yakyak/issues/1125

Try the 1.5.5 beta
