### ISSUE TITLE
Hangouts video from iphone

### ISSUE THREAD

**Issue by broyuken** [yakyak/yakyak#1142]
Same issue from 3 years ago is still here. When viewing a chat from another user that has posted an iPhone video the application simply shows an image of the video preview with play button. When selected it simply loads it as an image in popup, rather than loading video. The link opens in a browser window, but the link is to an image, not a video.

**Comment by broyuken** [comment]
I see there was just an update to yakyak, but it did not resolve this issue.

**Comment by averissimo** [comment]
looking for a pull request that can solve this. We're probably using the wrong attribute for that kind of media as the link.

**Comment by broyuken** [comment]
I could give you a link of what I get vs what it should look like, but I don't know how to code it.

**Comment by averissimo** [comment]
Sorry, it would require you or someone to debug the message data structure in detail to figure out if Yakyak is doing something wrong or it simply doesn't access to a correct link.
