### ISSUE TITLE
Bad fonts in tray icon on KDE

### ISSUE THREAD

**Issue by autoferrit** [yakyak/yakyak#1146]
I just installed the app from snapcraft, and when I right click on the tray icon, i get messed up fonts and nothing is readable.
![image](https://user-images.githubusercontent.com/89895/79249196-c4e41280-7e31-11ea-9871-a5c6b9076ad3.png)

```bash
❯ uname -a
Linux ferritprime 5.4.28-1-MANJARO #1 SMP PREEMPT Wed Mar 25 12:45:29 UTC 2020 x86_64 GNU/Linux
```
installed with:
```bash
❯ sudo snap install yakyak
yakyak 1.5.4 from Snapcrafters installed
```

**Comment by 5c13nc3** [comment]
Same issue. Manjaro KDE

`uname -a 
Linux m4c1300k 5.6.7-1-MANJARO #1 SMP PREEMPT Thu Apr 23 10:50:31 UTC 2020 x86_64 GNU/Linux
`
`lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.0
Codename:       Lysia
`

**Comment by 5c13nc3** [comment]
Upon some digging. 
I ran 
`snap --shell yakyak`
`env`

and found this entry...

`LIBGL_DRIVERS_PATH=/snap/yakyak/58/gnome-platform/usr/lib/x86_64-linux-gnu/dri
FONTCONFIG_PATH=/snap/yakyak/58/gnome-platform/etc/fonts
SNAP_DESKTOP_RUNTIME=/snap/yakyak/58/gnome-platform
`


Makes me wonder if KDE isn't fully supported. Looks like gnome is their preferred. 

Then checking a few other things with the snap 
I see that the connections for snap are as follows...

`snap connections yakyak
Interface                 Plug                           Slot                             Notes
bluez                     yakyak:bluez                   -                                -
browser-support           yakyak:browser-support         :browser-support                 -
camera                    yakyak:camera                  -                                -
content[gnome-3-28-1804]  yakyak:gnome-3-28-1804         gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     yakyak:gtk-3-themes            gtk-common-themes:gtk-3-themes   -
content[icon-themes]      yakyak:icon-themes             gtk-common-themes:icon-themes    -
content[sound-themes]     yakyak:sound-themes            gtk-common-themes:sound-themes   -
gsettings                 yakyak:gsettings               :gsettings                       -
home                      yakyak:home                    :home                            -
mount-observe             yakyak:mount-observe           -                                -
network                   yakyak:network                 :network                         -
network-observe           yakyak:network-observe         -                                -
process-control           yakyak:process-control         -                                -
pulseaudio                yakyak:pulseaudio              :pulseaudio                      -
screen-inhibit-control    yakyak:screen-inhibit-control  :screen-inhibit-control          -
system-observe            yakyak:system-observe          -                                -
unity7                    yakyak:unity7                  :unity7                          -
wayland                   yakyak:wayland                 :wayland                         -
x11                       yakyak:x11                     :x11 `

I may try adding desktop and see what happens. Looks like the desktop connection includes plasma. 

 Famous last words...what's the worst that can happen?

**Comment by 5c13nc3** [comment]
update. 

connecting desktop and restarting had no change. 


`snap connections yakyak`
`Interface                 Plug                           Slot                             Notes`
`bluez                     yakyak:bluez                   -                                -`
`browser-support           yakyak:browser-support         :browser-support                 -`
`camera                    yakyak:camera                  -                                -`
`content[gnome-3-28-1804]  yakyak:gnome-3-28-1804         gnome-3-28-1804:gnome-3-28-1804  -`
`content[gtk-3-themes]     yakyak:gtk-3-themes            gtk-common-themes:gtk-3-themes   -`
`content[icon-themes]      yakyak:icon-themes             gtk-common-themes:icon-themes    -`
`content[sound-themes]     yakyak:sound-themes            gtk-common-themes:sound-themes   -`
`desktop                   yakyak:desktop                 :desktop                         manual`
`desktop-legacy            yakyak:desktop-legacy          :desktop-legacy                  -`
`gsettings                 yakyak:gsettings               :gsettings                       -`
`home                      yakyak:home                    :home                            -`
`mount-observe             yakyak:mount-observe           -                                -`
`network                   yakyak:network                 :network                         -`
`network-observe           yakyak:network-observe         -                                -`
`process-control           yakyak:process-control         -                                -`
`pulseaudio                yakyak:pulseaudio              :pulseaudio                      -`
`screen-inhibit-control    yakyak:screen-inhibit-control  :screen-inhibit-control          -`
`system-observe            yakyak:system-observe          -                                -`
`unity7                    yakyak:unity7                  :unity7                          -`
`wayland                   yakyak:wayland                 :wayland                         -`
`x11                       yakyak:x11                     :x11                             -
`

**Comment by 5c13nc3** [comment]
Solved it. 
Indirectly though. I was having issues with zoom, and stumbled across this forum. 
https://forum.snapcraft.io/t/slack-and-zoom-wont-open/16254/25
The last solution offered there solved the tray font issues for yakyak for me in kde. 

Close yakyak. 
Run the following commands in a terminal. 
```

sudo rm /var/cache/fontconfig/*

rm ~/.cache/fontconfig/*

fc-cache -r
```

**Comment by autoferrit** [comment]
That actually fixed it for me @5c13nc3 thanks. I have had to do that before I should have thought of that.

**Comment by averissimo** [comment]
Thanks @5c13nc3
