### ISSUE TITLE
Create icon, Linux

### ISSUE THREAD

**Issue by Studioartcz** [yakyak/yakyak#115]
How can i create icon for app to linux "start panel" ?
I have Linux Mint 17.3 Rosa, based on Ubuntu.

Thanks

**Comment by mhogerheijde** [comment]
I think, for now, you'd have to make a `.desktop` entry yourself.

Create a file `~/.local/share/applications/yakyak.desktop` with the following contents

```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=YakYak
Comment=Third party Desktop app for Hangouts
Exec=/home/mhogerheijde/.opt/yakyak/yakyak
Icon=/home/mhogerheijde/.opt/yakyak/resources/app/icons/icon@32.png
Terminal=false
StartupWMClass=YakYak
Type=Application
Categories=Network;
```

**Comment by maxkueng** [comment]
Creating the `yakyak.desktop` file, in my opinion, is part of of the installation process. The content of the file can be different depending on the Linux distribution. So it should be up to the maintainers of each package to decide what goes in to the file.

Here's what's in the desktop entry file of the AUR package:

```ini
[Desktop Entry]
Name=YakYak
Comment=Desktop client for Google Hangouts
GenericName=Hangouts Client
Exec=yakyak
Icon=yakyak
Terminal=false
Type=Application
Categories=Network;InstantMessaging;
```

**Comment by mhogerheijde** [comment]
I agree fully that it should be part of the packaging/installation process. For now, however, creating it yourself could be considered a _workaround_ ;).

**Comment by maxkueng** [comment]
Yes, good workaround :+1:
