### ISSUE TITLE
Window has no borders, making it look weird on top of a white browser/anything.

### ISSUE THREAD

**Issue by mthqwork** [yakyak/yakyak#1152]
Just attached a screenshot about it.
I know it can be 'fixed' by using dark theme, but I prefer the light ones.

![image](https://user-images.githubusercontent.com/19063751/80626758-38e80280-8a4f-11ea-9b17-8427293213a9.png)

**Comment by chomper700** [comment]
If you're looking to remedy this on your own while you wait for a developer reply (or if they don't think it's an issue), there are two things you could do. (I'm sorry I don't know how to give these instructions in Hungarian.)

1. In Windows, find the "advanced system settings" (either through the Control Panel > System; or just press Start and type "advanced system settings"), under Performance click "Settings", enable the "Show shadows under windows" setting.

or

2. Go into the YakYak file "resources/app/ui/app.css" and find the second instance of the string "body {". Within that second section, add a new line that says `border: 1px solid var(--grey);`. You could try other color variables as well if you'd like, such as --darkgrey, --black, --lightblack, or you could type in your own color choice such as `border: 1px solid green;` or `  border: 1px solid #FF0000;`.

![app,png](https://user-images.githubusercontent.com/30938242/80731330-c28fe280-8ad8-11ea-9cac-884b91152979.png)

**Comment by mthqwork** [comment]
Thanks for the quick reply. The strange thing is that on linux it DO have borders. Just somehow on Win 8.1, well, it does not.

**Comment by chomper700** [comment]
> Just somehow on Win 8.1, well, it does not.

I looked into it a little further, and apparently disabling the frame on Windows was a deliberate decision. If you look in the file "resources/app/main.js", you can see a line that disables the frame on Windows: `frame: process.platform === 'win32' ? false : void 0`. You can `// comment out` this line, but this also gives the window an ugly and redundant title bar, which is presumably why the devs chose to go frameless on Windows.
