### ISSUE TITLE
Ubuntu 20.04, yakyak 1.5.5, show trayicon causes segfault

### ISSUE THREAD

**Issue by aprsa** [yakyak/yakyak#1158]
Trying out the just-released 1.5.5; clicking on View->Tray icon->Show tray icon leads to a segfault repeatedly. I installed yakyak from the official deb package which doesn't come with debugging symbols, so I can't get a useful backtrace. Please let me know if I can provide you with any further information.

**Comment by averissimo** [comment]
For crying out, it will be sorted in v1.5.6 that is being released in around 10 minutes

electron bug for reference: https://github.com/electron/electron/issues/22725

**Comment by averissimo** [comment]
It's gonna take more than 10 minutes. The correction was not successful, we might have to use a previous version of electron

**Comment by averissimo** [comment]
@aprsa I think it's solved now on v1.5.6

**Comment by aprsa** [comment]
yep, I'm confirming it's solved. :) Thanks!
