### ISSUE TITLE
"New Conversation" Shortcut is Cmd+M on MacOS

### ISSUE THREAD

**Issue by mattrjk** [yakyak/yakyak#1160]
The keyboard shortcut to start a new conversation is Cmd+M on MacOS, when it should be Cmd+N. Cmd+M is the universal shortcut to minimize the application to the Dock.

<img width="240" alt="Screen Shot 2020-05-07 at 9 20 46 PM" src="https://user-images.githubusercontent.com/5483434/81359993-a081fb80-90a8-11ea-8be5-8d1dc51779b8.png">

**Comment by averissimo** [comment]
Merged and available in 1.5.7 beta
