### ISSUE TITLE
macOS dock icon bounce (v.1.5.7)

### ISSUE THREAD

**Issue by breaksbreaks** [yakyak/yakyak#1167]
The dock icon on Mac used to bounce in the previous versions of YakYak when I got a new message. In 1.5.7 it's not. Can I set this feature in this version somehow?

**Comment by averissimo** [comment]
There were some changes on the `notifications.coffee` file due to a bug in a different platform.

If someone can check that out and send a pull request it would be awesome

**Comment by averissimo** [comment]
Can you try downloading and running `v1.5.10-beta-rolling` ?

I've just updated it and I think it might solve the issue

**Comment by breaksbreaks** [comment]
You are right, it works again. Thanks a lot!
