### ISSUE TITLE
No system tray icon shows up -- Arch Linux, xfce4

### ISSUE THREAD

**Issue by drislands** [yakyak/yakyak#1170]
Installed on Arch Linux, with xfce4 window manager, via the packer AUR package manager.

The software itself is fully operational and I have no issue with it. But the lack of a system tray icon means I don't see when notifications are waiting, and I can't "unminimize" the software from the tray.

**Comment by averissimo** [comment]
There's an option to activate the tray icon. Have you turned it on?

**Comment by drislands** [comment]
I have, yes. No effect unfortunately.

**Comment by averissimo** [comment]
@drislands Can you try version `1.5.8-beta`?

The electron framework was updated from a very old version _(as a bug prevented us from updating it)_

**Comment by mthqwork** [comment]
I had the same issue, Arch + XFCE4. This affects another electron based apps as well. To solve this, install the "Status notifier" plugin and Electron based apps will work again. I'm using this in parallel with old "Notification area" plugin.
