### ISSUE TITLE
All previous messages are missing

### ISSUE THREAD

**Issue by adampatterson** [yakyak/yakyak#1171]
After updating to Mac OS 10.15.4 (19E287) and restarting, I opened YakYak and nothing was there.

I closed and reopened a few times then updated from 1.5.4 to 1.5.6 and I still don't have any previous messaged.

Adding a new message doesn't seem to fully work either.

**Comment by adampatterson** [comment]
Sorry, this might actually be related to Google.

![image](https://user-images.githubusercontent.com/31537/82349305-2bbb9500-99b7-11ea-8f4a-de03b72ef46d.png)

**Comment by smammy** [comment]
Yes, this is an outage on Google's end: https://www.google.com/appsstatus#hl=en&v=issue&sid=22&iid=f5eb4c5b15aef64b592064fcea397e7c

**Comment by adampatterson** [comment]
Perfect, I will close this once Google's end has resolved.
