### ISSUE TITLE
yakyak 1.5.6 getting stuck at loading stage

### ISSUE THREAD

**Issue by mojothejojo** [yakyak/yakyak#1174]
- the version 1.5.6 of yakyak is getting stuck at loading stage
- the window for login(taking credentials as input) and  window for animated loading are juggling forever by appearing and disappearing turn by turn

**Comment by gaieges** [comment]
Just updated to 1.5.6 as well and came across the same problem

**Comment by EndaerPatt** [comment]
Up until now I had no problem with that issue, but have tu conquer - it happens. Reverting to older version could help?

**Comment by mojothejojo** [comment]
Cleared the local user details - and did the fresh login - Still it persists.
Just checked the logs .. this is the error I am getting:
<img width="456" alt="yakyak" src="https://user-images.githubusercontent.com/16579106/84854701-efe02200-b07f-11ea-8de2-17402a855df6.png">

**Comment by mojothejojo** [comment]
Updating to 1.5.7 resolved this for me .. hence closing this issue

**Comment by gaieges** [comment]
Ah didn't even know there was a 1.5.7! Works for me too, thanks!
