### ISSUE TITLE
Can't sign in to google in app

### ISSUE THREAD

**Issue by ljden** [yakyak/yakyak#1175]
My login timed out, so I tried to log back in. Error given is:

> This browser or app may not be secure. Learn more
> 
> Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."

**Comment by gaieges** [comment]
I get the same thing after upgrading from 1.5.2 and clearing out my Application Support folder.  Message on signin after typing email is:

<img width="435" alt="Screen Shot 2020-06-16 at 3 58 09 PM" src="https://user-images.githubusercontent.com/6024347/84827651-64688180-afea-11ea-897f-138779eafde3.png">

**Comment by averissimo** [comment]
Only version 1.5.7 and 1.5.8-beta work right now.

Google changed part of the protocol which made all previous versions dead.
