### ISSUE TITLE
Changing account

### ISSUE THREAD

**Issue by chcgobears** [yakyak/yakyak#1176]
This program is great.  I don't see a way of changing the account I want to access this with.  When I installed it I used my personal account to test it but now I want to use if for my Hangouts at work.  What would be the process for that, reinstall?

**Comment by magicmatt253** [comment]
THIS ^^^

**Comment by chomper700** [comment]
Use the hamburger menu > YakYak > Logout. It seems that this is currently glitched and will not exit the app (for me at least), so exit YakYak manually, and it will prompt you for login when you launch it again. Bear in mind that this will also forget all of your preferences (size/notification/tray/theme/sound/etc) for some reason.

![image](https://user-images.githubusercontent.com/30938242/84818253-3a13c580-afe4-11ea-89f6-99aa147be71b.png)

**Comment by averissimo** [comment]
it clears all storage, maybe a better name for logout would be logout and reset configuration... as well as really quitting.

the code is at `main.coffee` if someone wants to give it a go :)

```
logout = ->
    log.info 'Logging out...'
    promise = client.logout()
    promise.then (res) ->
        argv = process.argv
        spawn = require('child_process').spawn
        # remove electron cookies
        mainWindow?.webContents?.session?.clearStorageData([], (data) -> console.log(data))
        spawn argv.shift(), argv,
            cwd: process.cwd
            env: process.env
            detached: true
            stdio: 'inherit'
        quit()
    return promise # like it matters
```
