### ISSUE TITLE
yak yak wont start

### ISSUE THREAD

**Issue by epizarro2** [yakyak/yakyak#1178]
![image](https://user-images.githubusercontent.com/49302511/84786149-5b5fbc00-afba-11ea-9aac-8558353bd2fc.png)

After reboot yak yak doesn't start, what can i do, just appears in task manager but not in tray

**Comment by epizarro2** [comment]
also, there isn't a log path to see whats its doing

**Comment by epizarro2** [comment]
after removing %appdata% folder, yask yak stuck at login

![image](https://user-images.githubusercontent.com/49302511/84786644-053f4880-afbb-11ea-8991-4d5014924a25.png)

**Comment by fgladu** [comment]
I think it's Google...

**Comment by epizarro2** [comment]
np, going back to chrome plugin

**Comment by xtrimsky** [comment]
same issue on Mac OS X build. Probably a change on the Google side. Don't forget Google is planning to drop support for Google Hangouts.

**Comment by adampatterson** [comment]
I have the same problem. Last time I think there was an issue with Google.

**Comment by HomerSp** [comment]
See #1177 for the cause and a solution to it not connecting.

**Comment by WinterWerewolf** [comment]
Same here. Stuck at Connecting screen.

**Comment by averissimo** [comment]
Should be fixed in v1.5.7 thanks to @HomerSp
