### ISSUE TITLE
Clicking user icons leads to dead Google+ pages

### ISSUE THREAD

**Issue by Syrail** [yakyak/yakyak#1179]
Clicking user icons in YakYak opens a link to the now-defunct google+ profile page, with a notice from Google saying that the pages have been discontinued. 

While this isn't a major usability issue, it would be nice if clicking said icons simply did nothing.

**Comment by thexavier666** [comment]
If clicking the profile picture can open a sidebar with a bigger profile picture + email address + other details (like Whatsapp Web/Messenger), that would be great.

**Comment by HomerSp** [comment]
Fixed in https://github.com/yakyak/yakyak/pull/1281
