### ISSUE TITLE
The newest OS X release reports as out of date

### ISSUE THREAD

**Issue by mgol** [yakyak/yakyak#118]
I downloaded (twice to be sure) the newest OS X app from https://github.com/yakyak/yakyak/releases (under `1.1.2`). However, the app reports itself as `1.1.1` and asks me to update to `1.1.2`.

It must either report an incorrect version or the `1.1.1` one was packaged instead of `1.1.2`.

**Comment by x-tk** [comment]
Experienced this also.

**Comment by davibe** [comment]
will be fixed in the upcoming 1.1.3
