### ISSUE TITLE
Connecting -> Not connected.

### ISSUE THREAD

**Issue by jfcartier** [yakyak/yakyak#1180]
The app doesnt seem to be able to connect. Here's the console error I get.

```
Uncaught (in promise) Error: 44:48: execution error: Not authorized to send Apple events to System Events. (-1743)
    at ChildProcess.<anonymous> (/Applications/YakYak.app/Contents/Resources/app/node_modules/applescript/lib/applescript.js:49)
    at ChildProcess.emit (events.js:182)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237)
```

**Comment by lhalegria** [comment]
same here. All day long

**Comment by chomper700** [comment]
Have you updated to 1.5.7? It looks like Google changed something, so now logging in is broken for previous versions.

The app won't notify you of the new version, since when it can't log in it unfortunately won't perform a version check.

**Comment by jfcartier** [comment]
It fixed the problem thanks. Which makes me think that having an auto-update feature would be nice :)
