### ISSUE TITLE
MacOS unable to check YakYak for malware

### ISSUE THREAD

**Issue by goodbyesky** [yakyak/yakyak#1182]
Since version 1.5.3, I haven't been able to install newer versions of YakYak because I'm getting the error that MacOS can't check the app for malware. My computer has an administrator that has disabled the ability to bypass this check in system settings. Is there something that can be done to sign the app or otherwise verify its creator so MacOS will let me install?

**Comment by goodbyesky** [comment]
Additionally version 1.5.3 is no longer loading for me so I'm stuck not being able to upgrade. =(

**Comment by averissimo** [comment]
How do you install it? via the zip file in releases, or homebrew, or other?

**Comment by goodbyesky** [comment]
Hello! I tried installing via the zip file. I haven't tried installing anything via homebrew before, but could look into that if you think that will bypass the issue.

**Comment by averissimo** [comment]
I would try it that way, seems like other users are using it.

**Comment by goodbyesky** [comment]
Ok, I installed via Homebrew but unfortunately am still getting the error. Here are the details:

"YakYak.app" cannot be opened because the developer cannot be verified. 
macOS cannot verify that this app is free from malware.
Homebrew Cask downloaded this file today at 3:42 PM from github.com

**Comment by goodbyesky** [comment]
Aha! Good news. I double checked my system prefs and have the option to open the app even though it was blocked. Thanks for the help!

**Comment by averissimo** [comment]
Awesome
