### ISSUE TITLE
Colorblind problem

### ISSUE THREAD

**Issue by kix2902** [yakyak/yakyak#1184]
Hi all,

I'm colorblind (deuteranomaly) and I can't distinguish the tray icon colors for read and unread states so normally I locally change the icons making the read state icon have a blue tone and leaving the unread as it is.

It could be any possiblity to make that change to be permanent in the repo so I don't need to make the change with every release version.

Thanks in advance.

_PS: If you accept the proposition I can make a PR with my modified icons as read state icons_

**Comment by averissimo** [comment]
Yes, I'll see this as a priority. Looking forward for your PR.
