### ISSUE TITLE
yakyak no longer works on my computer

### ISSUE THREAD

**Issue by ylefebvre** [yakyak/yakyak#1186]
I've been using yakyak for the past month and a half. Then earlier this week it just stopped working. When I try to start it up, it just displays the app logo and shows the 3 dots growing and shrinking, but it never connects. I've left it running for some time to see if it would eventually connect but it never does. I need to force quite the app to have it go away.

Could something have become corrupted in my local data or do I have a message or message attachment that can't be processed? How can I reset the client? I found where the application data from was stored in my roaming profile directory and delete it. When I restarted the client, it asked me for my login information, which made me hopeful, but after reconnecting, I still got an endless Connecting message...

Is there any kind of log that might contain useful error messages to troubleshoot this issue?

Thanks in advance!

**Comment by linuxsucks** [comment]
Yeah read this thread: https://github.com/yakyak/yakyak/issues/1178

**Comment by averissimo** [comment]
Fixed in version 1.5.7 and also in 1.5.8-beta
