### ISSUE TITLE
Sent Messages Are Not Received

### ISSUE THREAD

**Issue by nickmcummins** [yakyak/yakyak#119]
Firstly, thank you for making this client; I'm compiling a list of "essential apps for Linux" and this one will be on there. 

I am experiencing a major functionality issue however. I have been informed by two people who I have messaged using that client that they had not received my message. At first I thought it may have been something on their end, but after trying to send a message to myself from my cell number, I observed (a) messages sent from my mobile devices DO get received on the yakyak client, (b) messages I send from the yakyak client to my cell number are never received on my mobile device. 

![yakyak-noreply](https://cloud.githubusercontent.com/assets/9343202/12585378/b0be0576-c400-11e5-95ed-24d830ee4ce0.png)

As previously mentioned, this error has occurred with a total of 3 separate numbers, so it is doubtful to be an issue on that end. Has no one else experienced this problem? 

Note I have started yakyak via the command line, and the only output from the console is as  follows: 
<pre>
    linux-x64 git:(master) ✗ ./yakyak
    hconnect
    connected 0
    missing icons [TypeError: tray.setHilightMode is not a function]
    missing icons [TypeError: tray.setHilightMode is not a function]
</pre>
Oh yeah, and if it matters, my OS is Linux Mint 17.3 (x64), and I am using the latest prebuilt binary downloaded from <a href="https://github.com/yakyak/yakyak/releases/download/v1.1.2/yakyak-linux-x64.zip">here</a>.

**Comment by davibe** [comment]
when the message is grayed out it has not been sent correctly. Are all the missing message also grayed out on the sender side ?

**Comment by nickmcummins** [comment]
Yes, it appears so. If I send a message from the Android client, it appears in yakyak but as solid black rather than greyed.

**Comment by nickmcummins** [comment]
<img width="942" alt="screen shot 2016-01-28 at 12 54 44 pm" src="https://cloud.githubusercontent.com/assets/9343202/12658532/74d55e0a-c5be-11e5-93c9-dc34d8f94a55.png">
I am able to reproduce this issue on OSX using the pre-built packages for the latest release. Outgoing messages are not received, but incoming messages are received.

**Comment by nickmcummins** [comment]
JS Console: 

Uncaught Error: Rejected (alive) during action: init
/opt/yakyak/linux-x64/resources/app/node_modules/trifl/lib/action.js:40 Uncaught Error: Rejected (activity) during action: devtools
/opt/yakyak/linux-x64/resources/app/node_modules/trifl/lib/action.js:40 Uncaught Error: Rejected (activity) during action: attop

**Comment by davibe** [comment]
@nickmcummins all of them ?? or is it random

**Comment by nickmcummins** [comment]
I tried testing with a different Google Hangouts account and could not reproduce this problem. I am not sure why, but for the particular account I was using above, all outgoing messages are never received. Closing since this is not reproducible with another account.
