### ISSUE TITLE
No longer connecting, hangs after logon.

### ISSUE THREAD

**Issue by astralan** [yakyak/yakyak#1190]
Seen this before, usually js related. Did google change authentication standards again? Attempting to troubleshoot, I went back to 1.5.6 stable but won't connect. Thanks. -B

**Comment by brianjcohen** [comment]
Same here. I'm seeing on the console:

`connect_failed [NetworkError: Forbidden] {
  code: 403,
  message: 'Forbidden',
  body: <Buffer ...... >`

**Comment by astralan** [comment]
1.5.8 beta works.
