### ISSUE TITLE
Latest version (1.5.7) maxing out CPU

### ISSUE THREAD

**Issue by briankobler** [yakyak/yakyak#1191]
The previous version (1.5.6) suddenly stopped connecting for me. Downloaded the newest version (1.5.7), connected fine, but now it's maxing out my CPU usage for some reason. 

Device: Macbook Pro 2019
US: MacOS Catalina 10.15.5

<img width="960" alt="Screen Shot 2020-06-25 at 8 35 59 AM" src="https://user-images.githubusercontent.com/50964880/85720956-e75e9b80-b6be-11ea-8a47-55e70e9ecc22.png">

**Comment by averissimo** [comment]
Strange, can you try the v1.5.8 beta version and see if that's still the case?

v1.5.7 still uses a very old version of the framework due to a bug that was corrected only around 2 weeks ago.

**Comment by averissimo** [comment]
We're actually releasing v1.5.8 in a few minutes. I'm closing the issue as the update in the framework is a major one, even if there are few bug corrections.

Please reopen if problem persists.
