### ISSUE TITLE
No window decoration on yakyak 1.5.8

### ISSUE THREAD

**Issue by aprsa** [yakyak/yakyak#1194]
Not sure if that is by design, but there are no window decorations (title bar, min/max/close buttons etc). Escape key also doesn't seem to hide yakyak anymore, perhaps because of the missing window focus. On ubuntu 20.04.

**Comment by rauldipeas** [comment]
Same issue here with 1.5.8 version.

**Comment by HomerSp** [comment]
Indeed, I think it's the electron update causing it (possibly). I created a workaround in that pull request above that should work, so if you can, please test it.

**Comment by rauldipeas** [comment]
Now decorations it's working as expected.

**Comment by averissimo** [comment]
Thanks @HomerSp ... I'm pushing v1.5.9 for release
