### ISSUE TITLE
v1.5.9 tray icon change

### ISSUE THREAD

**Issue by kli0rf** [yakyak/yakyak#1198]
Why change something which is already perfect? That new colour doesn't look good. Pls, can you change it back to original colour? Or give and option to use the old style icon then.

**Comment by averissimo** [comment]
Check discussion on #1187 

Old icon was not suitable for the colorblind. will probably update to a non-blue in next version

**Comment by kli0rf** [comment]
Ah, ok, that's fair enough... It's a pity though, 'cause the old 'read' icon was really in the perfect balance with the green one. Well, i guess i'm gonna use them old icons from the previous release.
