### ISSUE TITLE
v1.5.9 spell check enabled by default

### ISSUE THREAD

**Issue by kli0rf** [yakyak/yakyak#1199]
I just noticed that... Is there a way to disable it?

**Comment by averissimo** [comment]
Corrected in #1201 should be out with v1.5.10 later today

If you can test the new spellcheck functionality please comment in #61

**Comment by averissimo** [comment]
@kli0rf ?

**Comment by kli0rf** [comment]
@averissimo Ah, right, sorry for late response. Unfortunately i can't test the spell check functionality, as the language i use for chats is not available for spell checks, i believe... And i didn't  go with v1.5.10, because i couldn't find how to change tray icons back to the old ones, so i'm still on v1.5.9 on both, fedora and windows systems. :) But i guess i'm gonna have go with v1.5.10 when you're releasing it as stable.
