### ISSUE TITLE
notify update availability

### ISSUE THREAD

**Issue by davibe** [yakyak/yakyak#12]
Cross-platform auto-update is a bit futuristic but having a way to inform the user a new update is available would be nice.

**Comment by maxkueng** [comment]
On OS X and Windows it should be possible to actually implement automatic updates using a thing called Squirrel :squirrel: ([docs](https://github.com/atom/electron/blob/master/docs/api/auto-updater.md)). But you need a Squirrel server or something.

On Windows this will only work if the app has been installed using an installer. But there's an npm package to create Windows installers.

On Linux I wouldn't recommend auto-updating (and Squirrel doesn't work anyway). Ideally, Linux users will install Yakyak through their OS's package managers and repositories (it's already possible on Arch and its derivatives) and get automatic updates from there.

As a start, though, I think a small bar at the top indicating that there's a new version would be nice.
