### ISSUE TITLE
Avatars and image colors are inverted

### ISSUE THREAD

**Issue by Japegrape** [yakyak/yakyak#120]
In every chat, avatar colors are inverted. Also, when a friend sends an inline image, the image is inverted. Images I send look correct, though.

YakYak version: 0.34.1 (1.1.2)
Mac OSX Version: 10.11.2

**Comment by davibe** [comment]
what does it mean colors are inverted ?

**Comment by Japegrape** [comment]
![image](https://cloud.githubusercontent.com/assets/800383/12727331/68fe420c-c8d1-11e5-8ac6-137a75219f07.png)

The colors are literally inverted. If you were to take an image into a photo editing program, and invert the colors, what I see is exactly that.

**Comment by davibe** [comment]
hahaha how is this happening

**Comment by erjiang** [comment]
Inverted avatars was an issue on Google+ once upon a time. Not sure if Google fully fixed it, but may be related.

**Comment by rameshdharan** [comment]
For what it's worth I have two Google accounts and I see this with 1.3.0 and 1.3.1 on both accounts. It only recently started happening for me.

**Comment by aaronj1335** [comment]
I'm seeing this too. Hacked a fix here: https://github.com/aaronj1335/yakyak/tree/ugh . I would try to post a PR, but a friend tried it out and is not seeing the issue, so I don't want to mess things up for other folks.

I'm wondering if it's because I've signed into the app w/ my work profile. Are you folks signed in with a work or standard @gmail.com account?

**Comment by deci-ftw** [comment]
Signed in with an @gmail.com account and seeing the inverted avatars

**Comment by yebrahim** [comment]
@aaronj1335 Please create the PR, this is happening intermittently for me.

**Comment by dsemaya** [comment]
I'm seeing this issue with a work account.

**Comment by dsemaya** [comment]
I am seeing inverted avatars on one Mac but not the other.  Not sure why.

**Comment by averissimo** [comment]
with the same account?

**Comment by dsemaya** [comment]
Yes.

**Comment by pdeslaur** [comment]
I troubleshooted the issue a little bit. The short answer is that those affected should unselect "Show Animated Thumbnai" from the "View -> Conversation List" menu.

The issue affects a very specific subset of users when the "?sz=" parameter is not provided in the image URL.

**Comment by Japegrape** [comment]
Good enough stop-gap for me, thanks!

~Jk

**Comment by rameshdharan** [comment]
@pdeslaur de-selecting "Show Animated Thumbnail" fixes the inverted avatar images but inline images in conversations are still inverted. Is there any other known workaround for that?

**Comment by pdeslaur** [comment]
Not that I'm aware - that would require a code change as far as I know :( It's not bugging me enough to write a PR yet...

**Comment by dsemaya** [comment]
Turning off animated thumbnails solves the problem for avatars for me but the user icons in macOS notifications are still inverted.  Is there a way to just replace them all with the generic app icon?

**Comment by swieder227** [comment]
This is still an issue and should likely be re-opened.

You can fix the avatar images in the conversation list following pdeslaur's comment. However, the issue still exists in the notification avatar image. You can disable the image completely, but that's not a real "fix".

**Comment by swieder227** [comment]
Oh, this affects all images. Including those uploaded into a chat. See screenshot (meme was not targeted at you, I promise!)

<img width="588" alt="screen shot 2017-12-04 at 1 08 14 pm" src="https://user-images.githubusercontent.com/1713558/33568372-37004b4e-d8f4-11e7-9c8f-8b82a3b0ac65.png">

**Comment by ravinald** [comment]
What if I buy you a bottle of whiskey?

**Comment by qqldd** [comment]
Same issue here.. can we reopen?
