### ISSUE TITLE
Very slow unzipping

### ISSUE THREAD

**Issue by Spleeen** [yakyak/yakyak#1203]
Hello,

Is it possible to speed up unzipping by reducing the number of small files?
Unziping under Windows 10 2004 takes at least  3-4 min with 14 300 files and only 100Mo of archive ( wow !!!).

I hope you will understand and support it, thank you very much

P.S : My English is in progress, please correct me if I'm wrong ! :D)

**Comment by averissimo** [comment]
Can you try the beta release v.1.5.10 ?

I've just updated it and the size should be much smaller now.

**Comment by Spleeen** [comment]
Yes, I did this morning, which is precisely why I'm leaving a comment.

*Bien cordialement,*
-- 
[image: Photo signature]

*Nicolas RICHARD *
*Ingénieur d'étude & développement logiciel chez la SLIB (Securities
Software Solutions) <http://www.slib.com/> pour Intuitiv Group
<http://intuitiv-group.com/> *
[image: Appelez-moi si besoin !]* 06 86 00 26 55 *
[image: Télécharger ma carte de visite (VCard)]
<https://bit.ly/35Zjs7w> [image:
Télécharger mon CV] <https://t.ly/HXYi> [image: Regarder mes disponibilités]
<https://calendly.com/nicolas-richard-dev> [image: Consulter mon profil
LinkedIn] <https://www.linkedin.com/in/nricharddev> [image: Regarder mon
profil HackerRank] <https://www.hackerrank.com/Spleen?hr_r=1> [image:
Prendre rendez-vous sur Superprof]
<https://www.superprof.fr/aide-domicile-informatique-cours-programmation-autour-lyon.html>



Le jeu. 2 juil. 2020 à 18:46, André Veríssimo <notifications@github.com> a
écrit :

**Comment by averissimo** [comment]
Sorry, I meant to say number of files. Please can you test `v1.5.10-beta` to see if it works on your environment

**Comment by Spleeen** [comment]
Part of my previous comment is gone, yes I tested this with the latest version this morning.

**Comment by averissimo** [comment]
Please confirm with the current beta version, from 3hours ago and after you created this issue.

`v1.5.10-beta` is continuously updated and I made a change to how it's packaged.

**Comment by Spleeen** [comment]
Pareil rien à changer

**Comment by averissimo** [comment]
I've just tested and it has 77 files in both linux and windows compressed files, while Max OSX has 337

What release file are you using, specifically?

![image](https://user-images.githubusercontent.com/211358/86470322-7d3b9b80-bd3b-11ea-8df9-4cf104d4d7ca.png)

**Comment by HomerSp** [comment]
Indeed, this looks to be fixed in 1.5.10 - the win32 x64 zip has 73 files now vs 12,000+ before.

**Comment by Spleeen** [comment]
I feel a bit stupid: you ask me to confirm that I used version 1.5.10, I tell you that there is no change... I had re-downloaded 1.5.9... coz not expanded https://cl.ly/8a119f
Mea culpa... that'll teach me to go too fast. It's actually much faster to unzip.
Congratulations for your support, your software is the only one to really do what it promises, you have all my encouragements...

Nice day.
P.S : correct my English if I'm wrong please.

**Comment by averissimo** [comment]
Don't worry, I was too hasty in my response/closing. Sorry for that.

You should be more confident with your English skill. It seems that you need to continue to work on it, but so does everyone :)
