### ISSUE TITLE
FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by cmurf** [yakyak/yakyak#1205]
It was working on 1.5.8, this starts happening after updating: git clean, git fetch, npm install, npm run gulp, 

> yakyak@1.5.10 electron /home/chris/Applications/yakyak
> electron "app"

../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0072
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0072
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0072
connected 0
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0072
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0072
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0072
[9147:0704/162527.196744:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
^C

git shows I'm at:
commit 2214cd268fd28b2eb3e21de24e281c00147fc6e9 (HEAD -> master, tag: v1.5.10-beta-rolling, origin/master, origin/HEAD)
5.8.0-0.rc3.1.fc33.x86_64+debug
npm-6.14.4-1.12.16.3.1.fc32.x86_64
nodejs-12.16.3-1.fc32.x86_64

**Comment by cmurf** [comment]
git bisect blames
f0bb10177951f50fcb5543732557d17a5ae5ebf3 is the first bad commit

**Comment by cmurf** [comment]
hmmmm so actually this is somewhat transient, it doesn't always fail so the git bisect is probably not valid

**Comment by HomerSp** [comment]
What kernel version are you on? Do you have regular chrome/chromium and does that work fine?
First thing I found when searching was this, which looks very similar to what you're seeing: https://lkml.org/lkml/2020/6/28/101 Though that's a kernel issue, so it would probably only happen if you're on a *very* recent (rc) kernel.
