### ISSUE TITLE
Notification behavior changed in Windows

### ISSUE THREAD

**Issue by Anttiac** [yakyak/yakyak#1206]
In the latest version, notification behavior of YakYak has changed for the worse. I can't find any way any more to make the YakYak on the task bar to change color when receiving a new message. Only Tray icon chances color now, and this is very unnoticeable compared to the old behavior. The Task bar icon color change on notification is default and expected behavior for all Windows programs.

Also there doesn't appear to be any way to control notification sound any, more besides by enabling popup notifications to show up, which also allows for audio notification.

Old behavior where task bar blink, sounds, popups, and tray icon notifications were all separately controllable and available. 

The lack of visual notification in task bar is the main issue though. Since I don't want popup notifications, I can't have sound enabled either and there's no way to tell when I have a new message as tray icon isn't noticeable. 

Expected behavior shown here with YakYak and Hangouts Chrome app side by side after receiving a message:
![image](https://user-images.githubusercontent.com/67882037/86547459-c2311f00-bf41-11ea-8798-34ec8b4a1731.png)

**Comment by averissimo** [comment]
Thanks for reporting, I need some clarifications as I don't have windows currently installed or in a virtual machine.

* [ ] Exactly What version of yakyak are you using?
    * If you are not using, can you please try v1.5.9 or v1.5.10-beta-rolling and continue the discussion with one of those versions
* [ ] Where were the controls for the options you are talking about below?

> Old behavior where task bar blink, sounds, popups, and tray icon notifications were all separately controllable and available.

Under yakyak menu `View` -> `Pop-up notification` there are some options to control notifications _(including sound)_. Does any of those options address your issue?

**Comment by averissimo** [comment]
I'm building on my personal yakyak fork a version that has some old code that I suspect were the cause for this taskbar problem.

In about 30minutes it should be available here: https://github.com/averissimo/yakyak/releases/tag/v1.5.10-fix1206

**Comment by Anttiac** [comment]
both 1.5.9 and 1.5.10 showed this behavior. Earlier version which I was running and used the expected Windows notification paradigm was 1.9.4. The versions between these I skipped over until the older version was no longer able to connect to the service. 

The View -> Pop-up notification setting don't really allow the customization required, as for example hiding the popup also always turns the sounds off, no matter what the actual setting is. The notification 'flash' on the task bar triggers Windows default sounds if desired, so it operates independently from program settings. This allowed granularity on setting what type of notification the user receives. 

The fork seems to fix this issue in most cases now though, so certainly the old code seems to default to the Windows' expected behavior little bit better. In some cases if the popup notifications are turned off, the task bar notifications also disappear. But I can't yet replicate the exact circumstances reliably yet. This could be just caused by another instance of Hangouts on my mobile device.

But overall this fork returns the default behavior in practically all cases at the moment. I'll keep running the fork for time being and seeing how it behaves.

**Comment by averissimo** [comment]
Can you also try this one: https://github.com/averissimo/yakyak/releases/tag/v1.5.10-fix1206-2

Thanks

**Comment by Anttiac** [comment]
So far 1206-2 fork seems to behave reliably when it comes to showing notifications now. All combinations of settings seem to also result in the expected notification behavior.

Only issue that I noticed is likely related to the library used for creating pop-up notifications. This issue I believe is also present in stable versions, so not related to this current issue as such and it doesn't affect the functionality of the notifications.

![image](https://user-images.githubusercontent.com/67882037/86772405-a2dae480-c05c-11ea-88b6-3ebd0bcabe10.png)

Pop-up notifications sent by YakYak are all called SnoreToast in Windows. Disabling "Show YakYak icon in notifications" results in SnoreToast icon appearing, with (YakYak) after the username of the sender. _popup 2 message in the example._

Enabling show YakYak icon removes all icons and name of the program sending the notification as seen from all the other messages.

This also creates Snoretoast.exe in the start menu, likely resulting from the lack of --appID parameter as described on https://github.com/KDE/snoretoast

This last issue doesn't affect the behavior logic of the notifications as I mentioned, and is present in the stable version pop-up notifications as well. So it can be considered as a separate issue to this current one.

**Comment by averissimo** [comment]
Ok, cool I'm merging it to beta-version.

Thanks for the help.
