### ISSUE TITLE
Tray Icon - can we hide it?

### ISSUE THREAD

**Issue by kecinzer** [yakyak/yakyak#121]
Is there somewhere option to hide tray icon? It's annoing for me and I would like to hide it.
Thanks.

OSX app.

**Comment by davibe** [comment]
We need to create a 'settings' area for things like this one. It's not done yet

**Comment by x-tk** [comment]
The ability to toggle between the tray vs the dock would be nice.  Also the ability to customize the icon easily would be nice, I prefer more of a "chat/messaging" style icon than the book look.

**Comment by davibe** [comment]
this is in master, will probably do a 1.1.3 release soon
