### ISSUE TITLE
Gulp/Deploy Broken on Windows

### ISSUE THREAD

**Issue by hexane360** [yakyak/yakyak#1210]
By adding `electron-installer-debian` to devDependencies in de56f180d81bb0deb2ff82f6807d57dadfe8ea42, installation is now broken on Windows. npm gives the following error message:
```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for electron-installer-debian@3.1.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

To fix this, `electron-installer-debian` should be moved to `optionalDependencies`, and `require('electron-installer-debian'` should be replaced with `try require('electron-installer-debian')`. This is exactly how `electron-installer-flatpak` is handled presently.

Let me know, and I can make a PR for this change.

**Comment by averissimo** [comment]
Opps, my bad!

A PR would be great!
