### ISSUE TITLE
Google Voice

### ISSUE THREAD

**Issue by SeanMGonzalez** [yakyak/yakyak#1216]
This is less an issue and more an inquiry. I love the app, great design! Hangouts has been transitioning to Google Voice, any plans to integrate YakYak with GVoice? Keep up the great work :)

**Comment by averissimo** [comment]
Yakyak is a text-based client. And all the main developers of this project lived in Europe and don't use Google Voice.

We'd welcome a motivated developer that wishes to push forward with GVoice integration.
