### ISSUE TITLE
No notifications since updating to macOS 10.15.5

### ISSUE THREAD

**Issue by sriharshachilakapati** [yakyak/yakyak#1218]
I'm not getting any notifications since updating to macOS 10.15.5. I have updated YakYak first in macOS 10.15.4, and then updated the OS. It showed notifications before updating OS, but not now.

There is nothing suspicious in the developer console as well. Just a few warnings stating 'couldn't load sourcemaps'.

![developer tools](https://user-images.githubusercontent.com/4593204/87562479-bd0b6700-c6db-11ea-8a19-8d6703a2fe26.png)

![YakYak about screen](https://user-images.githubusercontent.com/4593204/87562582-d01e3700-c6db-11ea-8cd5-68bb8ceaecab.png)

Weird thing is, there is also no entry of YakYak in the Notifications preference pane. Seems like OS is not aware that YakYak sends notifications. However, whenever a message appears, the dock icon does bounce. I have also checked whether notifications are enabled in the menu, and they sure are checked.

**Comment by averissimo** [comment]
I was wrong, this is in fact a problem with the beta version.

Related with the packaging of yakyak

> Reduces the number of files included in the release by using an ASAR file

Thanks for reporting, working on it

**Comment by averissimo** [comment]
Can you test the updated version of v1.5.10-beta-rolling after about 25 mins from this comment.

**Comment by sriharshachilakapati** [comment]
Just updated. It indeed asked me whether to allow notifications from YakYak. Thanks!
