### ISSUE TITLE
1.5.10 Beta version Fatal error

### ISSUE THREAD

**Issue by mzso** [yakyak/yakyak#1219]
Hi!

I tried the beta version. There's a persistent bug. When clicking the tray icon I get:
![kép](https://user-images.githubusercontent.com/4479090/87881092-534ece00-c9f7-11ea-9e94-2cf06473237c.png)
And it won't result in the window being shown/hidden. I can only open the window via the toggle option in the icon's context menu.
Otherwise it seems to work normally.

**Comment by averissimo** [comment]
Thanks for testing v1.5.10 and reporting this

what is your operating system?

**Comment by mzso** [comment]
> Thanks for testing v1.5.10 and reporting this
> 
> what is your operating system?

Windows 10.

**Comment by averissimo** [comment]
I believe the bug is corrected in an updated `v1.5.10`, can you check it out?

**Comment by mzso** [comment]
[**@averissimo**](https://github.com/averissimo) commented on [2020. júl. 20. 17:37 CEST](https://github.com/yakyak/yakyak/issues/1219#issuecomment-661116126 "2020-07-20T15:37:33Z - Replied by Github Reply Comments"):
> I believe the bug is corrected in an updated `v1.5.10`, can you check it out?

It appears to be working now.

**Comment by mzso** [comment]
On further usage it doesn't quite work right.
Apparently it captures a click multiple times. The other day I couldn't hide/open it. When I had it opened it just blinked, got hidden and unhidden immediately.
Right now it it flickers several times before showing or hiding the window. Which would mean it the click is applied several times more.

**Comment by averissimo** [comment]
Another user reported the same problem on the v1.5.10 beta issue #1214 it sounds like a bug in the framework, I'll look into it when I can, unless someone wants to try and correct this
