### ISSUE TITLE
yak yak failed to start - Cannot find module 'hungupjs' 

### ISSUE THREAD

**Issue by SimaEnduro** [yakyak/yakyak#1239]
os windows 10
after clink on yak yak icon, error displays
![image](https://user-images.githubusercontent.com/36181102/93738974-778d7d80-fbe7-11ea-9e38-55101e5ea623.png)

**Comment by Collinormous** [comment]
https://github.com/yakyak/yakyak/issues/1234

**Comment by averissimo** [comment]
This is fixed on newer versions
