### ISSUE TITLE
issue with contact list resizing

### ISSUE THREAD

**Issue by msphair** [yakyak/yakyak#124]
if you make it smaller, when icons are on, it ends up clipping the left and not re-adjusting when you resize

<img width="244" alt="screen shot 2016-02-05 at 5 39 32 pm" src="https://cloud.githubusercontent.com/assets/1900880/12863706/90910c6c-cc2f-11e5-96b2-a3f755ddddd0.png">

**Comment by davibe** [comment]
ok. I can reproduce but only if I have starred friends. Needs some CSS love.
