### ISSUE TITLE
Yakyak crashes when starting new conversation

### ISSUE THREAD

**Issue by baspetersnl** [yakyak/yakyak#1241]
When i try to start a conversation with someone that isn't in de coversations list the app crashes, with the following error message;  https://www.dropbox.com/s/hrr7txakd5s7qjd/Schermafbeelding%202020-09-22%20om%2009.27.29.png?dl=0

currently using: yakyak v1.5.10 on MacOS 10.15.5

**Comment by baspetersnl** [comment]
problem also occured on v1.5.9

**Comment by Collinormous** [comment]
https://github.com/yakyak/yakyak/issues/1234
