### ISSUE TITLE
Presence and "… is typing" 

### ISSUE THREAD

**Issue by jcvignes** [yakyak/yakyak#1242]
Hello,

I love YY and I use it daily. For some reason I don't see the "green dot" when my friend is online, nor does it tell me when she is typing… She just sent me a screenshot (using YY too) and she sees a green dot next to me and whether I'm typing…  I thought it might be a Hangout issue, but on the web app (Hangout) I do see the green dot next to her name? 

I know it's a little thing but it's driving me crazy so any help would be greatly appreciated!

Thanks,
JC

**Comment by asacarny** [comment]
Seconding this issue (and I think YakYak is great as well!) I do not see any green dots on my contact list any more.

**Comment by HomerSp** [comment]
Can you check the beta build to see if it's working as intended there?
