### ISSUE TITLE
Possible Fatal Error - macOS 10.15.6

### ISSUE THREAD

**Issue by SpectralGM** [yakyak/yakyak#1244]
When trying to launch YakYak on macOS, I'm getting the following error message "Possible Fata Error on Main Process, YakYak could stop working as expected." Then it sits on "Connecting..." in perpetuity.
<img width="880" alt="Screen Shot 2020-09-24 at 8 42 55 AM" src="https://user-images.githubusercontent.com/50565295/94146615-2f1dcc00-fe42-11ea-9b5c-0dfe1271c733.png">

**Comment by jellisii** [comment]
See #1234

**Comment by lasersocks** [comment]
I have this issue on Ubuntu as well.

**Comment by turboladen** [comment]
FWIW, I'm also getting this on macOS 10.15.7.

**Comment by turboladen** [comment]
...and the workaround listed in #1234 fixed it for me.

**Comment by SpectralGM** [comment]
Can confirm that the fix outlined here: https://github.com/yakyak/yakyak/issues/1234#issuecomment-697455578 seems to have rectified the issue for me.
