### ISSUE TITLE
YakYak is dead

### ISSUE THREAD

**Issue by orion4444** [yakyak/yakyak#1251]
Long live YakYak!

**Comment by dep-dt** [comment]
It was good while it lasted.

**Comment by AAlchemy** [comment]
The last commit was 78 days ago, does anyone know if averissimo is ok? I'm assuming just life getting in the way of code.

**Comment by hnilsen** [comment]
If @averissimo woulld grant other people permission to take control, that would be nice. I'd be willing to carry the torch for a while.

**Comment by dep-dt** [comment]
Hopefully @averissimo didn't get the coronavirus 😬😬😬

**Comment by hnilsen** [comment]
I think he's all right, he's contributing to other projects, so I'm just assuming yakyak isn't a focus any more. Which is too bad, because there are so many people that rely on it still.

**Comment by Spleeen** [comment]
Crashes, instabilities, impossible to connect for weeks. Do you have alternatives?

**Comment by AAlchemy** [comment]
> If @averissimo woulld grant other people permission to take control, that would be nice. I'd be willing to carry the torch for a while.
@hnilsen 
You can always fork it.

**Comment by hnilsen** [comment]
@AAlchemy Sure, but the users are here in this repo, the pull requests, community, issues and everything. Best would be to have a few other people able to contribute here.

**Comment by gigecogary** [comment]
I can't believe the one and only macOS client is now dead and no one is able to make it work. Meanwhile google continues to have no interest in making a native client

**Comment by dep-dt** [comment]
I only recently discovered that going to this URL shows my Hangouts conversations:

https://chat.google.com/

Then I just used Fluid to create a MacOS app for Hangouts. Seems to work well!

**Comment by awgordon** [comment]
> I only recently discovered that going to this URL shows my Hangouts conversations:
> 
> https://chat.google.com/
> 
> Then I just used Fluid to create a MacOS app for Hangouts. Seems to work well!

I haven't been able to get notifications working using this method (not to mention having all links open in same window as chat is annoying) but those are relatively minor. Any luck there?

**Comment by dep-dt** [comment]
Yes, if you navigate to https://chat.google.com/ in Chrome and then visit the 'Settings' menu there should be an option to "Install Desktop App" which will create a standalone Chrome app.

If the option isn't there, you might have it already installed. Goto `chrome://apps` to see Google Chat it's listed.

This is kinda cool because then you can apply your chrome extensions to it.  I've been able to use this method to use "Dark Reader" and "Click to Remove Element" extensions to give it a nice, clean appearance

![](https://dpeck.d.pr/84Hk96+)

Not sure about the Notifications issue though.  I use Pushbullet on my phone to mirror notifications on my desktop, so I can at least continue to get Chats notifications that way.

Worth noting that Google Chat is being slowly rolled out and some people might get a G-Suite error when they visit chat.google.com, but patience prevails, and [you should have access soon](https://arstechnica.com/gadgets/2020/10/google-chat-goes-free-in-2021-while-hangouts-loses-features-this-month/).

**Comment by dep-dt** [comment]
Probably worth emphasizing that [since Hangouts is going away in 2021](https://arstechnica.com/gadgets/2020/10/google-chat-goes-free-in-2021-while-hangouts-loses-features-this-month/) we should all be looking for YakYak alternatives, since it's on its way towards deprecation at this point.

**Comment by awgordon** [comment]
I'm trying to find a workaround that doesn't involve the Chrome app as I tend to use other browsers. The Fluid app solution is working mostly OK for me with the exception of the aforementioned issues.

**Comment by dep-dt** [comment]
>  I tend to use other browsers

What are you using out of curiosity?

**Comment by awgordon** [comment]
Firefox primarily, Opera and Safari when I need to use another one for whatever reason

**Comment by driph** [comment]
Anyone interested in forking the project and continuing from here?

**Comment by dlannan-fmad** [comment]
@dep-dt - Just wondering if Hangouts is being deprecated, how does that effect gmail though - chats is embedded in gmail? Will that disappear as well?

**Comment by dep-dt** [comment]
Hangouts in Gmail will be replaced with Google Chat, but still accessible in Gmail. Everyone will just be migrated over. It'll look mostly the same:

![](https://dpeck.d.pr/E3rzGQ+)

**Comment by solarmosaic-kflorence** [comment]
Google Chat now has a desktop support https://support.google.com/chat/answer/9455386?hl=en

**Comment by hnilsen** [comment]
I would prefer Yakyak over the current state (and probably future state for a long while) of Google Chat. The responsiveness of Google Chat is abysmal, the hot keys I can't get friendly with at all (how to switch conversations and navigate the chats with your keyboard?).

https://support.google.com/chat/answer/7649271?hl=en

**Comment by orion4444** [comment]
YakYak is alive! Thanks @averissimo 

Download latest binaries here: https://github.com/yakyak/yakyak/releases

**Comment by averissimo** [comment]
Sorry about being non-responsive. After a vacations and some changes in my life I've been mostly off-github for the past months and didn't track the project as I should.

The code is stable on our part, but still requires some love and care, and I didn't do that. Again, sorry.

I've started the process of granting access to the repository for @HomerSp, but I don't have the permissions to do that myself and I'm waiting for a reply from another collaborator and huge contributor to this project.

If he doesn't reply soon I'll talk with the founder _(which left the project long well before I created my first pull request)_

Until this is sorted in the next few days I'll test and merge all pull requests.

I really hope Yakyak continues on. @HomerSp just submitted a fix for user status and we also had a pull request to build binaries for mac arm64.

This makes me hopeful!

If additional people want to collaborate on Yakyak, just start a pull request :-) ... even if you don't know exactly all that you should do in this framework I'll be very glad to help out.

**Comment by dep-dt** [comment]
@averissimo 
> I really hope Yakyak continues on. @HomerSp just submitted a fix for user status and we also had a pull request to build binaries for mac arm64.

Thanks for the replies, and I'm glad you're ok. :) 

Do you have any thoughts around how Google's deprecation of Hangouts in favor of Google Chat might affect YakYak? Wouldn't this remove essential APIs needed that YakYak requires in order to function properly?

**Comment by averissimo** [comment]
https://github.com/tdryer/hangups/issues/477#issuecomment-505260765

> Yes, I expect hangups will stop working when Hangouts "classic" is shut down.

Probably not the answer you're looking for, but our backend is a javascript rewrite of tdryer/hangups, so his answer is our answer.

### what will be needed?

A new backend in javascript, probably after some reverse engineering with the protocol _(same that happened with our current backend)_

Google becomes a generous god and publishes the protocol or a js library _(really unlikely)_

### Some hope?

Given there are other electron-based hangouts apps, I hope that a new js backend will pop up eventually _(either by a yakyak contributor, from one of those projects, or even a collaboration)_

An alternative to this scenario, would be a python backend that pops from tdryer's and we just need to re-write it in javascript.

In the end, we just need something that can communicate with google and publish the same set of events as we now use _(at least for a seamless transition)_

**Comment by crunchprank** [comment]
Apologies for going a bit off topic here, but seeing as this conversation was already started and the ticket has been closed, I thought I wouldn't spam the Issues section with such a general question.

In regard to the users commenting about using Google Chat, my understanding is that Chat is not an available service to the public right now and is only available to G Suite members. Is that a correct assumption? When I browse to `https://chat.google.com/`, I simply see the following:

![](https://i.imgur.com/8ocoN3v.png)

**Comment by solarmosaic-kflorence** [comment]
@crunchprank Google Chat works fine for personal accounts. If your account is part of a company workspace, admins will need to enable support for it as a feature, as it says there.

**Comment by crunchprank** [comment]
@solarmosaic-kflorence I should have clarified, I'm going to that link and seeing that image from my personal account - not a business account.

**Comment by solarmosaic-kflorence** [comment]
@crunchprank strange. Is your personal account also a business account? Chat works fine for me in my personal account. Might want to reach out to Google support.
