### ISSUE TITLE
Possible fatal error on main process, YakYak could stop working as expected.

### ISSUE THREAD

**Issue by adampatterson** [yakyak/yakyak#1256]
For a few weeks now, when I open YakYak I get `Possible fatal error on main process, YakYak could stop working as expected.`

Looking in the inspector I see

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at conv.coffee:17
    at add (conv.coffee:17)
    at Object._initFromConvStates (conv.coffee:271)
    at Object.init (dispatcher.coffee:37)
    at doAction (/Applications/YakYak.app/Contents/Resources/app/node_modules/trifl/lib/action.js:45)
    at action (/Applications/YakYak.app/Contents/Resources/app/node_modules/trifl/lib/action.js:21)
    at Object.init (dispatcher.coffee:25)
    at app.coffee:163
    at EventEmitter.<anonymous> (app.coffee:87)
    at EventEmitter.emit (events.js:223)
```

I am running YakYak **v1.5.9** on Mac OS **10.15.6 (19G2021)**

**Comment by lividhen** [comment]
https://github.com/yakyak/yakyak/issues/1234
does this help?

**Comment by adampatterson** [comment]
@lividhen Hey, was there a specific response that I should look at?

**Comment by lividhen** [comment]
https://github.com/yakyak/yakyak/issues/1234#issuecomment-697297068

Depending on what os there are different ways to access the file, but the on you need to edit is conv.js. i am not sure how to get to it on mac.

**Comment by donpdonp** [comment]
https://github.com/yakyak/yakyak/issues/1234#issuecomment-715927573 fixes this problem on yakyak 1.5.8 linux. Please make a release for this. I stopped using yakyak for a couple months because the fix was unclear. https://hangouts.google.com/ is good in a pinch, but yakyak is a better solution. thanks!

**Comment by adampatterson** [comment]
@donpdonp Same, using Hangouts in the browser is terrible!

**Comment by lividhen** [comment]
https://github.com/lividhen/yakyak/releases/tag/Final
here, i forked it and uploaded with the fix if you haven't already fixed it.

**Comment by ds-tx** [comment]
@lividhen - I installed your v.10 beta (yakyak-1.5.10-osx) on MacOS 10.13.6 High Sierra, and problem persists.
At first, app opening simply shows "connecting" but never connects.
Then, if I let it try to connect long enough, the same error message as with v.9 appears, then disappears - Possible fatal error on main process, YakYak could stop working as expected.
I'd really like to try out the app, but I can't get it to connect to my gmail account, and error message appears in v.10 beta just as it did in v.9 install.
I completely uninstalled all v.9 files before install v.10 beta.

**Comment by solarmosaic-kflorence** [comment]
This is the same issue as #1234 -- which has a workaround that fixes it on Mac OS 10.15.6.

**Comment by AtmaDarkwolf** [comment]
Personally, tried each of the fixes in that thread, then all at once (with fresh 1.5.10 each time) and does not fix issue, please stop pointing people to a very old thread that will get limited attention due to 'it working for some' and not others.

Although flooding page with the same issue is a problem, in this case, where it is quite obvious it is still a widespread issue, and the instructions in 1234 fail to fix it for many, a new issue would get better attention to those who CAN fix it.

Thanks.

**Comment by solarmosaic-kflorence** [comment]
@AtmaDarkwolf just pointing out that this ticket should be closed as a duplicate, and also confirming that the fix mentioned in the other ticket worked for me on the same OS version as the OP.

**Comment by adampatterson** [comment]
I'm on a brand new fresh install of macOS and just installed the app, I still have this problem.

**Comment by solarmosaic-kflorence** [comment]
With hangouts being deprecated, I have just given up on YakYak and switched to https://chat.google.com/ https://github.com/yakyak/yakyak/issues/1251

**Comment by adampatterson** [comment]
@solarmosaic-kflorence I am already trying to cope with the loss of Google Music, not sure I can take the loss of Hangouts as well. 😭

**Comment by adampatterson** [comment]
The latest Beta release for now works!

**Comment by averissimo** [comment]
The latest stable release should also work

**Comment by adampatterson** [comment]
Awesome feels so good to have the app back even if it's for a short period of time.

Does the team have any plans to switch over to Google Chat?

**Comment by averissimo** [comment]
Not at this moment, see https://github.com/yakyak/yakyak/issues/1251#issuecomment-743317594
