### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by LEV7n** [yakyak/yakyak#1258]
![10-26-2020_10-04-51](https://user-images.githubusercontent.com/3475776/97135738-02c3db00-1773-11eb-8743-4c25ad98a29b.png)

**Comment by LEV7n** [comment]
![10-26-2020_10-12-30](https://user-images.githubusercontent.com/3475776/97136038-d52b6180-1773-11eb-96e2-3b2bb5e26783.png)
Fixed the issue

**Comment by LEV7n** [comment]
![11-08-2020_12-39-16](https://user-images.githubusercontent.com/3475776/98459894-01f26680-21c1-11eb-8f57-662173b266ce.png)

After update

**Comment by dlannan-fmad** [comment]
I get the same problem running the last two releases on debian10

**Comment by HomerSp** [comment]
Closing as the first issue is fixed, and the second looks to be a duplicate of #1254
