### ISSUE TITLE
arm builds. 

### ISSUE THREAD

**Issue by necrose99** [yakyak/yakyak#1260]
**https://github.com/electron/electron/releases/download/v9.3.4/electron-v9.3.4-linux-arm64.zip**
upstream isssue is solved. 
https://github.com/Zerx0r/Kage/issues/21  ,

kage builds on rpi64 Gentoo/Pentoo..  with a bit of hacking to json file as mentioned. in **[#21](https://github.com/Zerx0r/Kage/issues/21)**  i didnt want an app image.   similar example hopefully yarn/electron to build in it's case.  so i opted for a manual build. 

and was able to do rpm/deb or tarball instead of just appimage as a bonus i found the **_muti-platform-build_** , since i also have been port building pentoo packages against the arm64 gentoo rpi image. 

Rasberrypi-OS now offers 64bit images. 

the mentioning also can build arm7hf via the electron builder.  ie in iss.21 on kage. 

_yarn run build --linux --arm64 --armv7l , -mwl also works apparently_  (with kage , as an example) 

_(https://www.electron.build/multi-platform-build )_

_electron-builder -mwl / yarn run build -mwl outputs even a macos pkg...
--linux --arm64 --armv7l_

#962 

hopefully  yakyak could likewise offer more packages.. in arm/arm64 flavors since upstream issue's been solved. 

the electron builder will crossbuild.

**Comment by averissimo** [comment]
This support was added today by a new contributor for Mac OS arm64 in particular, but it also covers other platforms.

Can you test this version: https://github.com/averissimo/yakyak/releases/download/v1.5.11-arm64-averissimo/yakyak-1.5.11-linux-arm64.tar.gz
