### ISSUE TITLE
Yak Yak Not Opening

### ISSUE THREAD

**Issue by Wasca** [yakyak/yakyak#1266]
Hi Guys

I'm getting this error when opening Yak Yak v1.5.9 today, it was working perfectly fine yesterday. I'm unsure what could be causing it.

I'm running macOS High Sierra 10.13.6

![Screen Shot 2020-12-04 at 10 17 00 am](https://user-images.githubusercontent.com/869112/101105702-f6f0f180-3619-11eb-9a23-c99b3cf71af0.png)

Yak Yak opens but it's just a blank screen.

![image](https://user-images.githubusercontent.com/869112/101105802-3c152380-361a-11eb-8cac-7197893c26ea.png)

This is the error in the console

![image](https://user-images.githubusercontent.com/869112/101105972-aa59e600-361a-11eb-945d-366065ec8738.png)

**Comment by Wasca** [comment]
My YakYak seems to be working again. Only thing I did was update my Chrome browser, not sure if it's related.

**Comment by jeffbyrnes** [comment]
@Wasca glad it’s working again! Seems like you can close this out, in that case.
