### ISSUE TITLE
In 1.5.10, scrolling up a little bit in a chat causes YakYak to load message history and scroll up further

### ISSUE THREAD

**Issue by smammy** [yakyak/yakyak#1271]
Steps to replicate:
1. Upgrade to 1.5.10.
2. Open a chat with some history.
3. Scroll up at all.

Expected result:
When you stop scrolling, the window stays put.

Actual result:
When you stop scrolling up, after a couple of seconds (presumably network delay) the scroll position changes. Scrolling further causes more unpredictable jumps around. It's sometimes hard to get it to scroll to a particular position and stop. It' sometimes hard to get it to scroll back down to the bottom.

Note:
If I disconnect from the internet before scrolling up, this doesn't happen, so I think it's probably related to message history loading. History loading has always been a little janky but at least in previous versions it didn't get triggered until I had scrolled all the way up.

macOS 10.15.7 (19H15) on MacBook Pro (16-inch, 2019)

**Comment by zackotronic** [comment]
can confirm that this occurs on macOS Big Sur

**Comment by m00dawg** [comment]
In Linux (Mint 19.3) and for me it seems to scroll up randomly and then stays there so I have to scroll back down again. Seems to happen while I'm typing. Otherwise looks to be a similar issue as well.

**Comment by Mibix** [comment]
Happens for me in windows 10 LTSC as well

**Comment by larstobi** [comment]
second confirm that this occurs on macOS Big Sur

**Comment by smammy** [comment]
Before this gets out of hand: please, folks, don't add "+1"/"ditto" comments on this issue. You can react 👍 to the original comment and/or subscribe to the issue instead. Thanks!

**Comment by tylerbrockett** [comment]
Windows 10 user here. May be related to images in the chat. Seems to jump around those a ton, but plain text isn't so bad.

I thought this issue was present in past releases, but it may have gotten worse with this release or something.

**Comment by joecoolio** [comment]
This appears to be fixed in the rolling beta as of December 17, 2020.
