### ISSUE TITLE
Wild and unexpected scrolling behavior

### ISSUE THREAD

**Issue by joecoolio** [yakyak/yakyak#1280]
In Yakyak 1.5.10 on Windows 10, I'm seeing a periodic weird scrolling problem.  I click on one of my contacts and it pops up.  Then it starts scrolling backwards in time and never stops.  The only way to stop it from continuing backwards in time is to click on a different contact and then come back.  Sometimes, it doesn't scroll all crazy but starts in the past instead of on the latest messages.

Very intermittent and just started on the latest release.  Was something changed on the scrolling that could do this?

**Comment by averissimo** [comment]
Can you test the beta version? I think that issue is resolved there.

**Comment by joecoolio** [comment]
Certainly!  What exact version should I test?

**Comment by joecoolio** [comment]
Nevermind, #1273 looks like it might be related so I'll get the version with that fix in it.  Thanks!

**Comment by averissimo** [comment]
The prerelease v1.5.11-beta-rolling

I was waiting for people to test it out, but it seems some are already using it. _(from another issue)_

**Comment by HomerSp** [comment]
You're not alone as per #1271, but the good news is that this issue should indeed be fixed in the rolling release. Please let us know if you manage to test it so we can know for sure if it's fixed or not.

**Comment by joecoolio** [comment]
Yes, this appears to be fixed with the patch for 1271!  Awesome!

**Comment by jaydawgx7** [comment]
Also confirmed switching to the beta/rolling updates solves the scrolling issue

**Comment by averissimo** [comment]
Thanks @HomerSp
