### ISSUE TITLE
[solved] 1.5.11 Windows 10 missing directory resources/app/media

### ISSUE THREAD

**Issue by crix-lab** [yakyak/yakyak#1284]
It used to be possible to replace new_message.ogg (in resources/app/media) with another sound, but there is no such directory (or ogg files available) in v. 1.5.11, stable or beta. 

 It would be nice to have the possibility back.

Thank you anyway for your work!

**Comment by crix-lab** [comment]
My fault - there is nothing missing but my knowledge about .asar files :D

**Comment by averissimo** [comment]
It's possible to add an exception to the asar build to avoid packing that file in `gulpfile.coffee`

if you want to, please create a pull request with that change.
