### ISSUE TITLE
Unable to open 1.5.11 on Windows 10

### ISSUE THREAD

**Issue by definitelysmib** [yakyak/yakyak#1285]
When attempting to open, I get the attached error message. The Inspector won't open, so I don't know how to give any more detail.

![yakyakerror](https://user-images.githubusercontent.com/46250775/102681060-4f80cc80-418c-11eb-8e05-7ceecdcbac3e.PNG)

I've tried deleting the folder in AppData/Roaming and restarting, which pretty much sums up the tricks I know of to remedy problems.

**Comment by sneakyjoeru** [comment]
![image](https://user-images.githubusercontent.com/54816725/102686506-35310800-41f9-11eb-88f7-fcde5d33982d.png)
![image](https://user-images.githubusercontent.com/54816725/102686511-3b26e900-41f9-11eb-8c36-8da01b1a5baa.png)

Having it too (tried last and previous versions)

**Comment by HomerSp** [comment]
@definitelysmib Do you get the same error on 1.5.10? It may be due to electron being updated to v11, though I'm not entirely sure. It's a bit annoying since it's not happening for everyone. I'm working on something that should fix this anhow, so if 1.5.9 is working I would probably stick with that for now.

**Comment by sneakyjoeru** [comment]
@definitelysmib Ctrl+Shift+i to open dev tools

**Comment by definitelysmib** [comment]
@HomerSp I have not tried 1.5.10, sticking with 1.5.9 for now.

@sneakyjoeru That also doesn't work for me.

**Comment by jorrit** [comment]
I added `enableRemoteModule: true` twice to main.js because of this StackOverflow answer:

https://stackoverflow.com/a/37893140/261747

**Comment by HomerSp** [comment]
Could you all test the latest 1.5.12 beta from here to see if it's still crashing: https://github.com/yakyak/yakyak/releases/tag/v1.5.12-rolling-beta

**Comment by sneakyjoeru** [comment]
Yes, it lanunched just fine, but struggled to load my theme for a few seconds.

**Comment by HomerSp** [comment]
> Yes, it lanunched just fine, but struggled to load my theme for a few seconds.

Thanks for checking, that's good! I'll check what's going on with the theme not loading. It seems to be instant for me, but I have a few ideas of what it might be so I'll try and get this sorted for the proper release.

**Comment by definitelysmib** [comment]
The 1.5.12 beta also worked for me. No issue with loading the theme, either.

Thanks for the fix.

**Comment by Matt-Wetzel** [comment]
This is happening for me in both 1.5.11 and the 1.5.12 beta.
