### ISSUE TITLE
OSX: notification popup doesn't bring up minimized window

### ISSUE THREAD

**Issue by kecinzer** [yakyak/yakyak#129]
I just noticed, that if I minimize main window of YakYak and someone write me, I can see popup, but when I click on it, to bring window up and reply, it do nothing.
Popup click only works when window is not minimized.

**Comment by davibe** [comment]
are you talking about the "minimize to tray" feature ? are you on windows ?

**Comment by kecinzer** [comment]
No one else have this issue?

**Comment by randymorris** [comment]
I can confirm this behavior on OSX (El Captain) in Version 0.34.1 (1.1.3).
