### ISSUE TITLE
Error occurred in the main process

### ISSUE THREAD

**Issue by Neuroxiide** [yakyak/yakyak#1295]
Everytime i try to open V1.5.11, V1.5.10, or the V1.5.12 beta it gives me this error
![Screenshot 2020-12-27 213301](https://user-images.githubusercontent.com/44472684/103185708-91e09280-488b-11eb-93e5-fe8c384d4696.png)

**Comment by averissimo** [comment]
Can you try to remove yakyak's local folder at `c:\Users\neuro\AppData\Roaming\yakyak`

and then run it again (you'll need to login again)

**Comment by Neuroxiide** [comment]
That worked, thanks so much!
