### ISSUE TITLE
All contact names show as "Unknown" on new conversation screen

### ISSUE THREAD

**Issue by ajs256** [yakyak/yakyak#1306]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/67526318/107253048-c5feb580-69ea-11eb-98cf-3dda4d43ad5e.png">
- macOS 11.1
- YakYak v1.5.11 (latest)

Console output consists of a bunch of `setpresence: User 'person name' does not show his/hers/it status [Object]` as well as a `Warning: could not retrieve message input to store.`

**Comment by cwmcbeejr** [comment]
I get the same thing on windows 10 64 bit using 1.5.11 (latest) as well. 
![error](https://user-images.githubusercontent.com/16760106/111335012-097bbd80-8642-11eb-81a3-504032951e5d.png)

**Comment by HomerSp** [comment]
Working on a fix for this

**Comment by HomerSp** [comment]
The latest beta has a fix for this now, so feel free to test it and let me know if it works.

**Comment by ajs256** [comment]
It works now, thank you so much @HomerSp! I will close this issue now.
