### ISSUE TITLE
Close to tray - does not reopen - Win x64

### ISSUE THREAD

**Issue by skanadian** [yakyak/yakyak#1346]
winx64 latest release.

With "Close to tray" selected, close the app.  When clicking on the system tray icon to restore the app, yakyak rapidly fills the task bar with processes before it disappears completely.  The app does not become visible.

If you right click the tray icon and click "toggle window show/hide" it appears normally.

**Comment by HomerSp** [comment]
Could you open yakyak through cmd and post the output here? I'm unable to reproduce this issue using the latest release, so I'm not sure what might be going on.

**Comment by skanadian** [comment]
Command prompt does not show anything exciting while the bug is occurring.  Is there a flag for higher verbosity?

C:\Program Files\yakyak-win32-x64>
Starting Yakyak v1.5.11.3...
  using hangupsjs v1.3.11
syncrecentconversations: Asking hangouts to sync recent conversations
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
Goodbye

The window closes and restores normally as long as the first conversation is selected.  If I leave an older conversation selected the bug occurs.  If I use the menu option to restore window, select the first conversation again, the bug goes away.

I'm also unable to hide the window by clicking the tray icon with an older conversation selected.

Occurs on both my systems.   Win7 x64 and Win 10 x64.  Tested i386, did not help.

I did not experience this with previous versions.  Unfortunately I can't recall my last version, I only upgrade when things break.

It seems the beta is not affected, I will run that.  Let me know if you need any other information.

**Comment by HomerSp** [comment]
Thanks for the additional info! It's fixed by this commit in the beta, which is why you're not seeing it there: https://github.com/yakyak/yakyak/commit/c105351eb91f004facc9f2ad511dffb777f49a52 It basically happens because the click listener for the tray is added multiple times which causes it to toggle the window visibility as many times as it's been added. That commit fixes it by ensuring the click listener is only added once.
I'll backport that and release a new stable version today.

**Comment by HomerSp** [comment]
I've released 1.5.11.4 which fixes this, please let me know if it works!

**Comment by skanadian** [comment]
Confirmed resolved!  Thank you!
