### ISSUE TITLE
Unable to close to tray

### ISSUE THREAD

**Issue by boekkooi** [yakyak/yakyak#135]
Hi there,

So in version 1.1.2 I was able ti hit the X (close) button in the window and it would close to the tray icon this function seems to be gone in 1.1.3. 
Could you tell me where to look so i can reintroduce this?

Cheers,
Warnar

**Comment by Georgeto** [comment]
+1

**Comment by Georgeto** [comment]
In 1.1.2 [this piece of code](https://github.com/yakyak/yakyak/blob/v1.1.2/src/main.coffee#L355-L361) was responsible for the minimize to tray instead of close feature.

**Comment by Jimi-James** [comment]
+1

**Comment by boekkooi** [comment]
Closing since there is a PR for this. Thanks for the pointer @Georgeto

**Comment by Jimi-James** [comment]
I'm still having the issue on Arch Linux. It quits instead of closing to tray. Running 1.2.0.
