### ISSUE TITLE
Google Chat pictures do not show up in YakYak

### ISSUE THREAD

**Issue by joecoolio** [yakyak/yakyak#1366]
When someone shares a picture from Google Chat to me using YakYak, I get this:
> I shared "Image_20210720_142417.(null)" using the new Google Chat.
> Click here to view.

Also, if I send a picture from Google Chat on Android and then look at the conversation in YakYak, I see the same thing.

I would expect the image to appear inline - is that not happening on purpose?

**Comment by HomerSp** [comment]
It's Google doing that, which is a pain - I'm guessing they want everyone who's using third-party clients to switch over to Google Chat. I've added a workaround in the latest beta release though, so please give that a try and let me know if it works for you.

**Comment by joecoolio** [comment]
Big pimpin!  It works just fine now!  For my test, I sent a picture to someone from my Android phone using Chat.  Before it would show "I shared ..." but now the picture just pops up.

Perfect!

**Comment by HomerSp** [comment]
Great, thanks for confirming! I'll close this now.
