### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by x-tk** [yakyak/yakyak#137]
There is not an issue, but what about a feature to enable light mode vs dark mode?  basically white background vs black background?  

thanks for all you do

**Comment by vandasian** [comment]
Having user-pickable colors would be best :) I've seen many dark modes that (IMHO) were unusable because of the color choices (straight black, weird combos of grays, etc.)

**Comment by x-tk** [comment]
Either way but light/dark modes until full features are still cool.

**Comment by mrohr** [comment]
I've created a pull request for a dark theme (themes in general) implementation.  #146

**Comment by vandasian** [comment]
:+1:
