### ISSUE TITLE
YakYak fails to start after upgrade to glibc 2.34

### ISSUE THREAD

**Issue by V-Z** [yakyak/yakyak#1377]
I recently upgrade my openSUSE Linux system and it now uses glibc 2.34. Since the YakYak fails to start:
```
$ /opt/yakyak/yakyak
Starting Yakyak v1.5.11.5...
  using hangupsjs v1.4.0-beta
--------
[19522:0924/111705.562176:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
```
The computer is desktop with AMD CPU and Radeon RX 550 640SP graphics. I don't know if the failure is related to the glibc update, but I don't see any other relevant change in recent updates. Also I don't have (other) problems with graphical driver.

**Comment by V-Z** [comment]
It seems the problem is in general (in)compatibility of Electron-based applications with glibc 2.34. Temporal workaround is usage of `/opt/yakyak/yakyak --disable-gpu-sandbox`. Everything then works.

**Comment by lipoja** [comment]
I would like to confirm this issue. I hit this after upgrading to Fedora 35 which is using `glibc-2.34-8.fc35.src.rpm`

**Comment by HomerSp** [comment]
Sorry for the delayed response - apparently this issue was fixed in electron 13.5.0, so I've updated the beta to use that. Please test it and let me know the result. Thanks!

**Comment by V-Z** [comment]
Thank You for the fix, but I can't install `yakyak-1.5.12-beta-linux-arm64.rpm` on openSUSE:
```
sudo zypper in yakyak-1.5.12-beta-linux-arm64.rpm
Loading repository data...
Reading installed packages...
'_tmpRPMcache_:yakyak=0:1.5.12_beta-1' not found in package names. Trying capabilities.
No provider of '_tmpRPMcache_:yakyak=0:1.5.12_beta-1' found.
Resolving package dependencies...
Nothing to do.
```
The previous releases I could installed without any problem... :-(

**Comment by HomerSp** [comment]
@V-Z Looks like an issue with zypper, see eg https://forums.opensuse.org/showthread.php/410095-Install-local-rpm-with-dependency-rezolving https://forums.opensuse.org/showthread.php/534960-zypper-wont-install-local-rpms . Not sure why it started happening now, and hasn't before, but the solution seems to be to set up a local repository in yast and install the rpm from there.

**Comment by V-Z** [comment]
Hm, I was probably still sleeping and confused `arm` and `amd`... :-D Installation of correct RPM package works and YakYak starts and works normally, so the issue seems to be solved.

**Comment by HomerSp** [comment]
No worries - thanks for confirming the fix!
