### ISSUE TITLE
App Badge shows up on outgoing messages on Mac

### ISSUE THREAD

**Issue by DevinFalgoust** [yakyak/yakyak#138]
The App Badge shows up both in the friends list and on the app icon in the Dock when sending a message to anyone. The badge goes away in a second or two, but it's still a bit annoying.

**Comment by davibe** [comment]
known problem, will fix

**Comment by averissimo** [comment]
is this still a problem?

**Comment by davibe** [comment]
i don't think so it was fixed long ago
