### ISSUE TITLE
Add 'About' menu item

### ISSUE THREAD

**Issue by martin-g** [yakyak/yakyak#140]
Today I've downloaded 1.1.3 but I am not really sure that this is the version I actually use because there is no "About" menu item.

Running Ubuntu 15.10.

Please let me know if you need more information.

**Comment by x-tk** [comment]
Haven't installed on Linux but on the MAC side, the About is under the main "Yakyak" option.

**Comment by martin-g** [comment]
Having an "About" page is not something very important to me.
Having a way to get that information from the Dev Tools would be fine too.
Or old school like "yakyak --version".

**Comment by averissimo** [comment]
implemented in 1.4.0 help -> menu :)
