### ISSUE TITLE
Sent message stays in the text box

### ISSUE THREAD

**Issue by martin-g** [yakyak/yakyak#141]
With the upgrade from 1.1.2 to 1.1.3 the sent messages stay in the "Message" text box after sending them by pressing ENTER key.
I.e. I type something in the textbox and I press ENTER. In 1.1.2 the message moves to the list of messages above the textbox. With 1.1.3 the message moves to the list but doesn't disappear from the textbox, so I have to select it and remove it (Ctrl+a, Del).

OS: Ubuntu 15.10
Arch: 64bit

**Comment by harmonymeow** [comment]
It happens in Windows 10 64bit, too.

**Comment by x-tk** [comment]
Same on OS X

**Comment by yermulnik** [comment]
Same here (Linux Mint 17.1 Rebecca)

**Comment by jnbek** [comment]
Behavior replicated on Arch Linux

**Comment by yeahbert** [comment]
Also happens on Ubuntu Mate 15.10

**Comment by vician** [comment]
Still testing it but it seems to be fixed in version 1.2.0
