### ISSUE TITLE
OS X: Notification shows the message information while on screensaver

### ISSUE THREAD

**Issue by x-tk** [yakyak/yakyak#142]
Just a privacy thing, the message notification shows the message details even while the screen saver is up on the background.

**Comment by cyril-bouthors** [comment]
It's not a bug, it can be configured in the OS X Notifications.

**Comment by x-tk** [comment]
Yeah, I mean I don't mind them displaying but the problem is that they show the actual message in them. This doesn't happen with the built in messaging app.  I suppose I can just turn it off as mentioned.
