### ISSUE TITLE
Option to use Noto Emojis on OS X

### ISSUE THREAD

**Issue by Cortys** [yakyak/yakyak#143]
OS X shows the system emojis by default and ignores the Noto Font. I guess this is intended.

However it would be nice if there was an option to change this behavior.

Using CSS only I wasn't able to quickly replace the system emojis, so I'm not sure whether this is an easy request. Maybe every emoji would have to be replaced programmatically to circumvent the OS emoji rendering.

**Comment by Nxt3** [comment]
#108

**Comment by Cortys** [comment]
@Nxt3 That pull request does not quite cover this issue if I'm not mistaken.

The Noto Emojis added in #108 are only visible on Windows and Linux, OS X shows the system emojis instead.

**Comment by Nxt3** [comment]
Oh. Weird. I figured they'd have it for us as well. :| My bad!

**Comment by vandasian** [comment]
@Cortys not quite, see #132

**Comment by Cortys** [comment]
@vandasian Ah, ok. Didn't test it on Windows and just assumed it would work there.

This is what I get on OS X:
![screenshot 2016-02-23 14 24 34](https://cloud.githubusercontent.com/assets/1737630/13252926/8fbe6e98-da39-11e5-930d-bf507c5c08d1.png)
