### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by austin-guevara** [yakyak/yakyak#147]
I'm going to try to implement some of these changes myself, but I must admit that I'm more of a designer than a developer.

I would love to see some visual improvements to the UI. A phenomenal example of how the future YakYak could look is this Whatsapp redesign on Behance: [https://www.behance.net/gallery/24706121/WhatsApp-for-OS-X-Yosemite-App-design-concept].

Additionally, I believe the font choice needs updating: perhaps Roboto, which is a beautiful UI face and is the official font for Google UI.

**Comment by thekonofman** [comment]
Couldn't agree more with both of those points.


—
KONRAD KOSMALA University of North Carolina at Chapel Hill
Kenan-Flagler Business School
Signature Image [https://www.dropbox.com/s/657lcs5mf6e8pbs/Konrad%20%7C%20Cir_Sig.png?dl=1]
On Wed, Mar 2, 2016 at 10:09 AM, Austin Guevara <notifications@github.com>
wrote:
I'm going to try to implement some of these changes myself, but I must admit
that I'm more of a designer than a developer.

I would love to see some visual improvements to the UI. A phenomenal example of
how the future YakYak could look is this Whatsapp redesign on Behance: [ 
https://www.behance.net/gallery/24706121/WhatsApp-for-OS-X-Yosemite-App-design-concept
[https://www.behance.net/gallery/24706121/WhatsApp-for-OS-X-Yosemite-App-design-concept] ].

Additionally, I believe the font choice needs updating: perhaps Roboto, which is
a beautiful UI face and is the official font for Google UI.

**Comment by maxkueng** [comment]
Wow that mockup looks really nice! I agree YakYak doesn't look very pretty at the moment and It'd be really nice if it did.

**Comment by austin-guevara** [comment]
I would be happy to create mockups more specified to the existing functionality w/in YakYak as it stands now if any of the developers would be interested in implementing it.

**Comment by x-tk** [comment]
Agreed with above, would be nice to add a lot of those design elements.

**Comment by austin-guevara** [comment]
Working on mockups now, should be done in a couple of days.

**Comment by austin-guevara** [comment]
Hey everyone,

Did a quick mockup in my free time, to let us dream of YakYak's future... let me know what you think!

![render](https://cloud.githubusercontent.com/assets/14018074/13725200/83331894-e868-11e5-94e0-61c33fa339c7.png)

**Comment by thekonofman** [comment]
This looks great. Nice job.


—
KONRAD KOSMALA University of North Carolina at Chapel Hill
Kenan-Flagler Business School
Signature Image [https://www.dropbox.com/s/657lcs5mf6e8pbs/Konrad%20%7C%20Cir_Sig.png?dl=1]
On Sat, Mar 12, 2016 at 12:39 PM, Austin Guevara <notifications@github.com>
wrote:
Hey everyone,

Did a quick mockup in my free time, to let us dream of YakYak's future... let me
know what you think!

render
[https://cloud.githubusercontent.com/assets/14018074/13725200/83331894-e868-11e5-94e0-61c33fa339c7.png]
[https://cloud.githubusercontent.com/assets/14018074/13725200/83331894-e868-11e5-94e0-61c33fa339c7.png]

—
Reply to this email directly or view it on GitHub
[https://github.com/yakyak/yakyak/issues/147#issuecomment-195805583] .[https://github.com/notifications/beacon/AQvP0gpzIlpdZe4SSOqrBuBHa6OGRKhWks5psySdgaJpZM4HnhJ7.gif]

**Comment by austin-guevara** [comment]
Better with rounded corners.
![rounded-corners](https://cloud.githubusercontent.com/assets/14018074/13725225/57325b32-e869-11e5-8733-ef8806f69bd9.png)

**Comment by thekonofman** [comment]
Yeah looks a tad cleaner. Though the sharp corners gave it a different
personality.


—
KONRAD KOSMALA University of North Carolina at Chapel Hill
Kenan-Flagler Business School
Signature Image [https://www.dropbox.com/s/657lcs5mf6e8pbs/Konrad%20%7C%20Cir_Sig.png?dl=1]
On Sat, Mar 12, 2016 at 12:46 PM, Austin Guevara <notifications@github.com>
wrote:
Better with rounded corners.
rounded-corners
[https://cloud.githubusercontent.com/assets/14018074/13725225/57325b32-e869-11e5-8733-ef8806f69bd9.png]
[https://cloud.githubusercontent.com/assets/14018074/13725225/57325b32-e869-11e5-8733-ef8806f69bd9.png]

—
Reply to this email directly or view it on GitHub
[https://github.com/yakyak/yakyak/issues/147#issuecomment-195805954] .[https://github.com/notifications/beacon/AQvP0o5-13gFIZMoz_mNkpCITcsmvYAGks5psyYqgaJpZM4HnhJ7.gif]

**Comment by x-tk** [comment]
Looks killer

**Comment by ariu** [comment]
Ok, so I took your idea and made this: https://github.com/ariu/yakyak/releases
What do you think ?

**Comment by austin-guevara** [comment]
@ariu MY GOD! It's beautiful! Splendid work. Thank you for making the dream come alive!

**Comment by ariu** [comment]
Happy that you like it :D
New update uploading with minor graphic fixes, and details window.

@maxkueng if you like it too, please feel free to use some or all of it

**Comment by austin-guevara** [comment]
@ariu I should \add that the new icon is a significant improvement from the original as well. Simple solution, but it works great.

**Comment by ariu** [comment]
Updated graphics with new group chat thumbs. Fixed some minor graphic glitchs. This release also has new "presence" feature to see who is online in your conversation list.
https://github.com/ariu/yakyak/releases

**Comment by swrobel** [comment]
@ariu presence doesn't seem to be working for me on the mac build
<img width="366" alt="screen shot 2016-03-23 at 6 33 53 pm" src="https://cloud.githubusercontent.com/assets/157270/14005999/d5e34044-f125-11e5-9161-37a0be9dd362.png">

**Comment by ariu** [comment]
Hey @swrobel 
You sure your contacts are online, and active in the last minutes? This is what I have before and after being active on my other test account:
(yes green dot on blue is weird, will fix it later... :p )

![capture d ecran 2016-03-24 a 02 39 14](https://cloud.githubusercontent.com/assets/5445403/14006093/07900be2-f16a-11e5-9aa8-68ea09ea4a74.png)
![capture d ecran 2016-03-24 a 02 39 41](https://cloud.githubusercontent.com/assets/5445403/14006094/0b35dfba-f16a-11e5-9adb-d3928967046b.png)

**Comment by swrobel** [comment]
@ariu yes, definitely, I'd just received a message from the top one less than a minute before I took that screenshot. It's definitely enabled in this build?

**Comment by ariu** [comment]
Yes it's included. I just re-uploaded mac binaries, maybe I did a mistake earlier... It should work fine, I ran those binaries for my last post screenshots. Can you download again and re-try?

**Comment by ariu** [comment]
Oh, don't forget, your contact must accept status share. Otherwise, well, we can't see if he is here or not.

**Comment by swrobel** [comment]
@ariu if I get the green does in the Hangouts Chrome app, I should see them in yakyak, right?

**Comment by ariu** [comment]
yes, i tested it from https://hangouts.google.com , the green dots are exactly synchronized.

**Comment by swrobel** [comment]
@ariu latest from your releases page on the left, hangouts chrome app on the right. same contact at the top.
<img width="151" alt="screen shot 2016-03-23 at 7 08 15 pm" src="https://cloud.githubusercontent.com/assets/157270/14006469/baa0bc26-f12a-11e5-89d7-9e73927a47c0.png">

**Comment by ariu** [comment]
Can you open menu yak yak -> open inspector , then "console" tab, check "hide networks messages" and click "Errors" only. Do you have a red error displayed when you do that? 

![capture d ecran 2016-03-24 a 03 17 20](https://cloud.githubusercontent.com/assets/5445403/14006590/0c442c54-f16f-11e5-8bc4-d6e3fd59e6fd.png)

**Comment by swrobel** [comment]
yes:

```
(25) /Applications/yakyak.app/Contents/Resources/app/node_modules/trifl/lib/action.js:40 Uncaught Error: Rejected (alive) during action: init
/Applications/yakyak.app/Contents/Resources/app/node_modules/trifl/lib/action.js:40 Uncaught Error: Rejected (alive) during action: attop
```

**Comment by ariu** [comment]
those are unrelated... Well, in this same console window, type: "models.entity"
It will return a list of objects. each number in this list is one of your contact. I you open those contacts, can you see "presence", or is it not there at all?
![capture-d ecran-2016-03-24-a-03 47 55](https://cloud.githubusercontent.com/assets/5445403/14007160/63eba7b6-f174-11e5-965a-9ae058c905dd.jpg)

**Comment by swrobel** [comment]
Presence is false despite getting the green dot in the chrome app.

**Comment by ariu** [comment]
Ok, now we have a lead: if presence is there, set to false, i means that, at least on start, yakyak asked server about your contacts status, and server answered "nope, didn't see them". This, or yakyak (well, in fact, me... :p ) misunderstood the answer from the server. This is reverse engineering, so i'm still figuring out what exactly the server tells us. I thought I understood, and it works well with my contacts, but it seems that I'm missing something.

I'll give it a try in the next days. For now, I'm off to bed, it's 4am here in France... :) Thank you for your time and your help !

@others : sorry we flooded this issue with that. Just try this release if you want, and tell us if it works for you !

**Comment by maxkueng** [comment]
Looks really cool! I like the refreshing colors very much.

There's an icon brainstorming issue #21 where I posted some of my ideas too. But I like your you Hangouts bubble with the "Y". Why don't you post your icon ideas there too? Would be nice if we could get as many ideas as possible.

**Comment by maxkueng** [comment]
@ariu I just tried out your build. It looks totally awesome! When you think it's ready, you could create a pull request. Amazing work on the design, @austin-guevara!

@algesten, @davibe what do you think?

**Comment by ariu** [comment]
@maxkueng Glad you like it ! I'd like more testing on this https://github.com/yakyak/yakyak/issues/103 before any pull request. It works on my side with the accounts I tested, but @swrobel reported it doesn't work for him. And I can't figure why.

Also I think you will have to clean my code a bit, I'm still new to coffee script, tried to understand how trifl works, electron, etc... this is a lot of fun but I'm sure I did some really dirty mistakes :p

**Comment by maxkueng** [comment]
@ariu When I first started your build, I had to close YakYak and start it again and then it worked. But I think that's a general YakYak bug.
I'm also not very familiar with CoffeeScript. In fact I don't like it at all. But I have experience with Electron from different projects, and I do like YakYak. So I try not to do too much coding here and just help out with issues and PRs and testing stuff.

**Comment by ariu** [comment]
Updated with fixes, new chrome engine, and color schemes. I'll submit a pull request soon, meanwhile, please test it, tweak colors, and submit your own color schemes ! :)
https://github.com/ariu/yakyak/releases/tag/v1.2.0-beta.3

**Comment by austin-guevara** [comment]
@ariu holy crap, you are incredible. excited to create and share some color schemes!

**Comment by randymorris** [comment]
@ariu Using your latest build on OSX (Version 0.37.2 (0.37.2)) I've got a couple of issues.

  1. If the list of conversations is short enough that it doesn't scroll there is a white gap where the scrollbar would be.

  2. There seems to be some sort of focus bug when switching between conversations.  It appears that the yakyak window loses focus and immediately regains focus causing the window chrome (titlebar/buttons) to flash.

Can anyone replicate this?

Also, rather than filling this tracker with discussion about the fork would it make sense to open up issues on your repo so we can discuss specific problems there?

**Comment by ariu** [comment]
@randymorris both issues fixed in last commit (no binaries yet).

As for your suggestion to open issues on fork, well my fork is only intended for dev and test on my own, not to be another app. I just submitted a pull request to merge with main yakyak :)

**Comment by algesten** [comment]
feel free to continue to discuss this. but closing it as #160 is getting near.
