### ISSUE TITLE
Does not work for domained google accounts

### ISSUE THREAD

**Issue by jackal242** [yakyak/yakyak#148]
Trying to use it to connect to my company's domained google hangout and it just hangs on "connecting".

This is after making my way through MFA.

**Comment by lukosanthropos** [comment]
I've got my domained account working just fine
Running: v1.1.3 
Os: Ubuntu x64

**Comment by algesten** [comment]
i have a domained account. with 2-factor. works fine for me :/

**Comment by beppegg** [comment]
I'm unable to connect my company account too.

I open YakYak, input my company userid and click on "next".
YakYak then presents a white page, without any content.

With a browser, I'm usually prompted with a basic authentication module.
