### ISSUE TITLE
Enable spell check in Mac OSX?

### ISSUE THREAD

**Issue by uratrtl** [yakyak/yakyak#149]
Is there a way to enable os x's built in spell check in yakyak?

**Comment by x-tk** [comment]
I'd like to know, also.

**Comment by rjcrouch** [comment]
I commented on a java based plugin on an old thread:
https://github.com/yakyak/yakyak/issues/61

I'm more of a designer than a developer but I figured a java based plugin could cross with a coffee based application?

For reference here's the plugin.
http://www.javascriptspellcheck.com/

**Comment by ariu** [comment]
https://github.com/atom/electron/issues/3189

**Comment by algesten** [comment]
duplicate of #61
