### ISSUE TITLE
Notify on calls

### ISSUE THREAD

**Issue by Jimi-James** [yakyak/yakyak#150]
I'm kind of confused by how calls work with this program. It says:
"Video/audio integration (open in chrome)"
When I first read that, it made me think that from YakYak, I can open Chrome to use the video/voice features of Hangouts. Which made me think that it would tell me if I was being called and have some kind of open-in-Chrome button, because why else would it even have an open-in-Chrome button?

Maybe it's supposed to, but in my experience using this app on Linux, it does not notify me of incoming calls and doesn't even have an open-in-Chrome button anywhere. In other words, the app is completely divorced from having anything to do with Hangouts' video/voice conversations.

So, if it doesn't already, can we please add call notification as a feature? I'm OK with having to open it in Chrome (though it would be nice to do calls and stuff right in YakYak), but I need a desktop app that at least lets me know someone's trying to call me, and YakYak already does everything else so well.

**Comment by Jimi-James** [comment]
Suddenly, as of like this week, I'm getting call notifications with Accept / Reject links on them when somebody calls. They aren't as obvious as I'd like, but they're happening, and they're happening reliably every time. Strange, since it didn't work the last time I tested it, but hey.

**Comment by algesten** [comment]
PR:s welcome ;)

**Comment by lonniev** [comment]
Today (02 Nov 2016), I observe that when an incoming voice call originates, the other Hangouts apps (such as the mobile app) will wake up immediately and start to notify the recipient (me). However, the YakYak app shows no status, no notifications. As soon as the call is concluded on the more noticeable apps, the YakYak app will throw up its notification that an incoming call is pending. It is too late: the call has already ended.
