### ISSUE TITLE
White page on startup

### ISSUE THREAD

**Issue by stilllife00** [yakyak/yakyak#151]
After launching the precompiled linux-64 version on Ubuntu 14.04 I get an empty (white) window.
The terminal says:

    mirko@mirkobuntu ~/apps/linux-x64 $ ./yakyak 
    hconnect
    asking for login credentials
    2016-03-14 9:50:02 WARN no SAPISID cookie
    2016-03-14 9:50:02 WARN no SAPISID cookie

Might it be related with the fact that I am using i3 window manager and 2 monitors?

**Comment by collinsnji** [comment]
I have the same thing on Ubuntu 15.10 linux-32. Here is what terminal shows after `./yakyak`
`hconnect`
`2016-03-15 16:52:17 WARN no SAPISID cookie`
`2016-03-15 16:52:17 WARN no SAPISID cookie`
`2016-03-15 16:52:17 WARN no SAPISID cookie`

`

**Comment by jnbek** [comment]
I fixed this by changing the electron version to 0.36.10 on Arch Linux

**Comment by EazyDefcon** [comment]
I disabled tray icon to solve this

**Comment by jg777** [comment]
I'm having same issue on Ubuntu 14.04 linux-64:

~/linux-x64$ ./yakyak 
hconnect
asking for login credentials
2016-03-30 17:04:49 WARN no SAPISID cookie
2016-03-30 17:04:49 WARN no SAPISID cookie
2016-03-30 17:04:49 WARN no SAPISID cookie

**Comment by algesten** [comment]
dupe of #32

**Comment by felixbores** [comment]
I'm having this issue on windows 10 x64
