### ISSUE TITLE
Styling issues on linux 

### ISSUE THREAD

**Issue by lukosanthropos** [yakyak/yakyak#152]
So very minor and picky, there should be a little bit more padding on the left hand side of the contacts/chats pane 
![screenshot from 2016-03-16 09-39-03](https://cloud.githubusercontent.com/assets/594625/13807808/fdfaa75a-eb5a-11e5-92ff-a998512e4a8b.png)

Running: v1.1.3 
Os: Ubuntu x64

**Comment by DASPRiD** [comment]
Interesting, I don't have that on Ubuntu GNOME 14.04 here. I wonder what the source for that is.

**Comment by maxkueng** [comment]
I don't have this problem either on Manjaro x64.

**Comment by maxkueng** [comment]
I also don't have a scroll bar but my list of conversations is short. @DASPRiD do you have a scrolbar? Scrollbar could cause the padding issue.

**Comment by DASPRiD** [comment]
@maxkueng No, I have an overlay scrollbar.
