### ISSUE TITLE
Message box not clearing on send

### ISSUE THREAD

**Issue by lukosanthropos** [yakyak/yakyak#153]
What it says on the tin. 
When I send a message, the message box doesn't clear meaning I have to remove the message manually before sending 

![screenshot from 2016-03-16 09-41-08](https://cloud.githubusercontent.com/assets/594625/13807924/97e8914c-eb5b-11e5-9207-e6aa7839bf03.png)

Running: V1.1.3
Os: Ubuntu x64

**Comment by randymorris** [comment]
This appears to be a duplicate of #141.

**Comment by lukosanthropos** [comment]
Closing in preference of #141
