### ISSUE TITLE
Request: message timestamps (on each message)

### ISSUE THREAD

**Issue by psouza4** [yakyak/yakyak#155]
( Possibly related to issue #22 )

It'd be fantastic to see message timestamps like they appear at https://hangouts.google.com/ -- I will regularly check to see how long it's been since my last interaction with someone an hour or more ago and those timestamps are missing unless I start sending new messages.  The website version lets me see the timestamp of every message if I hover over them.  I'd like a similar feature in YakYak please.

**Comment by ariu** [comment]
Added this to my fork, while rethinking the conv list. Feel free to use it (binaries still uploading): https://github.com/ariu/yakyak/releases

@maxkueng , you can find implementation here: https://github.com/ariu/yakyak/blob/master/src/ui/views/convlist.coffee#L44

**Comment by psouza4** [comment]
@ariu tried your fork, but there were multiple issues and your fork doesn't permit me to submit issues.  I do like that I can hover over and see the time (thanks!), but...

(1) I greatly dislike that I've lost a ton of real estate at the top of the program to a new green bar that is largely unnecessary with a standard caption bar menu right above it.  See example:
http://www.petersouza.com/yakyak_issue1.png

(2) there's also a weird graphical positioning glitch whenever a message is received and YakYak is maximized.  It is taking the cascade of thumbs for the hangout participants and stretching it full-size under the contacts panel.  See image:
http://www.petersouza.com/yakyak_issue2.png

(and yes, one of my contact's avatars is a fish smoking a cigarette in a turkey... I don't know why)

I'd love the functionality from this request without sacrificing so much wasted space.  The skin/theme/layout changes are otherwise welcome if we can do it in a smarter way, otherwise I'll have to wait for an official change to the YakYak master fork (or fork it myself, heh).

Cheers!

**Comment by ariu** [comment]
hey @psouza4 thanks for the feedback.

For the green bar, and the skin related questions, I'm just implementing @austin-guevara work. See his issue here: https://github.com/yakyak/yakyak/issues/147 . Can you please comment and discuss about that on his issue, I'm not much of an artist, I just know some tools to make his great ideas real.
My thought is, on 1.1.3, your contact's names are repeated everywhere on each messages, and it takes vertical space too. We just removed it everywhere to put it in one spot, on top, with the action button next to it. Inspiration also came from hangout official iOS app, they do the same. I don't know if its good or not (well i kinda like it this way though), just discuss it with the art guys ;p

For the graphical glitch, I don't have it on my screen, on macosx.  But I have an idea, i'll give it a try. I didn't touch the notification system yet (numbers next to conversation saying "you have 2 replies"), and I think this is related. When the number is updated, it "pushes" the elements next to it, and BOOM... I'll let you know if I find something.

I'm still new to this project, my fork is only an experiment. I think i'll look into notification system, then maybe presence status on contact list.

Have a nice day !

**Comment by ariu** [comment]
Fixed the bug you reported in my latest release :) . Group chat thumbs have been greatly improved.

**Comment by algesten** [comment]
the not-having-timestamp-on-every-message things is very deliberate. no clutter.

**Comment by psouza4** [comment]
I can hover over the message for the message date/time, which will suffice, however it should likely be up to the user to consider that information clutter or not.  I leave YakYak on a 24" monitor (maximized) while I do work on two other monitors and it'd be very nice to see that information without having to go out of my way to look for it all the time.

Thanks for reading.
