### ISSUE TITLE
Message history inconsistent loading

### ISSUE THREAD

**Issue by JeremyEnns** [yakyak/yakyak#159]
I noticed when opening the application it does not always correctly pull in the previous history.  When I compare the hangout history between yakyak and google's native app it contains a lot more of the conversation.  It will display some odd empty bubbles like conversations happened at those times but all of the content is missing. 

Tested versions.  Mac OS X `1.1.3`, `1.1.2` and `1.2beta`
I tried to clear out any cache related issues by removing the various cache folders in `~/Library/Application Support/yakyak` and reloading.

**Comment by JeremyEnns** [comment]
How it appears

![history error](https://cloud.githubusercontent.com/assets/11463175/14288445/5b10db0a-fb1c-11e5-8e70-2891715f7ee3.jpg)

**Comment by zaphod777** [comment]
Same here

**Comment by MrOerni** [comment]
same with 1.2 prebuilt on Mac OS 10.11.4

**Comment by x-tk** [comment]
Same on 1.3, MacOS X El Capitan 10.11.4

**Comment by ZackBoe** [comment]
Same on latest Windows 10 and Debian 8

**Comment by psouza4** [comment]
Yeah this started happening a few weeks ago for me.  Hoping for a bug fix.

**Comment by davibe** [comment]
as far as i understand it there are some "empty messages by myself" that should not be there. This has been fixed already in master but its not released. Can someone confirme this ?

**Comment by psouza4** [comment]
No, this is not the issue.  If I close YakYak right now and re-open it, there will just be a series of bubble heads indicating where messages used to be in a conversation, but every single message will be blank.  This occurs regardless of the chat client or interface used to have that conversation, even if I use YakYak exclusively (and I pretty much do), myself.

YakYak will correctly retrieve the message history ten messages back and then all of the prior messages are blank with chat heads.

**Comment by mideeks** [comment]
Actually I am even seeing blank messages even for the last ten. It is definitely a rendering problem. If I Select All and Copy everything in the YakYak chat window, and then paste it into a text editor I will see all of the actual text I typed. It just isn't being displayed correctly in YakYak.

Closing and reopening the app doesn't fix it.

**Comment by davibe** [comment]
Are you running the master branch or are you using the released version ?

**Comment by mideeks** [comment]
The released version 0.37.4 (1.2.0)

**Comment by davibe** [comment]
Indeed. I think it's is fixed in master as i said

**Comment by mideeks** [comment]
Sorry, I failed at reading apparently. I just built and ran master and it appears to be working correctly. I can see all of my history now (though profile pics don't show up in this build). Thanks for fixing!

**Comment by averissimo** [comment]
closing as seems to be fixed.
