### ISSUE TITLE
Application hangs 

### ISSUE THREAD

**Issue by vgavrila** [yakyak/yakyak#161]
I've just updated to version 1.2.0 and the application hanged for 30-40 seconds while writing messages. This happened 4 times in 5 hours. 
The menu was functional, I was able to navigate through options, but couldn't type in the message box.
I've only used dark theme and don't know if this could be an issue.
Does any one else experienced this? I don't know if this is an issue with my computer, but I'll be certain the next few days.

Thanks,
Victor

**Comment by algesten** [comment]
we're reverting out that particular skin switch with #160. perhaps that will resolve itself.
