### ISSUE TITLE
Open images in plus.google.com

### ISSUE THREAD

**Issue by SplinterHead** [yakyak/yakyak#165]
Clicking on an image in a chat should open the `plus.google.com/` version of the image, rather than the `lh3.googleusercontent.com/` version. 
This would show the image in a larger, better quality format

**Comment by algesten** [comment]
PRs are welcome

**Comment by x-tk** [comment]
Good idea

**Comment by jadengore** [comment]
@SplinterHead I actually prefer the `googleusercontent` version so that I don't have to use Google+'s heavyweight UI to view a simple photo. Maybe this could be configurable?
