### ISSUE TITLE
Signs in across Google services (Gmail, Inbox, and Google+)

### ISSUE THREAD

**Issue by HobbinHood** [yakyak/yakyak#168]
When using YakYak, it also activates/enables Hangouts on Gmail, Inbox, and Google+.

One can use Hangouts via [hangouts.google.com](url) without getting signed in on the services mentioned above. It won't sign you in on these other services, though it will sign you out across all Google services if you sign out on [hangouts.google.com](url).

This is mentioned here:
[https://support.google.com/hangouts/answer/3114221?co=GENIE.Platform%3DDesktop&hl=en](url)

> **Sign out in Gmail, Inbox, or classic Google+**
> 
> Signing out of Hangouts in Gmail, Inbox, or classic Google+ won't sign you out of Hangouts at hangouts.google.com. To show yourself as offline, close your hangouts.google.com window.

So, is there a possibility that YakYak uses hangouts.google.com for operation instead of using the Google+ service that triggers a sign in across above services?

**Comment by davibe** [comment]
needs some investingation. Help wanted
