### ISSUE TITLE
observed events are displayed as blank chat entries

### ISSUE THREAD

**Issue by cameronr** [yakyak/yakyak#170]
events with no chat message and an `event_id` like `observed_7-H0Z7-E47E8Cja62wgE5F` are displayed as blank chat lines:

<img width="845" alt="screen shot 2016-04-16 at 2 08 01 pm" src="https://cloud.githubusercontent.com/assets/38429/14583622/b4660ce8-03dc-11e6-9d18-caca5603654c.png">

<img width="420" alt="screen shot 2016-04-16 at 2 09 49 pm" src="https://cloud.githubusercontent.com/assets/38429/14583654/ea86d01e-03dc-11e6-9b10-e604efb7b961.png">

they seem to only happen for self (i.e. i don't see them for any of my contacts).

those events could be filtered out in the `models/conv.coffee` and i'm happy to submit a pull request for that but wanted to check and make sure those events weren't useful for something else first.

**Comment by randymorris** [comment]
I can confirm seeing blank messages show up for my user only.

**Comment by krp312** [comment]
confirming as well
