### ISSUE TITLE
unable to install on windows 7

### ISSUE THREAD

**Issue by seanmore** [yakyak/yakyak#171]
![js_error_when_running_install](https://cloud.githubusercontent.com/assets/8571047/14655182/ff9a557e-0635-11e6-9992-7606ccdfc5c9.png)

**Comment by davibe** [comment]
still happening ?

**Comment by averissimo** [comment]
this is something tha has been reported when pinning the icon to the taskbar.

closing this issue for lack of feedback.. see #258 for more information
