### ISSUE TITLE
latest update locks up often on windows

### ISSUE THREAD

**Issue by msphair** [yakyak/yakyak#174]
windows 10

cpu usage hits 13.8% and UI stop responding

**Comment by msphair** [comment]
Might be related:

When you resize the yakyak window, the cpu usage spikes and the app freezes for a couple seconds.

**Comment by stotes** [comment]
Having the same issues when the window is moved or resized. 

Also on Windows 10.

**Comment by stotes** [comment]
Not just resize, even moving the YakYak window causes it to freeze for a couple minutes. I'd love to have a crack at fixing this but I haven't worked with Electron and have no idea where to start.

**Comment by davibe** [comment]
Please try 1.2.2 (currently pre-release) and tell us if this is still happening

**Comment by msphair** [comment]
@davibe I might be looking in the wrong place, but I don't see a windows build for 1.2.2. Only a linux build.

**Comment by davibe** [comment]
now..

**Comment by davibe** [comment]
https://github.com/yakyak/yakyak/releases/tag/v1.2.2

**Comment by msphair** [comment]
Just installed 1.3 and it's still happening.

I love it on OSX, but it's unusable for me on Win10

**Comment by kingnothin** [comment]
Not specific to Windows 10. I'm seeing the same behavior on Windows 7 (running 1.3)

**Comment by arnriu** [comment]
@msphair @kingnothin can you try latest 1.3.1 pre-release build?
https://github.com/yakyak/yakyak/releases

**Comment by kingnothin** [comment]
@arnriu works great with 1.3.1. No issues moving or resizing the window now. (Really like the app btw!)

**Comment by davibe** [comment]
yay
