### ISSUE TITLE
Better Project Fi Support

### ISSUE THREAD

**Issue by CyanJDroid** [yakyak/yakyak#177]
It'd be nice if there were better Project Fi support (ability to start new text message conversations, ability to make calls, etc.).

**Comment by davibe** [comment]
can you elaborate further ?

**Comment by CyanJDroid** [comment]
Basically just basic Project Fi capabilities you'd find in the web Hangouts app for Project Fi users, like the ability to send text messages (I realize you can do this now, but it's very limited. The ability to start new text message conversations would be ideal), the ability to make/receive phone calls. Things like that.

**Comment by davibe** [comment]
I don't know Project Fi at all. I looks like something that bridges the mobile phone world to hangouts and you can activate it on your phone. I don't have an android phone at the moment.

You can start new messages/conversations in yakyak using the (+) icon. What's wrong with this ? Are you not able to find contacts that are using Project Fi on the other end ?

Hangout audio/video calls are a bit outside the scope of yakyak which is mostly about making multiuser text chat fast and more usable while letting more advanced features (videocalls, screensharing) to be consumed with the an external browser. Of course we need to better handle hangout events displaying links-to-externa-webapp in case someone tries to audio/video call you.

**Comment by CyanJDroid** [comment]
Ah, you don't know Project Fi! Well that explains your confusion. So basically, Project Fi is an MVNO (mobile virtual network operator) by Google that uses Hangouts (along with Google Voice) as part of its backend, which allows users who opt-in to the feature to text and call via any device that can run Hangouts, without the phone ever needing to be touched or sent any information at all. So to answer your question, yes, I am not able to send messages to people via Project Fi, as entering a phone number as the person I'm initiating the chat with does not work. If I've already received a text from a number, then it shows up as a chat, which I can then attempt to send messages via (though that's hit-or-miss as to whether it actually sends), but initiating new text message conversations does not work. While it would be nice to be able to at the very least be able to initiate new text message conversations via Project Fi, I understand if implementing any Project Fi features isn't feasible or possible.

**Comment by davibe** [comment]
Thank you for the explanation. There is probably a way to search by phone number which we could try to support. As for messages not always arriving that's going to be hard to debug for someone who does not have Project Fi.

I leave this open to see if someone has time to inspect it further (I don't at the moment)

**Comment by Serubin** [comment]
Fi texting works just fine, calling may be out of the scope of this project.

**Comment by pshah88** [comment]
Adding to this forum, text conversations with hangouts is hit or miss for me as well. Takes a long time to send if it sends at all. I am replying to incoming texts, not creating new conversations just as an fyi.

**Comment by bradreardon** [comment]
I'm willing to provide any insight or help test anything that helps make this a reality. I have limited OS X development experience, but if there's any progress being made on this feature, I'll be glad to assist.

**Comment by Serubin** [comment]
I think the key will be finding where the fi/voice specific data is being loaded. 
It should be pretty easy to do by just looking at the xhr requests on [https://hangouts.google.com](url) and sifting through to see where that contact list get loaded from.

**Comment by bradreardon** [comment]
If anyone wishes to work on this at any time, feel free to get in touch with me and I'll be glad to help log any information required to fix this.

From the looks of it, I can pick out a good bit of data from the XHR requests. Just not 100% sure how the Hangouts protocol works, or how the data I get as a Fi user differs from a Google Voice or Hangouts-only user.

**Comment by hadees** [comment]
Any update on this?  I think the biggest thing I'm noticing is that yakyak isn't matching the numbers with my android contacts like it does on my phone.  Not sure how to fix that, i just see my friend's cell numbers.

**Comment by natecox** [comment]
Confirming @hadees sentiments here. I love the idea of this client, but I can't currently see any of the names of my contacts I'm talking to via project fi.

![image](https://cloud.githubusercontent.com/assets/2782695/23517630/c76e0a1c-ff25-11e6-97ec-461069ac4910.png)

**Comment by projectfi** [comment]
Hi there! We are very impressed with your hangouts client! But can't help you from Google sorry due to the terms and conditions 😞.

**Comment by hadees** [comment]
@projectfi really? that seems odd, why even respond?
