### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by devin42r** [yakyak/yakyak#179]
I apologize this might be user error, but I could not find a good place to post my question.  I want to support FOSS where I can but am having trouble installing yakyak.  I tried using the documentation supplied but then realized that it must be for development (I'm not familiar with node.js and tried cd into app after program.js error but still experienced gulpfile.js error).  I followed tutorial here http://sourcedigit.com/16487-install-yakyak-google-hangouts-client-on-ubuntu-15-04-and-ubuntu-14-04/ and am seeing quite a bit of deprecated stuff in terminal.  After login, the screen goes white...any idea what I might be doing wrong?

**Comment by davibe** [comment]
which version have you tried ?

**Comment by devin42r** [comment]
Thanks for response

![screenshot from 2016-06-08 09 35 22](https://cloud.githubusercontent.com/assets/9112811/15900357/75cfe392-2d5c-11e6-8aba-f4f7bc65b0fd.png)

v1.2.0...followed same tutorial as above..

**Comment by davibe** [comment]
https://github.com/yakyak/yakyak/releases/tag/v1.2.2 
try now

**Comment by averissimo** [comment]
@devin42r yakyak (as of 1.4.0) gives a better understanding about what went wrong

can you try running yakyak from command line (either a development or a binary) and see if the problem still persists?

thanks!
