### ISSUE TITLE
Enhancement Ideas

### ISSUE THREAD

**Issue by x-tk** [yakyak/yakyak#180]
- User definable history (list of past conversations is very short, a longer list would be nice)
- Google hangouts style of seeing when a user has read a message, or alternatively some kind of "Seen at xx:xx"
- Customizable notifications for sounds
- See which conversations are muted for notifications next to the name in the list

**Comment by davibe** [comment]
Those area all good ideas for new features. If you ask me they are a bit against the minimalism we tried to persue at first.

That being sed those thingsl require more dev power. We currently have limited time and not many pull requests. We are already striving to keep things updated and going the way they are so don't expect to see that any of that soon unless you want to take over some if it.

Thank you for the imput i am going to close this to clean up issues a bit (we have so many).
