### ISSUE TITLE
OSX Memory Leak

### ISSUE THREAD

**Issue by gamut** [yakyak/yakyak#182]
Just noticed that Electron is up to 4.4 GB memory usage on my Mac while YakYak is running.  Feels like a memory leak to me.

El Capitan, YakYak Version 0.37.4

**Comment by davibe** [comment]
Could be an electron bug. In version 1.2.2 (currently a pre-release) i have updated electron version significantly. Can you check again please ?

**Comment by ckald** [comment]
The leak is still present

**Comment by averissimo** [comment]
@ckald @gamut is the leak still present?

in ubuntu it remains stable at 65-74MB (depending on the process).. granted that seems too much, but electron has a big overhead

**Comment by gamut** [comment]
Honestly, I’m not sure.  It’s at 175 MB at the moment, and i routinely have to restart the app — maybe once per day, because it stops sending messages.  I haven’t bothered to check memory when that happens.   I will do so the next time.
