### ISSUE TITLE
Can't delete conversations

### ISSUE THREAD

**Issue by ilium007** [yakyak/yakyak#183]
When clicking on the X in the bottom left corner of the UI to delete a conversation nothing happens. I can not delete any conversations.

**Comment by billnordwall** [comment]
I am also seeing this issue in 1.2 and 1.2.1.

**Comment by averissimo** [comment]
leaving conversations was fixed, closing this issue

it is throwing an exception but that does not block anything, which is corrected in #524

**Comment by Chris-Dickerson** [comment]
RE: Version v1.5.1 (win32 x64)
I have 3 phone number conversations that I cannot delete. No exceptions or errors, it just doesn't work.

**Comment by averissimo** [comment]
We need a google voice developer to debug and correct this. Can any of you open a new ticket as this is very old.

Thanks
