### ISSUE TITLE
Fresh install 1.2.1 spawns infinite windows and never starts

### ISSUE THREAD

**Issue by psouza4** [yakyak/yakyak#187]
See comments on issue #185 -- if YakYak does not already have user data, it will spawn an infinite number of windows every few seconds in an attempt to do... something.  It never finishes loading and must be killed.

It does this in multiple operating systems, including Windows 7 x64, Windows 10 x64, and OSX 10.11.5 and for multiple users (myself, @Durpn, @deantoader, etc.).

**Comment by davibe** [comment]
The bug is present in every platform. Please try pre-release 1.2.2 and confirm if this is fixed

**Comment by psouza4** [comment]
Just wanted to throw a thumbs up for jumping on these issues.  Big fan of YakYak!

**Comment by davibe** [comment]
:)
