### ISSUE TITLE
Toggle notification doesn't actually toggle back on

### ISSUE THREAD

**Issue by mideeks** [yakyak/yakyak#189]
If I toggle notifications off for a user and then toggle them back on in yakyak, they aren't actually toggled back on when I view the user in the hangouts web app (hangouts.google.com). It still shows the bell with the slash through it.

**Comment by davibe** [comment]
Ok thank you. Does the "slashed bell" also survive a restart of the application ?

**Comment by davibe** [comment]
I can't reproduce using 1.2.3 release. Please, try with latest version and if it happens again clearly describe steps to reproduce this. Thank you.

**Comment by mideeks** [comment]
I think this was actually just caching on the hangouts.google.com site. If I reload the page it shows notifications are set correctly. Closing.
