### ISSUE TITLE
hangout calls in chat

### ISSUE THREAD

**Issue by faxe78** [yakyak/yakyak#191]
Hi,

Just a small thing which i saw, if there are calls in the chat history they are shown as empty messages.

Thx

**Comment by davibe** [comment]
Ok, thank you. Does this involve missed calls ? all calls ? no difference ?

**Comment by faxe78** [comment]
missed calls, made calls at least looks like all. if there are chat messages before you just have a small gap, if its just the call it's an empty message.

**Comment by davibe** [comment]
Ok, we need to UI for those types of events. Thank you.
