### ISSUE TITLE
Missing user icons in 1.2.3

### ISSUE THREAD

**Issue by adamtheturtle** [yakyak/yakyak#196]
https://github.com/yakyak/yakyak/releases/tag/v1.2.3 says "Fix missing user icons" but I still have the issue.

Thanks for the software 😄

**Comment by davibe** [comment]
screenshot please ?

**Comment by adamtheturtle** [comment]
![screenshot 2016-06-10 11 22 44](https://cloud.githubusercontent.com/assets/797801/15961678/dc311dde-2efd-11e6-9936-8d5a1738a07a.png)

OS X 10.11.5

**Comment by davibe** [comment]
it does not happen with my contacts.
It would be interesting to know the url of that picture. It looks like an url has been set but it is invalid. cmd+alt+i fires up an inspector if you care to investigate a bit

**Comment by adamtheturtle** [comment]
```
https://plus.google.com/_/focus/photos/private/AIbEiAIAAAAjCM2u98nbiIzp4QEQjZDF6aL5oeSnARiSs6WEjbHjkpEBMAGWIHIxPaIOAV7rgGpmL-LMbXHx3w Failed to load resource: the server responded with a status of 403 ()
```

![screenshot 2016-06-10 11 33 35](https://cloud.githubusercontent.com/assets/797801/15961868/3214f512-2eff-11e6-8216-d4263cd14fdf.png)

**Comment by davibe** [comment]
which is a valid image. It failed to download somehow

<img src="https://plus.google.com/_/focus/photos/private/AIbEiAIAAAAjCM2u98nbiIzp4QEQjZDF6aL5oeSnARiSs6WEjbHjkpEBMAGWIHIxPaIOAV7rgGpmL-LMbXHx3w" />

**Comment by davibe** [comment]
have you tried to logout and login again ? Or to close the app, delete completeliy `~/Library/Application Support/yakyak`, restart it

**Comment by adamtheturtle** [comment]
@davibe Thank you for your help. Sorry it took me so long to respond - when I saw the message I wasn't in a position to log out and then I forgot about it. That didn't work, but deleting `~/Library/Application Support/yakyak` did work.

**Comment by adamtheturtle** [comment]
Note that after trying logging out and before trying the deletion, I upgraded to 1.3.0 and the problem persisted.

**Comment by jraoult** [comment]
FYI, I had the same problem and log out + removing `~/Library/Application Support/yakyak` did work for me.

**Comment by sander-adhese** [comment]
I still have this issue with contacts who don't set a custom photo/avatar. (In google hangouts, displayed by their initials). Any help? Removing the cache+reloading doesn't help.

**Comment by averissimo** [comment]
Have you removed the directory mentioned above (or equivalent in you OS)?

Does the link work on a private window of a browser? (incognito mode or equivalent)

**Comment by sander-adhese** [comment]
I have. What link?

**Comment by averissimo** [comment]
You have a message in the console saying: Failed to load resource... and on the right side of that error there is a link as figure below shows:

![](https://cloud.githubusercontent.com/assets/797801/15961868/3214f512-2eff-11e6-8216-d4263cd14fdf.png)

**Comment by sander-adhese** [comment]
It works, but not in incognito mode

**Comment by averissimo** [comment]
I have that same problem

The strange thing is that even in Hangouts (gmail web interface) there is no avatar, just the initials.

YakYak should do the same and fallback to initials if failing to retrieve an avatar.

**Comment by sander-adhese** [comment]
Yes, indeed. I didn't even know a picture was available, other people do have one.

**Comment by averissimo** [comment]
which OS are you running, you motivated me to fix this and I think I have a solution.

**Comment by averissimo** [comment]
If you can build YakYak, just merge #428 (and #403 if you are on latest YakYak code)

Otherwise I can build you an archive for Linux or Windows (sorry no MacOSX but it seems to requires some native tools)

**Comment by sander-adhese** [comment]
I use MacOS :) I'll try to build it and keep you updated!
