### ISSUE TITLE
JavaScript error on startup

### ISSUE THREAD

**Issue by adamtheturtle** [yakyak/yakyak#197]
I started 1.2.3 for the first time and it showed:

![screenshot 2016-06-10 10 53 09](https://cloud.githubusercontent.com/assets/797801/15960891/e3164a60-2ef9-11e6-9d0c-0d19284e5639.png)

**Comment by davibe** [comment]
did re-starting again fix the problem ?

which OS do you use ?

**Comment by adamtheturtle** [comment]
I quit and re-opened YakYak and did not see the error.

OS X 10.11.5.

**Comment by davibe** [comment]
I have never seen it. I just tried re-downloading and removing ~/Library/Application Support/yakyak before starting and could not reproduce. Could be a race condition of some sort or an electron bug. Thank you for reporting.

**Comment by averissimo** [comment]
this should not happen anymore since we are using the ready-to-show event now and also check if window exists before any show call

reopen if you are still experiencing this.

thanks for reporting!
