### ISSUE TITLE
logout does not work on windows

### ISSUE THREAD

**Issue by davibe** [yakyak/yakyak#2]
The logout fails when trying to delete chromes Cookie file with EBUSY (file busy) because Chrome is still using it. This is a known windows problem.

We probably need to wait proper cookies api support from Electron

Windows user can logout by closing the app and deleting C:\Users\[username]\AppData\Roaming\yakyak

**Comment by algesten** [comment]
The solution is probably to fork a second process and delete the cookies in there. So:

1. select logout in main process
2. fork process2, process2 goes to sleep for 1 second.
3. quit main process
4. process2 wakes up and deletes cookies
5. process2 launches app again

https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options
