### ISSUE TITLE
v1.2.3 windows release zip files won't open

### ISSUE THREAD

**Issue by msphair** [yakyak/yakyak#201]
![image](https://cloud.githubusercontent.com/assets/1900880/16027613/312d45ca-318c-11e6-99d3-1fb1f89e6367.png)

**Comment by msphair** [comment]
I tried x86 and x64

**Comment by davibe** [comment]
It's a kind of zip that you need to open with some program like 7 zip or pkzip. I am aware of the problem. Next release will have this fixed, and so much more.

Thank you
