### ISSUE TITLE
How to build binaries?

### ISSUE THREAD

**Issue by chrisabrams** [yakyak/yakyak#204]
I don't see any instructions on how to build the binaries?

**Comment by jadengore** [comment]
@chrisabrams It looks like you want to follow the setup steps first:
```
$ sudo npm install -g gulp
$ npm install
$ gulp
```

After you've run those, run the `deploy.sh` script in the top-level directory. It builds for all platforms, so if you just want to build for a specific one try pulling out the distribution you want.

**Comment by jadengore** [comment]
@davibe Can you close this? Believe this question is answered.

**Comment by davibe** [comment]
sure, ty
