### ISSUE TITLE
Gitter link broken

### ISSUE THREAD

**Issue by randymorris** [yakyak/yakyak#205]
I was going to go in and ask a question about the build size for OSX (it's huge compared to the rest), and I found that the community no longer exists on gitter.  If the gitter chat has been abandoned the link should be removed.

**Comment by davibe** [comment]
You're right. I didn't even know it gitter existed in the first place.

OSX is larger for a number of reasons which need to be inspected individually. We should probably try removing un-used electron files during packaging and see how far we can go with that. That being said it's just disk space. It's not heavier at run time. The web-application itself is veeery small and electron (the engine that runs it) is outside of our control.

**Comment by arnriu** [comment]
@davibe, try this in deploy.sh
`zip -r -y -X ../yakyak-osx.app.zip YakYak.app`

My zip file is 54.7Mo instead of 132Mo

**Comment by arnriu** [comment]
And unzipped is 152.2 instead of 382.1Mo

from **man zip**:

>  -y
>        --symlinks
>               For UNIX and VMS (V8.3 and later), store symbolic links as such in the zip archive, instead of compressing and storing  the  file
>               referred  to  by  the  link.  This can avoid multiple copies of files being included in the archive as zip recurses the directory
>               trees and accesses files directly and by links.

**Comment by randymorris** [comment]
@davibe I agree, it just threw me off because previous builds have been comparable in size to the other platforms so I wasn't sure if something funky happened with the later builds.

**Comment by arnriu** [comment]
@davibe https://gist.github.com/arnriu/e0d7ee878fe0ec2e8b8208b7f9d38d88
@randymorris try this one: https://we.tl/xy70pxzEhI

**Comment by davibe** [comment]
@randymorris in 1.2.3 i changed the compression engine from zip to pkzip but windows users had problems opening it and i had to revert to plain zip.

**Comment by randymorris** [comment]
Fair enough.  To get back to the topic of this issue, do you have any intentions of using Gitter at all?  If not, I'll open a pull request to remove the link from the readme.

**Comment by davibe** [comment]
Personally, i don't use it. However I am not the only developer/contributor of the project

**Comment by averissimo** [comment]
this can be closed, right?

if not please reopen :)

**Comment by averissimo** [comment]
lol got what it is by trying to click on it

created a pull request #534 that's probably going to get merged

I also don't use, but I'm not the only developer/contributor to the project.. however the link is broken and useless as is

If someone want's to revive yakyak's gitter please create new pull request with a valid room
