### ISSUE TITLE
[SUGGESTION] - YakYak Icon on Dock

### ISSUE THREAD

**Issue by marcoslacerda** [yakyak/yakyak#206]
What's up guys,

Initially I would like to congratulate the excellent work!
Let me make a suggestion to you, so that you can "swap" the dock icon YakYak, I found the new beautiful icon but particurlarmente liked the first Buffalo icon or Yake (not sure which animal is .. lol).

Again, congratulations on the job!

**Comment by arnriu** [comment]
For icon discussion: https://github.com/yakyak/yakyak/issues/21

I'm not sure icon switching within app is a good idea. You can change icons of applications with your os.
On mac: http://hashbangstar.net/blog/changing-icons-in-el-capitan
If you are looking for the yak icon: https://github.com/yakyak/yakyak/blob/140835b1a502fe893d03f25ada2e8a0b76c50864/src/icons/electron.icns?raw=true

**Comment by marcoslacerda** [comment]
Thanks a lot for your answer.
