### ISSUE TITLE
Privacy Mode feature request

### ISSUE THREAD

**Issue by x-tk** [yakyak/yakyak#207]
I use yak yak for hangouts at work, and I do love the new design and styling so major props!  One thing that would be nice would be a privacy mode, where it will show the date/timestamp as it does now but mask the preview of the message?  Not sure how difficult this would be but it would be a major win in my book.

Thanks!

**Comment by arnriu** [comment]
We can add this as a menu toggle, same as "show conversation thumbnails" in "view" menu.
Will look into this when I have time ;)

**Comment by davibe** [comment]
I don't get it. Are you referring to desktop notifications ?

**Comment by arnriu** [comment]
I think he is referring to last message in contact list.

**Comment by davibe** [comment]
can be tested in 1.3.1 pre-release
