### ISSUE TITLE
Can't change UI on Windows 10

### ISSUE THREAD

**Issue by bryanzw15** [yakyak/yakyak#208]
This might be a really stupid question, but how do I change the UI colors on Windows? I've looked in the view and YakYak settings at the top but I can't find the option.

**Comment by kforsberg** [comment]
I am also unable to change it on Linux. After looking in the source, I saw that the menu item to change the UI only appears on the Mac.

**Comment by davibe** [comment]
just noticed it too. Pull requests ?

**Comment by ctcpip** [comment]
+1

**Comment by arnriu** [comment]
I'm so sorry I forgot to add it for all platform. I only had a mac when I added this feature. :s

**Comment by Naatan** [comment]
Works on Linux fwiw :)

**Comment by ctcpip** [comment]
@Naatan - there are at least two of us using Linux that do not have the option at all.  I am using LXDE

**Comment by bryanzw15** [comment]
I can confirm that update 1.3.1 fixes this issue, at least on Windows

**Comment by ctcpip** [comment]
yes, code I just pulled from master and compiled, now I have a "Color scheme" option in the top menu and works as expected.  on Linux using LXDE.

**Comment by NxtGenCowboy** [comment]
Windows seems fine but on TumbleWeed, prebuilt from two days ago, Color Scheme is still missing, also the version is stated as 1.2.1

**Comment by ctcpip** [comment]
@NxtGenCowboy the change was only committed yesterday.  1.2.1 is from over a week ago

**Comment by davibe** [comment]
since you're testing the 1.3.1 pre-release, please, also partecipate to #21

**Comment by davibe** [comment]
Since it's fixed in next version, can we close this ?

**Comment by ctcpip** [comment]
@davibe I vote for closing it.  Issue is resolved on Windows+Linux as reported by multiple folks.
