### ISSUE TITLE
'Leave Conversation' is broken

### ISSUE THREAD

**Issue by ctcpip** [yakyak/yakyak#209]
In a conversation, going to 'Details' >> 'Leave Conversation' does nothing, and the conversation still appears in the list on the left.  No errors in the console

**Comment by davibe** [comment]
thank you

**Comment by ctcpip** [comment]
potentially related to #183

**Comment by neurosnap** [comment]
Any updates on this?

**Comment by ctcpip** [comment]
looks like this got resolved
