### ISSUE TITLE
icon brainstorming

### ISSUE THREAD

**Issue by rhoconlinux** [yakyak/yakyak#21]
Hi guys, I'm in for the icon design. We can start throwing ideas here so I may find some directions on how to build the first proposals. 

If you don't have any premises, I can start with something. Just let me know. :)

**Comment by davidbanham** [comment]
In my mind it's a big Yak face staring out at you.

**Comment by algesten** [comment]
@rhoconlinux there is a guy working on an icon right now. he's not ready to show it to the world just yet, but i don't want anyone to start investing a lot of time in various routes.

**Comment by algesten** [comment]
strike that. here's the work-in-progress. specifically the dude doing it is not totally happy with the colours and the relative sizes of the bubbles.

![yakyak](https://cloud.githubusercontent.com/assets/227204/8371894/fb6ed18e-1bdd-11e5-974e-f1827eecd69a.jpg)

**Comment by rhoconlinux** [comment]
likey! 

Can you share the source (e.g. svg)? so I can throw some ideas or do some mods from here! :) 

First things that comes to my mind: I would like to put some frame on the stuff, somehow. Is me or It doesn't seem to have a squared template, but a rectangular one? 
@davidbanham jajajajajaj :+1:  
Let me know guys! :dancers:

**Comment by mdciotti** [comment]
I spent a few design iterations thinking about the icon. How does this look?
![yakyak](https://cloud.githubusercontent.com/assets/1747960/12805302/d97654c6-cabf-11e5-9628-0f487d6c16f4.png)

Additionally, we could use a single-color version:
![yakyak2](https://cloud.githubusercontent.com/assets/1747960/12805298/d319628a-cabf-11e5-912b-bdcb1ffae154.png)

**Comment by davibe** [comment]
hahah i think it's very funny!! but it looks more like a pig than a yak. At least judging by https://www.google.it/search?q=yak&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj0wuWwleHKAhVDkg8KHZ3DCcUQ_AUIBygB&biw=1300&bih=717&dpr=2

**Comment by maxkueng** [comment]
Cool! I like the idea of combining the commas from the Hangouts logo with a yak. But I agree that it looks more :pig2:  than :cow2: at the moment.

I tried something too based on @mdciotti's idea that looks more yak-ish.

![yakyak](https://cloud.githubusercontent.com/assets/168709/12861343/fe25ff98-cc62-11e5-9bfc-74a2cc04a59b.png)

I'm not very good at this :worried:  [Here's the SVG](https://gist.github.com/maxkueng/5b6a6d0572a8f42af185#file-yakyak-svg).

**Comment by maxkueng** [comment]
here's a yak from the side ([svg](https://gist.github.com/maxkueng/7a8526b8c7cd423730ad))

![yakyak2](https://cloud.githubusercontent.com/assets/168709/12861902/08d4f2f6-cc67-11e5-9fba-65aeb1ca9621.png)

**Comment by algesten** [comment]
@maxkueng the one from the front is great! i think the nostrils should be a bit closer together, but otherwise perfect. we have a winner :D

**Comment by maxkueng** [comment]
@algesten haha, yeah it looks funny but it doesn't really look like a real icon. Too many colors, no grid. I'm not a designr. I think @mdciotti did a better job at it.
Maybe he can do something based on it? Like with a big nose, hair in the face and horns to the side. I think that's what makes up the yak-look. 
The wide nostrils are intentional. It makes it look more like cattle and less like a pig. But maybe a bit closer would still work.

Would you be up to it, making it look more like a yak, @mdciotti?

**Comment by maxkueng** [comment]
![yakyak3-test](https://cloud.githubusercontent.com/assets/168709/12875071/2e801a68-cde2-11e5-9a97-c81a440ff476.png)

I'm playing around with the Material Design guidelines a bit.

**Comment by x-tk** [comment]
I like all of them but the google play on the yak is pretty awesome.

**Comment by maxkueng** [comment]
Some more iterations:

![yakyak3-s](https://cloud.githubusercontent.com/assets/168709/12988770/9ca040fe-d102-11e5-81e1-53eb93aec4bd.png)

**Comment by maxkueng** [comment]
Am I going in the right direction? More abstract or more details?
Anyone else have ideas for an icon?

**Comment by ariu** [comment]
Hey, didn't se that issue.
Mine is pretty simple. Hangout original icon speech bubble shape, with green background. Removed comas, added "Y" letter. The Y font is [futura regular](https://typekit.com/fonts/futura-pt), very close to Google logo font. And Finally, there is a long shadow 45° angle to look like modern apps icons. 
I'm not good with illustrator and art things, please be nice to me :) , just tryied this because yakyak placeholder logo felt wrong with the new skin from my fork.

[Here is svg](https://github.com/ariu/yakyak/blob/master/src/icons/yakyak-logo.svg)
![yakyak-logo](https://cloud.githubusercontent.com/assets/5445403/14043864/63e754ac-f289-11e5-8aa8-d6b833f60c8e.png)

I realy like your work though, especially second row, 5th column one (colored with eyes and green backrgound)

**Comment by rhoconlinux** [comment]
+1 @ariu :+1:  
It's google talk after all, the similarity has to be plain and simple, like in your approach. Cheers! :+1:

**Comment by algesten** [comment]
@maxkueng cows are go

**Comment by austin-guevara** [comment]
I have to say, I'm highly partial to @ariu's basic Y icon. I think many of the "Yak" icons are really great too, but the whole cow face seems a bit much. The simpler ones are more successful. They contribute to a more professional appearance/branding for the app.

**Comment by randymorris** [comment]
The biggest concern I have about the yak is what it looks like scaled down (say in the menu bar/tray on OSX).  There are lots of details that may get muddy at a really small size.  I haven't tried the new build yet so I don't know if it's in there.

**Comment by ariu** [comment]
@randymorris you can check small and big sizes here: https://github.com/yakyak/yakyak/tree/master/src/icons

**Comment by randymorris** [comment]
@ariu Thanks.  To me it's pretty hard to distinguish at 16x16, and even at 32x32 everything sort of starts to run together.  I think if I were going to use the yak as the logo I would consider maybe using a version with less detail for smaller sizes.  In particular, I think the solid green one (fourth row, fourth column) would look great at any size, but would be a good choice as a simplification at smaller sizes.

I don't want to clutter this thread up with my opinions though so that's the last I'll say on it.

**Comment by algesten** [comment]
for 16x16 i'd like to see just a black/white with alpha channel. 32x32 is kinda ok.

**Comment by dliscomb** [comment]
Dang... I liked the YakYak yak... complete with single-quote-nostrils irony

**Comment by davibe** [comment]
But if most people prefer the old one I can revert to it. Maybe tomorrow i can make a pre-release with the new UI and the old icon for you to try and we can gather feedback here

<img width="1438" alt="screenshot 2016-06-15 22 06 16" src="https://cloud.githubusercontent.com/assets/123929/16095563/6bc2b46c-3345-11e6-83d8-c60600b22d91.png">

**Comment by maxkueng** [comment]
Drawing the yak was probably my biggest Inkscape adventure. I'm not really a designer and I learned a lot doing it. It's a bit sad that it had to go. But I had fun doing it and I also like the new "Y" icon. The new icon no doubt fits better with the new design and colors.

![y](https://cloud.githubusercontent.com/assets/168709/16103236/fa003264-3376-11e6-8f41-a8557c937fd6.png)

Bye bye YakYak yak :wave:

**Comment by davibe** [comment]
https://github.com/yakyak/yakyak/releases/tag/v1.3.1
This is a pre-release with new ui and old icon together. Please test and give feedback here :)

**Comment by dliscomb** [comment]
I don't see what the big deal was:

the yak has a sly expression, looks distinctive in the menu bar, and doesn't blend in like the 'Y'. http://www.linkedin.com/in/drewliscomb
 

    On Thursday, June 16, 2016 5:29 AM, Davide Bertola <notifications@github.com> wrote:
 

 https://github.com/yakyak/yakyak/releases/tag/v1.3.1
This is a pre-release with new ui and old icon together. Please test and give feedback here :)—

**Comment by maxkueng** [comment]
Here's whet the different icons in 64px, 48px, 32px, 22px and 16px look like on light and dark backgrounds. 
The "Y" definitively stands out the most while the yak without background is the least visible.

![yakyak-sizes](https://cloud.githubusercontent.com/assets/168709/16125298/65c87962-33f3-11e6-89d3-e0486b5e434b.png)

**Comment by davibe** [comment]
Im not getting enough feedback

**Comment by dliscomb** [comment]
I favor the yak, white horns, with green background.  
The circular 'Y' is pretty generic.  I already have too many icons on my desktop with the circular esthetic, like HipChat, TreeView, Jabber, Chrome, FireFox, iTunes, Atom, even dBeaver.
Interestingly, Apple chose to put a square behind the System Preferences gear(s).  How would it look with a similar gradient background?

**Comment by maxkueng** [comment]
@dliscomb Can you post a picture of the gradient background? Then I can put the yak on it and you can see what it looks like.

**Comment by arnriu** [comment]
@maxkueng http://media.idownloadblog.com/wp-content/uploads/2015/05/System-Preferences-for-OS-X-Yosemite-app-icon-full-size.jpg

**Comment by maxkueng** [comment]
@arnriu So, a metallic green? That might look weird.

**Comment by algesten** [comment]
the yak was perfect as is. no need to change it. the y is terrible, generic and non-imaginative.

**Comment by maxkueng** [comment]
@algesten But the yak without a background does have issues with light and dark backgrounds. On a light background the horns let lost and on a dark background the hair disappears.

**Comment by algesten** [comment]
and design by committee is never a good idea. you get some average trade off without any edge.

**Comment by maxkueng** [comment]
But just ignoring all criticism doesn't make a design perfect.

**Comment by maxkueng** [comment]
I feel very honored that people like my yak though :heart_eyes_cat:

**Comment by arnriu** [comment]
@maxkueng dunno, maybe @dliscomb will explicit his idea. I'd say, just try some green gradient, such as http://www.colorzilla.com/gradient-editor/#0f9d58+0,0b6e3e+100

**Comment by dliscomb** [comment]
many thanks, @arnriu, both for the full-size 'System Preferences' and for the gradient.  Combine the two, and you have what I was trying to convey.  I was trying to find a compromise that would address the concerns, but to paraphrase @algesten, that will end up being... a compromise.

I love that OSS has the freedom to be different.  I have a pronounced contrarian streak, and so I find the 'Y' too derivative.  Regardless, I won't stop using YakYak regardless of the icon.

Many thanks to all the committers, and to those who contribute their viewpoints to this particular discussion!

(hmmm... maybe if the YakYak was blonde... :D )

**Comment by YesThatAllen** [comment]
I like how the current yak's (full size) horns seem to change when the icon is highlighted (via command tab).

**Comment by dliscomb** [comment]
fwiw, atom's icon is a black rectangle, but there is a fine edge around the rectangle to highlight it.
![image](https://cloud.githubusercontent.com/assets/10132519/16206455/8dc05786-36f6-11e6-8a22-8d2a9063ff50.png)

**Comment by jadengore** [comment]
Hey everyone, please go and vote for which icon you want over in #249!

**Comment by monchote** [comment]
The icon proposed in #265 is pretty cool, have you guys seen it?

**Comment by davibe** [comment]
So far votes are in favour of the new Y-icon. The new proposal in #265 still needs work to become an icon.

**Comment by jadengore** [comment]
@davibe I think that the icon voted on should be the one for now, maybe 2.0 could use #265?

**Comment by rhoconlinux** [comment]
Yeap... according to the voting process should be https://github.com/yakyak/yakyak/issues/249 right? :)
Cheers!

**Comment by PMiner** [comment]
@davibe What work specifically do you think needs to be done? or do you not know specifics, just a more vague though?

**Comment by link6155** [comment]
@davibe would be useful to know what "needs work".

**Comment by PMiner** [comment]
Any chance we could get a description? I would be happy to make the changes
an icon with the changes.

**Comment by clrg** [comment]
More fiddles.

![myyakyak2 svg 128](https://cloud.githubusercontent.com/assets/68176/16587512/e09d98a6-42c2-11e6-8a6e-2218ce9371b9.png)

Wtih zipped SVG.

[MyYakYak2.zip](https://github.com/yakyak/yakyak/files/347908/MyYakYak2.zip)

**Comment by clrg** [comment]
More ideas back on #308 but I liked this one:

![myyakyak4chew2 svg 128](https://cloud.githubusercontent.com/assets/68176/16614601/116d38d6-436a-11e6-8a93-bf3df6f80c4e.png)

**Comment by davibe** [comment]
haha, for some reason i see a sad pacmam instead of the yak

**Comment by clrg** [comment]
ROFL that's 2 iconic references!

Here's another fiddle...

![myyakyak5chew1 svg 128](https://cloud.githubusercontent.com/assets/68176/16671537/c6fa4d82-4497-11e6-89bc-08c575824521.png) ![myyakyak5chew2 svg 128](https://cloud.githubusercontent.com/assets/68176/16671538/c70b05e6-4497-11e6-9e5b-8fb9c7cd1a64.png)

**Comment by clrg** [comment]
Procrastinating on something else, played about and made a .ico file, trying to make the lo-res ones look less like smudges.

[MyYakYak-ico-xcf.zip](https://github.com/yakyak/yakyak/files/354141/MyYakYak-ico-xcf.zip)

**Comment by davibe** [comment]
@PMiner @link6155 what i meant by work is
- create all resolution and formats
- see how it looks with different backgrounds and with no shadow as well as in the tray on ios/win/linux (trays are different)

**Comment by PMiner** [comment]
Ok! @davibe I will work on this ASAP.
