### ISSUE TITLE
Hide window borders on Windows

### ISSUE THREAD

**Issue by Naatan** [yakyak/yakyak#211]
On windows it shows the native window borders (including titlebar).

**Comment by davibe** [comment]
we need windows contributors for this. I am not a windows user.

**Comment by tvthatsme** [comment]
Confirmed that windows shows the native borders which takes a lot away from the sleek look.

The route forward for this would be to add a frame property if the process.platform is 'win32' to the creation of the browser window (src/main.coffee):

```
    mainWindow = new BrowserWindow {
        width: 730
        height: 590
        "min-width": 620
        "min-height": 420
        icon: path.join __dirname, 'icons', 'icon.png'
        show: true
        titleBarStyle: 'hidden-inset' if process.platform is 'darwin'
        frame: false if process.platform is 'win32'
    }
```

However, this removes the toolbars as well (YakYak, View, Color Scheme). So this change is going to need to dig deeper into the UI of the app to be able to expose the toolbar menus without the frame support. I'd like to help but can't promise my availability for windows access.

Just wanted to help get that conversation started :smile:

**Comment by Naatan** [comment]
I guess it needs a burger menu or something similar. Or you can just make it an ALT menu (hide it by default, show it when someone presses ALT). This would be an issue on linux as well.

**Comment by davibe** [comment]
Maybe we could un-hide borders when mouse reaches the top yakyak titlebar ?

**Comment by Naatan** [comment]
That sounds really awkward. Imo ALT hiding would be a better/cleaner solution.

See:

https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions

Ctrl+F for `autoHideMenuBar`

**Comment by tvthatsme** [comment]
Going the ALT or mouse proximity methods hides information from the users which is normally bad from a usability point of view. You have to know that functionality is there before you can use it.

I would favor a full integration of the toolbar into the app (think <header>) across all platforms. It would be a lot more work but it could be beautiful and wouldn't put the app at Window's or Linux's mercies on how things get styled. It would affect a lot more people though so idk if its worth all the trouble.

**Comment by tvthatsme** [comment]
Or... hamburger menu on the top right?

**Comment by Naatan** [comment]
Couldn't it just be added here?

![image](https://cloud.githubusercontent.com/assets/278649/16161304/c49e0536-349a-11e6-9506-3f90ef4ab009.png)

**Comment by tvthatsme** [comment]
Yeah, that's exactly what I was thinking!

**Comment by davibe** [comment]
we can make the hamburger visible just on windows. It can sit aside of the "three-vertical-dots" icon. Does linux benefit from this too ?

**Comment by Naatan** [comment]
Linux would benefit too, but why add another burger menu? Just add it to the "3 dots menu" (burger menu).

**Comment by davibe** [comment]
So you would reveal the menu window menu while also revealing the conversation menu (which is what the buger-menu does right now) ?

**Comment by Naatan** [comment]
No, I would place the menu items that are currently in the menubar inside the "conversation menu". Essentially the conversation menu becomes the all inclusive menu, part of which would have to become for conversations.

**Comment by davibe** [comment]
mh, re-implementing the window menu bar..

**Comment by Naatan** [comment]
IIRC Electron saves the menu markup in a JSON file, so it shouldn't be too hard to simply take that JSON file and use it to populate an alternate menu.

**Comment by Naatan** [comment]
Relevant: 

https://github.com/ragingwind/electron-menu-loader

**Comment by tvthatsme** [comment]
I think the whole point of this is that the style of the default windows menu bar doesn't mix with the material-like style of yakyak. So to match those styles for a windows user, yes, you would have to re-implement the menu bar. If you do it right, it looks really slick (take GitHub for Windows as an example https://github.com/blog/1127-github-for-windows).

**Comment by Naatan** [comment]
Given that this menu is unlikely to hold many items it would be overkill to do some type of metro specific styling. Imo putting the relevant menu entries into the dots menu and calling it a day is totally fine given the scope of this application and how often you would be accsessing those menu items (once, twice?)

**Comment by mrdimfox** [comment]
It will be so awesome if you make something with disgusting titlebar in Windows! Completely removing it will be the best option. Something like in Discord. You can use some separated settings screen instead of using menu bar. I hope it will be done someday cause now it is so ugly...

**Comment by averissimo** [comment]
@mrdimfox there was a regression on feeabb4c98bbecae8efdf7cfa8a7880501ae815e and the menu stop being hidden.

Already corrected and it is already in master branch  #489

**Comment by averissimo** [comment]
@mrdimfox can you try to install 1.4.1 pre-release, it has been updated and does not show menu anymore

you have to click on the 3 stacked lines to show menus :)

**Comment by mrdimfox** [comment]
Yes, thanks. That's good. But I said about title bar. See in screenshot below with red border.

<img src="https://cloud.githubusercontent.com/assets/5342162/20938241/4e635cca-bbfb-11e6-8a52-e4ccc2a1d44f.jpg" width="80">

And Discord here (have no any title bar):
<img src="https://cloud.githubusercontent.com/assets/5342162/20938317/aaab18b0-bbfb-11e6-96f3-22a3986e48ba.png" width="80">

For Discord it's look very naturaly. For example, Telegram have not any title bar too. But Whatsapp have, and it's ugly, IMHO.

**Comment by Sazpaimon** [comment]
So I decided to take a stab at this, and experimented with frameless windows and managed to come up with something that looks like this in Windows 10:
![image](https://cloud.githubusercontent.com/assets/247570/24320984/bb4959f4-1117-11e7-8002-e4fa54f740bd.png)
Clicking the hamburger menu will bring up the application menu as a context menu instead of displaying the menu as a separate row, and the window controls are integrated with the rest of the application.

I need to double-check if this looks okay on Linux, but if this design looks good to you all, I'll make a PR. Word of warning, though, this was my first time working in Electron so I may have made some rookie mistakes in the implementation.

**Comment by mrdimfox** [comment]
@Sazpaimon yeah, it looks pretty good!

**Comment by averissimo** [comment]
looks nice!!

**Comment by chazz422** [comment]
How do I change it back to have native window borders?  I'm on linux and I don't like the new borderless look.  I prefer to shade my window at times and I can no longer do this without the native titlebar.  Is there an option I'm missing?

**Comment by Sazpaimon** [comment]
Linux should have native window borders as of 1.4.4
