### ISSUE TITLE
Wrong icon on Windows

### ISSUE THREAD

**Issue by Naatan** [yakyak/yakyak#212]
It briefly shows the Yakyak icon (at low res) but then switches to the Electron icon.

**Comment by davibe** [comment]
some sort of windows cache ? Again, we need more window contributors :P

**Comment by bryanzw15** [comment]
Just as an addition, if I do npm run electron app, it shows the YakYak icon at low res. If I run the pre-built binary I downloaded from here, it shows the Electron icon.

**Comment by cobrabr** [comment]
I get the low-res icon even getting the binaries from the Releases page.

**Comment by averissimo** [comment]
@Naatan @cobrabr @msphair we changed the way we package the application, is this still an issue with 1.4.0 or up?

**Comment by cobrabr** [comment]
Working perfectly now, at least for me! 👍 😁
