### ISSUE TITLE
'Conversations' stomped by 'Max' button

### ISSUE THREAD

**Issue by dliscomb** [yakyak/yakyak#216]
YakYak 1.2.1 (1.3.1)
On OS X 10.11.15, the title bar text 'Conversations' gets stomped by the Close/Min/Max buttons:

![image](https://cloud.githubusercontent.com/assets/10132519/16117628/0b4b8bf2-33a1-11e6-8b6b-752da1e28f10.png)

**Comment by arnriu** [comment]
Try ⌘+ or view -> Zoom in.

Will look into it later to make this part of window responsive to zoom.

**Comment by randymorris** [comment]
I can confirm that zooming out causes this, but the default zoom level displays correctly.
