### ISSUE TITLE
Replace emoticon signs to emoji automatically

### ISSUE THREAD

**Issue by TadeasKriz** [yakyak/yakyak#220]
The Google Hangouts application automatically replaces character combinations like `:)`, `:(` etc with corresponding emoji. Could this be added to YakYak?

**Comment by davibe** [comment]
Of course it's possible. Just needs someone looking into it ;)

**Comment by peterhogg** [comment]
This could be helpful to map the input to emoji: https://aprescott.com/posts/hangouts-emoji

**Comment by acordar** [comment]
I've done a pull request #248  for a solution to this. It uses emoji codes from http://www.emoji-cheat-sheet.com/. I've only added emoji codes for the People category; however, it would be trivial to add the rest.

**Comment by davibe** [comment]
merged
