### ISSUE TITLE
Updater States Wrong Release 

### ISSUE THREAD

**Issue by NxtGenCowboy** [yakyak/yakyak#221]
![yakyak](https://cloud.githubusercontent.com/assets/1991409/16131019/a1aa5774-33d1-11e6-86ca-8577f081473b.PNG)

It seems the Updater Window is incorrect with the versioning. Or I'm reading it wrong..

**Comment by bryanzw15** [comment]
I've noticed it does this for the pre-release versions. I think it's because it only checks if your version is the same as the release and if it isn't, it tells you to download the release version, regardless of what your version is.

**Comment by davibe** [comment]
yes it's just a pre-release thing. It tells you to update to stable. We are not handling version checks very well but it does work correctly for normal releases.

**Comment by averissimo** [comment]
belived it stopped doing it with pre-releases.

closing
