### ISSUE TITLE
Global Shortcut for Show/Hide

### ISSUE THREAD

**Issue by derekderaps** [yakyak/yakyak#223]
v1.3.1
OS X

I love the option to run faceless (no Dock icon) but need a global show/hide shortcut to pull it back up without going to my system tray.

**Comment by davibe** [comment]
I think it can be difficult to pick a generic shortcut for yakyak therefore it should be configurable (?)

**Comment by acca** [comment]
v1.4.3
OS X

I am also interested in this feature. Usually I use `CMD + m` or `Cmd + h` to close or hide the chat window. Then I use `CMD + tab` to switch back to the application. Once the application has the focus I would like to open the chat window with a shortcut. I propose few options:

1) As of now `CMD + 1` brings to the first chat if you have the chat window already open. This should work also when the chat window is on hidden or in the background or even closed. This works in many other OSX applications: when you are in the application context and you press any particular shortcut the main window comes back to the foreground (Try with Mail.app -> `CMD + w`  to close main window and `CMD + 1` to with the Sent mailbox)

2) the function of `Toggle minimise to tray` in the system tray icon already does the trick. It is just inconvenient to use the mouse. Why not replicate the same menu item in the `View` or `Window` main menu of YakYak? In this way every user could map the preferred shortcut using `Keyboard->Shortcuts` in OSX Preferences

I will be happy to help testing any possible solution.
