### ISSUE TITLE
[Windows] Allow minimize or close to tray

### ISSUE THREAD

**Issue by Viper007Bond** [yakyak/yakyak#225]
I did a search for similar issues and it seems something like this used to exist, but I guess it went away?

I want YakYak running 24/7 but not cluttering up my taskbar and instead minimized to my tray, notifying me when I receive new messages.

It seems possible to do this currently but the flow is pretty clunky. I'm forced to right-click the tray icon and select "Toggle minimize to tray". Or am I missing something?

In an ideal world (at least mine), minimize would minimize to the taskbar, close (X) would minimize to the tray, and you would exit the application by right-clicking the tray icon. If the tray icon feature was disabled, then close (X) would exit.

v1.3.0 on Windows 10

**Comment by wigster** [comment]
I concur that this should be how it works. In addition, double-clicking the tray icon should open the Yakyak window,

Whatsie, the Electron-based Whatapp client, works exactly like that, so it should be possible.

**Comment by Viper007Bond** [comment]
Yep, totally possible. The company I work for has an Electron-based app that works similarly as well: https://github.com/Automattic/wp-desktop

**Comment by ctcpip** [comment]
+1  - should be this way for Linux (LXDE) as well

**Comment by Arithmomaniac** [comment]
On 1.3.3 (Win10), Even when "close to tray" is checked in the tray options, clicking X still exits the application.

**Comment by averissimo** [comment]
the close to tray issue is solved in #397 :)

**Comment by awprgrmmr** [comment]
I am on Windows 10 and can confirm that it neither minimizes or closes to tray.

**Comment by averissimo** [comment]
This should be solved in the next version, #397 pull request has not been merged yet and has this fix.

If you want to test it before hand try to find a file called `resources/app/main.js` and replace `close` with `unload`:

    return mainWindow.on('close', function(ev) {

with 

    return mainWindow.on('unload', function(ev) {

run yakyak and it should work (credit to @nerijus )

**Comment by averissimo** [comment]
see #451 for the beta release. It should solve the problem
