### ISSUE TITLE
New version notifier wants to downgrade

### ISSUE THREAD

**Issue by KoenPasman** [yakyak/yakyak#226]
Not sure if this is a bug, or a feature. 

I just installed the 1.3.1 pre-release and when I logged in immediately received a notification to upgrade to the newest version. 

"A new yakyak version is available, please upgrade 1.3.1 => 1.3.0". 

Seeing that this is a prerelease I understand that it wants me to run the latest, but I don't think the notification is necessary. 

(Github media upload seems broken atm, so no screenshot attached)

**Comment by arnriu** [comment]
duplicate https://github.com/yakyak/yakyak/issues/221
