### ISSUE TITLE
Minimize to tray issue on Ubuntu Gnome 16.04

### ISSUE THREAD

**Issue by jfyu** [yakyak/yakyak#228]
Hi, 

I have a issue similar to the Windows specific tray question earlier. Essentially I am forced to left-click the tray icon and manually select "toggle minimize to tray" in order to see Yakyak UI again. Right-click does nothing. Also close minimize to tray doesn't work, the thing just closes and the tray icon disappears. On the plus side, the "start minimized to tray" option does work. 

I am using the latest 1.3.0 pre-built binaries. I also don't see the "change UI theme" menu item but that's cosmetic and less important to my usage.   

P. S. The reason why I'm using pre-built binaries is because I am having trouble compiling from source, keep on getting a gyp error (I have Anaconda python). When using /usr/bin/python I still get "gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp" Haven't got around to debug that yet.

**Comment by davibe** [comment]
for changing theme try 1.3.0 pre-release

**Comment by davibe** [comment]
the "nan" issue is something related to recent node.js versions. Try using node.js 4.4

**Comment by arnriu** [comment]
(fwiw, I use node 6 on both mac and windows, I have the NaN error, and I am still able to build and run from fresh clone. Do not give it too much attention).

**Comment by oblitum** [comment]
I'm having similar issues. I'm on ArchLinux running the latest release from AUR, even with close-to-tray enabled, closing the application simply closes it.

**Comment by averissimo** [comment]
I think I had similar problems and solve it (for my **ubuntu** system) in this branch: https://github.com/averissimo/yakyak/tree/keep_in_tray

It is rebased against yakyak/yakyak and just tested as working and master branch not working.

@oblitum Can you test it?

**Comment by oblitum** [comment]
hi @averissimo, I'm sorry but I'm running this client installed from AUR, I'm not installing from master.

**Comment by averissimo** [comment]
@jfyu @oblitum can you test latest beta version

see #451 for the download link

**Comment by averissimo** [comment]
that was solved in recent builds by @nerijus
