### ISSUE TITLE
YakYak prompting to upgrade when running pre-release version

### ISSUE THREAD

**Issue by mattselph** [yakyak/yakyak#230]
I'm running YakYak v1.3.1, which is a pre-release version.  When starting up for the first time, it prompted me to upgrade with a message that a newer version was available, and the string "1.3.1 >= 1.3.0."  I think this string should be more clear, maybe alerting the user only if their version is less than the released version.

**Comment by mattselph** [comment]
Issued pull request #231

**Comment by jarrydfillmore** [comment]
+1!

**Comment by davibe** [comment]
should be fixed in my last commit and in the 1.3.1 pre-release i just updated. Please give me feedback on the icon #21
