### ISSUE TITLE
OS X autocorrect does not function in text entry

### ISSUE THREAD

**Issue by jkuss** [yakyak/yakyak#237]
It would be great if this worked.

**Comment by davibe** [comment]
autocorrection is the first thing i disable everywhere on desktops :) but ok. If someone wants to jump-in could be a nice addition

**Comment by aPoCoMiLogin** [comment]
Autocorrection is something i don't like too, but spell checker is fine and i'm missing it too.

**Comment by davibe** [comment]
closing as duplicate of https://github.com/yakyak/yakyak/issues/61
