### ISSUE TITLE
Text entry field is not unique to conversation

### ISSUE THREAD

**Issue by jkuss** [yakyak/yakyak#238]
If I type in chat A and switch to chat B before sending, the text i was typing is available to sent to chat B. This field should be unique to the chat as it is a 'drafts' area of sort. You should be able to type in there, switch to B and type something else, and maintain 2 separate text fields.

**Comment by ctcpip** [comment]
+1

**Comment by ctcpip** [comment]
Bump.  👎 `probot-stale` ^ 👎

**Comment by averissimo** [comment]
hummm, this is because when message is built, it takes current selected conversation (userinput.coffee)

```
buildChatMessage = (sender, txt) ->
    conv_id = viewstate.selectedConv
```

this needs to passed as an argument instead

**Comment by averissimo** [comment]
@ctcpip thanks for keeping this alive! :)

**Comment by ctcpip** [comment]
Bump. 👎 stalebot 👎
