### ISSUE TITLE
icon on windows needs improving

### ISSUE THREAD

**Issue by algesten** [yakyak/yakyak#24]
![tmp-52438kggn14bu58l3](https://cloud.githubusercontent.com/assets/227204/8416305/185d9ec8-1ea5-11e5-9d30-46e4f7883e99.png)

**Comment by maxkueng** [comment]
Maybe the standard icon needs to be larger. Can you try to play around with the sizes? What if the `icon.png` was 64px? Does it still look good in in the window title? I don't have a Windows computer and my Linux desktop doesn't have window titles. I only have a small taskbar-like thing.

![yakyak-taskbar](https://cloud.githubusercontent.com/assets/168709/8427000/589c69f0-1f14-11e5-93fd-80766de923b5.png)

**Comment by algesten** [comment]
i don't use windows myself. but yes. i think it should be one of the larger sizes.

**Comment by Gibbz** [comment]
yeah it looks horrific on ubuntu also. Looks very low resolution

**Comment by AdrianoCahete** [comment]
And if you have a dark wallpaper, its seems to quite off/dark...

![yakyak_win10.PNG](https://files.zenhub.io/566582ddb51138092d360b6e)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
