### ISSUE TITLE
Window freaks out if long message is taller than window height

### ISSUE THREAD

**Issue by zuccs** [yakyak/yakyak#242]
Not a big deal, but thought I would add it to the list for you. 

If you write a message taller than the height of the window (mine is full height), and send it. Both panels of the app (contacts and message) freak out.

Restarting the whole app fixes it and it can display the tall message properly.

**Comment by davibe** [comment]
hehe

**Comment by averissimo** [comment]
Example:

It is ok while the input container is smaller than the right side of the interface.

However, at one point the contact lists is shifted up _(leaving white space below it)_ and after pressing "enter" the contact list is frozen as is, and the input box also changes (leaving underlying emoji container visible.

![outmtmywsflot](https://cloud.githubusercontent.com/assets/211358/19392806/3c0643bc-922a-11e6-9fc1-bff07dc5a59f.gif)

**Comment by averissimo** [comment]
Reported by @PSiAU

When pasting in multi-line text dumps (like log output), the text input area gets messed up.
I'm running v1.4 on a Mac.
To recreate it, paste 28 or more lines worth of text into the text input area. It can even be lines with a single character on it. The more lines past 28 you paste, the messier it gets.
Screenshot attached
![capto_capture 2016-12-02_02-32-35_pm](https://cloud.githubusercontent.com/assets/2519639/20822223/fe0febe6-b89c-11e6-82d8-6f486c890e55.png)

**Comment by averissimo** [comment]
@zuccs i'm changing the title a little. Hope you don't mind

**Comment by averissimo** [comment]
As @kusioST reported this bug is still active when pasting or writing long inputs

from #574

![](https://user-images.githubusercontent.com/25057693/28655908-098a3f8c-729f-11e7-8c83-8ff564bdf289.jpg)

**Comment by averissimo** [comment]
See pull request #730 for an implementation... I used maximum of 5 lines for the textarea.

It was an arbitrary choise, if you guys prefer more or less let me know :) @zuccs @KusioST

Please give feedback so I can merge the changes

**Comment by averissimo** [comment]
Screencast with demo

![outfmkulac7za](https://user-images.githubusercontent.com/211358/28672594-7023eeaa-72e0-11e7-8616-78b4783b5ae0.gif)

**Comment by KusioST** [comment]
At the request of a averissimo (#729) - screen from #574 
![error_yak_yak](https://user-images.githubusercontent.com/25057693/28820764-209c5fbc-76b3-11e7-8838-803aad90a78a.jpg)
