### ISSUE TITLE
osx dock bounce on messagess

### ISSUE THREAD

**Issue by Jeppesen-io** [yakyak/yakyak#244]
Typically, osx icons bounce when chat programs receive a message. This is very helpful on systems where the dock is hidden.

![bounceicon](https://cloud.githubusercontent.com/assets/5796153/16205270/ddcfd9aa-36d7-11e6-8424-bf7de9787069.gif)

**Comment by ctcpip** [comment]
This may have been fixed as part of #101 / #235 

Have you tried compiling/running the latest code?

**Comment by randymorris** [comment]
I can confirm that it works on 1.3.1 for me.

**Comment by Jeppesen-io** [comment]
Yep, I wen't to 1.3.1 pre-release and it works. Thanks!
