### ISSUE TITLE
Signing the binary?

### ISSUE THREAD

**Issue by YesThatAllen** [yakyak/yakyak#245]
I, as would others, I'm sure, would be open to signing this project's binary. 

Let me know know if there are plans for that, or if there's a fund I can contribute to for the Yak to get its own dev account.

**Comment by davibe** [comment]
I never looked into this but as yakyak becomes more and more popular i can see how it would help.

**Comment by johnduhart** [comment]
Still relevant, for example my corporate policy prevents users from installing unsigned binaries.

**Comment by danchr** [comment]
I've posted pull request #768 which should enable signing binaries when built on a Mac. What's the build process for releases? Are they built manually or by Travis?

**Comment by averissimo** [comment]
They are built by Travis

**Comment by averissimo** [comment]
Reopening just to see if any conclusion was reached. If not just let it close again.
