### ISSUE TITLE
User's Name is not displayed in conversation list for new conversations

### ISSUE THREAD

**Issue by ctcpip** [yakyak/yakyak#246]
When I initiate a new conversation via yakyak (or if I simply receive a message from someone that causes a new conversation), the name of the contact is not displayed.  Once I close and re-open the application, then the name is displayed.

![yakbug](https://cloud.githubusercontent.com/assets/15326526/16206959/7ab79fa6-36f0-11e6-9142-f3a556280655.png)

**Comment by x-tk** [comment]
+1'd

**Comment by ctcpip** [comment]
Bump.  👎 `probot-stale` ^ 👎

**Comment by ctcpip** [comment]
Bump. 👎 stalebot 👎
