### ISSUE TITLE
Vote for new/old icon

### ISSUE THREAD

**Issue by jadengore** [yakyak/yakyak#249]
Currently, @davibe has removed the new icon temporarily since some have expressed that they like it more than the newer one. I'm hoping to use my post as a discussion/voting ground so we can decide which logo to use going forward. Since I prefer the new one, but am all for using what the community wants, let's use the reaction feature to count votes.

👍 for the new logo

![New logo](https://raw.githubusercontent.com/yakyak/yakyak/98830b559b503e334383b83b9abb295f035d633f/src/icons/icon_256.png)

👎 for the old

![Old logo](https://raw.githubusercontent.com/yakyak/yakyak/9d5f78326d7c29391079fd2bcb0a610f6de13732/src/icons/icon_256.png)

**Comment by maxkueng** [comment]
Those looking for the icon discussion thread can find it in issue #21.

**Comment by compuguy** [comment]
Both are great looking icons, but I think the new one better tells and displays what the product is....

**Comment by PMiner** [comment]
could you add #265 to vote for as well? i prefer that one.

**Comment by jadengore** [comment]
@PMiner See [this](https://github.com/yakyak/yakyak/issues/21#issuecomment-228591151), I don't think it's going to make it currently. Maintainers think the design needs some work, and both of the ones above have already been shipped with YakYak.

@davibe Can you switch the icon back?

**Comment by jadengore** [comment]
I think we are sticking with new, closing this issue.
