### ISSUE TITLE
Blank page at two-step verification, 32 bit Linux Ubuntu

### ISSUE THREAD

**Issue by jfyu** [yakyak/yakyak#251]
Hi all,

Just tried yakyak on my old office computer running 32 bit Linux Ubuntu 16.04. I get a blank page at the two-step verification page . running ./yakyak doesn't give any error though...

This happens on both the point release and the latest stable release. 

This is interesting, I think I ran into similar problem with the other electron app Franz, but I think that was a 64 bit computer. 

Yakyak was running fine on linux 64 bit Ubuntu Gnome 16.04 on my other computer though (except the save to tray issue that I opened earlier).

**Comment by anarchocurious** [comment]
I am having the same issue on the 64 bit version.

I suspect the issue has more to do with two-step verification than the architecture.

**Comment by davibe** [comment]
Is twostep auth something you can enable / disable ? Never played with it

**Comment by PMiner** [comment]
yes, it is. also, you can generate an app password to bypass 2-step authentication.

**Comment by davibe** [comment]
How can i enable two step ? i am not android user, i am a gmail user.

**Comment by averissimo** [comment]
@jfyu can you try with 1.4.0 or earlier?

`./yakyak`now shows what was the error

**Comment by annie2004** [comment]
Test Yakyak 1.4.0 for "google sign in two step verification", Ubuntu x64. Doesnt show the error. Return blank page.

**Comment by averissimo** [comment]
can you try 1.4.1 pre-release. It will show an error window with a link to open the inspector.

Please open and take a screenshot of the Console tab

**Comment by cyruscuenca** [comment]
I'm having the same problem with 64 bit Ubuntu 16.04 LTS. 
![screenshot from 2017-02-15 07-35-00](https://cloud.githubusercontent.com/assets/18109870/22981504/6a215de4-f351-11e6-8ef0-e177e526f659.png)
