### ISSUE TITLE
change the notification sound

### ISSUE THREAD

**Issue by tech4eleven** [yakyak/yakyak#254]
It would be great to allow the notification sound to be changed. its too quiet for my taste. (I'm on OS X)

**Comment by mattsigal** [comment]
Further, is there a way to disable the notification sound entirely?

**Comment by davibe** [comment]
You can do all those things in osx "System Prefernces" app, i think

**Comment by Siddhartha90** [comment]
You can disable the notification sound from System Prefs -> Notifications but can't assign it a new sound.
