### ISSUE TITLE
Add proxy configuration to UI

### ISSUE THREAD

**Issue by joshstrom** [yakyak/yakyak#255]
In my work environment, I sit behind an HTTP proxy. Out of the box, while the Google sign-in process worked, the application itself hung on "Connecting" after login. To resolve this, I added and Windows shortcut that set the HTTP_PROXY and HTTPS_PROXY environment variables prior to starting the application.

Would it be possible to add proxy configuration to the UI, preferably supporting both HTTP and SOCKS proxies?

**Comment by davibe** [comment]
we don't have a preferences/settings screen yet. That's why most flags sit in the window menu.
