### ISSUE TITLE
Pin to taskbar in win 10 breaks

### ISSUE THREAD

**Issue by msphair** [yakyak/yakyak#258]
![image](https://cloud.githubusercontent.com/assets/1900880/16239934/1e3585e8-379c-11e6-967d-5673d38b38cf.png)

this is version 1.3.1

This happens when you right click on yakyak and click "pin to taskbar" in windows 10.

I got around this by right clicking the YakYak icon on the taskbar then right clicking the "electron" icon in that menu, and _then_ clicking "pin to taskbar"

**Comment by averissimo** [comment]
@msphair is this still an issue?

seems like it is trying to spawn a new instance :\

**Comment by msphair** [comment]
@averissimo, this seems fixed. However, if you pin to taskbar, then unpin from taskbar, the next time you right click on the icon you only get a "close" option instead of the full options with "pin to taskbar". You need to close the program and re-open it in order to pin it again.

I created https://github.com/yakyak/yakyak/issues/540
