### ISSUE TITLE
the win10 taskbar icon uses the electron icon when pinned

### ISSUE THREAD

**Issue by msphair** [yakyak/yakyak#259]
![image](https://cloud.githubusercontent.com/assets/1900880/16240116/e220d246-379c-11e6-839b-f20cbe152e30.png)

Only when it is closed. When you click that icon and it opens, it switches to the YakYak icon

**Comment by compuguy** [comment]
Plus the fact the app uses the electron icon vs. the yak yak icon. Only way to fix this is to convert one of the pngs to ico, then change a shortcut to the correct icon.

**Comment by davibe** [comment]
we had the .ico for the Y-icon but we don't have for the Yak-icon. See #21 #249 #24

**Comment by LinkofHyrule89** [comment]
You can use XnView to easily convert any image to an ico. Making a shortcut with the correct icon is pretty easy. I wonder if you can just include the shortcut with the changed icon with the project?

**Comment by davibe** [comment]
does this still happen in 1.3.2 ?

**Comment by msphair** [comment]
yes same behavior

**Comment by averissimo** [comment]
@msphair does this still happen in 1.4.1? we changed the way YakYak is packaged.

**Comment by averissimo** [comment]
closing because #212 seems to be about the same issue

@msphair please reply there :)
