### ISSUE TITLE
Link of image not showing the image inline

### ISSUE THREAD

**Issue by xori** [yakyak/yakyak#26]
For example when pasting the link http://blogs.ubc.ca/lillienne/files/2011/01/nike-yesterday-you-said-tomorrow.jpg the image will show in the chat for a frame, then dissappear. 

I have seen it work successfully, but 95% of the time it will show then immediately hide it.

Windows 8.1 x64 beta 3

**Comment by davibe** [comment]
I fixed this in 6c5784e682d1952ce3043640c1c45c35f3849117

Will be landing in next release, thank you!
