### ISSUE TITLE
Notifications in Mac aren't followable

### ISSUE THREAD

**Issue by AceKatz** [yakyak/yakyak#260]
When a notification for a new message pops up, clicking on it doesn't bring forward the window (like most other Mac applications), it just closes the notification.  

Dunno if this was intentional or not, thought it'd be worth mentioning.

**Comment by arnriu** [comment]
Can you try this if you know how to do it ? https://github.com/yakyak/yakyak/pull/256

If not, just wait, it should be in the next [pre-release](https://github.com/yakyak/yakyak/releases) build if @davibe merges it, and you'll be able to give it a try.

**Comment by AceKatz** [comment]
That worked.  I probably patched it in the least maintainable way possible, but it works. 

Thanks for your help!
