### ISSUE TITLE
Feature request: in mac os, when tapping notification, should bring app to foreground

### ISSUE THREAD

**Issue by lowellk** [yakyak/yakyak#261]
This is what I think all other apps do.

**Comment by arnriu** [comment]
Can you try this if you know how to do it ? https://github.com/yakyak/yakyak/pull/256

If not, just wait, it should be in the next [pre-release](https://github.com/yakyak/yakyak/releases) build if @davibe merges it, and you'll be able to give it a try.

**Comment by lowellk** [comment]
I don't know how to do it. But this issue looks like a dupe of that other
one, so feel free to close it

On Wed, Jun 22, 2016 at 3:06 PM, Arnaud Riu <notifications@github.com>
wrote:

> Can you try this if you know how to do it ? #256
> <https://github.com/yakyak/yakyak/pull/256>
>
> If not, just wait, it should be in the next pre-release
> <https://github.com/yakyak/yakyak/releases> build if @davibe
> <https://github.com/davibe> merges it, and you'll be able to give it a
> try.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yakyak/yakyak/issues/261#issuecomment-227891765>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAOdmfxx6Gn4WRMlXHLmNqMiONwqvEPzks5qObHQgaJpZM4I8P8N>
> .
>



-- 
Cheers,
Lowell

**Comment by monchote** [comment]
I can confirm I fixed this in #256

**Comment by monchote** [comment]
#256 is now merged so this can be closed.
