### ISSUE TITLE
Feature Request? - have a way to not show any chats?

### ISSUE THREAD

**Issue by dustinarden** [yakyak/yakyak#263]
In Google Hangouts (im on the mac client) you could click out of any active chat thus keeping anything from showing up.  Say i dont want my previous chat glaring on my screen as someone walks by I could simply click out of the chat and it wouldnt show the contents of that particular chat with that specific person or group.
Is there a way to do this already?  If not i propose this functionality be included?  

Thanks!

**Comment by apiccirilli** [comment]
A bit of a hacky workaround, but you can click on the plus to start a new conversation, don't choose any people for the conversation, and click OK. Shortly thereafter the previously open chat closes. I'd love to be able to just press escape while in a conversation to go to this blank screen.

**Comment by x-tk** [comment]
Yes, would prefer to have some privacy features added so when people walk up on me at work, they aren't reading my last conversations with other employees.

**Comment by averissimo** [comment]
plus button, minimize button or any operating system shortcut would do the trick.

newest skypeforlinux adds a generic overlay when clicking on the username on top of the contacts, but that is also achieved with the plus button.
