### ISSUE TITLE
Won't connect.  Then crashes.

### ISSUE THREAD

**Issue by KennethScott** [yakyak/yakyak#264]
On Windows 7 Ultimate x64.  Tried yakyak 1.3.0 and 1.3.1

When launching app for the first time, it successfully takes my credentials and MFA, but then proceeds to a blank screen where it attempts to connect unsuccessfully, over and over:

![image](https://cloud.githubusercontent.com/assets/823499/16312011/6b690f2c-3938-11e6-84f1-c06bf73395bb.png)

If I close the app and then relaunch the exe, I get a javascript exception:
![image](https://cloud.githubusercontent.com/assets/823499/16311676/1330abb8-3937-11e6-9912-efce0c65cc67.png)

I'm using a google apps for work account.

If I delete the yakyak folder in %APPDATA%, I can start over but it always does the same thing.

Is there a log somewhere I can possibly see a little more info about the exception?

**Comment by kennethscott** [comment]
Now thinking this is a proxy issue after reading issue #255.  

We point to a proxy PAC file (proxy auto-config script) - so I'm not sure how to apply that to the two environment variables referenced in issue #255.  I know I can get the actual proxy addresses out of the PAC file, but they do change periodically.  Would be nice if the app could just use the system proxy configuration.

**Comment by joshstrom** [comment]
@KennethScott 
As a workaround to set proxy on launch from Windows (and still launch with double-click from an icon), create a shortcut and specify as the target:

```
C:\Windows\System32\cmd.exe /c "SET HTTP_PROXY=http://<proxy-host>:<port> && SET HTTPS_PROXY=http://<proxy-host>:<port> && START /D ^"\YakYak^" yakyak.exe"
```

If your proxy requires a username/password, I'm not sure how to set it like this.

With this, I am able to run YakYak under Windows behind a proxy. Alternatively, something like Proxifier could likely be used to force the connection through the proxy.

**Comment by datanotion** [comment]
Same problem for me, but on a Mac.  Is there a workaround for the Mac?

**Comment by joshstrom** [comment]
@datanotion 
Untested, but a likely fix: [this answer on StackOverflow](http://stackoverflow.com/a/588442/542494) or one of the other ones on the page cover setting environment variables for apps launched through Spotlight.

**Comment by datanotion** [comment]
@joshstrom - bummer, didn't seem to have any effect.  Thank you for the idea though!

**Comment by catskull** [comment]
I am also having this issue. I was able to install and use it just fine until about a week ago.

**Comment by averissimo** [comment]
@catskull On december 1st google changed the protocol. You need to update to 1.4.0 or 1.4.1 to get it back working

**Comment by catskull** [comment]
@averissimo Thanks! I install with brew cask, should that have the latest version?

**Comment by davibe** [comment]
@catskull you can use brew cask commands to see which version it is going to install (seems 1.4.0).
I don't remember who is maintaining the cask package :)

**Comment by catskull** [comment]
Okay, looks like cask installs 1.2.5 for me. I'll just download the release!

**Comment by davibe** [comment]
thank you
