### ISSUE TITLE
Suggestion: New icon

### ISSUE THREAD

**Issue by link6155** [yakyak/yakyak#265]
I went ahead and made a new icon for YakYak. It combines the Hangouts icon with the current icon from YakYak using proper Material specs:

![Image of YakYak](http://i.imgur.com/X59ozMY.png)

I tried to keep it simple and meaningful.

**Comment by austin-guevara** [comment]
This is well-executed! I'm a fan. It's a nice combination of material, unique to Yak Yak's branding, and also has a strong connection to Hangouts.

**Comment by davibe** [comment]
this makes choice more difficult :P

**Comment by x-tk** [comment]
Hahaha, I love this teen one but man that's a good one too.

**Comment by PMiner** [comment]
This is my favorite! I hope this one gets chosen! :smile:

**Comment by PMiner** [comment]
@link6155 do you mind if I make a couple variants of your icon?

**Comment by link6155** [comment]
@PMiner I don't mind, just as long as you stick the MD guidelines.

**Comment by PMiner** [comment]
MD guidelines?

**Comment by NBonaparte** [comment]
[Material Design](https://material.google.com/style/icons.html#icons-product-icons).

**Comment by PMiner** [comment]
OK thanks!

**Comment by PMiner** [comment]
@link6155 do you have an SVG? It's fine if you don't, I was just wondering.
