### ISSUE TITLE
Closing window when fullscreened just blanks screen in osx

### ISSUE THREAD

**Issue by maxkorp** [yakyak/yakyak#266]
In osx, if i fullscreen the app, and hit cmd+w (or mouse up top, wait for the bar to appear, and hit the close button), the app just goes black, rather than closing out of fullscreen, which is contrary to the behavior of most apps. looking at the source, I'm guessing this is an issue with electron and the BrowserWindow.prototype hide method, since it's being hidden rather than closed.

https://github.com/yakyak/yakyak/blob/master/src/main.coffee#L364-L369

I'm guessing this is done to keep load time down? I'm not sure if it's just a bug in electron that hiding causes that (searched around and didn't see anything), in which case I guess it's just a wait for a fix kind of thing, but if not, it's probably necessary to close and reopen the window.

**Comment by austin-guevara** [comment]
The easiest fix for this when it happens it to open mission control (control + up) and then click the "fullscreen" button at the top left of the offending black window in question.

**Comment by maxkorp** [comment]
Yeah it's not to hard of a state to get out of, it was just odd getting in it to begin with. The found solution makes sense IMO. Thanks for getting to that so quickly
