### ISSUE TITLE
Does the 'Close to tray' option do anything in macOS?

### ISSUE THREAD

**Issue by monchote** [yakyak/yakyak#273]
Should we hide if not?

**Comment by monchote** [comment]
@davibe Any idea about this?

**Comment by davibe** [comment]
It seems to do nothing. We lost that behavour when we re-introduce the "hide window on close" osx thing. Also "hide dock icon" is not working as expected for me. The icon looks like the app is closed but i still have it in the dock. Is it the same for you ?

**Comment by davibe** [comment]
Ok now i remember a bit more. Hide dock icon works if the icon was not added to the dock permanently. If you use it then you have no way to show the window app again. This whole thing needs to be sorted out

**Comment by monchote** [comment]
@davibe That's right, if the icon is pinned to the dock then it won't go away. If find that feature quite weird and non-standard anyway.

Should we hide the close to tray option on macOS? Happy to work on it.

**Comment by davibe** [comment]
If i was for me I would say yes but someone wanted it in the past. It seems to me more a Windows thing but there are apps that minimize to tray also on osx. So yea, this is not a proper answer

@maxkueng @arnriu @algesten what do you think
