### ISSUE TITLE
Javascript Uncaught Exception upon exit

### ISSUE THREAD

**Issue by mxxcon** [yakyak/yakyak#277]
I just tried exiting from Yakyak 1.3.1 on Windows 10 and got this error message.

![clipboard01](https://cloud.githubusercontent.com/assets/847140/16364921/4c8cd158-3bc0-11e6-8db4-609f74c1bbd5.png)

**Comment by monchote** [comment]
@mxxcon Was that compiling from the latest master or downloading the pre-compiled binary?

**Comment by mxxcon** [comment]
Binary from this site

**Comment by KruyKaze** [comment]
Same here
