### ISSUE TITLE
Electron App Failed Install

### ISSUE THREAD

**Issue by Knock201** [yakyak/yakyak#279]
Followed simple instructions, failed to install. I have all the required dependencies too.
[npm-debug.txt](https://github.com/yakyak/yakyak/files/334136/npm-debug.txt)

**Comment by averissimo** [comment]
Can't reproduce this.

Node v6.7.0
Npm 3.10.8

can you try again?

**Comment by averissimo** [comment]
@Knock201 I'm closing this for lack of feedback, reopen if you still are experiencing this

have you ran `npm install` before?

small note: our current version of electron requires node v6
