### ISSUE TITLE
Twitter preview does not show videos

### ISSUE THREAD

**Issue by bseber** [yakyak/yakyak#283]
maybe we should speak with the twitter API instead of the hacky hack of HTML parsing 😅

**Comment by monchote** [comment]
It is my duty as a Twitter employee to take this one on :D

**Comment by monchote** [comment]
So I started working on this in [here](https://github.com/monchote/yakyak/commit/b198b1a973654feb22a4327b4e69c4e77aadfb3c) but I'm struggling to get the html block that the Twitter API returns rendered in the chat.

The html code gets escaped no matter what I've tried. Any help would be welcome.

<img width="461" alt="screen shot 2016-06-28 at 22 26 01" src="https://cloud.githubusercontent.com/assets/1186808/16433183/cff10912-3d80-11e6-9563-e4504ce41bb7.png">

**Comment by arnriu** [comment]
Maybe you will find what you need here https://github.com/algesten/tagg

@algesten , do you have any easy html escape solution?

**Comment by monchote** [comment]
Thanks @arnriu, I checked the docs in the tagg repo but couldn't find anything unfortunately.
