### ISSUE TITLE
Add link (to external browser) to initiate calls with people in a conversation.

### ISSUE THREAD

**Issue by pandaman4125** [yakyak/yakyak#286]
Why cant you call in yakyak?Can you call in yakayak?

**Comment by pandaman4125** [comment]
Ok.Thanks

**Comment by PMiner** [comment]
Could yak yak yak last have a link to open an external hangouts call?

**Comment by bozerkins** [comment]
+ initiating the call could be useful

**Comment by davibe** [comment]
Can someone do a pull request for it ?

**Comment by bozerkins** [comment]
Sure. I might have time this weekend.
