### ISSUE TITLE
Tray Icon not Functioning On Ubuntu 16.04

### ISSUE THREAD

**Issue by sschwetz** [yakyak/yakyak#287]
OS: Ubuntu 16.04
Desktop: Gnome 3

The System Tray Icon, does not reopen the window when being clicked on. If you minimise the app to the tray the only way to get the icon to re-open is to quit out and then restart the application.

**Comment by davibe** [comment]
if you left-click on the icon you should be able to reveal a menu. The first voice should be something like "toggle.." which allows you to toggle the window. At least this is how it works on osx at the moment

**Comment by kolorafa** [comment]
Testing the pre-release.
Everything cool, the only peace for me that is missins is:

### Left click on tray icon - show window.

Now to open YakYak i need to right click and click "toggle..."
Left click is not assigned, and it would be awesome if left click would toggle show/hidden!

(Both windows and linux (arch))

Thanks

**Comment by averissimo** [comment]
I tried this and the framework does not allow to assign left button (for what I researched/tried)

Anyway, I much prefer the Skype behavior of activate instead of toggling, which always shows window when menu is pressed.

I have done it locally at a branch if anyone want to try it out: https://github.com/averissimo/yakyak/tree/activate

**Comment by averissimo** [comment]
@sschwetz this should be solved in latest 1.4.0-beta

see #451 for download link

**Comment by kolorafa** [comment]
As far as i did dig in, this should be possible to handle left mouse click.
https://github.com/electron/electron/pull/1741

There seems to be some OnClicked event observer:
https://github.com/electron/electron/blob/f31bfab127c47b3419b6ea787658e819d1e8be93/atom/browser/ui/tray_icon.cc

**Comment by averissimo** [comment]
included in 1.4.0 release
