### ISSUE TITLE
Basic Text Formatting

### ISSUE THREAD

**Issue by acook** [yakyak/yakyak#290]
Provide the same basic text formatting features as browser-based Hangouts, at the very least (the ones I use most):
- bold
- italics
- underline

https://support.google.com/hangouts/answer/3112005?hl=en
- `/me` (covered by #282 - `/me` is taken from the IRC protocol and has been part of Hangouts since at least 2014, and previously part of Gtalk and XMPP)

**Comment by PMiner** [comment]
#282

**Comment by averissimo** [comment]
Input box has to be replaced with editable content tag for this to work.

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content

would be awesome to have

**Comment by Phantec** [comment]
👍
