### ISSUE TITLE
Google Talk SMS Appears Not to send, but does.

### ISSUE THREAD

**Issue by PMiner** [yakyak/yakyak#292]
When using Google Talk integrated into hangouts, the message typed to a phone number is grayed out as if it was waiting to send. When checked, though, the message was sent. Also, after restarting YakYak, The issue is resolved until another message is sent. Please fix! 
-PMiner

**Comment by TotalLag** [comment]
Hello, I have the opposite, but similar issue.  SMS sent through YakYak will show up in GMail Hangouts app, but the receiver does not actually get anything.  If I copy and paste the same message in actual GMail Hangouts, they will get it. 

I still receive SMS replies in YakYak however.

**Comment by jordanade** [comment]
I have the same problem as TotalLag. SMS sent through YikYak are grayed out, but show up across all Google services, but are never actually sent to the recipient.

**Comment by heihachi** [comment]
I am getting the same issue with it being grayed out but not actually sending

**Comment by dinoboy197** [comment]
Confirmed as still an issue in version 1.3.3. I would love to use this client, but unfortunately, this problem prevents me from being able to switch from Google's client.

**Comment by chazz422** [comment]
Also having this problem here.  SMS messages look like they were sent, even showing up on other hangout clients, but never make it to the destination.  This problem only happens if the message was typed and submitted from the yakyak client.

**Comment by averissimo** [comment]
Closing the issue (duplicate), please add all comments in #738 

If you want to help with this bug, subscribe to #738 as I'm now active and trying to fix it with @hawksprite excelent work

but I do not have a google voice account / conversation, so I need help debugging my advances :)

ps. this is also a duplicate of #90
