### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by PMiner** [yakyak/yakyak#293]
On windows 10, the touch keyboard pops up and covers the input box. is there a way you could raise the input box so the keyboard is not covered?

**Comment by link6155** [comment]
I vouch for this. Touch support is one of the things that I would really like to have.

**Comment by PMiner** [comment]
or better yet, shrink the size of the window entirely?

**Comment by PMiner** [comment]
I'm new to github, but if it says "help wanted" how would i help? How to i make a fork, and then request to merge?

**Comment by davibe** [comment]
Are you a developer ?

**Comment by PMiner** [comment]
yes. Also, I figured out how to make a pull request.
