### ISSUE TITLE
sent url https:// smiley

### ISSUE THREAD

**Issue by faxe78** [yakyak/yakyak#294]
hi,

if you send a https://www url it shows it as a smiley, did not test if they are sent out correct but high chance that not. 

thx

markus

**Comment by PMiner** [comment]
Nope they do not. i can confirm.

**Comment by randymorris** [comment]
Another related issue: sending times has become very difficult.  Try to send "06:38 am" and it gets converted to "6😸8 am".

**Comment by PMiner** [comment]
On hangouts, you have to type a space for the emoji to appear.

**Comment by kolorafa** [comment]
I did paste few urls with space between them and it changed urls to emoji ...
How to completely disable replacing text to emoji?

**Comment by davibe** [comment]
I guess i will have to revert the current implementation

**Comment by averissimo** [comment]
I created pull request https://github.com/yakyak/yakyak/pull/329 that only converts to emoji exact emojis surrounded by space/beggining/end

Appreciate if someone could test this! :)

**Comment by dbehnke** [comment]
works great, I am able to send people http:// links again :+1:

**Comment by davibe** [comment]
thanks
