### ISSUE TITLE
YakYak confused by outgoing calls

### ISSUE THREAD

**Issue by PMiner** [yakyak/yakyak#295]
When you make an outgoing call, yakyak thinks you are calling yourself. For example, if I call someone, yakyak says, Incoming call from "me" obviously, I don't want to put my name.

**Comment by arnriu** [comment]
https://github.com/yakyak/yakyak/issues/286

**Comment by PMiner** [comment]
@arnriu This is not the issue i was having. i think you read the title, but not the actual message. I'll admit though, the title is confusing.
I will update it soon.
