### ISSUE TITLE
system-wide proxy setting ignored

### ISSUE THREAD

**Issue by davibe** [yakyak/yakyak#3]
The app ignores system wide proxy settings. This is confirmed on Windows but I suspect it's the same on Mac.

**Comment by davidbanham** [comment]
Ideally, proxy support needs to be added to hangupsjs. As a hack, looks like we can just set an environment variable and request will pick it up.

**Comment by davidbanham** [comment]
This has had to be removed temporarily due to a bug in Electron. We had a working workaround for OSX, but it failed on Windows.

**Comment by algesten** [comment]
can win 7 be detected and just disable this for that platform?

**Comment by davidbanham** [comment]
Are we sure it's just win7 though? For all we know it's all the other windows versions too.

**Comment by davibe** [comment]
I did not test Linux and yes, it's quite possible other windows version have the same problem. The guy who requested proxy support is a Windows user in the first place. I would say let's wait a bit because there is a new electron release every ~5 days so maybe next one has the fix.

Or.. i think its possible to work it around some other way because if I disable proxy support, let the app run and then I open dev tools i can do 

    require('remote').require('app').resolveProxy(...) 

and it works fine. Maybe it works when called from another thread .. or being called after <something> has been initialised fixes it. Need to investigate more. But first, again, i would wait for electron.

**Comment by maxkueng** [comment]
> I would say let's wait a bit because there is a new electron release every ~5 days so maybe next one has the fix.

Is there already an issue in the Electron process? I couldn't find it. If nobody reports it's most likely not going to get fixed.

If it's a Windows-ony issue, is there a reason why it can't be enabled for the other platforms?

**Comment by davibe** [comment]
- yes there was an electron issue, its now closed. I don't remember which one was it must be.
- ideed it can be disabled only on failing platforms
- there have been 2 releases of electron since last time i updated this so we should test with newer ones and see if the bug is still there https://github.com/atom/electron/releases
