### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by averissimo** [yakyak/yakyak#301]
Backend and frontend :)

Tried using electron-debug, but I guess this is only for the frontend.

_ps. I am a total newbie in this framework, I tried the obvious github repository search, google queries and a couple non-obvious.. if this info is already explained please point to the link, I'll be happy to contribute with a wiki page after I succeed :)_

**Comment by PMiner** [comment]
if you are on windows press Windows+R and then type cmd then press enter. Then navigate using the cd command (ex. cd C:/Users/*yourname*/Downloads/YakYak), and start yakyak with yakyak.exe. if you are on Linux, open the terminal, depending on your operating system, usually ctr+alt+t and then using the cd command (ex. cd /home/*yourname*/Downloads/YakYak), and start YakYak with the ./yakyak command. Then paste the log in Github.

**Comment by averissimo** [comment]
I was asking to actually pause the process and inspect variables. Specifically in main.coffee (backend) 

With the ui the inspector can be called directly in the window.

**Comment by arnriu** [comment]
If you want an easy solution, you can log any variable using console.log anywhere. If it's a front-end variable, it will be in inspector's console. If it is backend, it will be in your terminal.

**Comment by averissimo** [comment]
Added information to the wiki page, I guess this issue can be closed

https://github.com/yakyak/yakyak/wiki
