### ISSUE TITLE
Support Multiple google accounts

### ISSUE THREAD

**Issue by eyadsibai** [yakyak/yakyak#302]
I have two different gmail accounts that I would like to login with.

**Comment by invisiblegarage** [comment]
Agreed. Great app. Would love support of mulitple google logins.

**Comment by davibe** [comment]
we already talked about this. It require quite some effort but it's interesting.

**Comment by jlp78** [comment]
This is a duplicate of https://github.com/yakyak/yakyak/issues/13

**Comment by davibe** [comment]
closing as duplicate
