### ISSUE TITLE
The app icon is badged with unread messages when there are none unread

### ISSUE THREAD

**Issue by aexmachina** [yakyak/yakyak#305]
Restarting the app fixes the problem.

**Comment by PMiner** [comment]
could you include logs? if you are on windows press `Windows+R` and then type `cmd` then press enter. Then navigate using the cd command (ex. `cd C:/Users/*yourname*/Downloads/YakYak`), and start yakyak with `yakyak.exe`. if you are on Linux, open the terminal, however, your operating system works, usually `ctr+alt+t` and then using the cd command (ex. `cd /home/*yourname*/Downloads/YakYak`), and start YakYak with the `./yakyak` command. Then paste the log in Github.

**Comment by aexmachina** [comment]
I'm on Mac, but here's the log:

```
/A/Y/C/MacOS $ ./YakYak
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
```

Doesn't seem to show much.

1. Opened the app from the Terminal (see above)
1. App icon had no badge
1. A friend sent me a message
1. The app icon showed a badge with 3
1. I viewed the message from my friend
1. The app icon showed 2

**Comment by PMiner** [comment]
Search the Yakyak folder for anything called log. You might find a log file.

**Comment by aexmachina** [comment]
Nope, can't find anything:

```
/A/YakYak.app $ find . -name '*log*'
./Contents/Resources/app/icons/yakyak-logo.svg
./Contents/Resources/app/login.js
./Contents/Resources/app/node_modules/autosize/changelog.md
./Contents/Resources/app/node_modules/node-notifier/node_modules/cli-usage/node_modules/marked-terminal/node_modules/cardinal/node_modules/redeyed/examples/replace-log.js
./Contents/Resources/app/node_modules/node-notifier/node_modules/cli-usage/node_modules/marked-terminal/node_modules/cardinal/node_modules/redeyed/examples/sources/log.js
./Contents/Resources/app/node_modules/node-notifier/node_modules/cli-usage/node_modules/marked-terminal/node_modules/cli-table/node_modules/colors/themes/generic-logging.js
./Contents/Resources/app/node_modules/node-notifier/node_modules/which/changelog.sh
./Contents/Resources/app/node_modules/request/node_modules/har-validator/lib/schemas/log.json
./Contents/Resources/app/node_modules/request/node_modules/hawk/images/logo.png
./Contents/Resources/app/Y-icons/yakyak-logo.svg
```

**Comment by PMiner** [comment]
While yakyak is open, press `ctrl+alt+i` that opens the inspector. you can check for errors there.

**Comment by ruzihao** [comment]
Same issue here. Once triggered by one unread message, the red "1" is always shown in the badge.. 

However, the app is pretty cool overall. Using much less memory than Google's own Hangout app

<img width="154" alt="yayak" src="https://cloud.githubusercontent.com/assets/3221780/16991923/4fea4f48-4e6b-11e6-96d0-96f80475a7bf.png">

**Comment by averissimo** [comment]
@ruzihao @aexmachina do you still experience this?
