### ISSUE TITLE
Crash on exit: Cannot read property 'isFullScreen' of null

### ISSUE THREAD

**Issue by clrg** [yakyak/yakyak#306]
This happens every time I close YakYak on OpenSUSE - which is a bit annoying because then no preferences (e.g. favourites) are saved.

![screenshot_20160704_155734](https://cloud.githubusercontent.com/assets/68176/16565594/46d91f72-4206-11e6-8007-14e16843d63a.png)

**Comment by PMiner** [comment]
#278

**Comment by averissimo** [comment]
@clrg I believe this is solved in latest beta
