### ISSUE TITLE
Proposed icon

### ISSUE THREAD

**Issue by clrg** [yakyak/yakyak#308]
Here's a mockup/idea I came up with, perhaps inspired by a certain other icon but not a copy or derivative of it. Consider all work posted by me in this thread to be public domain.

<removed - see below>

Had to zip the SVG due to Github limitations.

<removed - see below>

**Comment by clrg** [comment]
And an alternative although perhaps a bit too close to another well known app's icon? Does allow him to be even hornier though (erm, see previous explanation).

![myyakyak2 svg 128](https://cloud.githubusercontent.com/assets/68176/16587022/8e277d46-42c0-11e6-9361-af565cb74478.png)

Wtih zipped SVG.

[MyYakYak2.zip](https://github.com/yakyak/yakyak/files/347865/MyYakYak2.zip)

**Comment by JoeDuncko** [comment]
The second one looks mysteriously like Homestar Runner...

**Comment by clrg** [comment]
Haha I knew I recognised the shape! It was just a chat bubble rotated with an extra line.

**Comment by clrg** [comment]
![myyakyak2chew svg 128](https://cloud.githubusercontent.com/assets/68176/16590380/39cdf0cc-42cf-11e6-8d28-bb87972fae8f.png)

Omnomnom. "I'm chewing grass to stop people confusing me with Homestar Runner."

**Comment by clrg** [comment]
Woke up with a couple more ideas. First with a tilted mouth:

![myyakyak3 svg 128](https://cloud.githubusercontent.com/assets/68176/16614598/11630410-436a-11e6-953c-800e07ae0831.png) ![myyakyak3chew svg 128](https://cloud.githubusercontent.com/assets/68176/16614597/116249f8-436a-11e6-9edd-cd213cf0a653.png)

Zipped SVG: [MyYakYak3.zip](https://github.com/yakyak/yakyak/files/349526/MyYakYak3.zip)

And then with a bigger nose / smaller chin:

![myyakyak4 svg 128](https://cloud.githubusercontent.com/assets/68176/16614599/1169d8ee-436a-11e6-9052-4def0ba443d8.png) ![myyakyak4chew svg 128](https://cloud.githubusercontent.com/assets/68176/16614600/116a05f8-436a-11e6-8b26-cef18822f7db.png) ![myyakyak4chew2 svg 128](https://cloud.githubusercontent.com/assets/68176/16614601/116d38d6-436a-11e6-8a93-bf3df6f80c4e.png)

Zipped SVG: [MyYakYak4.zip](https://github.com/yakyak/yakyak/files/349524/MyYakYak4.zip)

**Comment by clrg** [comment]
More playing about.

![myyakyak5chew1 svg 128](https://cloud.githubusercontent.com/assets/68176/16671537/c6fa4d82-4497-11e6-89bc-08c575824521.png) ![myyakyak5chew2 svg 128](https://cloud.githubusercontent.com/assets/68176/16671538/c70b05e6-4497-11e6-9e5b-8fb9c7cd1a64.png)

Zipped SVG: [MyYakYak5.zip](https://github.com/yakyak/yakyak/files/353150/MyYakYak5.zip)

**Comment by clrg** [comment]
Procrastinating on something else, played about and made a .ico file, trying to make the lo-res ones look less like smudges.

[MyYakYak-ico-xcf.zip](https://github.com/yakyak/yakyak/files/354141/MyYakYak-ico-xcf.zip)

**Comment by averissimo** [comment]
submitted in #21 closing issue

ps. looks really nice :)
