### ISSUE TITLE
Auth loop [from sources]

### ISSUE THREAD

**Issue by averrin** [yakyak/yakyak#31]
Prebuilded apps (under linux and windows) logins succesfully, but when i try do it from sources (under windows 10), i have such glitch:
1. enter login
2. enter password
I expect pin-code input (two-factor auth)
but i saw login form again.

May be i need somethiing more, then
npm install
gulp
?

**Comment by vandaimer** [comment]
I'm with this problem too. Anybody with any idea?

Excuse me my bad english.

**Comment by algesten** [comment]
should definitely be enough. i use two-factor auth and it works :/

**Comment by averrin** [comment]
Now it works without problems
