### ISSUE TITLE
Ctlr+Enter doesnt send

### ISSUE THREAD

**Issue by PMiner** [yakyak/yakyak#310]
This should be a simple fix. Just make ctrl+Enter send the message. It works on the official hangouts client.
You might be wondering why this is useful, because if you paste something over and over again you can press enter while still holding ctrl. its a really tiny detail, but it is still something.

**Comment by easauceda** [comment]
Hey guys, opened a PR for this: https://github.com/yakyak/yakyak/pull/319

First time working with coffeescript & electron, so please let me know if there's anything wrong or that could be done better.
