### ISSUE TITLE
Sugestion: Config a Proxy

### ISSUE THREAD

**Issue by RandyHBH** [yakyak/yakyak#311]

**Comment by davibe** [comment]
you mean you want to add configuration screen for manually setting a proxy ?

**Comment by RandyHBH** [comment]
Yes, because in my case I am behind a proxy, and I is not feasible to proxy the entire system, so I was wondering if poible add the functionality to manually set a proxy.

**Comment by soasme** [comment]
+1

A feature MUST HAVE for this program running in China.
If Shadowdocks Protocol can be support, it would be nice.

**Comment by PSiAU** [comment]
I'm using YakYak in a corporate environment and proxies are mandatory here (along with proxy user authentication).

**Comment by ajhodges** [comment]
+1

**Comment by durd** [comment]
+1

**Comment by averissimo** [comment]
do you guys use simple http(s) proxies?

I've just tested and the HTTP_PROXY and (I hope) HTTPS_PROXY environment variables are respected

can someone try running yakyak by:

    HTTP_PROXY=http://proxy_ip:proxy_port ./yakyak

where `proxy_ip` is the ip or domain name of the proxy, and `proxy_port` the port.. switch to HTTP**S**_PROXY if using https

**Comment by averissimo** [comment]
ps. seems like socks protocol (for tor) could eventually be used, but requires changes

see request/request:

https://github.com/request/request/blob/06e8f851ad460afc1094a622eec2b72f33489b3b/examples/README.md#proxys

**Comment by PSiAU** [comment]
Could you clarify what you mean by simple http proxy?
We use a pac file here, along with proxy authentication as some destinations are proxied and some are not. The pac file handles that but the proxy requires authentication.

**Comment by averissimo** [comment]
This "simple" http(s) proxy is setup via environment variables, i.e. if you open a terminal and run the command below it will show something other than blank output

`echo http: $HTTP_PROXY -- https: $HTTPS_PROXY`

I don't think the module we use to connect to hangouts server supports a pac file. However if you know the proxy dns name (or ip), authentication and port then you can set it up manually as:

`$ HTTP_PROXY=http://username:password@proxy_ip:proxy_port ./yakyak`

or

`$ HTTPS_PROXY=https://username:password@proxy_ip:proxy_port ./yakyak`

(or even combine both sequentially before calling yakyak)

__Did this answer your question?__

ps. if you want to stop using an already configured proxy and instead want a direct connection, `$ HTTP_PROXY='' HTTPS_PROXY='' ./yakyak` in theory should work

**Comment by PSiAU** [comment]
Is it possible to hook into macos's proxy settings and use whatever is in there? That would IMHO be the ideal way to do it.

**Comment by averissimo** [comment]
definitely.. defaulting to OS would be awesome, @davibe any clue on if this is possible?
