### ISSUE TITLE
Text formatting is messed up

### ISSUE THREAD

**Issue by rroll1** [yakyak/yakyak#313]
I'm running into a strange issue. Arch Linux, both on Yakyak stable and latest git version.

The text formatting in messages is behaving strangely. It appears that there are no spaces -- text is getting compressed down, and it's doing odd things with numbers. See the screenshot below.

I've uninstalled and reinstalled the program, as well as removing ~/.config/yakyak and /usr/share/yakyak (and /usr/share/yakyak-git), then reinstalling again, and no dice.

The odd thing is that this doesn't occur on other machines running the same OS, with the same updates: only on one of my machines. Where might I go to get more details on what's causing this?

![yakyak-text](https://cloud.githubusercontent.com/assets/20097968/16698368/8dfa53c0-4513-11e6-8d77-10107df77de0.png)

**Comment by PMiner** [comment]
since it only appears on one of your computers, and updates dont fix it, it is most likely a electron problem as apposed to yakyak. also, #240

**Comment by kolorafa** [comment]
When you paste link and click space link get f.. up, emoji apear.

**Comment by rroll1** [comment]
Purging all evidence of Electron from my system and reinstalling corrected this.
