### ISSUE TITLE
:) should be switched to emoji when I hit enter 

### ISSUE THREAD

**Issue by KruyKaze** [yakyak/yakyak#315]
We shouldn't need to hit space first
Thanks

**Comment by kolorafa** [comment]
And ability to disable that functionality

**Comment by austin-guevara** [comment]
Does that work for you? When I enter ":)" and hit space, it doesn't convert it to emoji.

**Comment by kolorafa** [comment]
on windows and 1.3.1 it change from :) to emoji after hitting space, maybe it's related that i did use/test Google Hangouts app on windows?

Downloading never version to test on linux

**Comment by kolorafa** [comment]
Latest from git on linux - when typing :)[space] the smile disapears as it probably does not have needed font

http://kolorafa.firehost.pl/test/snapshot-2016-07-18-22-50-26.png
![](http://kolorafa.firehost.pl/test/snapshot-2016-07-18-22-50-26.png)

**Comment by averissimo** [comment]
I created pull request https://github.com/yakyak/yakyak/pull/329 that converts to emoji when pressing enter, appreciate if someone could test it!

**Comment by averissimo** [comment]
close it? #329 solves this and has been merged
