### ISSUE TITLE
no cmd-tab entry when dock item is hidden

### ISSUE THREAD

**Issue by sodiumjoe** [yakyak/yakyak#316]
With the "Hide Dock Icon" setting enabled, you can't cmd-tab to yakyak anymore.

**Comment by davibe** [comment]
This is true on osx. Unfortunately this is an electron choice (or bug).

**Comment by davibe** [comment]
This is true on osx. Unfortunately this is an electron choice (or bug).

**Comment by averissimo** [comment]
@sodiumjoe we've updated electron version recently.

Does it still happen?

**Comment by sodiumjoe** [comment]
@averissimo i stopped using yak yak and went back to the hangouts chrome app. I'll try it and report back.

**Comment by averissimo** [comment]
try the latest beta #451 :)

**Comment by kmontag** [comment]
Just confirming this is still happening in 1.4.0 for me. fwiw ideal behavior for me would be:

- when yakyak window is open, tray icon appears and cmd-tab allows it to be selected
- when yakyak is minimized to tray, icon and cmd-tab entry are hidden

Is this behavior supported by any combination of options?
