### ISSUE TITLE
You should be able to toggle notification methods

### ISSUE THREAD

**Issue by karsai5** [yakyak/yakyak#317]
As a user I would find it useful to toggle how YakYak notifies me of new messages. For example I like having the toast notifications, but often find the sound annoying. So it would be useful to be able to toggle sound for notifications. (Note this is different from muting notifications)

**Comment by jraoult** [comment]
@karsai5 or anyone finding this issue, I managed to hack around. Might not be the ideal solution but it could fix your problem waiting for a longer term solution. The notification in YakYak is based on the following NPM module: https://www.npmjs.com/package/node-notifier#all-notification-options-with-their-defaults. So, open `/Applications/YakYak.app/Contents/Resources/app/ui/views/notifications.js` and change the property`sound: true` to `sound: false` then restart YakYak it will mute the sound of the notification.

**Comment by jjt** [comment]
@karsai5 This method worked for me, as outlined [here](https://github.com/yakyak/yakyak/issues/254#issuecomment-233226825):

> You can disable the notification sound from System Prefs -> Notifications

**Comment by karsai5** [comment]
Thank you @jraoult that worked a charm. I think I'll keep this as an open enhancement as it would be useful to toggle sound from the options menu some time in the future.
