### ISSUE TITLE
URLs with IP addresses get truncated when creating link

### ISSUE THREAD

**Issue by MarttiR** [yakyak/yakyak#321]
To reproduce:
- Enter IP url with three digits in the last set, such as http://192.168.100.100/
- Link leaves out last digit: http://192.168.100.10 0/

**Comment by averissimo** [comment]
it does not even detect url :\

![image](https://cloud.githubusercontent.com/assets/211358/20725619/5d36ea82-b66a-11e6-864c-d405326d918c.png)
