### ISSUE TITLE
Feature Request: Separate Pop-Up (Toast) Notification from Flashing Window Notification

### ISSUE THREAD

**Issue by ctcpip** [yakyak/yakyak#323]
Currently, with notification enabled, when a new message is received, two things happen:

1. the window flashes in the taskbar
2. a pop-up/toast notification appears, containing the message

*#*2 can be a privacy issue, so I would like to add an option to disable/enable *#*2

**Comment by ctcpip** [comment]
@davibe - do you have a recommendation for UI to control this option?

**Comment by brianredbeard** [comment]
@ctcpip similar to this I was just looking into a mechanism to "snooze" notifications.  There's only so many times I can have a message pop up while screen sharing during a presentation on Hangouts.  

I was about to explore doing this and got as far as:

https://github.com/yakyak/yakyak/blob/master/src/ui/views/notifications.coffee#L15

Then I realized there was no real `CONTRIBUTORS` file or other guidelines providing big picture for the project.

**Comment by ctcpip** [comment]
@brianredbeard it's a bit loose in that sense.  I'll probably just implement the option(s) in the way I think makes sense, in the least invasive way possible, and submit a PR.  Most likely, I will add options to the 'View' menu.

**Comment by davibe** [comment]
on osx people can control notification appearance using notification center. Does it make sense to do this window/linux only ?

**Comment by ctcpip** [comment]
@davibe but that would affect notifications globally. this gives the user the ability to turn off just for yakyak

**Comment by ctcpip** [comment]
also, I would think we'd want to have parity regarding settings across operating systems
