### ISSUE TITLE
Does it support RTL?

### ISSUE THREAD

**Issue by perpi** [yakyak/yakyak#33]
I mean right-to-left direction for [some languages](https://en.wikipedia.org/wiki/Right-to-left#RTL_Wikipedia_languages), is it supported?

**Comment by algesten** [comment]
it doesn't for no other reason that I have never implemented something like that. which is kind of ignorant, thinking about it.

**Comment by maxkueng** [comment]
Is this even possible? Does Google provide the language or the direction when receiving a message? I think otherwise it's really hard to figure out whether to display it RTL or LTR.

It has to be done per message because somebody could send a message in Arabic (RTL) and receive a message back in English (LTR).

**Comment by diff-** [comment]
We don't have any problem in builtin hangout within gmail!
All Google services such as: blogger, Gmail, Hangout and others supports for RTL. Even, some of them like translate.google.com have auto-detection facility for RTL languages.
(Do you use bootstrap in this app someway?)

As a note: It's told that near to 50% of [Telegram](telegram.org) traffic is in the hand of RTL languages!

Anyway, it would be appreciated if you implement it for supporting RTLs.

I'm not familiar with desktop apps, but in the web, we simply use/change some css elements to get a RTL view for theme/website.
In other enviroments, we use right `Alt` (called [AltGr](https://en.wikipedia.org/wiki/AltGr_key)) +` ]` to make sentences RTL.

**Comment by algesten** [comment]
> (Do you use bootstrap in this app someway?)

No

Just for my understanding. When you use RTL in google hangouts. Does  the message automatically appear RTL for the reader, and can you switch between LTR and RTL between messages, to the same recipient, and they would alternate between LTR and RTL?

Does the RTL support kick in automatically or do you use `Alt + ]`.

**Comment by diff-** [comment]
I updated the post. Unfortunately RTL is not supported by gmail-built-in hangout automatically :(
Yep. we need to `Alt + ]`. When we send a message in a RTL language.
