### ISSUE TITLE
Should there be an option to convert to emoji as you type?

### ISSUE THREAD

**Issue by averissimo** [yakyak/yakyak#331]
This is a question that came from pull request https://github.com/yakyak/yakyak/pull/329

I have implemented this option in a0a0f2507d02a76692a42af1db9c0dc4da4446e4

It works with minimal (manual) tests

Feedback?

**Comment by notdevinclark** [comment]
Thank you for implementing this option. Was looking for it all over the place in the stable release.

**Comment by davibe** [comment]
i guess we can close this
