### ISSUE TITLE
Messages can't be sent

### ISSUE THREAD

**Issue by pencarsa** [yakyak/yakyak#334]
When we connect the app to our enterprise google apps account and try to communicate messages don't reach the user and they are grayed out. 
<img width="937" alt="yakyak_and_downloads_and_releases_ _yakyak_yakyak" src="https://cloud.githubusercontent.com/assets/3245173/17463860/32dee2b4-5cd1-11e6-98a8-0f895b3974eb.png">

**Comment by davibe** [comment]
did you try released 1.3.1 ? (not pre-release)

can you launch it from terminal and paste output when you send messages ?

can you try to hit alt+cmd+i and check console for some meaningful output ?

**Comment by pencarsa** [comment]
I tried 1.3.1 release and also compiled the source code. 

There are no terminal messages when I try to send the message:
./YakYak
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0

Console doesn't give any meaningful output, only errors about fonts.

In our gapps the history of messages is turned off, maybe this will help too :) 
![screen shot 2016-08-09 at 11 03 48](https://cloud.githubusercontent.com/assets/3245173/17510871/036e15a8-5e21-11e6-9172-666d98800da9.png)

**Comment by averissimo** [comment]
@pencarsa i've tested an apps account and is working fine, does this still happen in latest version (as of this comment it was 1.4.1)

**Comment by dankox** [comment]
I'm not sure if I can add comment here or if I should open a new issue, but I have the same problem. 
Enterprise account, history turned off and I can't send messages. I will receive all the messages which are sent to me, but mine won't go out. 

Also I do not have any conosle log messages or terminal messages.  I tried even to build the app from source and run it like that.
