### ISSUE TITLE
Service Unavailable - no CAPTCHA support

### ISSUE THREAD

**Issue by jlp78** [yakyak/yakyak#335]
I have YakYak 1.3.1 (about screen says 1.2.5 (1.3.1).  It was working fine when I was using it from home, but today I started it up at work and am receiving this message in the terminal when I run it: [http://pastebin.com/uYJ9KwUP](url)

Looks like Google thinks there is something weird about my IP and wants me to solve a CAPTCHA, but YakYak doesn't know how to do that.

**Comment by davibe** [comment]
ha.. bad :(

**Comment by jlp78** [comment]
Just a FYI, down near the bottom of that message was a link... after I visited that link in a browser, the problem appeared to go away.  I don't know if it went away because I visited that link or because my IT department fixed something (or had Google fix something).

For now, everything is working again.  Until next time.  Maybe a decent resolution would be for YakYak to detect this error condition and just present the HTML for the user to read?

**Comment by davibe** [comment]
Yes.
