### ISSUE TITLE
Scroll bars for dark theme on OSX 10.11.6 do not match.

### ISSUE THREAD

**Issue by njnygaard** [yakyak/yakyak#337]
Here's an image.
![screen shot 2016-08-10 at 2 15 13 pm](https://cloud.githubusercontent.com/assets/4606342/17571437/08387e9a-5f05-11e6-8ad2-27fafcb6aa92.png)

I was expecting it to be darker.

**Comment by arnriu** [comment]
Well, for me, they are black with dark color scheme.

![sb](https://cloud.githubusercontent.com/assets/9418756/17692796/0cda7926-639c-11e6-951e-3fbaf2ac9ffc.jpg)

**Comment by randymorris** [comment]
I'm using master as of 59e9d9e (current HEAD) and I'm seeing the light scroll bar as well.  Using the same version of OSX as @njnygaard.

**Comment by chasetb** [comment]
I'm also using [`59e9d9e`](https://github.com/yakyak/yakyak/commit/59e9d9ea956071e37f7de2e8856cb2f8f49f9553) and the scroll bars are black when in dark mode. Strange inconsistency, eh?

**Comment by randymorris** [comment]
FWIW I removed my `~/Library/Application Support/yakyak` and tried again from scratch and I still get the light scrollbars.

**Comment by chasetb** [comment]
Is your mac running in dark mode? That might be the difference if not. [How-to: Enable Dark Mode](https://9to5mac.com/2014/11/08/yosemite-dark-mode/)

**Comment by randymorris** [comment]
It is not.  However, enabling it does not seem to affect the scrollbars YakYak.

**Comment by chasetb** [comment]
I wonder if there is something in `~/Library/Preferences/com.github.yakyak.plist` that might be causing it. I don't see anything in mine related to scroll bars but have you tried deleting that file also?

**Comment by randymorris** [comment]
No dice.  Killed YakYak, deleted it, then started YakYak and selected the dark theme.  Still have light scrollbars.

**Comment by arnriu** [comment]
@randymorris @njnygaard are you using a mouse or trackpad? I remember that scrollbar behavior can be different depending on input: large scrollbar with background when using mouse input, transparent thin scrollbar with touch input (can be both with a magic mouse i guess since magic mouse is hybrid).
I do not have mouse right now to test though, can you try it?

**Comment by randymorris** [comment]
Tried with a normal USB mouse, an external trackpad, and the internal trackpad on my MBP and all have the light scrollbar.  I do not have a magic mouse to test with.

**Comment by arnriu** [comment]
@randymorris go to system prefpane, general, and try to switch scrollbar behavior manually. (as seen in this screen: http://0.tqn.com/d/macs/1/S/Q/j/-/-/GeneralPreferencesMacOSSierra.jpg ).
You may have to restart yakyak.

**Comment by randymorris** [comment]
Ah ha!  I prefer to always show the scrollbar, and when this setting is on I get the light scrollbars.  Setting it to only show when scrolling shows the dark scrollbar.

**Comment by arnriu** [comment]
@randymorris Ok, so mystery solved ! Other systems have custom scrollbar behavior, but we kept system scrollbar behavior for mac. Can't remember exactly why though, I think @davibe wanted to keep it has "macos feeling" as possible.

**Comment by arnriu** [comment]
See: https://github.com/yakyak/yakyak/commit/7afdc3c3cb15787473a3779025c644c04f570c58
Custom scrollbar explicitly excluded for mac. Can't find issue / PR where we discussed it :s .

**Comment by davibe** [comment]
@arnriu can i close this ? I am trying to clean up issues a bit

**Comment by arnriu** [comment]
@davibe yeah sure. The problem is very simple: we use native scrollbar and we can't change colors or behavior, but the user has control on scrollbar system via macos pref pane. For now, I think we will stick with native. If this problem comes up again, we will see then if we switch to custom scrollbar.

**Comment by njnygaard** [comment]
Hey I downloaded the 1.3.3 darwin x64 binary and the issue is fixed. Love the app.
