### ISSUE TITLE
Characters Not Supported

### ISSUE THREAD

**Issue by WhiteHatHacker1** [yakyak/yakyak#34]
Many non-standard characters including emoji are not supported and show up as blank rectangles.

**Comment by algesten** [comment]
emojis are a special case since we may want to use a specific font for exactly those unicodes. beyond that we use standard fonts which may then lack characters. what platform are you on and can you give an example character that is missing.

**Comment by WhiteHatHacker1** [comment]
Thank you for responding so quickly!
I'm on an Arch Linux variant. The characters I've noticed missing are some Greek ones such as the letter epsilon (ɛ) or alpha (ɑ) and other characters of the IPA Extensions and Spacing Modifier Letters Unicode blocks ([see here]( https://en.wikipedia.org/wiki/Phonetic_symbols_in_Unicode#From_Unicode_blocks_to_scripts)).

**Comment by brendan-benting** [comment]
I'm using Ubuntu (Gnome) 15.04 64 bit, Chinese Traditional characters are being rendered as blank rectangles as well.

**Comment by algesten** [comment]
This will be down to the font installed on those systems not having the glyphs for those characters. Our font string is currently:

```
    font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
```

Are there better options for these systems. Or is the solution to ship a (free) font that has the glyphs – and in that case, which font?

**Comment by brendan-benting** [comment]
Google noto has these glyphs, open source and attractive to boot.

**Comment by algesten** [comment]
I tried notosans in a separate branch https://github.com/yakyak/yakyak/tree/notosans – however I think it looks ridiculous.

<img width="960" alt="screen shot 2015-07-26 at 10 07 29" src="https://cloud.githubusercontent.com/assets/227204/8893032/45b77a18-337e-11e5-9e11-30e88bb5a7aa.png">

**Comment by brendan-benting** [comment]
Would it be possible for adding more fonts to the font-family string:

宋体, SimSun -- OSX and Windows at least will have it, and those using linux have already installed extra chinese fonts themselves.

**Comment by algesten** [comment]
does the font fall back if the current lacks glyphs for the character. that would be good in that case.

**Comment by jorgeavaldez** [comment]
Wouldn't this work? http://emojione.com/

**Comment by davibe** [comment]
can someone try to set notosans or any other richer font as a fallback for the current one and see if that works with special characters ? In that case a pull request would be trivial.

**Comment by DASPRiD** [comment]
How about shipping yakyak with the Dejavu font? It's pretty unicode complete.

**Comment by algesten** [comment]
@DASPRiD there's some roboto-font being pulled in #160 – any thoughts on that one?

**Comment by averissimo** [comment]
colored emoji are working if font is installed on system level

usually black and white if not installed

please reopen if this is still an issue :)
