### ISSUE TITLE
Top conversation constantly being hidden

### ISSUE THREAD

**Issue by apoisonedgift** [yakyak/yakyak#340]
Often when I open up the latest (1.3.1 pre release) build, the top (most recent) conversation has disappeared, and until the person messages me, I cannot retrieve it. This didn't happen in the prior version. Running it on 64 bit windows 10.

**Comment by davibe** [comment]
1.3.1 is now released. Does this still happen ?

**Comment by apoisonedgift** [comment]
Where is the release available? The description still says it's a pre-release on here: https://github.com/yakyak/yakyak/releases

**Comment by davibe** [comment]
I forgot to update the description, you're right. However it is not marked as pre-release anymore. I will handle this better next time. Just re-download the "same" packages (their content has been updated a couple weeks ago)

**Comment by apoisonedgift** [comment]
Ah, okay. I was -probably- running that version already then, but I've just re-downloaded and set it up just in case. Will let you know how it goes. Usually it happens a few times a day so I should be able to let you know in the next 24 hours.

**Comment by apoisonedgift** [comment]
Yeah. It still happens I'm afraid.

**Comment by averissimo** [comment]
@apoisonedgift can you check 1.4.0-beta3? download link here #451

**Comment by averissimo** [comment]
@apoisonedgift closing for lack of feedback.

If you are still experiencing this please reopen :)

latest pre-release version as of this comment is 1.4.1
