### ISSUE TITLE
Show drag and drop however and image/video preview.

### ISSUE THREAD

**Issue by LinkofHyrule89** [yakyak/yakyak#343]
I would very much like it if when I hover over to drag and drop an image or video if it would show that it knows I'm trying to drag and drop something similar to the actual hangouts chrome app. Also an image preview would be wonderful so we don't accidentally send images to the wrong people.

**Comment by davibe** [comment]
yes we should give some feedback and this is easy. Preview could be more difficult but can be done too. Waiting for contributions on this.

**Comment by LinkofHyrule89** [comment]
This would be very helpful much appreciated.

**Comment by averissimo** [comment]
first attempt at previewing the image: #398 

needs some feedback, but it is a working version (for pasting from clipboard) :)

**Comment by averissimo** [comment]
included in 1.4.0 release
