### ISSUE TITLE
Feature Request: unread number icon next to conversations/icons

### ISSUE THREAD

**Issue by jwhipp** [yakyak/yakyak#347]
It would be nice to have the unread numbers next to the conversation like the official app does.

**Comment by randymorris** [comment]
This already works for me in 1.3.1, or is this not what you're talking about?

![screen shot 2016-08-24 at 9 43 59 am](https://cloud.githubusercontent.com/assets/17761/17932773/912f8434-69df-11e6-91d2-4bca785d735e.png)
