### ISSUE TITLE
Ability to only show user picture

### ISSUE THREAD

**Issue by zachthezman** [yakyak/yakyak#349]
First off, top-notch job here. Love this app. I use it all the time.

I would love to see an option to only show the user's picture in the left pane. You've already added the ability to hide the timestamp and last message. My goal is to slim up the left pane to be as minimalistic as possible. I split the app with Slack on my screen so the more real estate I can free up in the actual conversation pane on the right would be great.

**Comment by randymorris** [comment]
This used to be possible just by resizing the pane.  I'm guessing this changed when the overall theme changed a while back.  Here's an old screenshot from the old v1.0.0 README that showed this:

![Screenshot](https://cloud.githubusercontent.com/assets/227204/8255540/d922d252-16a0-11e5-86b2-bfec901bbdbc.png)

**Comment by arnriu** [comment]
I don't know if I can help with this... Maybe if you could grab me a beer...

Ok, ok, fine. Here you are: #350

**Comment by zachthezman** [comment]
![Mother of God](http://i.giphy.com/kCo3euE2yScYo.gif)

@arnriu you are a rock star! Thank you.

**Comment by averissimo** [comment]
already implemented and merged
