### ISSUE TITLE
Archived conversations visibility

### ISSUE THREAD

**Issue by aditya-pai** [yakyak/yakyak#351]
The conversations that have been archived on google hangouts still appear listed on yakyak.

Also, resizing fonts is slightly counter-intuitive, in the sense that, when you reduce the font size you expect to see a larger number of messages, but in fact, the number of messages that are visible to you without scrolling decreases with decreasing font size.

**Comment by randymorris** [comment]
For the hiding of archived chats #252 is already open.

I can't reproduce your second issue.  Decreasing the font size shows more messages for me.

**Comment by davibe** [comment]
closing as duplicate
