### ISSUE TITLE
Feature Request: Mute Notifications

### ISSUE THREAD

**Issue by ahpatel** [yakyak/yakyak#352]
An option to mute notification sounds and/or control notification volume would be helpful for me.  I don't see any way to do this in 1.3.1. 

My use case... I use my PC for VoIP calls.  Often, I'll get a hangout message while on a call and the ping is very load for the person on the other end of my VoIP call.  Today, I have to close yakyak when I'm on a call.

**Comment by davibe** [comment]
You can already mute conversations.
