### ISSUE TITLE
Thumbnails not being retrieved by default

### ISSUE THREAD

**Issue by tresni** [yakyak/yakyak#353]
OS: OSX 10.11.6 (15G31)
Version: 1.2.5 (1.3.1) & master branch

Steps to replicate:
1. Disable `Show Conversation Thumbnails`
2. Restart YakYak

Expected results:
- User specific thumbnails show in chat windows (especially multi-user chat windows)

Actual results:
- Thumbnails show as a question mark

If I toggle "Show Conversation Thumbnails" then it will start showing thumbnails for users I have an ongoing 1-on-1 chat with, but still shows question marks for users that I don't.

**Comment by chasetb** [comment]
I see this too (also on OS 10.11.6, v1.3.2(1.3.1)). In my group chats, most thumbnails don't populate unless I click on "Details" and then then will populate. I do this everytime I re-launch the app.

**Comment by cameronr** [comment]
Still seeing this in the latest 1.3.2 release

**Comment by averissimo** [comment]
@tresni @chasetb @cameronr is this still a problem?

**Comment by cameronr** [comment]
@averissimo seems fixed in the 1.3.3 prerelease

**Comment by averissimo** [comment]
cool, i'm closing this issue then :)

**Comment by averissimo** [comment]
@cameronr thanks for quick feedback ^^
