### ISSUE TITLE
Install Ubuntu 16.04 "No protocol specified"

### ISSUE THREAD

**Issue by Sovepro** [yakyak/yakyak#355]
Hello,
I've tried to install yakyak on ubuntu 16.04.
I followed these steps to installe your software:
$ unzip yakyak-linux-x64.zip
$ cd linux-x64
$ ./yakyak
Installation failed, returning "No protocol specified".
`principal@cb-Aspire-5735:/home/cb/Téléchargements$` cd linux-x64/
principal@cb-Aspire-5735:/home/cb/Téléchargements/linux-x64$ ./yakyak
No protocol `specified`

If I directly execute the yakyal application file, it doesn't stop opening "screens".

Could you tell me what to do ?
Thank you in advance

**Comment by averissimo** [comment]
I've tried in my machine with lastest version "1.3.1" and it works out of the box.

Have you ran Yakyak before?

Try to remove/move configuration directory in ``~/.config/yakyak`` (either remove it or rename to something else to try with a blank start).

I'm running Ubuntu 16.10.

**Comment by davibe** [comment]
closing because of no reply
