### ISSUE TITLE
Menu bar icon is invisible on OSX when using dark menu bar due to blending colors

### ISSUE THREAD

**Issue by ironcladlou** [yakyak/yakyak#356]
When using the "dark menu bar" option in OSX, the YakYak menu bar icon becomes invisible. Clicking the icon's space reveals the icon because of the background of the menu icon is changed to something lighter which contrasts with the icon.

**Comment by ctcpip** [comment]
it's pretty hard to see using Linux as well ..  (doesn't change when clicking though)  - LXDE/Lubuntu 16.04

**Comment by arnriu** [comment]
which " YakYak menu bar icon " are we talking about here? If its the three dots on the upper right corner of the window, I do not have any problem, the dots are same grey as text, in contrast of black background, in dark mode. Or is it something else?

**Comment by ironcladlou** [comment]
Examples:

<img width="412" alt="screen shot 2016-08-30 at 9 29 13 am" src="https://cloud.githubusercontent.com/assets/298299/18090767/58f61146-6e94-11e6-9fc9-8b21522b3e61.png">
<img width="256" alt="screen shot 2016-08-30 at 9 29 26 am" src="https://cloud.githubusercontent.com/assets/298299/18090768/590579c4-6e94-11e6-9d55-6451aebef5d9.png">

**Comment by arnriu** [comment]
https://github.com/electron/electron/blob/master/docs/api/native-image.md#template-image
https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/ToolbarIcons.html#//apple_ref/doc/uid/20000957-CH89-SW3

@Stanko @monchote

**Comment by Stanko** [comment]
It seems this can be done by using [Template Image](https://github.com/electron/electron/blob/master/docs/api/native-image.md#template-image). I'll take a look tomorrow.

**Comment by ironcladlou** [comment]
I'm not seeing any change with the new release (1.3.2, OSX 10.11.5). Same results as before (https://github.com/yakyak/yakyak/issues/356#issuecomment-243438819).

**Comment by monchote** [comment]
@ironcladlou I've just built master and it's now displayed as expected: <img width="98" alt="screen shot 2016-09-17 at 23 42 06" src="https://cloud.githubusercontent.com/assets/1186808/18611521/6d67bf00-7d33-11e6-954e-9b3da7de6180.png">

**Comment by arnriu** [comment]
@ironcladlou It's now live on master as @monchote said, if you build on your own. It should be available on next release if you prefer pre-built binaries.

**Comment by ironcladlou** [comment]
Confirmed fixed as of 2aa9f8d99708c3913c9943a27b2966b6a503391a, thanks!
