### ISSUE TITLE
No right click menu.

### ISSUE THREAD

**Issue by LinkofHyrule89** [yakyak/yakyak#357]
When I right click highlighted text or pictures I expect to be able to have a copy/paste in both the chat and message field. This could also include information about the message similar to how Android does it but that's not a required feature.

**Comment by ctcpip** [comment]
+1 for copy-to-clipboard functionality when right-clicking on a hyperlink.  a cursory inspection of #357 suggests this will be addressed

**Comment by averissimo** [comment]
@LinkofHyrule89 @ctcpip doesn't this already work with selected text?

Images seem to be more problematic

**Comment by ctcpip** [comment]
right click and copying of hyperlinks are working for me in 1.4 beta

**Comment by averissimo** [comment]
yay! closing it then. thanks @ctcpip 

@LinkofHyrule89 if you still see this problem please reopen
