### ISSUE TITLE
Improve icon to new stylish design

### ISSUE THREAD

**Issue by MartSerra** [yakyak/yakyak#363]
I think the icon is a little simpler. I would be awesome if **YakYak** re-design a logo following [Material Design Style guide](https://material.google.com/style/icons.html#icons-product-icons).

Thanks for make this great application.

**Comment by arnriu** [comment]
Users voted for this icon here: #249
But you can submit new icon ideas here: #21

**Comment by averissimo** [comment]
closing, @MartSerra you can continue this conversation on the two issues that @arnriu referenced
