### ISSUE TITLE
not working at all for me autentication  issue

### ISSUE THREAD

**Issue by ale82to** [yakyak/yakyak#366]
as soon as i open this app i get this message =
scope=https://www.google.com/accounts/OAuthLogin
response_type=code
redirect_uri=urn:ietf:wg:oauth:2.0:oob
client_id=936475272427.apps.googleusercontent.com

very disappointed

**Comment by tfreedman** [comment]
I can confirm this issue on OS X - it happens immediately upon launching the app.

![screen shot 2016-09-01 at 11 57 05 am](https://cloud.githubusercontent.com/assets/850412/18174379/5f92e2c4-703b-11e6-9973-2f1dbc89d91f.png)

**Comment by CatLover91** [comment]
This is already an open issue #358 and is based upon tdryer/hangups#260 needing to be fixed.
