### ISSUE TITLE
Not authorized to request the scopes

### ISSUE THREAD

**Issue by MrAbaddon** [yakyak/yakyak#367]
When I Open yakyak I get an 400 error:

GOOGLE

400. That’s an error.

Error: invalid_scope

Not authorized to request the scopes: [https://www.google.com/accounts/OAuthLogin]

Learn more

Request Details
=
scope=https://www.google.com/accounts/OAuthLogin
response_type=code
redirect_uri=urn:ietf:wg:oauth:2.0:oob
client_id=936475272427.apps.googleusercontent.com
That’s all we know.

I cant login.
I've tried to update but no luck.
I'm using version 1.3.1 .

Thanks.

Bruno Morais

**Comment by PavelPod** [comment]
Check the issue #358 - https://github.com/yakyak/yakyak/issues/358
