### ISSUE TITLE
Does YakYak have an opinion on the future of Coffeescript?

### ISSUE THREAD

**Issue by greghuc** [yakyak/yakyak#369]
Hi guys,

A quick heads up that there's a pretty active discussion going on over at [coffeescript6/discuss](https://github.com/coffeescript6/discuss) about possible next steps for Coffeescript.

Thought you might want to comment, given YakYak is a heavy Coffeescript user. Discussed issues are [here](https://github.com/coffeescript6/discuss/issues).

There's also a survey that's relevant to you: [Survey for devs/teams with maintained Coffescript codebases: happy with CS, or considering migrating?](https://github.com/coffeescript6/discuss/issues/32)

**Comment by davibe** [comment]
I do have an opinion. I think coffeescript needs support for async and await.

I do not care about other advanced ES6 features too much. They are not very useful to me. I do not consider removing coffeescript. There are simple things I simply can'd to with JS unless i want to syntax-kill myself . `isnt.it?.true?`

I will try to partecipate a bit but it's a big topic and i don't have much time for it.

**Comment by greghuc** [comment]
@davibe thanks for the response.

If you haven't much time, it would be great if you could express a short opinion at the [survey](https://github.com/coffeescript6/discuss/issues/32). It shouldn't take long: 4 questions in a tiny markdown template. It's not "official", it's just a way of getting feedback about Coffeescript from devs/teams that are currently using it. Opinions gathered will be taken into consideration when considering the future of Coffeescript.

It would be great to get the opinion of someone who is not considering removing Coffeescript. Quite a few teams in the survey are switching to ES6.

**Comment by davibe** [comment]
Those who have given up on coffee are unlikely to participate
