### ISSUE TITLE
Wrong version 

### ISSUE THREAD

**Issue by wickles** [yakyak/yakyak#371]
For the OSX app, the file info says 1.2.5. In the help window it says "1.2.5 (1.3.x)" (for whatever release x you're on).

**Comment by Arithmomaniac** [comment]
In Windows 10 for 1.3.3, it only says 1.2.5.

**Comment by mliq** [comment]
I believe the first version number is the electron version, the one in parentheses is the YakYak version? Agree that this should be made more clear.

**Comment by davibe** [comment]
@mliq that's true on osx. I don't know what happens on other platforms. Needs to be handled better for sure.

**Comment by averissimo** [comment]
Could this solve the version problem in **MacOSX**?

![image](https://cloud.githubusercontent.com/assets/211358/19457978/035771dc-94c1-11e6-8caa-132399740e35.png)

https://github.com/electron/electron/blob/master/docs/api/app.md

**All platforms**

I've been working on a new `Help -> About` menu. Should it appear on all platforms? (I have no idea on OSX)

What other information should it contain?

branch: https://github.com/averissimo/yakyak/tree/feature-about (needs #403 to be able to run)

![image](https://cloud.githubusercontent.com/assets/211358/19460377/fd641b9c-94d2-11e6-97f0-a14a44f164c1.png)

**Comment by averissimo** [comment]
solved in latest 1.4.0-beta see #451
