### ISSUE TITLE
Error 400 (OAuth2 Error) when launching for first time

### ISSUE THREAD

**Issue by apbitner** [yakyak/yakyak#373]
Looking forward to using this app, however when I launched it for the first time I got the attached error. I'm on Mac OS 10.11.6.

<img width="957" alt="screen shot 2016-09-13 at 11 03 18 am" src="https://cloud.githubusercontent.com/assets/22176302/18481413/b5c2eea4-79a1-11e6-9c24-1374253b338b.png">

**Comment by averissimo** [comment]
**which version did you install?** 1.3.1 is broken and has that known bug since google changed something.

Try: https://github.com/yakyak/yakyak/releases/tag/v1.3.2

If it is not then crap, and try to put the output of the console as well.

**Comment by apbitner** [comment]
I must've installed 1.3.1, because I was unable to unzip 1.3.2. However I
downloaded an app to unzip it now and was able to install successfully.

**Comment by averissimo** [comment]
cool, so can you close the issue? :)
