### ISSUE TITLE
Blank screen on start

### ISSUE THREAD

**Issue by MarkusMcNugen** [yakyak/yakyak#374]
I'm trying to run the 1.3.2 binaries on my Windows 7 x64 desktop and upon opening YakYak I'm greeted with a blank window. I've tried running both the 32 and 64-bit versions for good measure but both do the same thing. I also double checked the application was being allowed through the firewall. If you need any information just let me know what you need and where to get it.

![yakyakerror](https://cloud.githubusercontent.com/assets/14831105/18516469/23038fa8-7a67-11e6-9b27-7d8309a321c6.png)

**Comment by Celti** [comment]
1.3.2 (both the binaries and building it myself) is giving me a blank screen as well — it shows me the Google Account login page, lets me enter a password, then shows a blank screen instead of progressing to asking for my TOTP code. Output:

```
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
asking for login credentials
2016-09-17 1:17:51 WARN no SAPISID cookie
2016-09-17 1:17:51 WARN no SAPISID cookie
login: did-finish-load https://accounts.google.com/ServiceLogin?passive=1209600&continue=https://accounts.google.com/o/oauth2/programmatic_auth?top_level_cookie[...]
login: programmatic auth
login: did-finish-load https://accounts.google.com/signin/challenge/totp/2?continue=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fprogrammatic_auth%3Ftop_level_cookie[...]
```

URLs are trimmed because I'm not entirely sure of the security issues with their content, I can provide more if necessary.

**Comment by pmcanseco** [comment]
I'm having the same issue as OP on Windows 10 64-bit, when compiling the latest commit (https://github.com/yakyak/yakyak/commit/fbcc26736c9a11fd7f7d7805fff8782c8c4c9b61). I tried running it from the windows commandline but there was no commandline output. I'm not sure where the log files are but I can post them if someone knows how to find them.

**Comment by pmcanseco** [comment]
I also just compiled it under the above commit in Arch Linux (Kernel 4.7) 64-bit and also got a blank screen on startup.

**Comment by averissimo** [comment]
The latest commit problem is from a typo in the menu generation in the last PR merge.

#403 has the solution for that one.

**Comment by averissimo** [comment]
To debug the application when there is a blank interface the console is a great place, but if no error/warnings are there you need to debug YakYak using the developer's tools.

Available through the links in the menus or by shortcut using Ctrl+Alt+I

In case the shortcut does not work it is usually the sign that a problem happened during menu generation or before. In Ubuntu I can always access the Developer's Tools via the menu, not sure about other environments though.

**Comment by pmcanseco** [comment]
@averissimo thank you for the prompt response and debugging tips. I'm still getting a white screen after applying the fixes from your PR. The console spams the message in the screenshot below indefinitely, and Ctrl+Alt+I doesn't bring up anything.


![image](https://cloud.githubusercontent.com/assets/1095661/18979351/1bf7e244-8698-11e6-9457-4911a041807a.png)

![image](https://cloud.githubusercontent.com/assets/1095661/18979399/8bf946dc-8698-11e6-9578-578167c31fa6.png)

**Comment by averissimo** [comment]
- Can you access the menus if you try to press `Alt` key or via the menu bar?
  - getting info from developer's console would be really great
- Are you authenticating an account in this process or is that already saved in your profile?
- Have you done `npm install` recently just to make sure you have all packages?
  - this only apply for who is compiling from git

I cannot replicate this :\

![outknvgupur3b](https://cloud.githubusercontent.com/assets/211358/18988506/f4dd69ba-86fe-11e6-83e4-be38bffe14f4.gif)

**Comment by averissimo** [comment]
install electron-dev

    $ npm install --save electron-debug

add this below `app = require...`in `main.coffee`

    require('electron-debug')({showDevTools: true})

And this opens dev tools automatically.

![outhsdxpj1zhq](https://cloud.githubusercontent.com/assets/211358/18989255/de87a42e-8702-11e6-85a2-65a3d265fb42.gif)

ps. screencast shows me running without the PR fix, that's why I get the blank window.

**Comment by pmcanseco** [comment]
Hi @averissimo ,

I gave it another try just now with your new instructions. First I ran `npm install` to make sure I had all the packages. Then I ran `npm install --save electron-debug`. See screenshot:
![1](https://cloud.githubusercontent.com/assets/1095661/19008598/5adf88ac-873a-11e6-85ef-4b354ea80553.PNG)

Then I added the line in `/src/main.coffee` : `require('electron-debug')({showDevTools: true})` as in the screenshot:
![2](https://cloud.githubusercontent.com/assets/1095661/19008618/77766382-873a-11e6-96e4-76a26868719f.PNG)


Then I tried running the app using `npm run electron app` like from the readme, but it's been giving me the following error: 
![error running dev mode](https://cloud.githubusercontent.com/assets/1095661/19008644/99097764-873a-11e6-82ba-87aceee54a3f.PNG)

So I compiled it with `npm run deploy` and ran the resulting windows binaries on Windows 10 64-bit. No console came up and white screen:
![2016-09-30_18-22-34](https://cloud.githubusercontent.com/assets/1095661/19008689/f54813e6-873a-11e6-8a2f-34377b8aa2fc.gif)

I should note that I do see errors when running the deploy command:
```
pablo@elemio:~/yakyak$ npm run deploy

> yakyak@1.3.3 deploy /home/pablo/yakyak
> bash ./deploy.sh

checking dependency... curl
checking dependency... unzip
checking dependency... sed
npm ERR! max depth reached: autosize@3.0.17, required by yakyak@1.3.3
npm ERR! max depth reached: hangupsjs@1.3.2, required by yakyak@1.3.3
npm ERR! max depth reached: moment@2.15.1, required by yakyak@1.3.3
npm ERR! max depth reached: node-notifier@4.6.1, required by yakyak@1.3.3
npm ERR! max depth reached: notr@1.1.2, required by yakyak@1.3.3
npm ERR! max depth reached: q@1.4.1, required by yakyak@1.3.3
npm ERR! max depth reached: request@2.75.0, required by yakyak@1.3.3
npm ERR! max depth reached: tmp@0.0.28, required by yakyak@1.3.3
npm ERR! max depth reached: trifl@0.0.10, required by yakyak@1.3.3
npm ERR! max depth reached: url-regexp@1.0.2, required by yakyak@1.3.3
npm ERR! max depth reached: electron-debug@1.0.1, required by yakyak@1.3.3
npm ERR! max depth reached: coffee-script@1.11.0, required by yakyak@1.3.3
npm ERR! max depth reached: electron-prebuilt@1.4.1, required by yakyak@1.3.3
npm ERR! max depth reached: gulp@3.9.1, required by yakyak@1.3.3
npm ERR! max depth reached: chai@3.5.0, required by yakyak@1.3.3
npm ERR! max depth reached: gulp-auto-reload@0.1.0, required by yakyak@1.3.3
npm ERR! max depth reached: gulp-changed@1.3.2, required by yakyak@1.3.3
npm ERR! max depth reached: gulp-coffee@2.3.2, required by yakyak@1.3.3
npm ERR! max depth reached: gulp-concat@2.6.0, required by yakyak@1.3.3
npm ERR! max depth reached: gulp-less@3.1.0, required by yakyak@1.3.3
npm ERR! max depth reached: gulp-install@0.6.0, required by yakyak@1.3.3
npm ERR! max depth reached: gulp-rename@1.2.2, required by yakyak@1.3.3
npm ERR! max depth reached: gulp-sourcemaps@1.6.0, required by yakyak@1.3.3
npm ERR! max depth reached: gulp-util@3.0.7, required by yakyak@1.3.3
npm ERR! max depth reached: mocha@2.5.3, required by yakyak@1.3.3
npm ERR! max depth reached: rimraf@2.5.4, required by yakyak@1.3.3
npm ERR! max depth reached: sinon-chai@2.8.0, required by yakyak@1.3.3
npm ERR! max depth reached: sinon@1.17.6, required by yakyak@1.3.3
npm ERR! not ok code 0
```

but the binaries do get rebuilt. I'm not sure if these errors are related to the white screen and lack of console, but I thought I'd mention them in case they're relevant.

I really appreciate the help thus far!

**Comment by averissimo** [comment]
I'm guessing it is using the previously compiled version as you did not run

    $ npm run gulp

Then the `npm run electron app` should work and the deploy will also rebuild with the recently compiled version

PS. Nice screen cast :)

**Comment by pmcanseco** [comment]
Thank you sir!

`npm run gulp` gives the following output:
```
pablo@elemio:~/yakyak$ npm run gulp

> yakyak@1.3.3 gulp /home/pablo/yakyak
> gulp

[13:07:49] Requiring external module coffee-script/register
[13:07:52] Using gulpfile ~/yakyak/gulpfile.coffee
[13:07:52] Starting 'package'...
[13:07:52] Starting 'coffee'...
[13:07:52] Starting 'html'...
[13:07:52] Starting 'images'...
[13:07:52] Starting 'icons'...
[13:07:52] Finished 'icons' after 22 ms
[13:07:52] Starting 'less'...
[13:07:52] Starting 'fontello'...
[13:07:52] Finished 'html' after 305 ms
[13:07:52] Finished 'images' after 305 ms
[13:07:53] Finished 'less' after 564 ms
[13:07:53] Finished 'package' after 910 ms
[13:07:54] Finished 'coffee' after 1.49 s
[13:07:54] Finished 'fontello' after 1.63 s
[13:07:54] Starting 'default'...
[13:07:54] Finished 'default' after 3.79 μs
```

And I still get the max depth reached errors from above, leading to the blank screen. I can't run it in Linux because `npm run electron app` gives:

```
pablo@elemio:~/yakyak$ npm run electron app
npm ERR! Error: ENOENT, open '/home/pablo/yakyak/node_modules/electron/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-66-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "electron" "app"
npm ERR! cwd /home/pablo/yakyak
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/pablo/yakyak/node_modules/electron/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pablo/yakyak/npm-debug.log
npm ERR! not ok code 0
```

Does `npm run electron app` work for you? what is the content of your electron package.json?

**Comment by pmcanseco** [comment]
I dug a bit and found that `~/yakyak/node_modules` contains an `electron-debug` and `electron-prebuilt` folder. It seems that it can't find the electron folder for some reason, which is why it's erroring out.

**Comment by averissimo** [comment]
you are using a really old version of node and npm, can you updatee to v4 or v6 (i use this one) and then `npm -g install npm`

After delete the electron folder inside modules and run `npm install` (you can also delete all contents of node_modules, and run the install command)

**Comment by averissimo** [comment]
Not sure if it is necessary though (it is not for running the binaries, but it should be for starting the dev tools, when like you cannot call it via shortcuts or menu)

i'm not that experienced with node and started playing with yakyak recently, if other people want to chip in please do :)

**Comment by rlees85** [comment]
Not a fix, but a workaround, have you tried running with --disable-gpu parameter? Fixed the problem for me (on Linux)

**Comment by averissimo** [comment]
just though of a slightly better solution to debug YakYak when cases like this appear and it is already on pull request #418 for discussion.

With this change the original menu is visible and can access the DevTools directly.

@pmcanseco If you really want to debug you don't have to build everything (sorry, but I did not know better), just change file `resources/app/main.js` in released binary to add above the line containing `loadAppWindow();`: 

```
mainWindow.webContents.openDevTools();
loadAppWindow();
```

It will open the DevTools when running YakYak and you can see the error preventing the interface from loading

**Comment by pmcanseco** [comment]
@averissimo that's really cool! I'll give it a shot.

**Comment by averissimo** [comment]
@pmcanseco @MarkusMcNugen (cool name) I'm closing this issue

Right now YakYak has better debugging capabilities (as it shows errors in terminal), and when pull request #521 is merged it will have a cool error window with a descriptive message

__If you guys are still having problems please open a separate issue__

thanks!
