### ISSUE TITLE
Code sign Mac binaries.

### ISSUE THREAD

**Issue by williamsjj** [yakyak/yakyak#375]
It would be really awesome if the Mac binaries could be code signed. Its pretty painful on El Capitan forward to do the initial launch.

**Comment by jacquescrocker** [comment]
whats the workaround to actually opening this?

I had to enable apps for all unknown sources. Clicking "Open Anyways" just errored out.

**Comment by averissimo** [comment]
duplicate of #245

**Comment by averissimo** [comment]
@jacquescrocker not a osx user, sorry

**Comment by williamsjj** [comment]
@jacquescrocker Right-click on the YakYak binary, then hold down the Option key while you click "Open". 

That will tell OS X to prompt you to accept the reduced to security rather than refusing to run YakYak. Afterward you can launch normally.
