### ISSUE TITLE
Some user icons showing question mark.

### ISSUE THREAD

**Issue by charliemathews** [yakyak/yakyak#376]
<img width="668" alt="screen shot 2016-09-14 at 3 12 09 pm" src="https://cloud.githubusercontent.com/assets/484580/18528250/d3838254-7a8d-11e6-880b-5d95440614c1.png">

yakyak 1.3.2, osx 10.11.6

**Comment by charliemathews** [comment]
If I use any other hangouts app, I can see user icons on every person. The people who's pictures I can't see in yakyak are "chosen" for no obvious reason.

**Comment by chasetb** [comment]
If you click on the "Details" option at the top of a chat, does the app populate the thumbnails properly? If so, this is a know problem: #353

**Comment by charliemathews** [comment]
Yes, that took care of it. Just came back to say that exact thing.
