### ISSUE TITLE
No Longer Connects

### ISSUE THREAD

**Issue by pryorda** [yakyak/yakyak#38]
Windows 1.0.0 32 and 64

Stuck at Connecting in the top right corner. Worked before yesterdays release.

Troubleshooting steps. Remove App -> remove AppData-> Roaming, reboot try again etc.

**Comment by algesten** [comment]
@davibe do you see this too?

**Comment by davibe** [comment]
Confirmed. I can reproduce on win 7 32b.

**Comment by algesten** [comment]
we hope new version is working.
