### ISSUE TITLE
Wish List: selectable notification sound

### ISSUE THREAD

**Issue by NSDodgers** [yakyak/yakyak#381]
I would love to set a dedicated YakYak notification sound in windows and mac so I can tell it from other apps.

Thank you

**Comment by averissimo** [comment]
@NSDodgers right now it is the notification system that controls the sound that's produced

**Comment by averissimo** [comment]
The current options interface would require a big change to support this type of customization.

**Comment by averissimo** [comment]
I'm working on a custom yakyak sound for notification systems that don't support sound

in theory when this is released it would be just a matter of replacing the sound file by your own custom one.

I don't see this as an option unless the way we set options in yakyak is changed in the near future :\

any help is welcome!

@NSDodgers do you think we can move this conversation to #405 and close this issue?

**Comment by averissimo** [comment]
closing, as #405 is more generic conversation on notification sounds 

It's not customizable, but you can activate a default sound in `view -> notifications -> use custom YakYak sound`

if you really want to change it, just replace `new_message.ogg` (in `resources/app/media`) by your own sound (the filename has to be the same)
