### ISSUE TITLE
Auto updater?

### ISSUE THREAD

**Issue by LinkofHyrule89** [yakyak/yakyak#382]
It would be great if we had a full blown auto updater instead of just the notification.

**Comment by mattsigal** [comment]
I'm not even sure I've even gotten notifications? A update checker that we could manually trigger from the menu would be awesome. Maybe a "Check for Updates" button within the 'About YakYak' dialogue box?

**Comment by averissimo** [comment]
@LinkofHyrule89 awesome ideia, do you have any idea on how to do that with an electron app?

@mattsigal Yakyak already has this notification (I believe in the form of an alert when it is outdated to latest STABLE version) You can open the console to see that is running.

![image](https://cloud.githubusercontent.com/assets/211358/20649671/5b09ec0a-b4bc-11e6-9225-677bb6228781.png)

The about menu also shows the same information, but it is only shown when the installed version is older than latest release stable here yakyak/yakyak

**Comment by TwisterMc** [comment]
I would love a visual notification that wasn't in the console. Like a little red dot, or banner.

Auto update would be amazing, but some sort of other indicator would be nice too.

**Comment by creedda** [comment]
Would love to see an auto-update feature added

**Comment by averissimo** [comment]
@TwisterMc there is popup that appears (as well as the console line).. but I think we can change it to fit the UI a little bit better by using a notification in the top right corner instead

**Comment by averissimo** [comment]
Created a pull request with a better (less intrusive) alert system notification.

However updates to Yakyak are quite sparse, as we build on pre-releases for some time before releasing a new version.

see #759

**Comment by averissimo** [comment]
about the auto-updater, last time I checked a package to do this did not work for all systems.

If this has changed let us know :)
