### ISSUE TITLE
AutoSmilie!

### ISSUE THREAD

**Issue by astralan** [yakyak/yakyak#384]
There a way to turn off the feature that substitutes a smilie when I type a time into a chat? When I type, say, 7:30, I get this instead: 7😸0 
Most annoying! Thanks in advance. -B

**Comment by arnriu** [comment]
There must be an option in view menu "convert text to emoji". Did you try to uncheck it?

**Comment by randymorris** [comment]
I have the "Convert text to emoji" option enabled and when I type "7:30" it (correctly) does not get converted.

I rebuilt this morning from master.  What version are you using @astralan ?

**Comment by astralan** [comment]
Not seeing that option.
V 1.3.2
![yakyak](https://cloud.githubusercontent.com/assets/21952876/18712401/de442504-7fd3-11e6-8c0a-54edb4155e41.png)
Thanks for the response, yall. -B

**Comment by arnriu** [comment]
can you try 1.3.3 ? https://github.com/yakyak/yakyak/releases

**Comment by astralan** [comment]
Yup, the beta has it. Not usually into early adoption, but this works. Thanks! -B

**Comment by averissimo** [comment]
@astralan **do you still experience that bad conversion to smile in v1.3.3?** With that option activated?

**Comment by astralan** [comment]
This has gone away since the 1.3.3 build. No longer interprets a : as an invitation to become emoji
