### ISSUE TITLE
Missed avatars

### ISSUE THREAD

**Issue by averrin** [yakyak/yakyak#385]
After launch all avatars in conversation is "?" if "Show conversation thumbs" is disabled. Avatars will shown if i turn in this option on. Very annoying =(

**Comment by arnriu** [comment]
what version are you running? This should be fixed in 1.3.3 https://github.com/yakyak/yakyak/releases

**Comment by averrin** [comment]
hm, its really fixed. Seems like i merged upstream wrong.
Thanks!
