### ISSUE TITLE
Feature Request: Notifications format option which does not reveal name and message received

### ISSUE THREAD

**Issue by mliq** [yakyak/yakyak#386]
My use case for YakYak is that I need to be made aware when I get a message there, but I do not want the content of that message, or the sending username, to be revealed to anyone who might be looking at my screen.

**Comment by averissimo** [comment]
looks like a slightly modified version of #328 could solve this, by adding a new option called "hide message from notifications" if notifications option is on.

**Comment by averissimo** [comment]
Isn't the change of colors in the tray icon enough for you?

![selection_00040](https://cloud.githubusercontent.com/assets/211358/18746989/f5fdca04-80ca-11e6-95f5-d4d52f47c469.png)

![selection_00041](https://cloud.githubusercontent.com/assets/211358/18746987/f19ff3f6-80ca-11e6-8b0d-8e844bd43ded.png)



I could see disabling notifications and hiding the message as useful features

Actually I've just implemented hiding the message in https://github.com/averissimo/yakyak/tree/popup-only-username , if you really need for you try to extend to hiding the username using identical code :)

**Comment by mliq** [comment]
My tray icon does not change colors for some reason. It is also invisible.
![image](https://cloud.githubusercontent.com/assets/7573605/18794404/fc8e9db6-8184-11e6-9406-d085d8c5ab34.png)

For now I just have the dock notification, but if I am busy working on something I will not see that (I auto-hide the dock).

While I am mentioning this, it would be nice to get a global notification when YakYak is disconnected, which happens pretty frequently for some reason.

**Comment by mliq** [comment]
@averissimo Thanks for the branch, I will try that if I get some time!

**Comment by mliq** [comment]
@averissimo I made the changes, should i do a fork from and PR to your branch?

**Comment by averissimo** [comment]
Do it directly to yakyak/yakyak .. the community is here, my fork is just for fun and breaking things :)
