### ISSUE TITLE
Can't focus on new conversation

### ISSUE THREAD

**Issue by ctcpip** [yakyak/yakyak#389]
When receiving a message that begins a new conversation, the conversation appears in the list, but clicking on it does not open up the conversation. (Focus remains on your other conversation which was already open.)  You have to quit the app and open it back up to respond (and/or view the conversation).  Also, the username does not appear in the conversation list but this is tracked in #246

**Comment by averissimo** [comment]
I confirm it :)

Seems like new conversations lack array with `current_participant` and `participant_data`

If you check for the existence of the property it will open up conversation, but avatar and 'details' of conversation won't appear.

    c = conv[conv_id]
    if c.current_participant? # add this and spaces in lines below
        for participant in c.current_participant
          entity.needEntity participant.chat_id

**Comment by averissimo** [comment]
@ctcpip can you try latest beta? I believe it has solved it

**Comment by ctcpip** [comment]
It's working for me in the beta, BUT - clicking on the 'Details' button does nothing.  You have to quit and reopen the application before 'Details' button has any effect.

**Comment by ctcpip** [comment]
#246 is still outstanding as well

**Comment by averissimo** [comment]
Gotta figure out a way to ask for that information.

thanks for the very well described report! :)

**Comment by davibe** [comment]
Maybe, if the chat is of type one-to-one that information is somewhere else in the payload.

**Comment by ctcpip** [comment]
Bump.  👎 `probot-stale` ^ 👎

**Comment by ctcpip** [comment]
Bump. 👎 stalebot 👎
