### ISSUE TITLE
Some suggestions to make it the #1 IM app

### ISSUE THREAD

**Issue by Compyooter** [yakyak/yakyak#39]
Disclaimer :) I am not a developer and don't do any type of coding. Point is, I have no idea how to carry out these ideas, how difficult they may be, or if they're even possible. Since so, I greatly appreciate developers, you guys!

1) add the ability to use various types pf accounts, in addition to Google and have them active simultaneously. Such as Facebook, Yahoo messenger, Twitter. Those modules are pretty common in many IM apps, so I assume that it should be quite easy to integrate.

2) making the app lighter (as in less resource hungry). It uses a substantial amount of RAM. I've observed this on multiple Linux machines. Don't remember what I saw on Windows machines.

Thanks for the app. It is currently the only IM app that can be used with Google's heightened security settings.
I've used many IM apps, and tested many more. I really think that if these two will be addressed, Yakyak will outrun all others.

**Comment by Gibbz** [comment]
imoh, I think keeping it as hangouts only is a good idea.
It would be great to see minimise to tray, and only display a tray icon(not on the task bar) in the next release.

**Comment by davibe** [comment]
1) This requires a "client abstraction" to support multiple clients. It's related to another request we had to enable using multiple Google Hangout accounts which is easier and would probably have precedence. We are currently more concentrated on bugs and less disruptive changes. I can see a strong case for multiple hangout accounts. I am not sure we should try to be the next multiuser chat application as that forces you to abstract lots of peculiarities of each chat provider that are difficult to make usable and coherent. 
Of course if somehow, someday, things turn into money then everything is possible. For the moment this is a nice side project therefore there are some limits to what we can do.

2) The app runs on Electron, which is a complete browser environment based on Chrome. I expect it to use as much memory as Chrome. Our implementation sits on top of that and it's a very simple application. It's possible that we have some memory leak on our application that makes memory grow over time. In this case we need a proper bug report with steps on how to reproduce. If you are talking about memory that is used right at application start then i am afraid there is not much we can do. I am sure Electron guys will optimize things over time as much as possible. That being said thanks for your feedback we will take a look to memory consumption too.

**Comment by Compyooter** [comment]
Well, I'll have to trust you on that. I ain't a developer, and I appreciate your work. I do still enjoy yakyak, thank you.
