### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by trgcyln** [yakyak/yakyak#390]
Hello,

I've tried 1.3.2 and 1.3.3 x64 & 32bit  windows versions but i had a problem with login.
It keeps reopening new login screens after i enter my credentials. Looks like an infinite loop.

**Comment by PMiner** [comment]
do you have 2FA? (two-factor authentication) if so, that's still in the works. try logging in with an app password though.

**Comment by averissimo** [comment]
@trgcyln can you give more information?

if the problem persists try removing yakyak config directory at %APPDATA%

that seems to be the only solution so far

**Comment by averissimo** [comment]
@trgcyln if you are still experiencing this problem in 1.4.1 or up, please reopen this issue
