### ISSUE TITLE
Visually indicate that text input is focused when app switching back to YakYak

### ISSUE THREAD

**Issue by jjt** [yakyak/yakyak#392]
I was just typing up an issue about how it's annoying to have to move my hands to the mouse/trackpad in order to re-focus the text input, but then stumbled upon the fact that the input is already focused.

Having a visual indication of the text field's focused state would provide a better UX.

OSX El Capitan, 10.11.6 (15G1004)
YakYak Version 1.2.5 (1.3.2)

**Comment by victorstuber** [comment]
Totally agree with this. I often find myself clicking the input field multiple times because it's not clear that it's focused.

**Comment by averissimo** [comment]
Improved this a bit, by focusing on input when window is focused (i.e. changing windows) and switching conversations.

Cannot be always focused as it would break the app interface experience. (for instance selecting text and copy would not work)

test versions 1.4.1 and above for this improvements

__re-open if you feel that this is still not enough.__

ps. paste now also works even if input is not focused (only if message pane is showing, of course)

**Comment by jjt** [comment]
Amazing thx! Will check out later today :)
