### ISSUE TITLE
Missing fonts in OS X build

### ISSUE THREAD

**Issue by tseven** [yakyak/yakyak#396]
Downloaded the pre-built binary from:
https://github.com/yakyak/yakyak/releases/tag/v1.3.2

![screen shot 2016-09-26 at 11 29 26 am](https://cloud.githubusercontent.com/assets/311287/18846858/abc42f4a-83dc-11e6-80b3-092b5726d8ad.png)

I verified that the css folder inside the YakYak.app package does not contain the files being referenced. Perhaps it's just a build/compile error.

Building the app from source doesn't contain this issue.

**Comment by arnriu** [comment]
This has been fixed in next release.  See https://github.com/yakyak/yakyak/releases/tag/v1.3.3
(and dont worry, if you stick with 1.3.2, font isnt missing, just woff2 files missing, but you still have woff files working) .
