### ISSUE TITLE
Crash/Freeze on startup

### ISSUE THREAD

**Issue by Gibbz** [yakyak/yakyak#40]
Windows 8.1 x64
Extract the app, then it opens the window and says "connecting" the the app freezes.
If i kill the task "electron" i can resume using my computer...

Is there a log file somewhere I can submit?

**Comment by davibe** [comment]
@Gibbz there is no log file you can submit. Do you have a single core machine or did you limit the application to use just one core somehow ?

**Comment by Gibbz** [comment]
No, i have a quad core machine. I didn't do any limiting of any kind

**Comment by davibe** [comment]
Ok, you should be fine with the next release. Please be patient :)

**Comment by davibe** [comment]
@Gibbz new release available
