### ISSUE TITLE
Two Step Verification

### ISSUE THREAD

**Issue by tribbledt** [yakyak/yakyak#402]
When logging in to YakYak I enter my Google e-mail address and password and get a blank screen when I am receiving my two step verification code from Google. The screen remains blank and that's as far as I can get logging in.

**Comment by davibe** [comment]
2 step thing is not supported at the moment. Need to do it

**Comment by randymorris** [comment]
FWIW, I've been using two factor auth on OSX since I started using YakYak quite a few versions ago and it's currently working for me.  I'm using a Google Apps account though, not just a normal Google account so that could be a difference.

**Comment by averissimo** [comment]
just logged-in in Ubuntu and worked without any problems (normal google account)

ps. running from master branch and #403 merged

**Comment by ajimix** [comment]
I just installed fresh install, in OSX and works perfectly, and I have two factor authentication

**Comment by LinkofHyrule89** [comment]
2FA works fine for me on YakYak although I do have to do it a few times before it lets me in.

**Comment by evaryont** [comment]
2FA works for me as well, but notably not U2F support. The U2F 2FA screen popped up with a generic error message about attempting to connect to my USB key (a Yubico key). Tried plugging it in and retrying but that didn't work. Switched methods to the TOTP/app authentication and it worked just fine.

**Comment by maroc81** [comment]
I'm seeing the same thing with version 1.32 on Mint 18.  Previously 2FA worked with with version 1.31 on Mint 17.3.

**Comment by averissimo** [comment]
Is this still a problem for those who reported it?

@maroc81 @tribbledt

**Comment by gregflynn** [comment]
Just downloaded YakYak 1.4.0 on debian stretch. Got a white screen after entering credentials, got my verification code and blindly entered it in on the white screen and authenticated. There were no errors in the inspector console.

**Comment by stdavis** [comment]
FWIW I'm having the blank screen issue when trying to authenticate via two-factor. But I'm not sure that it's the out-of-the-box two-factor that google provides. It might be something that my org has implemented. Here's the workflow:
![image](https://cloud.githubusercontent.com/assets/1326248/21996398/48584e4c-dbe7-11e6-8775-23ff35c401d9.png)
![image](https://cloud.githubusercontent.com/assets/1326248/21996406/4fa0df34-dbe7-11e6-9f58-3f5423932e4b.png)
![image](https://cloud.githubusercontent.com/assets/1326248/21996414/5cfda11c-dbe7-11e6-8f46-e04fcc5efecf.png)
![image](https://cloud.githubusercontent.com/assets/1326248/21996424/67e2c706-dbe7-11e6-885e-603463fc68f3.png)
![image](https://cloud.githubusercontent.com/assets/1326248/21996433/7894a808-dbe7-11e6-92b6-169ae2cf7d1b.png)
I don't see anything in the console...
![image](https://cloud.githubusercontent.com/assets/1326248/21996468/a2b22944-dbe7-11e6-993f-ef364faf399b.png)

**Comment by stdavis** [comment]
Here's what I have in that folder:
![image](https://cloud.githubusercontent.com/assets/1326248/22113910/0c8c4ee6-de25-11e6-8c56-0b231c951ee1.png)

I'd be interesting in helping get this working. I don't have a lot of time but if you point me in the right direction I can take a look.

**Comment by averissimo** [comment]
It seems to be missing a `refreshtoken.txt`, which just confirms that google authentication stops at one point _(thus: the blank window)_

Anyway, I can't reproduce this unless you can create a test account in that provider _(or equivalent)_

**Comment by wjcarpenter** [comment]
WFM on Ubuntu 12.04 with mate desktop. Normal inidividual gmail account.

(If anyone is still broken, have you tried using an application password that Google offers as an alternative for applications that don't support MFA? Not as good as a working MFA, but something.)

**Comment by stdavis** [comment]
I just tried again this morning and I was able to log in with my two-step google apps account! Not sure what has changed on our end or with the app.

**Comment by averissimo** [comment]
@stdavis I don't believe we changed anything that is related
