### ISSUE TITLE
Windows XP support?

### ISSUE THREAD

**Issue by Dimsok** [yakyak/yakyak#406]
I've downloaded the last version for Windows, but can't run (нет доступа). No access. Is it should work on Win XP?

**Comment by arnriu** [comment]
wtf is xp ? :)

Time to upgrade, there is no (and will never be) support for xp. Chromium has dropped support, and electron will never support it.

**Comment by PMiner** [comment]
yeah, @arnriu is correct. there is nothing the developers of YakYak can do about that.

**Comment by averissimo** [comment]
@Dimsok see here the electron team response: https://github.com/electron/electron/issues/5676

ps. electron is the ui framework we use in yakyak :)
