### ISSUE TITLE
Private avatar images broken

### ISSUE THREAD

**Issue by zachwood** [yakyak/yakyak#41]
If a user's avatar image is private it returns a 403 response, which displays as a broken image in the interface.

Here's the image, source, and google's response all crammed into one screenshot:

https://dl.dropboxusercontent.com/spa/wn0oryty1do7jho/u_df5zyp.png

**Comment by xori** [comment]
Yea I had this issue too, quick fix I found was logging out and logging in. Silly I know.

**Comment by zachwood** [comment]
Thanks xori, worked for me to. I'm going to close this issue.

**Comment by xori** [comment]
I dunno, personally I still think a better way to handle it would be to have some kind of yakyak default profile image.
