### ISSUE TITLE
Feature Request: Panels-Style Windows

### ISSUE THREAD

**Issue by ajayk111** [yakyak/yakyak#410]
Is there any way to add chat windows that can dock to the bottom of the screen like the current hangouts extension for Chrome does?

It would be really helpful for me to have since I usually need at least one panel open while I'm working, and I don't have a lot of real estate to have an entire window open.

**Comment by randymorris** [comment]
Duplicate of #370?

**Comment by averissimo** [comment]
have you tried using the option: "View -> Conversation List -> Show thumbnail only"

![image](https://cloud.githubusercontent.com/assets/211358/19244015/4576b1e0-8f12-11e6-9fec-78b87b5e9fa4.png)

**Comment by ajayk111** [comment]
Thanks for the fast reply,

That works, but is there anyway for me to dock the window and/or have multiple chats open at once?

**Comment by averissimo** [comment]
see @randymorris reply, as this issue is already being discussed in #370 with a tip on how to still do it after google's update.

**Comment by ajayk111** [comment]
Oh sorry, I guess this is a duplicate then.
Thanks for the help.
