### ISSUE TITLE
Emoji replacement inserts "undefined" for emjois that don't exist

### ISSUE THREAD

**Issue by randymorris** [yakyak/yakyak#412]
To reproduce, type `:test:<space>` in a message.  You should see `undefined<space>`.

This may just be a personal preference, but I think that if a replacement is attempted and none is found then the original text should be preserved.

Thoughts?

**Comment by averissimo** [comment]
confirmed it and corrected it with: #413

it was seeing everything with :...: as an emoji

and it did not handle it when it did not map to anything

corrected two other bugs:

1. when writing an :...: emoji (for instance :bank:) followed by a space in the middle of the input it did not place cursor correctly
1. in fact it was not replacing at all :)

ps. to test this pull request you also need to merge #403

**Comment by averissimo** [comment]
@randymorris can you confirm that #413 solves this?

**Comment by randymorris** [comment]
Unfortunately I didn't get an opportunity to test this.  I have actually stopped using YakYak for a few reasons unrelated to this.  If I get a chance I'll certainly test it but I'm sure you'll have it sorted by that time.

**Comment by averissimo** [comment]
looking forward for you return ;)

**Comment by averissimo** [comment]
included in 1.4.0 released
