### ISSUE TITLE
Emoticon stylized

### ISSUE THREAD

**Issue by capcla** [yakyak/yakyak#415]
Hello,
I've installed yakyak 1.3.2 on debian GNU linux.
From the version 1.3.1, i see stylized emoticon like in the attached

![screen](https://cloud.githubusercontent.com/assets/22839536/19392734/5b1f92d2-9232-11e6-9ec3-df4d650d226d.png)

**Comment by averissimo** [comment]
The font was removed from the package -_- and defaults to the system's font.

Anyway, I found the solution and is described in this comment: https://github.com/yakyak/yakyak/issues/132#issuecomment-242366680

- Install the `Noto Color Emoji` font
- Apply fix described in comment

A nice way to test if it works, is to open http://getemoji.com/ with chrome (if it works, then yakyak should also work)

**Comment by averissimo** [comment]
@capcla have you tried to install the font?

**Comment by Nefari0uss** [comment]
I'm currently having this issue; I'll test out the fix with the font.

**Comment by Nefari0uss** [comment]
Here's an imgur link of the result for me: [Imgur](http://imgur.com/f8TQvju)

**Comment by capcla** [comment]
I don't understand. I have created the file fonts.conf in ~/.config/fontconfig/
[code]$ fc-match 'Noto Color Emoji'
DejaVuSans.ttf: "DejaVu Sans" "Book"[/code]
And now?

**Comment by averissimo** [comment]
@capcla current v1.4.2 pre-release should have out of the box support for colored emoji

If you want to have it systemwide you also need to install noto color emoji from https://github.com/googlei18n/noto-emoji/
