### ISSUE TITLE
Emoticons shortcut support

### ISSUE THREAD

**Issue by jajabro1** [yakyak/yakyak#417]
I'd like to request emoticon shortcuts to be implemented. Google has already done this and I sorely miss the feature.

For example:
/shrug will output  ¯_(ツ)_/¯ when sent.

I mostly want the /shrug command, but other popular short cuts are tableflip and tableback.

Engadget has an article with a list of the shortcuts added in the previous Hangouts update.

**Comment by averissimo** [comment]
You can try implementing it by creating a pull request with:

1. Adding the commands and result to `src/ui/emojishortcode.coffee`
1. Add the pattern for the commands to `convertEmoji` method in `src/ui/util.coffee`

**Comment by averissimo** [comment]
A valid pattern would be `/\/[a-zA-Z]+/`

- after '/' does it contain only letters or any numbers/special symbols?

If you can build a mapping of "commands" and "output" I can help implement this :)

**Comment by a-maas** [comment]
Hello. I just started using YakYak I am interested in this feature. I these hangouts "commands" frequently and miss them a lot. I can also help implement them once I get my head around the code. Any suggestions on implementation appreciated. Here's the mappings that @averissimo requested.

Hangouts only will run these commands if the forward slash is the first character, so a valid regex is something like: `/^\/[a-zA-Z]+/` (untested).

At the bottom I detailed the `/roll` command for rolling dice. This may be more complicated to implement, but I actually use this one frequently and is a fun feature.

`/algebraic`
| ( •◡•)| (❍ᴥ❍ʋ)

`/dealwithit`
( •_•)
( •_•)>⌐■-■
(⌐■_■)

`/disapprove`
ಠ_ಠ

`/facepalm`
(－‸ლ)

`/flowerbeam`
(  ・◡・)つ━☆🌸🌺🌼

`/happy`
ᕕ( ᐛ )ᕗ

`/lgtm`
👍 👍 👍

`/lit`
🔥 🔥 🔥

`/octodisco`
🎶🐙🎶

`/puppyparty`
🐕🐩🐕🙌🐩🐕🐩

`/shame`
🔔 🔔 🔔

`/shrug`
¯\_(ツ)_`/¯`

`/success`
(•̀ᴗ•́)و ̑̑

`/sunglasses`
( •_•)
( •_•)>⌐■-■
(⌐■_■)

`/tableback`
┬─┬﻿ ノ( ゜-゜ノ)

`/tableflip`
(╯°□°)╯︵ ┻━┻

`/that`
(☞ﾟヮﾟ)☞

`/this`
☜(ﾟヮﾟ☜)

`/wizard`
(∩ ` -´)⊃━━☆ﾟ.*･｡ﾟ

`/yuno`
ლ(ಠ益ಠლ)

**Others**
`(Y)` or `(y)`
👍

`(N)` or `(n)`
👎 

`/roll`
/me rolls a die and gets 3.

`/roll 2d20`
/me rolls 2d20 and gets 13. [ 7 6 ]

`/roll d8`
/me rolls d8 and gets 5.

`/roll d1`
/me tries to "/roll d1" but Google can't find any double-headed coins.

`/roll d0`
/me tries to "/roll d0" but the dice never stopped rolling.

`/roll 329320d92308429384394`
/me tries to "/roll 0329320d92308429384394" but Google ran out of dice.
