### ISSUE TITLE
Smileys/Emoticons not displaying

### ISSUE THREAD

**Issue by Gibbz** [yakyak/yakyak#42]
The smileys and emoticons are not displaying in either the chat windows or in the chat headings. It just shows a small rectangle.

Also theres no button on the interface to add them either :)

**Comment by averrin** [comment]
I did it by two ways:
1. Add emoji font to css:
```
@font-face {
		font-family: "EmojiSymbols";
		src: url('css/EmojiSymbols-Regular.woff') format('woff');
		text-decoration: none;
		font-style: normal;
}
body {
    font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif, "EmojiSymbols";
}

But its too small and non-colored

2. I add ugly hack for EmojiOne support.
Its too bad for pull request, but if someone want to see it:
https://github.com/averrin/yakyak
(also added some hotkeys and dark theme design)

**Comment by Gibbz** [comment]
just noticed they have a dedicated site

https://hangouts.google.com/

**Comment by averrin** [comment]
I know, but Google products always have a horrible customization. I prefer dark design and vim-like shortcuts, but but its impossible if i use web-app=(

**Comment by davibe** [comment]
@averrin can you make something pretty we can merge ? :)

**Comment by averrin** [comment]
@davibe ok, i will try

**Comment by AdrianoCahete** [comment]
:+1:

**Comment by lernerd** [comment]
what about using this? https://github.com/twitter/twemoji

**Comment by Studioartcz** [comment]
Will be good :)
