### ISSUE TITLE
YakYak added a link to a random program in Windows Start Menu

### ISSUE THREAD

**Issue by Xodiced** [yakyak/yakyak#420]
I copied the YakYak unzipped folder and created a shortcut to it in the Start Menu.  So far I love not having to keep Chrome running in the background to use Hangouts, however I am wondering what toast.exe is and why a shortcut to it was placed in my Start Menu.  Launching it seems to do nothing.

Thanks.

**Comment by averissimo** [comment]
It seems to be the notification infrastructure for the popups to appear in windows environment. I could be wrong though, all I did was searching for `toast` and looking at toaster.js that has the code at the end of the comment

https://github.com/nels-o/toaster

```
/**
 * Wrapper for the toaster (https://github.com/nels-o/toaster)
 */
var path = require('path'),
    notifier = path.resolve(__dirname, '../vendor/toaster/toast.exe'),
    utils = require('../lib/utils'),
    Balloon = require('./balloon'),
    cloneDeep = require('lodash.clonedeep');

var EventEmitter = require('events').EventEmitter;
var util = require('util');

var fallback = void 0;

...(continue)...
```

**Comment by averissimo** [comment]
@Xodiced any more questions just re-open the issue
