### ISSUE TITLE
Toggle visibility with left click

### ISSUE THREAD

**Issue by HeikoTietze** [yakyak/yakyak#422]
This is likely a FAQ: right click the tray icon to find Toggle minimized is tedious. Please toggle by clicking the tray icon, and open the context menu on right click. 

It would also be nice to (optionally) hide also on close, like Thunderbird, Konversation, Qmmp just to mention a few I run. Exit could be available in the context menu.

**Comment by averissimo** [comment]
This is a duplicate on #338 and #397

It seems that left click is a limitation on linux, check @nerijus comment in #338

Regarding hiding when closing, there is a pull request with the implementation that fixes this #397

**Comment by nerijus** [comment]
Left click toggling is working on Linux now.

**Comment by averissimo** [comment]
I'm not experiencing that with my version based on current code and on Ubuntu. But maybe that's Ubuntu's default behavior :)

**The fix is not yet available in the latest release is it?**

**Comment by arvindvenkataramani** [comment]
+1 
Also, calling it 'Toggle minimize to tray' is very confusing. What it does is show or hide the window. So it should just say "Show chat window" or "Hide chat window" as appropriate, or even "Show/hide chat window" if it's going to be a single label. Settings are toggled, and window visibility is not a setting, so using the "toggle" language is misleading.

**Comment by HeikoTietze** [comment]
The request is not about renaming labels. It should exactly do what it is labeled: toggle, and that per left click.

Since some say it work, the issue depends maybe on the window manager and how the system tray is being handled (https://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/). 
The problem is also relevant for other tools like Thunderbird where the icon disappears from tray when the app is shown. But closing hides it into the tray and left click shows, which is a better solution than the left/right click headstand.

Running Arch based LXQt here should be bleeding edge ;-).

**Comment by nerijus** [comment]
https://github.com/yakyak/yakyak/pull/388 - this fixes left click toggling on Linux (Fedora). It is not in the latest release yet. @averissimo, does it work on Ubuntu?

**Comment by averissimo** [comment]
Not in Ubuntu with Unity desktop. Although I think it may be a Unity restriction.

I'm running with your PR merged for a while and it never worked.

p.s. I believe I only have two other changes to the trayicon, but neither should interfere.

**Comment by averissimo** [comment]
Yup, it's a Unity only problem, it works on Gnome as expected.

This fix will be available in upcoming v1.3.4

**Comment by averissimo** [comment]
@arvindvenkataramani create a new issue for renaming the label (I already have the code for it)

**Comment by Shuino7** [comment]
I'm seeing this same problem on Win10 (64-bit) with both 32 and 64 bit clients.

Single or double left click on the tray icon or does nothing.

**Comment by averissimo** [comment]
The fix that solves this is not in 1.3.2 or 1.3.3, it is still in the development code and should be released in the next version.

**Comment by averissimo** [comment]
included in 1.4.0 released

**Comment by HeikoTietze** [comment]
Well done (running 1.4.1 from git). To maximize UX you could add a separator to the context menu after the first "Toggle minimized" entry (and perhaps also before Quit).

**Comment by mguare** [comment]
Sorry but, i have a same "bug" in linux mint 18.1 - KDE 5.8.5

Left click, dont restore the window, only can restore when i do right click and choose "Toggle minimized to tray"

How i can fix it?

**Comment by HeikoTietze** [comment]
Left click in systray works for 1.4.0 under LXQt but not when I run Plasma (KDE). So it might be not Yakyak what is to blame.

**Comment by mguare** [comment]
Yes, I guessed it.
Does anyone know how to fix it?  :(

**Comment by averissimo** [comment]
This is something that is window-manager dependant, I can't use it in Unity, but gnome, xfce, mate works fine :\

**Comment by mguare** [comment]
ok ;(

i'll try find that use this software in kde

Thanks for all!!

**Comment by averissimo** [comment]
If you find a workaround please let us know!!

In unity at least, I think the default action is to right click, regardless os which mouse button you use.
