### ISSUE TITLE
after login, blank in KDE-Neon

### ISSUE THREAD

**Issue by v-cycl3** [yakyak/yakyak#425]
![screenshot_20161025_202014](https://cloud.githubusercontent.com/assets/10367285/19710063/20adace8-9af1-11e6-8b18-304a417f0750.png)

`./yakyak
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
`

Why occur this? using yakyak 1.3.3 x64

**Comment by averissimo** [comment]
Can you open the inspector by clicking the `YakYak -> Open inspector` menu entry?

It will open a window that has a `console` tab, click on it and check if there is an error. If there is and you can print it here, maybe we can help :)

**Comment by averissimo** [comment]
@v-cycl3 can you test version 1.4.0-beta3? see #451 to download it

**Comment by averissimo** [comment]
closing for lack of feeback
