### ISSUE TITLE
Chat log export

### ISSUE THREAD

**Issue by ckald** [yakyak/yakyak#427]
Original Google Hangouts app do almost nothing to prettify the log being copied from the window. This basically happens because of the HTML — the userpics are getting copied along with absolutely stupid message timestamps in a format "Now" or "7 mins".

YakYak goes even further and I personally get userpics about 300 px large on Mac OS and no message times of delimiters between messages.

How hard would it be to implement a formatted export of the chat log from the client window? 

I imagine this feature can be implemented on the markup level:
- absolute datetimes for the messages can be added with display:none — they would nevertheless be copied properly
- userpics and other unnecessary for the text log elements should not be possible to select
- other markup should be as simple as possible not to provoke selection jumps.

What do you think?

**Comment by davibe** [comment]
I think if someone works on this, then it's going to happen :)
