### ISSUE TITLE
Minimize to tray/start minimized

### ISSUE THREAD

**Issue by Georgeto** [yakyak/yakyak#43]
It would be awesome, if it was possible to minimize yakyak to tray, and hide it from taskbar while being minimized. In combination with that feature, a 'start minimized' option would be handy.

**Comment by algesten** [comment]
None of the more active devs have currently windows as their main platform. This project could really do with someone helping out on that side.

**Comment by Georgeto** [comment]
I've tried to implement it by myself, but it didn't work out as expected. The problem is hiding the window from taskbar. I've done it through calling mainWindow.hide() on minimize event, but immediately after the window is hidden, it pops up again, but without content.

*main.coffee*
```coffee
...
Tray      = require 'tray'
...
tray = null
...
app.on 'ready', ->
    ...
    mainWindow.on 'minimize', ->
        tray = new Tray path.join __dirname, 'icons', 'icon.png'
        mainWindow.hide()
```

![blackyakyak](https://cloud.githubusercontent.com/assets/9250103/9179779/1278ddd6-3f9f-11e5-8071-72afcd01be03.PNG)

**Comment by maxkueng** [comment]
Linux has trays too (sometimes) and as far as I know (but I'm not sure) the OS X Dock basically acts as a tray because on OS X apps typically don't really exit when you close the window. But I may be talking nonsense.

Yes, would be nice if more Windows people came to help out.

**Comment by maxkueng** [comment]
@Georgeto: I'm not sure if the `minimize` event is the right place to hide the window. I think the regular minimize (to taskbar) and minimize to tray should be treated as different things.

Typically, apps that support tray icons do it as follows:

 - The minimize button in the window  title bar minimizes the window to the taskbar just like any other window.
 - Clicking the tray icon toggles window visibility and when hidden it also disappears from the task bar. When shown it also reappears in the task bar.
 - There is an setting/option whether to just minimize to tray when closing the window (through "×" button in the window title bar), or whether to actually exit the app. It's often labeled as "Keep running in the system tray when closed". Minimize to tray is usually the default.
 - Right-clicking the tray icon usually opens a context menu that offers additional functionality including showing the window if it's hidden, hiding it if it's visible, and actually exiting the app.

**Comment by Georgeto** [comment]
@maxkueng: It was just a quick test, that I have done to play around with the tray object. The behavior  you described is exactly what I requested and its a shame, that I did not described it in such detail.

**Comment by maxkueng** [comment]
Cool, I'm excited to see the result! If you need someone to try it out on Linux let me know. I do have a tray :)

**Comment by abhigenie92** [comment]
Did this work?
