### ISSUE TITLE
Tray icon not turning green when a new message arrives

### ISSUE THREAD

**Issue by Samanm** [yakyak/yakyak#432]
Current behavior in Mac OSX (El Capitan):

When there is no new message, the icon displayed is 
![osx-icon-read-template 2x_old](https://cloud.githubusercontent.com/assets/863113/19945921/75abb820-a0ff-11e6-9b2d-ee7809aaa91c.png)

When a new message arrives, the icon turns into a solid back icon (without the "Y" letter)

Expected: 
The try icon should turn  into
![osx-icon-unread-template 2x](https://cloud.githubusercontent.com/assets/863113/19946029/efd19336-a0ff-11e6-8f11-94add27ced00.png)

**Comment by averissimo** [comment]
@Samanm Could you try to find the folder in YakYak installation: `resources/app/icons`

Are there the png files named osx-icon-unread* all black?

Can you try and replace the osx-icon-unread* with icon-unread* (equivalent) and see if they turn to green with 'Y'?

ps. I'm not a Mac user so my help here is limited

**Comment by averissimo** [comment]
@Samanm does this continue to appear in 1.4.0 latest beta? see #451

**Comment by Silveran** [comment]
I tried, here what I got...

Without modification without unread messages 
<img width="34" alt="screenshot 2016-12-05 a 02 14 04" src="https://cloud.githubusercontent.com/assets/10518880/20871000/050db4fa-ba91-11e6-9c76-f5cf6a293edc.png">

Without modification with unread messages
<img width="28" alt="screenshot 2016-12-05 a 02 14 11" src="https://cloud.githubusercontent.com/assets/10518880/20871003/0e4b8196-ba91-11e6-99bb-77f13e09e04d.png">
 
After modification with unread messages
<img width="23" alt="screenshot 2016-12-05 a 02 16 32" src="https://cloud.githubusercontent.com/assets/10518880/20871009/1a75ee8e-ba91-11e6-8915-e8ddb8c62098.png">

**Comment by averissimo** [comment]
what do you mean modification?

**Comment by smkent** [comment]
I'm also experiencing this bug, using yakyak version 1.4.2 on Linux (both Linux Mint 17 and 18, binary compatible with Ubuntu 14.04/16.04, respectively).

If I have unread messages when I start yakyak, the tray icon is green and changes to gray when I read all of the unread messages (correct behavior).

If I have no unread messages when I start yakyak, the tray icon is gray (correct behavior).

If I receive a new message after yakyak is running, the icon does not change from gray back to green (bug).

**Comment by averissimo** [comment]
@smkent can you open a new bug with this information?

I believe I am also experiencing the same bug but this is a different issue __that will be closed due to lack of feedback__

**Comment by smkent** [comment]
> can you open a new bug with this information?

Filed as #566.
