### ISSUE TITLE
Menu icon in "Dark" color scheme is not clearly visible 

### ISSUE THREAD

**Issue by ashergarland** [yakyak/yakyak#433]
Dark theme
![yakyakissue](https://cloud.githubusercontent.com/assets/1329051/19981459/445b7178-a1bf-11e6-8fdd-cdb1dc401017.PNG)

Blue theme
![yakyakblue](https://cloud.githubusercontent.com/assets/1329051/19981504/744b4656-a1bf-11e6-9199-97340f6491fb.PNG)

If you selected the Dark theme then the Menu button is hidden. Should be visible like in the blue theme.

**Comment by averissimo** [comment]
This is fixed in pull request #437

Do you see any other problems in the dark color scheme?

**Comment by averissimo** [comment]
@ashergarland  you can test the fix in #445 beta version.

If it solves it please close the issue :)

Thanks

**Comment by averissimo** [comment]
1.4.0 released
