### ISSUE TITLE
YakYak should support hangout stickers.

### ISSUE THREAD

**Issue by Christoph-Harms** [yakyak/yakyak#438]
When I send a sticker in the Chrome app:
![bildschirmfoto 2016-11-16 um 12 52 19](https://cloud.githubusercontent.com/assets/17005834/20346297/93b63afa-abfb-11e6-87c4-9db1c1e87de3.png)

This is what YakYak displays:
![bildschirmfoto 2016-11-16 um 12 52 31](https://cloud.githubusercontent.com/assets/17005834/20346307/a0083916-abfb-11e6-85f6-8fa95b665838.png)

If possible, YakYak should also display those stickers. They are hosted publicly on googleusercontent.com.

Sincerely,
Christoph

**Comment by averissimo** [comment]
Can you confirm that version available at #445 (v1.4.0-beta1) solves this?

If it does, please close the issue :)

Thanks

**Comment by mattsigal** [comment]
Running the latest Beta2. Just tested sending a sticker in the Chrome app, and it did appear in YakYak :)

**Comment by averissimo** [comment]
1.4.0 released

**Comment by DavidJSmart** [comment]
Stickers created in the Chrome app are not visible in 1.4.3.  This report needs to be reopened.
