### ISSUE TITLE
Unable to switch languages with alt+shift

### ISSUE THREAD

**Issue by browseman** [yakyak/yakyak#439]
Linux Debian7 Xfce4.8
There is a problem when switching language with alt+shift combination. When the switch combination is pressed, the hidden menu is opened and the language is switched, but it's unable to continue writing unless you hide back the menu (which usually is opened with alt key).
Is there a way to have an option to disable this behavior of the hidden menu? Hope my explanation are sufficient.

**Comment by averissimo** [comment]
what's the full key combination? alt + shift + **??**

**Comment by browseman** [comment]
Only "alt+shift", there is no additional keys involved.

**Comment by averissimo** [comment]
does clicking on the three lines 'menu' work on setting it while yakyak keeps running?

this option is not permanent, but if this works maybe it could become permanent :)

**Comment by browseman** [comment]
I don't think I understand you correctly. But when I click on "three lines" button the menu is falling down. Then I was able to choose from it until I press some button of the keyboard. The "alt+shift" combinations does not simply open the menu but is like actually

**Comment by averissimo** [comment]
@browseman which version of yakyak are you using? my comments below are for 1.4.0-beta3

I tried installing xfce and can't reproduce this in my laptop with Xfce 4.12.3 (current version of xubuntu-desktop as of 17.04)

The point about the icon is that once I click on the "three stacked lines icon" the menu either permanently appears or disappears *(until clicked again)*. I believe this would be the same as having an option to always show the menu

Alt produces nothing (which I think is strange, as it should highlight the menu)

Alt + Shift produces nothing and doesn't switch keyboard languages, how do you go on setting this?

**Comment by browseman** [comment]
@averissimo - I'm using v1.2.5 (according to the version file in the prebuilt binaries that I've download).

My version of Xfce is a bit older version 4.8 as already mentioned in my first post, but I doubt that is the reason. Most probably the reason is in the older version of the app. I will try to test with the latest one.

This behavior with the "three stacked lines icon" does not work like you describe it with v1.2.5. But with pressing the:

- Alt key - only opens the menu
- Alt + Shift keys - opens the menu with first dropdown also opened.

I will give a feedback after test with the new/latest version.

**Comment by browseman** [comment]
I've tried with the latest version (git clone https://github.com/yakyak/yakyak.git). Currently the behavior of the "three stacked lines icon" is working as it should. The menu is constantly stay on or off regardless of the pressing of other buttons. The behavior of:

- Alt key - is changed, currently the single pressed alt key doesn't do any thing.
- Alt + Shift key - is not changed and still is opening the menu with the first dropdown also opened. 

For language change I'm using the following standard Xfce plugin "xfce4-xkb-plugin". Which is configured to change languages via Alt + Shift key, nothing unusual.

**Comment by iovd** [comment]
I have the same issue on Mint. Alt key does nothing, but Alt+Shift causes left menu opening and selecting first (YakYak) menu entry.

In the same time, SHIFT+Alt works as expected.

I used the latest versions of YakYak and Node.JS.

**Comment by averissimo** [comment]
@browseman as I can see you have a dev version working, can you run the command below and see if the problem also happens in the new window?

`npm run electron`  (without the app)

ps. @iovd feel free to do it too if you have the dev environment on your computer

**Comment by iovd** [comment]
Yes, Alt+shift causes the same reaction in the "empty" electron app.

Also, there is a dirty workaround to quick fix that issue: just add a new EMPTY menu entry is src/ui/views/menu.coffee:370, just like that:

`{
            label: 'Workaround'
 }`

This will cause selecting first entry, not opening it, so you can type in the text area free.

**Comment by browseman** [comment]
@averissimo - I'm unable to build the latest version from Master, here is the error what I have:
http://pastebin.com/4k88RQdk

**Comment by averissimo** [comment]
can you try using node v6? I think your version is too old for some of our modules (v0.10.29)

plus, the new `electron` dependency *(replacing `electron-prebuilt` that was deprecated)* requires an newer node version

![image](https://cloud.githubusercontent.com/assets/211358/21180979/86305920-c1f3-11e6-8925-a0588d57eb66.png)

**Comment by browseman** [comment]
I've manage to update the nodejs to v6. This time the recompile was successful. I've tried to execute:
npm run electron (without the app)

but the problem with alt+shift is persisting to exist. I will try the patch/workaround of iovd.

**Comment by browseman** [comment]
@averissimo + @iovd

**Comment by averissimo** [comment]
haven't got time to test the patch. __Does that interfere with normal way of calling menus?__ (using alt key to give focus to menu)

maybe we should open an issue in electron/electron instead as this is an upstream problem that can be patched

**Comment by browseman** [comment]
> Does that interfere with normal way of calling menus? 
IMHO - no, the menu is working normally, and the issue with change of languages is not present. I've been testing it for a few weeks with no troubles + the patch also work for the latest version from git.
