### ISSUE TITLE
Provide real 'appname' when creating notifications on linux

### ISSUE THREAD

**Issue by hoschi** [yakyak/yakyak#441]
At the moment all notifications have `appname` 'notify-send' which should be something like 'yakyak' so this notification can handled in a sepecific way. My use case to give them a special color to separate them from e.g. HipChat.

**Comment by averissimo** [comment]
can you figure out what arguments does function `notify` requires for this?

I believe the node module is `node-notifier`

And the code for notifications can be found at:

https://github.com/yakyak/yakyak/blob/master/src/ui/views/notifications.coffee

**Comment by averissimo** [comment]
solved with icon on #467 (already in 1.4.1)

in case options to hide icon, the notification says (via YakYak) after sender's name
