### ISSUE TITLE
Easily send gifs from Giphy

### ISSUE THREAD

**Issue by tylerzika** [yakyak/yakyak#442]
Be nice if there was a button you can click that searches giphy.com based on text you enter.

**Comment by averissimo** [comment]
seems cool :)

**Comment by wjcarpenter** [comment]
I agree. The only ways I have found to do it so far are pretty clumsy. (Maybe I just haven't found the non-clumsy way.) Cut-and-paste from giphy.com only gets the still image. To get the animation, I have to download to a file, and then drag that file into yakyak.

Anyone know any easier way?
