### ISSUE TITLE
Blank hangout window

### ISSUE THREAD

**Issue by martinbutt** [yakyak/yakyak#444]
I'm using the precompiled Darwin binary. I open the app, enter my Google credentials and am show a blank hangout window. There is a message that says connection, which disappears after a few seconds. Nothing loads after that.

The console has the following:
```
messages.coffee:100 Uncaught TypeError: Cannot read property 'current_participant' of undefined
version.coffee:26 YakYak local version is 1.3.3, released version is 1.3.2
2messages.coffee:100 Uncaught TypeError: Cannot read property 'current_participant' of undefined
```

**Comment by averissimo** [comment]
Can you try #445 and report if problem still appears.

If it does please open yakyak via command line (see screenshot below, should be similar) and copy the output here of both

- The console
- DevTools Console Tab

![image](https://cloud.githubusercontent.com/assets/211358/20606992/bd3aec50-b26c-11e6-9cc1-37ffcfba824c.png)

**Comment by martinbutt** [comment]
https://github.com/yakyak/yakyak/issues/445 works
