### ISSUE TITLE
Beta version 1.4.0-beta1 (for testing)

### ISSUE THREAD

**Issue by averissimo** [yakyak/yakyak#445]
### Please report all BUGS related to 1.4.0-beta here

Include a screenshot (or copy the messages) when reporting.

### Download: [1.4.0-beta1 is available in my repository through this link](https://github.com/averissimo/yakyak/releases/tag/v1.4.0-beta1)

It includes almost all the pull requests currently pending, so a lot of new improvements and bug fixes.

Please leave some feedback when you find a bug (I'm sure there are a some)

*edit:* working on all operating systems (Linux, Windows and MacOSX)

### New Features:

- [FEATURE] Embedded photos in chat messages (#407)
- [FEATURE] Image preview when pasting or adding images via selector (#398)
- [FEATURE] 'Help -> About' window (#423)
- [FEATURE] Add startup screen and fix window position on startup (#418)
- [FEATURE] Switching between hide window and clear input when pressing 'escape' key (#409)
- [FEATURE] Feature Request: Notification Privacy (#386 and #399)
- [FEATURE] Add "show popup notifications" option to tray (#393)
- [FEATURE] Debugging: All errors from main window are shown in command line (#426)

### Bug fixes

- [FIX] Fix on not fitting images in conversations list (#430)
- [Fix] menu icon in dark scheme (#433 and #437)
- [Fix] fallback to initials when thumbnail image not available #428
- [FIX] fix deploy.sh and add --no-zip option (#424)
- [FIX] Fix 'event.keyIdentifier' depreciation in favour of 'event.key' (#419)
- [FIX] fixes three bugs with emojis (#412 and #413)
- [FIX] menus had a typo 'getAccelarator' should be 'getAccelerator' (#403)
- [FIX] Make hide the window (close to tray) work on all platforms if "Close (#397)

### Experimental (now fully working)

- [Experimental] Shows who has seen each message group (#429)

**Comment by aPoCoMiLogin** [comment]
Really like the start up feature/fix! Looking forward with fix for #407

**Comment by averissimo** [comment]
Got positive feedback from all operating systems. If it was not working for you try again now.

Have fun and give some feedback

**Comment by averissimo** [comment]
There's an extra functionality that is not working 100%, but I'm using it everyday even if limited, activate it under `View -> Experimental -> Show seen status in messages`

It is still rough and only works when other participant starts typing or sends something

![outaxhiaojjbg](https://cloud.githubusercontent.com/assets/211358/20605266/6dd59f66-b262-11e6-98b9-60904d1f4494.gif)

**Comment by chasetb** [comment]
It's running really well on my computer (MacBookPro12,1 macOS 10.12.1 16B2657)

**Comment by aPoCoMiLogin** [comment]
On OSX cmd + v is not working..

Steps to reproduce:

- copy any text or image to clipboard
- try to paste it in text field via keyboard shortcut (no errors in inspector -> console)

it's working only via right click menu.

Also `About window` from #423 is opening randomly. Tell me if I should report it here or in separated issues/pr's.

Cheers

**Comment by averissimo** [comment]
Please continue to report it here.

**Comment by averissimo** [comment]
[Copy Paste in MacOSX]

**Can someone with MacOSX please try to replace file below** ( @aPoCoMiLogin , @pmusaraj )

`YakYak.app/Contents/Resources/app/ui/views/menu.js`

**with:** `menu.js` from here: [https://gist.github.com/averissimo/26..04](https://gist.github.com/averissimo/26ecec00fe55edf224d942c9124a904c)

And see if it solves

**Comment by averissimo** [comment]
and can you check if other shortcuts work (even withouth replacing the file)

Try one of these:

- Command+1 / Command+2 to change to conversation 1 / 2
- Command+Alt+I to open DevTools
- Command+Q to quit YakYak

**Comment by aPoCoMiLogin** [comment]
cmd+v still don't work at all, cmd+1/cmd+2 is working, cmd+alt+i is working, cmd+q sometimes is just hidding yakyak and have to close it via right click in dock and quit, otherwise is not quiting at all.

Tested before and after changes. Also there was no errors at all in devtools console.

**Comment by averissimo** [comment]
@aPoCoMiLogin can you try again with the new version in the gist

**with:** `menu.js` from here: [https://gist.github.com/averissimo/26..04](https://gist.github.com/averissimo/26ecec00fe55edf224d942c9124a904c)

*This one drops the `selector` attribute in favor of the generic `role` in the copy/cut/paste.. if it works then the whole menu actions for MacOSX must be replaced.*

**Comment by aPoCoMiLogin** [comment]
Sadly cmd+c/cmd+v still not working. In that release (changes from gist) also cmd+h (hide) just changed to cmd+m (minimize).

**Comment by averissimo** [comment]
In windows and linux the shortcut appears next to the menu.

Does it also appear in MacOSX? **if so, what does it show in the edit menu**

Example screenshot in Linux

 (_small note: only in MacOSX does the cut, copy and paste appear.. not sure why, but code was like this and don't want to change it_)

![image](https://cloud.githubusercontent.com/assets/211358/20625853/b224298e-b30d-11e6-9656-9b560470860d.png)

**Comment by averissimo** [comment]
ohhh c'mon!! That is so unpredictable :\

If you can try this last menu.js file, it has all the cases I can think of

from: [https://gist.github.com/averissimo/ba...1a](https://gist.github.com/averissimo/ba50e358432f2dea844b84d831c40a1a)

And test the following (big thanks in advance for doing this :) ):

- **please test Cmd+X** and see if the pastes the content outside YakYak
    - `Cut` menu item was removed.. this is what works in linux/windows

- **please test Cmd+C** and see if you can paste contents outside YakYak
    - `Copy` menu item was renamed to `&Copy` (following skypeforlinux code)

- **take a screenshot of the `edit` menu item.
    - `Select All` was renamed to `Selecta All` just to see if that part of the menu is really rendered
    - Two new menu items were added just to test if MacOSX detector is working as it should.

- Press Cmd+U and Cmd+T and screenshot the DevTools console
    - Just checking shortcuts are really working
    - *it should appear two lines in console that start with '[MacOSX]', please show here the contents of the DevTools console*)

ps. if none of this works then this will remain an open bug until a developer with MacOSX can figure this one out.

**Comment by aPoCoMiLogin** [comment]
CMD+X/CMD+C not working at all.

CMD + U: logs `Is it Darwin? true`
CMD + T: logs `Or is it: darwin`

screen of whole menu:

![menu](http://i.imgur.com/jXQqmvb.png)

also CMD+H is still working like CMD+M (minimize) and there are some differences between them in 1.3.3 and 1.4.0:

![1.4.0](http://i.imgur.com/adNMHjs.png)

![1.3.3](http://i.imgur.com/qk4iSeL.png)

> big thanks in advance for doing this :)

no problem!

**Comment by averissimo** [comment]
One last test please, after this I'm creating an issue in electron.

File: [https://gist.github.com/averissimo/9d...c5](https://gist.github.com/averissimo/9d6232b782a688de0f34360420e1cbc5)

This is my menu and it works on linux without an issue (it does not have any difference when rendering in darwin with code in file above)

![image](https://cloud.githubusercontent.com/assets/211358/20628843/58cc3706-b320-11e6-956c-fad60f6ab040.png)

Please only test "paste" and "copy"

![image](https://cloud.githubusercontent.com/assets/211358/20628857/792d48a0-b320-11e6-8b65-2078203241c1.png)

**Comment by averissimo** [comment]
Oh.. if it does not work, try the following line in the console and expand everything in the object

there should be two, use the last one

![image](https://cloud.githubusercontent.com/assets/211358/20629017/470dac10-b321-11e6-9517-8ccdf9fe7f71.png)

**Comment by aPoCoMiLogin** [comment]
Copy/Paste did get back and they are working! :D 

![copy & baste back again!](http://i.imgur.com/AlKdnjb.png)

but this time select all via CMD+A went away

inspector console:

![inspector console](http://i.imgur.com/YSsxtRU.png)

also CMD+H is still working like CMD+M

sorry for delay..

**Comment by arnriu** [comment]
@averissimo Hey, nice work here! Nice to see the yak is still alive :)

I have no time to work on the yak right now, so if you wish, you could try to include my previous work on links previews #448 to your beta, see if it works well. It's a cool feature, anticipated for a long time now.
Maybe I'll have time to tweak it and improve it later, implementing more than open graph for example, but without tests, I can't do more for now.

**Comment by averissimo** [comment]
@arnriu thanks!! happy to work on Yak :)

I've been using the links preview it for a while and found some possible issues with it.

Hadn't had a chance to comment again in the original issue, but will do it soon :) and if I can I'll also work on it as **I really like the links preview** :)

Hope you don't mind if now I'm focusing on this release as is to push forward the embed images that breaks core functionality

**Comment by averissimo** [comment]
**I've prepared beta2 with a full fix for MacOSX menus**, but again.. can't test it.

It would be awesome that someone could download the beta2 version and just confirm it works before 'releasing' it here.

[Download for beta2](https://github.com/averissimo/yakyak/releases/tag/v1.4.0-beta2) (again on my repository, sorry for that but I don't have permissions here)

ps. @aPoCoMiLogin don't appologize for the delay, it was really awesome and fast feedback :)

**Comment by aPoCoMiLogin** [comment]
@averissimo glad that I can help in app that I'm using every day!

About beta2:
CMD+C/CMD+V - are working
CMD+A - is working
CMD+X - is working
CMD+H/shift+CMD+A - are working

![edit menu](http://i.imgur.com/UBBVNP8.png)

![yakyak menu](http://i.imgur.com/mvSeZoJ.png)

only thing that need fix is (mostly after hide/CMD+H) popping up about window from #423 when CMD+H is used. Also the about window from #423 is not the same as from menu -> yakyak -> about:

![about window](http://i.imgur.com/DJrQir4.gif)

I think that this small about window is some kind of built in, which should be swapped with that new one from help -> about. If placement is for purpose, then CMD+H should not open it IMO.

Rest of it LGTM 👍

**Comment by mattsigal** [comment]
Just wanted to comment to say that copy/paste is definitely working again in Beta2. This issue was driving me crazy and I'm very glad I came upon this thread!

**Comment by averissimo** [comment]
@aPoCoMiLogin I'll switch the "about YakYak" with the new window as it is more complete.

I hope the issue with the shortcut is solved by this, I'll just replace the current binary and create another topic with beta2.

ps. great screencast!!

@mattsigal yay!! I just hope that it is obvious for people that download it that this is beta and is bound to have some problems (especially as there are major UI backend changes and I don't have a chance to test in MacOSX)

**Comment by mattsigal** [comment]
@averissimo Of course :) One never realizes how often they copy/paste using the keyboard shortcut until it stops working hahaha

**Comment by averissimo** [comment]
@aPoCoMiLogin @mattsigal  **just a quick question before trying to correct the about window**, 

-> what is the norm in terms of menu items in MacOSX, do they have both the "About <program>" in the main menu AND in help -> about.. or just one of them?

if so, which one?

ps. @mattsigal LOL

**Comment by mattsigal** [comment]
Most apps on OS X only have "About" in the Main Menu, not under "Help".

**Comment by aPoCoMiLogin** [comment]
@averissimo I'm fresh osx user so I'm not 100% sure if shortcut to about windo is in every app, but what I did notice that is most common place for it.

**Comment by averissimo** [comment]
Ok, thanks!!

**beta2 is updated by that logic**, download again to get it

(new about logic: only under the Main Menu and opening the "new" about dialog)

I'm going to close this issue and create a new one with beta2 link now

**Comment by averissimo** [comment]
forgot to ask, @aPoCoMiLogin can you check if the about window stopped appearing with cmd+h?
