### ISSUE TITLE
Command + C, Command + V for copy/paste in message field (Mac)

### ISSUE THREAD

**Issue by pmusaraj** [yakyak/yakyak#446]
Copy/paste keyboard shortcuts don't work in the app. I can't paste anything in the message field, and I can't copy any text using the keyboard. (I can do both using the right-click command menu)

I am using the latest beta 1.4.0.

**Comment by pmusaraj** [comment]
I cannot reproduce this on 1.3.2.

**Comment by averissimo** [comment]
Can you open the devtools, switch to the console tab and paste here the contents?

**Comment by averissimo** [comment]
@pmusaraj can you please move this conversation to #445 as this is about the beta version and not the current release.

Close this issue and we'll talk there.

**Comment by averissimo** [comment]
@pmusaraj solved in beta2, see #446

**Comment by pmusaraj** [comment]
Cool!
