### ISSUE TITLE
on openSuSE 12.3 : worked once, then never again

### ISSUE THREAD

**Issue by cnshht** [yakyak/yakyak#449]
...from a would-be new user (non-developer):

openSuSE 13.2  linux-0gub 3.16.7-48-desktop  x86_64

Had it running once, was working well.  Then trouble started, no difference w/
reinstall of 1.3.2 and then 1.4.0-beta1 :

Startup opens Google login dialog.  2-3 seconds later a 2nd dialog <2> 
opens on top of the first.  Loop opening new dialogs continues: 
<3>,<4>, 5>, etc.   I can drag a dialog box to new location to prevent it being repeatedly covered up by newly-opening dialogs,  then with quick cut/past ops, get username and PW into dialog.  Then fullscreen opens with Hangouts logo, w/ msg “not connected,” and progress-graphic indicates attempt to connect.  This screen also reloads itself in a loop of similar frequency to above.   Never connects, cannot proceed further.  Would like this desktop interface as an option to Google plugin….
Any ccomments/clues appreciated

Thx,   HTH

**Comment by averissimo** [comment]
@cnshht Thanks for reporting this, this is a big problem that has been reported before and really breaks the experience as you said

I really don't understand it as I never experienced it (with normal gmail and 2-step authentication)

It would be awesome if you could try 2 (independent) things

1. remove ~/.config/yakyak and try to connect again
1. install hangups (pyhton) and login via that interface

The instructions to install hangups are here https://hangups.readthedocs.io/en/stable/installation.html

The library used by yakyak to connect to hangouts is based on that one and I believe the login process there was updated recently

Yakyak login needs improvement and that may be the way.

**Comment by cnshht** [comment]
1. Removed /.config/yakyak, deleted the beta directory, unzipped v1.3.2 
again, then it worked.  Logged in & out several times and other than a 
few delays connecting during the first few times, it's working well for 
now.

2. I see that "hangups requires Python 3.3, 3.4, or 3.5...."  Is it 
enough to have libpython3_4m1_0 with interpreter python_2.7.12-3.1?
Sorry I'm an aged newb, not experienced with compiling source, which is 
all that's available from https://www.python.org/

OpenSuSE's repositories only have 2.7 interpreter
I'm willing to try compiling but will have to study/learn how, first....

**Comment by averissimo** [comment]
Don't compile it, yakyak worked without that directory. That was just in case yakyak alone didn't login.

It seems that once it has a 'bad' connect it can't or it's hard to get around it.

I guess I'll have to connect from scratch and hope one of them will have a problem to have a chance to replicate this.

this is probably a duplucate of #390, #333 and others

**Comment by cnshht** [comment]
ok, I looked at those, they differ in details.  For example my login dialogs were replicating/looping *without* entering any login info.   But you'd know better than I, whether those differences were just due to differing OS or something....  

  So as of now, with the minro workaround above, yakyak is working fine on openSuSE/12.3/KDE.  Token is doing the auto-logon,  I'm happy with it.  Thanks for responding.    I like having a freestanding desktop client option!

HTH

**Comment by cnshht** [comment]
After several days,  starting yakyak it attempts to auto-connect, fails,  then retries and fails, looping endlessly.  No way to break the loop and re-login.  
              Deleted ~/.refreshtoken.txt, no effect.  Deleted ~/.cookies.json, then got login dialog, entered login but then could not connect (same as before.)  Deleted entire  /.config/yakyak dir, no effect, logged in manually, ...no effect (same non-connecting loop.) 

 Noticed that launching by clicking launch-bar icon, I was starting 2 copies of the prog, so tried launching from the binary's dir, which avoids the 2-copies-start issue, but even after again deleting config dir and launching this way and logging in, same non-connect loop.       Deleted entire installation and config dir, re-extracted .zip, logged in, same non-connect loop.

Maybe something has changed at Google...?   I'm kinda bummed.  No more desktop client....

**Comment by averissimo** [comment]
On December 1st google changed the protocol and all past versions of YakYak are now in this loop.

Have you updated to officially released version 1.4.0 or 1.4.1?

If you already have this version, then can you try to open the DevTools (via YakYak menu or Ctrl+Alt+i) and see if any errors popup (they should be in red)

**Comment by cnshht** [comment]
Thanks for the heads-up!  1.4.1 (pre-release) creates an empty ~/.config directory and does nothing else, no gui initializes.
1.4.0 worked further: Google login done, then connected after some delay, "loading contacts" appeared, but then there was a blank dialog box, nothing worked, no conversations etc loaded.
I deleted the ~./config dir and tried again:  Logged in w/ Google dialog, then there was quite a delay (not connected.)  But on auto-retry, connection finally completed, then contacts and conversations loaded, and all seems ok...  But after quit and restart, auto-reconnect does not work...very well.  Long timeout, then 2-3 retries fail.   But then, after... 2-3 mins, it did connect and load chat data.  
I have no other trouble with my broadband connection, (which is ~ 18 Mbps down, 3 MBps up)
Here is the timing after 2nd Quit-restart:  
1st connect-attempt: ~2:23 (fail)
auto-retry #1: ~0:15 (fail)
auto-retry #2 : ~0:15 (fail)
auto-retry #3: ~0:18    -> connected, data loaded.  Total time to enable chat about 3 mins, 15 seconds from launch.  Not so nice.  But functional, after the first  ~/.config dir deleted, and these connect-delays.
HOWEVER, after another quit-restart, connection and loading was 2-3seconds.
Yet another quit-restart also connected and loaded in just a few seconds.    Okay, so far....

**Comment by cnshht** [comment]
If the dev tools can show useful info, let me know navigation to whatever display/view, I could post screenshots or copy-paste txt?

**Comment by averissimo** [comment]
I'd like ask you to start using the command line and watch if there are any errors appearing, toy example of what to expect:

![image](https://cloud.githubusercontent.com/assets/211358/20904994/e6b5f96e-bb39-11e6-80dd-80cb3620a6ed.png)

It will also show the interaction between yakyak and hangouts server.

**Comment by cnshht** [comment]
ok, I'm ignorant so it took me a while to add the right dir to my PATH, I'm thinking I should have just put a softlink in /usr/bin instead.  I'll try that next... but here's the terminal output on the first try, it took a couple mins but did end up connecting and loading data:
![yakyak-slow-connect](https://cloud.githubusercontent.com/assets/23747566/20912284/4e7cb504-bb3c-11e6-9a33-710e8ab73a72.jpg)

**Comment by cnshht** [comment]
I have discovered and reproduced something: if I start yakyak, the gui window pops up, with the "connecting..." animation, and it will sit there and not connect *unless I do a MOUSEOVER on the window.*  The instant I roll the mouse-pointer over the window, there is an error-connecting response in the terminal window and attempted reconnect if it has been a while since the gui window appeared.  IF I mouseover the window within the first few seconds after it appears (right after entering "yakyak" at the command line) it will connect and load data immediately!  This is reproducible, every time.  No mouseover on window, no connect.  If mouseover on the window right after initialization, connects quickly!

**Comment by averissimo** [comment]
this is reaaaaaaaaaaaaally strange to say the least, because as far as I know there's no requirement for mouse overs or clicking anything. I can't reproduce in unity, gnome or xfce :\

**but with this that you discovered, are you able to connect and using yakyak?**

with this appearing you should:

![image](https://cloud.githubusercontent.com/assets/211358/20929234/27f83e96-bbc1-11e6-8ae1-b6661d4cd7d3.png)

**Comment by cnshht** [comment]
Hi André,   I'm sorry... everything I wrote yesterday was true at the time.  But today, the app behavior changed.  I have the habit of installing system updates, maybe that had something to do with it; there have been relatively more of them just recently.  I wanted to set up a screenshot with various system-identifying info visible... The first time I ran yakyak from a terminal, it was just like yesterday.  The "connecting... ... ..." dialog sat there for over 5 minutes without any sign of action in the gui or the terminal.  But then after opening various info-windows for the screenshot, then opening yakyak from a fresh terminal window again, (with no mouseover or keyboard input), it connected and loaded data immediately.  (Talk about mixed feelings....)    I have no explanation for the success.  And then, after quitting/restarting, the problem recurred.  The "connecting..." dialog sat there again for an extended period with no change/progress or events reported in the terminal.  Then with a mouseover, suddenly a bunch of info dumped into the terminal (as if it had been cached somewhere but held back...?)  ...and yakyak connected and loaded data.     My output from uname used to report "Harlequin", now it says "SMP PREEMPT", could this have something to do with it? :
https://rt.wiki.kernel.org/index.php/RT_PREEMPT_HOWTO       
I'll go ahead and post the screenshot showing the most recently described connect-delay, but...
I guess this is some kind of transient/intermittent problem, maybe just in KDE (?) that would be very hard to track down,  may not have any significant bearing on your yakyak development, etc.    So I guess I'd better quit sending it at you.     At this time, yes, I can start and use yakyak 1.4.0 quite reliably, whether it takes a mouseover/keyboard trigger or not.  So, thanks for your work on it.  
-Harold
![yakyak-slow-connect1](https://cloud.githubusercontent.com/assets/23747566/20940530/1c1b9410-bbc1-11e6-91c6-ea13e4a0a4c0.jpg)

**Comment by averissimo** [comment]
Dude!! I got the same behavior yesterday!!

As you said, it hangs on "Connecting" and when mouse hoovers the window that error appears.

**Comment by cnshht** [comment]
So at least now it seems like I'm not just making stuff up!  Meanwhile, Last 2 times I've started it, it's connected/loaded everything *without* any triggering mouse/keyboard event.  There was another kernel update within the last 24 hours from my distro (OpenSuSE).  Maybe it actually is some kind of kernel-related thing.  Keep an eye on your updates and see if it resolves by itself on your system, too...?
