### ISSUE TITLE
Sending Multiple Photos/Images

### ISSUE THREAD

**Issue by mattsigal** [yakyak/yakyak#450]
I've been using YakYak for a while now (on OS X, 10.11.6), and come across an issue that I do not believe is open yet. 

Basically, when I use the "Attach Image" function, it works perfectly. The choose file dialogue appears, I select the image, and it uploads/attaches without issue.

However, if I switch conversations and try to send the same image to another friend, I click "Attach Image", the dialogue box appears, and I can select the image... but then nothing happens. It doesn't actually upload/send.  If I quit YakYak and restart the app, I can again send one image.

This issue has been present for me since at least 1.2.0, and I've recently replicated it on 1.3.1, 1.3.2, 1.3.3, and the latest Beta2.

**Comment by averissimo** [comment]
great catch, simple fix in soon to be available beta3 (as soon as it uploads)

**Comment by averissimo** [comment]
1.4.0 released
