### ISSUE TITLE
1.4.0-beta3 (for testing before release)

### ISSUE THREAD

**Issue by averissimo** [yakyak/yakyak#451]
### Please report all BUGS related to 1.4.0-beta3 here

Include a screenshot (or copy the console log) when reporting.

### Download: [1.4.0-beta3 is available in my repository through this link](https://github.com/averissimo/yakyak/releases/tag/v1.4.0-beta3)

It includes almost all the pull requests currently pending, so a lot of new improvements and bug fixes.

Thanks to @aPoCoMiLogin @chasetb @mattsigal for the help in MacOSX testing

### Difference to beta1 (see whole conversation at issue #445)

- Copy/Paste/Cut working on MacOSX
- Native about window problem solved, now calls on new "About" (MacOSX)
    - Help menu item is removed from MacOSX
- #450 
- About window is now created on demand instead of being pre-loaded at the beginning.

### New Features:

- [FEATURE] Embedded photos in chat messages (#407)
- [FEATURE] Image preview when pasting or adding images via selector (#398)
- [FEATURE] 'Help -> About' window (#423)
- [FEATURE] Add startup screen and fix window position on startup (#418)
- [FEATURE] Switching between hide window and clear input when pressing 'escape' key (#409)
- [FEATURE] Feature Request: Notification Privacy (#386 and #399)
- [FEATURE] Add "show popup notifications" option to tray (#393)
- [FEATURE] Debugging: All errors from main window are shown in command line (#426)

### Bug fixes

- [FIX] Fix on not fitting images in conversations list (#430)
- [Fix] menu icon in dark scheme (#433 and #437)
- [Fix] fallback to initials when thumbnail image not available #428
- [FIX] fix deploy.sh and add --no-zip option (#424)
- [FIX] Fix 'event.keyIdentifier' depreciation in favour of 'event.key' (#419)
- [FIX] fixes three bugs with emojis (#412 and #413)
- [FIX] menus had a typo 'getAccelarator' should be 'getAccelerator' (#403)
- [FIX] Make hide the window (close to tray) work on all platforms if "Close (#397)

### Experimental (now fully working)

- [Experimental] Shows who has seen each message group (#429)

**Comment by aPoCoMiLogin** [comment]
There are few things that is something wrong with them (at least on OSX).

--

First (more important) is error when yakyak is closed (CMD+Q or right click -> quit from dock), when started from terminal then this is shown:

```shell
$ ./Applications/YakYak.app/Contents/MacOS/YakYak 
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
Error on YakYak window:
 { columnNo: 17,
  error: {},
  lineNo: 143,
  msg: 'Uncaught TypeError: Cannot read property \'isFullScreen\' of undefined',
  url: 'file:///Applications/YakYak.app/Contents/Resources/app/ui/app.js' } 
--- End of error message in YakYak window.
Segmentation fault: 11
```
It not occurs all the time, on 10 attpemts it occurs 2 times. But still something is up with that.

--

Second is about window from #423 poping up after CMD+H on OSX. It pops when yakyak just started and CMD+H is used. Was wonder if something is triggering it, so edited `main.js` and added `console.trace` to check from where that trigger is coming from:

```js
ipc.on('show-about', function() {
      console.trace();
      aboutWindow.setMenu(null);
      return aboutWindow.show();
});
```
but this gots triggered only when menu about is clicked. This is how it looks like: https://goo.gl/photos/v8ZP5S7un2ukGMH4A

--

Third thing is something that I can't explain, did not found any html element responsible for it  https://goo.gl/photos/gCX3RGQUpEJB7FSg6 it show up only in material and dark color scheme.

-- 

Last thing is an error when there is no contact to show: 

```shell
$ ./Applications/YakYak.app/Contents/MacOS/YakYak
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
Error on YakYak window:
 { columnNo: 10,
  error: {},
  lineNo: 103,
  msg: 'Uncaught TypeError: Cannot read property \'current_participant\' of undefined',
  url: '/Applications/YakYak.app/Contents/Resources/app/ui/views/messages.js' } 
--- End of error message in YakYak window.
Error on YakYak window:
 { columnNo: 10,
  error: {},
  lineNo: 103,
  msg: 'Uncaught TypeError: Cannot read property \'current_participant\' of undefined',
  url: '/Applications/YakYak.app/Contents/Resources/app/ui/views/messages.js' } 
--- End of error message in YakYak window.
Error on YakYak window:
 { columnNo: 10,
  error: {},
  lineNo: 103,
  msg: 'Uncaught TypeError: Cannot read property \'current_participant\' of undefined',
  url: '/Applications/YakYak.app/Contents/Resources/app/ui/views/messages.js' } 
--- End of error message in YakYak window.
Error on YakYak window:
 { columnNo: 10,
  error: {},
  lineNo: 103,
  msg: 'Uncaught TypeError: Cannot read property \'current_participant\' of undefined',
  url: '/Applications/YakYak.app/Contents/Resources/app/ui/views/messages.js' } 
--- End of error message in YakYak window.
```

**Comment by averissimo** [comment]
wow, fantastic debugging skills!!

1. Solved by simpling checking if object actually appears.
2. Stopped pre-loading about window, let's see if this solves it
3. Can't reproduce it. Does it happen all the time? try uploading an image to see if it is a problem with the new uploading interface (when sliding on)
4. Solved it (although I believe this exception has no consequence)

Available in beta3, I just updated this issue to beta3 (no point on starting a new one)

ps. interesting that other than the about window all others were already existing bugs

**Comment by aPoCoMiLogin** [comment]
Well, my "luck" was involved :D just created new account and logged in, then found that 2 issues, which looks like are solved.

Can't reproduce that strange thing in textarea, so it might got solved or it was something on my side. Anyway good job on fixing it 👍

**Comment by cawka** [comment]
Today, the old and the beta versions (tried also the master branch) suddenly stopped working with the following error in console:

```
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed TypeError: Cannot read property 'length' of undefined
    at /Users/cawka/Downloads/yakyak/node_modules/hangupsjs/lib/init.js:125:20
    at _fulfilled (/Users/cawka/Downloads/yakyak/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/cawka/Downloads/yakyak/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/cawka/Downloads/yakyak/node_modules/q/q.js:796:13)
    at /Users/cawka/Downloads/yakyak/node_modules/q/q.js:556:49
    at runSingle (/Users/cawka/Downloads/yakyak/node_modules/q/q.js:137:13)
    at flush (/Users/cawka/Downloads/yakyak/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error connecting TypeError: Cannot read property 'length' of undefined
    at /Users/cawka/Downloads/yakyak/node_modules/hangupsjs/lib/init.js:125:20
    at _fulfilled (/Users/cawka/Downloads/yakyak/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/cawka/Downloads/yakyak/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/cawka/Downloads/yakyak/node_modules/q/q.js:796:13)
    at /Users/cawka/Downloads/yakyak/node_modules/q/q.js:556:49
    at runSingle (/Users/cawka/Downloads/yakyak/node_modules/q/q.js:137:13)
    at flush (/Users/cawka/Downloads/yakyak/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Anyway it can be fixed?

**Comment by averissimo** [comment]
google changed stuff -_-

I'm uploading a new 1.4.0 release.. but it will take some time

**If you want to test if this fix works** do the following in the master branch (or any other that was working)

- remove directories
    - node_modules/hangupsjs
    - app/node_modules/hangupsjs
- run `npm install` and `npm run gulp` to reinstall hangupsjs
- make sure you got the latest by
    - `grep -A 1 email node_modules/hangupsjs/lib/init.js`
    - output should be as image below

![image](https://cloud.githubusercontent.com/assets/211358/20781192/eb12090e-b778-11e6-8e0c-f2e78819c9d5.png)

**Comment by cawka** [comment]
Yeah, I understand that the core problem was google making changes.  

Thank you very much for addressing this issue quickly.  Your suggestion fixed the issue and I'm back to my normal workflow (yakyak really solved so many problems for me with hangouts).

**Comment by averissimo** [comment]
@cawka that's in which branch?

**Comment by averissimo** [comment]
can you paste here the block of code around line 73 of that file?

**Comment by cawka** [comment]
Tried with d37842f22b4e62923cda5c1db14ae3af36d6f502 commit of 1.4.0-beta4 branch from you repo. 

Here is value of viewstate.js around those lines:

```
switchInput: function(next_conversation_id) {
      var el;
      el = document.getElementById('message-input');
      this.messageMemory[this.selectedConv] = el.value;
      if (this.messageMemory[next_conversation_id] != null) {
        el.value = this.messageMemory[next_conversation_id];
        return this.messageMemory[next_conversation_id] = "";
      } else {
        return el.value = '';
      }
    },
```

Will try different branch(es) and report if it works.

**Comment by averissimo** [comment]
try with 1.4.0, i've just updated it

**Comment by cawka** [comment]
1.4.0 branch works! Thanks!

**Comment by averissimo** [comment]
yay! \o/

can you test one other feature?

- write something in the text area
- switch conversations
    - see if it cleared the text area
- switch back
    - see if it remembers the old text

**Comment by cawka** [comment]
Works.  Tried with several conversations.

**Comment by averissimo** [comment]
thanks :fist_bump:

**Comment by averissimo** [comment]
closing this issue as beta4 is out

see #464 or download latest pre-release from official yakyak
