### ISSUE TITLE
Archived group chat still shows in conversation list

### ISSUE THREAD

**Issue by Hongbo-Miao** [yakyak/yakyak#453]
I have archived an group chat, it does not show in the conversation list of web version Hangouts.
However, it still shows in conversation list of YakYak.

Thanks for the amazing app!

**Comment by jwhipp** [comment]
I am curious, how does Yakyak currently populate the chat list?   Seems that if I delete a chat it's gone, just not with archive.   I am wondering if Google exposes anything in the API that allows you to tell if a conversation is archived or active.
