### ISSUE TITLE
Feature Requests: port to UWP

### ISSUE THREAD

**Issue by livia-b** [yakyak/yakyak#459]
Have you considered to make a "Universal Windows Platform" release, too? 
Hopefully that would allow to use the application both on windows desktop and on windows phone. It seems to be possible to convert an electron app to UWP http://electron.atom.io/docs/tutorial/windows-store-guide/ , but I have no idea about other libraries. 
It should also be considered whether  possible to distribute the app as a download from github or if it's necessary to distribuite it via Windows store

**Comment by averissimo** [comment]
Seems cool :)

wanna try to do this?

this needs someone that has windows 10 installed and motivated :)

**Actually the first step is something that would be awesome to have overall**

![image](https://cloud.githubusercontent.com/assets/211358/20756999/998be0c6-b70c-11e6-846c-e035aa740a01.png)

**Comment by livia-b** [comment]
Unfortunately I don't have windows 10, I am interested as a user...  because I am one of the few people with a windows phone!

**Comment by averissimo** [comment]
I actually got interested in the package module and it will fulfill the step 1 of that page you sent.

It still requires someone to do the rest of the work.

ps. @livia-b LoL :)

**Comment by livia-b** [comment]
I've noticed now that this wouldn't work for phones 
"Another important limitation is that the compiled AppX package still contains a win32 executable - and will therefore not run on Xbox, HoloLens, or Phones."

**Comment by averissimo** [comment]
I'm glad that you like yakyak so much that you'd want it in your phone, but I guess it won't be possible in the near future :(

I'm closing the issue. if there is any change please reopen it :)

**Comment by averissimo** [comment]
by other change I mean "as soon as electron supports other UWP platforms"

I believe that is the only bottleneck at this point (that and having someone following the tutorial)

tutorial: http://electron.atom.io/docs/tutorial/windows-store-guide/
