### ISSUE TITLE
Connecting... Not Connected Loop

### ISSUE THREAD

**Issue by chefBrian** [yakyak/yakyak#463]
I am currently having an issue not being able to connect.  I am experiencing this on OSX as well as Windows using versions 1.3.2 and 1.4.0 - so I may be doing something wrong.

The application will open, I will type in my credentials, then it will say "Connecting...", then "Not Connected." This will loop as long as I keep the app open.

Thanks,
Brian

**Comment by averissimo** [comment]
@chefBrian google changed hangouts internal stuff :anger_emoji:

I'm uploading a new version that should be correct as I'm typing this :)

**Comment by chefBrian** [comment]
@averissimo you're fast! Thanks for the quick response!

**Comment by averissimo** [comment]
@chefBrian can you test the release here

https://github.com/yakyak/yakyak/releases/tag/v1.4.0-beta4

heads up I've been having problems creating binaries for OSX

**Comment by chefBrian** [comment]
@averissimo works great on macOS Sierra.  Thanks again!

**Comment by averissimo** [comment]
yay!
