### ISSUE TITLE
1.4.0-beta4 (works with connection problem)

### ISSUE THREAD

**Issue by averissimo** [yakyak/yakyak#464]
### Please report all BUGS related to 1.4.0-beta4 here

Include a screenshot (or copy the console log) when reporting.

### What's new since beta3

- **[MAJOR FIX] Google modified the protocol.** This version works with the new version
- [FEATURE] clears input when changing conversations, remembers when returns to it #76 #458
- [FEATURE] new packaging method
- [FIX] bad avatar and wrong initials #74

### What's new since beta1 (see whole conversation at issue #445)

- [FIX] Copy/Paste/Cut working on MacOSX
- [FIX] Native about window problem solved, now calls on new "About" (MacOSX)
    - Help menu item is removed from MacOSX
- [FIX] Send same image to two contacts in a row #450 
- [FIX] About window is now created on demand instead of being pre-loaded at the beginning.

### New Features:

- [FEATURE] Embedded photos in chat messages (#407)
- [FEATURE] Image preview when pasting or adding images via selector (#398)
- [FEATURE] 'Help -> About' window (#423)
- [FEATURE] Add startup screen and fix window position on startup (#418)
- [FEATURE] Switching between hide window and clear input when pressing 'escape' key (#409)
- [FEATURE] Feature Request: Notification Privacy (#386 and #399)
- [FEATURE] Add "show popup notifications" option to tray (#393)
- [FEATURE] Debugging: All errors from main window are shown in command line (#426)
- [FEATURE] clears input when changing conversations, remembers when returns to it #76 #458
- [FEATURE] new packaging method

### Bug fixes

- [MAJOR FIX] Google changed protocol
- [FIX] Fix on not fitting images in conversations list (#430)
- [Fix] menu icon in dark scheme (#433 and #437)
- [Fix] fallback to initials when thumbnail image not available #428
- [FIX] fix deploy.sh and add --no-zip option (#424)
- [FIX] Fix 'event.keyIdentifier' depreciation in favour of 'event.key' (#419)
- [FIX] fixes three bugs with emojis (#412 and #413)
- [FIX] menus had a typo 'getAccelarator' should be 'getAccelerator' (#403)
- [FIX] Make hide the window (close to tray) work on all platforms if "Close (#397)
- [FIX] Copy/Paste/Cut working on MacOSX
- [FIX] Native about window problem solved, now calls on new "About" (MacOSX)
    - Help menu item is removed from MacOSX
- [FIX] Send same image to two contacts in a row #450 
- [FIX] About window is now created on demand instead of being pre-loaded at the beginning.
- [FIX] bad avatar and wrong initials #74

### Experimental (now fully working)

- [Experimental] Shows who has seen each message group (#429)

**Comment by joshdick** [comment]
Running on macOS Sierra here.

On startup, the console shows: `Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'. view.js: 126`

Upon trying to select any conversations (which does nothing), the console shows: ```
Uncaught TypeError: Cannot read property 'value' of null viewstate.coffee:56
switchInput @ viewstate.coffee:56
setSelectedConv @ viewstate.coffee:72
(anonymous function) @ dispatcher.coffee:103
doAction @ action.js:45
action @ action.js:21
onclick @ convlist.coffee:61
```

**Comment by aPoCoMiLogin** [comment]
Can confirm that app icon is default electron icon, but can't reproduce any of @joshdick error. Also the first error jest strange, because yakyak doesn't have any `view.*` file 🤔

**Comment by Strayer** [comment]
I also just updated from the latest version to the beta on macOS Sierra. Can confirm that the app icon is wrong, but otherwise everything is working fine for me! The console only shows some "attachment" messages from messages.coffee:372, no errors.

**Comment by aPoCoMiLogin** [comment]
Ok did recreate that errors from @joshdick simple try to delete any conversation, after that those errors show up. Login and logout did not fix it, clearing cache too. Looks like there is something up with viewstate.

**Comment by Silveran** [comment]
Hi, I'm just a fresh user of YakYak, congrats, I already love it...
Just some things, on the notification popup, I have sort of Terminal icon, I dunno if it possible to have the user pic or Yakyak icon (which, I confirm, is not an Y but an atomic representation)
<img width="76" alt="screenshot 2016-12-01 a 13 26 46" src="https://cloud.githubusercontent.com/assets/10518880/20793944/d7886120-b7c9-11e6-909d-7dd26c80e507.png">

Other point, could it be possible to change the notification sound ?
Well, I have some others little evolutions to suggest, I don't know if I should create a new thread for each or not, just tell me.
Thanks to you all

**Comment by averissimo** [comment]
for the macOS users: had a bad path to the icon -_- new version in the release with correct icon, sorry about that.

@Silveran in specific, please check if the terminal icon still appears.. that should never happen

@joshdick @aPoCoMiLogin that one was supposed to be fixed in beta4. can you check now?

https://github.com/yakyak/yakyak/releases/v1.4.0-beta4

**Comment by aPoCoMiLogin** [comment]
@averissimo working again, grats on fixing it that fast 👏 also both icons are back.

**Comment by averissimo** [comment]
I'm starting to really dislike OSX ;)

**Comment by aPoCoMiLogin** [comment]
Well my first day with macbook was with trying to install ubuntu :D so I know that feeling, but I did used to it after few weeks. If you need any help with testing something on OSX just call me and I'll try to do my best!

**Comment by joshdick** [comment]
@averissimo Re-downloaded as recommended; the app icon is back and the app is working again, but am now seeing the terminal icon in notifications that @Silveran reported.

**Comment by Silveran** [comment]
@averissimo I switched the 2 files, it unfortunately didn't change anything 
If you need me to test anything on mac OS, just ask me

**Comment by averissimo** [comment]
@Silveran thanks for the feedback

can you try this to see if the yakyak icon replaces the terminal one?

https://github.com/averissimo/yakyak/releases/tag/test-icon

**Comment by Silveran** [comment]
@averissimo Yep, I now see Yakyak logo + tiny terminal ;)
<img width="85" alt="screenshot 2016-12-01 a 16 57 08" src="https://cloud.githubusercontent.com/assets/10518880/20800901/5ca4d27c-b7e7-11e6-8039-b1b1a514462f.png">

**Comment by averissimo** [comment]
Can you try the new version here?

https://github.com/averissimo/yakyak/releases/tag/test-icon

**Comment by averissimo** [comment]
it changes the appname to YakYak (not important for this), but also another option in Info.plist that will most likely make a difference (as @davibe pointed out :) )

**Comment by Silveran** [comment]
@averissimo No more the tiny terminal icon ;)
![test](https://cloud.githubusercontent.com/assets/10518880/20803648/35796ee8-b7f0-11e6-94ae-fe5a35251c82.png)

**Comment by averissimo** [comment]
Hell yeah!!!

I have a question with that screenshot. The Yakyak icon always appeared in the notification in OSX?

**Comment by Silveran** [comment]
Yes, when I receive a message, the notification popup always has the Yakyak icon as seen in the previous screenshot (no user pic).
The application in the dock pops with a red counter on it and the tray icon icon turns black
<img width="24" alt="screenshot 2016-12-01 a 18 11 24" src="https://cloud.githubusercontent.com/assets/10518880/20804030/a0aabe8c-b7f1-11e6-9882-c0c1b38ec2c2.png">
<img width="73" alt="screenshot 2016-12-01 a 18 11 17" src="https://cloud.githubusercontent.com/assets/10518880/20804029/a0aa385e-b7f1-11e6-8b27-727da3a0f08f.png">

**Comment by averissimo** [comment]
For what I learned with this so far is that user icons are only possible in osx 

other notification systems require a local path, osx can get it from the web

I'm thinking on really quick add the icon to all other os and user avatar in osx (with an option to disable)

what do you think?

**Comment by Silveran** [comment]
It would be great for us (Mac users) ;)
Hoping other OS will grant the permission too soon
I'll still be there for any further tests, don't hesitate

**Comment by averissimo** [comment]
@Silveran The binary is updated in the same location

This build should show the image if in fact OSX supports URLS as icons.

The only problem I currently have is that the options are not persistent (if you disable them they will be reset on the next application start)

**Comment by Silveran** [comment]
Unfortunately, still yakyak icon, not user pic...
I checked the parameter in the options, do I need to do a clean delete of the app ?

**Comment by averissimo** [comment]
nahh if you replace the icon assignment in the js file is enough

And test it with an user that actually has an image (initials do not work)

Can you test these replacing current icon line with: 
```
icon: fixlink(entity[cid].photo_url),
contentImage: fixlink(entity[cid].photo_url)
```

**Comment by averissimo** [comment]
if this doesn't work I guess support for urls does not really exist :\

that or someone with osx needs to figure this one out :)

**Comment by Silveran** [comment]
Can you tell me witch js file are you talking about ?

**Comment by averissimo** [comment]
LoL sorry

`YakYak.app/Contents/Resources/app/ui/views/notifications.js`

**Comment by Silveran** [comment]
It works !!!
<img width="366" alt="screenshot 2016-12-01 a 19 25 32" src="https://cloud.githubusercontent.com/assets/10518880/20806687/36cb18e4-b7fc-11e6-9409-1699ed2355c2.png">

Congrats !!!!

**Comment by DWhartenby** [comment]
Hey Team - Running 64 on Windows10 and yakyak connecting to not connected constantly.  I have reinstalled/rebooted multiple times with yakyak-1.4.0-win32-x64.

**Comment by averissimo** [comment]
@DWhartenby can I ask to open the inspector (menu `YakYak -> Open inspector`) and paste here the contents (you can filter out everything expect errors and warnings)

Please be sure to be running latest beta4 from the releases, link below

https://github.com/yakyak/yakyak/releases/tag/v1.4.0-beta4

**Comment by averissimo** [comment]
@Silveran YAY!!

Can you filter from the two lines which made it happen? `icon` or `contentImage`

**Comment by Silveran** [comment]
@averissimo `icon` put the pic on the left and yakyak in tiny mode
`contentImage` let yakyak on the left and profile pic on the right.

I prefer `contentImage` mode

**Comment by nerijus** [comment]
When trying to build the latest git:
$ npm run gulp

> yakyak@1.4.0 gulp /mnt/d/Linux/internet/IM/Electron/yakyak
> gulp

[23:03:50] Requiring external module coffee-script/register
module.js:471
    throw err;
    ^

Error: Cannot find module 'electron-packager'
  at Function.Module._resolveFilename (module.js:469:15)
  at Function.Module._load (module.js:417:25)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/mnt/d/Linux/internet/IM/Electron/yakyak/gulpfile.coffee:15:14)
  at Object.<anonymous> (/mnt/d/Linux/internet/IM/Electron/yakyak/gulpfile.coffee:1:1)
  at Module._compile (module.js:570:32)
  at Object.loadFile (/mnt/d/Linux/internet/IM/Electron/yakyak/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/mnt/d/Linux/internet/IM/Electron/yakyak/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Liftoff.handleArguments (/mnt/d/Linux/internet/IM/Electron/yakyak/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/mnt/d/Linux/internet/IM/Electron/yakyak/node_modules/liftoff/index.js:198:16)
  at module.exports (/mnt/d/Linux/internet/IM/Electron/yakyak/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.<anonymous> (/mnt/d/Linux/internet/IM/Electron/yakyak/node_modules/liftoff/index.js:190:9)
  at /mnt/d/Linux/internet/IM/Electron/yakyak/node_modules/liftoff/index.js:164:9
  at /mnt/d/Linux/internet/IM/Electron/yakyak/node_modules/v8flags/index.js:108:14
  at /mnt/d/Linux/internet/IM/Electron/yakyak/node_modules/v8flags/index.js:36:12
  at /mnt/d/Linux/internet/IM/Electron/yakyak/node_modules/v8flags/index.js:47:7
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at Module.runMain (module.js:606:11)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3


npm ERR! Linux 4.8.1-1.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "gulp"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! yakyak@1.4.0 gulp: `gulp`
npm ERR! Exit status 1

**Comment by mwillbanks** [comment]
@nerijus you need to run npm install first. You should just use the binaries on the 1.4.0-beta4 release.

**Comment by nerijus** [comment]
Yep. that was it, npm install helped.

**Comment by nerijus** [comment]
On Linux:
$ npm run deploy
...
Packaging app for platform win32 ia32 using electron v1.4.10
Packaging app for platform linux x64 using electron v1.4.10
Packaging app for platform darwin x64 using electron v1.4.10
Packaging app for platform linux ia32 using electron v1.4.10
Packaging app for platform win32 x64 using electron v1.4.10
Code sign failed; please retry manually. Error: Error in finding identities. See details in debug log. (electron-osx-sign:error)
  at yakyak/node_modules/electron-osx-sign/util-identities.js:49:29
...
Error: Error: rcedit.exe failed with exit code 1. Fatal error: Unable to load file
Created archive (yakyak/dist/yakyak-1.4.0-linux-x64.tar.gz)
...

IIRC there was no rcedit.exe error before.

**Comment by nerijus** [comment]
With latest git on Linux I too get Connecting... Not connected (check connection) constantly changing. What should I paste from inspector?

**Comment by averissimo** [comment]
If you want to package win32 you need wine

New module that creates binaries has that dependencies :/

`npm run gulp deploy:platform-arch` if you want a particular platform/arch

You need to remove all node_modules called hangupsjs and install it again (the connection fix is there and not in yakyak)

Then make sure init.js inside that library has the following string ds:36

Sometimes I also need to delete cached hangupsjs folders in ~/.npm

Sorry about these details, but we haven't got time to release official versions with correct numbering. We'll bump hangusjs version requirement in master and 1.4.0 branch in a short time to make this transparent for all developers. I did this last night waaaaaaayy to late and made some mistakes for others that are also developing (which is awesome to have btw)

**Comment by nerijus** [comment]
I have wine, but no rcedit.exe:
$ wine rcedit.exe
wine: cannot find L"c:\\windows\\system\\rcedit.exe"

$ locate rcedit.exe
(empty)

**Comment by averissimo** [comment]
I have it inside the node_modules

![image](https://cloud.githubusercontent.com/assets/211358/20813814/0bae60fe-b80f-11e6-8062-cb7717c5f800.png)

ps. I was using find . | grep <name of file> to search for files.. this is much better :)

**Comment by nerijus** [comment]
OK, I have node_modules/rcedit/bin/rcedit.exe. But npm run gulp deploy:win32-x64 shows:
Packaging app for platform win32 x64 using electron v1.4.10
Error: Error: rcedit.exe failed with exit code 1. Fatal error: Unable to load file

**Comment by averissimo** [comment]
both master and 1.4.0 now have as dependency the hangouts module version 1.3.3

npm repository version has been updated :)

please perform a `npm install` with current master/1.4.0 branches (the only difference from 1.4.0 to master is a pending PR that is being tracked in #74)

**Comment by averissimo** [comment]
can you try something for me?

remove the block below from `gulpfile.coffee`

```
    win32metadata: {
        CompanyName: 'Yakyak'
        ProductName: 'Yakyak'
    }
```

**Comment by nerijus** [comment]
The same - Error: Error: rcedit.exe failed with exit code 1. Fatal error: Unable to load file

**Comment by averissimo** [comment]
maybe packaging the app like this wasn't the best idea in the world.

what's your version of wine? >= 1.6 ?

**Comment by nerijus** [comment]
wine-1.9.23-2.fc25.x86_64

**Comment by averissimo** [comment]
I think someone had your problem here

https://github.com/electron-userland/electron-packager/issues/519#issuecomment-257101172

Can you try to install a 32-bit wine? (maybe rcedit.exe requires 32-bit)

**Comment by averissimo** [comment]
actually I don't think you need 32-bit wine, just a 32-bit configuration.

I have it by default in my laptop to avoid problems

**Comment by averissimo** [comment]
https://wiki.archlinux.org/index.php/Wine#WINEARCH

**Comment by averissimo** [comment]
and it seems like you do have to install it

**Comment by nerijus** [comment]
My default wine is 32 bit. But I am building win32-x64, so 64 bit wine prefix worked:
WINEPREFIX=~/.wine64 npm run gulp deploy:win32-x64

**Comment by nerijus** [comment]
But npm run gulp deploy:win32-ia32 still did not work with my wine 32 bit prefix, but worked with 64 and another 32 bit prefix dir. So it was a problem with my default wine prefix, sorry for the false alert.

**Comment by averissimo** [comment]
no problem, nevertheless this is helpful information!!

And publicly available for the next girl/guy that searches for the error :)

**Comment by averissimo** [comment]
@Silveran can you test this build for the user's image in avatar

@nerijus can you test the build with my branch `feature-notifications-icon-and-sound`

It supports the yakyak image in notifications (linux) and a custom sound being played when the notification system does not support it

(it was bothering me for a while now not having this)

All this is configurable in the view options

**Comment by Silveran** [comment]
@averissimo works great ;)
<img width="369" alt="screenshot 2016-12-02 a 01 09 56" src="https://cloud.githubusercontent.com/assets/10518880/20818174/49b14e3a-b82c-11e6-9529-b396ce88bc59.png">

**Comment by averissimo** [comment]
@Silveran Pull request submitted #467

Again! thanks for all the testing :)

**Comment by Silveran** [comment]
You're welcome ;) Thanks for all your work !

**Comment by Silveran** [comment]
@averissimo Just a new issue, it seems that the tray icon is impossible to activate... When I click on "Show tray icon", nothing happens

**Comment by averissimo** [comment]
That was working before?

There's a crazy circular logic there :\

Is "Hide Dock Icon" activated?

**Comment by Silveran** [comment]
Yeah, that was working this morning.
`Hide` doesn't appear, because `Show` doesn't do anything...

I tried to make a fresh install to test, but the release isn't available anymore, can you give it to me again ?

**Comment by Silveran** [comment]
Ok, I got the release...
Some weird stuffs...

At the first launch this morning, I logged in Gmail and Yakyak launched for the first time.
My contact list opened well but the messages zone was empty.
I was able to avoid this issue (discovered randomly) by selecting `Show seen status in messages`, close and reopen YakYak (my brother had the same issue on his mac).
This morning, Tray icon was ok.

Tonight, I just made a fresh install, still the problem with empty messages zone (same method to avoid this issue), and now tray icon can't show anymore.

(it's a little bit late now, not sure to be very clear)

**Comment by averissimo** [comment]
It is available now.

These are the conditions to change Show Tray and Hide Dock Icon

- "Show tray" is only available to change if "Hide Dock Icon" set to false
- "Hide Dock Icon" is only available to change if "Show tray" is set to true

I don't think there's a situation when you can't change both. This crazy logic should work in order to always either have tray or dock or both, but never none of them

**Comment by Silveran** [comment]
I just retested.
Still have weird behaviors...
<img width="257" alt="screenshot 2016-12-02 a 02 19 57" src="https://cloud.githubusercontent.com/assets/10518880/20819625/de5cdd8e-b835-11e6-80e1-8bcbc72e7c29.png">
When I click on `Show tray icon` : Nothing never happens (no tray icon, no change in the menu)
But I clicked on `Hide dock icon` : It was hell !!! Impossible to access the menu, neither close the app, I had to kill it via Terminal... And reinstall it totally. I suggest you to remove this option on Mac, it's very dangerous for casual Mac users...

**Comment by averissimo** [comment]
found the problem and I think at one point I changed the wrong function.. the one related with tray :\

Show tray should work as before.

regarding hidedockicon... can't really understand what happened there. It could work as normal since I reverted some code cleanup and now that show tray is corrected

Can you try to have you inspector window open before toggling the "hide dock icon" to see if anything comes up.

**Comment by Silveran** [comment]
@averissimo all works fine with your rollback... Tray icon is back and we can hide/show dock easily by tray ;)

**Comment by averissimo** [comment]
@Silveran by the way, the sound that you hear before and after disabling is the same as it was, right?

not the new one for linux and other notification systems that don't support sound notification

link here: https://notificationsounds.com/notification-sounds/you-wouldnt-believe-510

**Comment by averissimo** [comment]
it's just a simple confirmation, as some innocent changes keep coming back to bite me in the ass

ps. to me the zip sounded nothing like the custom one :)

**Comment by Silveran** [comment]
Sorry, I've got a new issue...
Looks like the bug at the new install and messages zone down. I just deleted a conversation, and I've got this now : 
<img width="947" alt="screenshot 2016-12-02 a 03 06 38" src="https://cloud.githubusercontent.com/assets/10518880/20820610/bf6c9796-b83c-11e6-96d8-6aa741f487e2.png">

Impossible to get messages zone back...
When I try to change the View (hide profile pics, timestamp, etc.) nothing happens, even after reload the app.
Should I try something for you before to reinstall the app ?
Here is the console log
<img width="793" alt="screenshot 2016-12-02 a 03 12 17" src="https://cloud.githubusercontent.com/assets/10518880/20820661/32e4f1be-b83d-11e6-8fc0-d1e2df428840.png">

**Comment by Silveran** [comment]
About the sound, I still have the same weird sound... It looks like a mac system sound named Bottle (hate it).
I still didn't get how to change this sound in YakYak, I'll try to figure out tomorrow ;)

**Comment by averissimo** [comment]
That's was awesome feedback, master is missing a commit!!

Just to be clear on something, this happened after you deleted a conversation?

(yeah bottle is the default sound, yakyak does not currently allow to have a custom sound, it is either the notification system default or yakyak current one -- if my latest pr is merged)

**Comment by Silveran** [comment]
I just tried again, same thing, messages zones disappear.
Here the fresh Console log (I just start the app and try to click on some profile pics)
<img width="796" alt="screenshot 2016-12-02 a 03 20 30" src="https://cloud.githubusercontent.com/assets/10518880/20820832/8073ecea-b83e-11e6-9b9f-40641df72c56.png">

Ah, sound seems ok so...
I'd prefer your yakyak sound ;)

**Comment by Silveran** [comment]
FYI, it seems to get back to normal only by receiving a message and restart the app... (just happened, and I retried several times)

**Comment by averissimo** [comment]
don't worry about it, it's already fixed.. just uploading it now

man you're really good at catching bugs :)

**Comment by Silveran** [comment]
And I just did a fresh install to get the initial bug again.
Here's the console log at the first launch of the app (with no message zone)
<img width="793" alt="screenshot 2016-12-02 a 03 28 07" src="https://cloud.githubusercontent.com/assets/10518880/20820990/82bc4e1a-b83f-11e6-88e9-c9ec71410473.png">

**Comment by Silveran** [comment]
I really enjoy your app, I was looking for it so long ;)
That's why...

So, time to sleep in France, see ya tomorrow

**Comment by Silveran** [comment]
Well done, it works now perfectly with the last release you just uploaded ;)
Fresh install works fine and I can delete a conversation without any problem...
Great job !!!!

**Comment by averissimo** [comment]
Not my app! @algesten and @davibe :) I'm just recently developing for it :)

Same problem here in PT ;)

If you want YakYak custom sound, find file named `notifications.js` and replace this line (only version the link you've been using has this)

`playSoundIn = ['WindowsToaster', 'NotificationCenter'];`

by

`playSoundIn = ['WindowsToaster'];`

**Comment by averissimo** [comment]
yay!! finally sleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeep

**Comment by Silveran** [comment]
By the way, I just changed the sound parameter, and I have now the YakYak notification sound, it's so better than the Bottle ugly sound ;)

**Comment by nerijus** [comment]
I am working with the latest git. If I run from the source dir npm run electron app, it works, but if I run binary:
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'hangupsjs'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/path/to/yakyak/dist/yakyak-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
...

**Comment by nerijus** [comment]
README.md states:
*note:* if you are building *Windows* binaries in *Linux* or *Mac OS X*, Wine (1.6 or higher) must be installed. It also requires a 32-bit Wine installation when building Windows 32-bit binary.

32 bit is not needed IMHO, as I used wine 64 bit prefix successfully.

**Comment by nerijus** [comment]
After  "npm install" directory node_modules appears.
$ npm run electron app

> yakyak@1.4.0 electron /path/to/yakyak
> electron "app"

Error launching app
Unable to find Electron app at /path/to/yakyak/app

Cannot find module '/path/to/yakyak/app'

After "npm run gulp deploy:linux-x64" app directory appears, and node_modules directory in it, but it has only 120 subdirs, while previous (upper) node_modules dir has 459 subdirs.

dist/yakyak-linux-x64 directory does not have any node_modules dir, nor in root neither in resources/app.

**Comment by averissimo** [comment]
@nerijus 

### APP directory

app directory is created with `npm run gulp` or `npm run gulp watch`

It's normal that node_modules has less subdirs, as there are modules only for development, such as `electron-prebuilt`, `electron-packager`, etc.. and their dependencies.

The following sequence of commands worked without problems for me.

```
$ git fetch origin
$ git checkout origin/master
$ rm -rf app/ node_modules/ dist/
$ npm install
$ npm run gulp && npm run electron app
```

### Hangups

I've had the hangupsjs problem before, npm get's stupid with stuff it has on cache. Try to delete all instance of hangupsjs from yakyak directory, and ~/.npm

What I had to delete at the time

```
$ locate -b hangupsjs
/home/averissimo/.npm/hangupsjs
/home/averissimo/.npm/_git-remotes/git-https-github-com-averissimo-hangupsjs-git-1-3-3-9864a132
/home/averissimo/.npm/_git-remotes/git-https-github-com-yakyak-hangupsjs-git-5373c835
/home/averissimo/.npm/_git-remotes/git-ssh-git-github-com-averissimo-hangupsjs-git-1-3-3-6ef3b2cf
/home/averissimo/.npm/registry.npmjs.org/hangupsjs
```

**Comment by averissimo** [comment]
@nerijus I'm adding this warning when building windows binaries outside windows, what do you think? :)

It appears only when building windows binaries outside windows

![image](https://cloud.githubusercontent.com/assets/211358/20842779/91369e3e-b8b0-11e6-9f61-254466b9dd39.png)

**Comment by averissimo** [comment]
regarding the sound, added an option to force custom YakYak sound even if notification system supports it :)

already in pull request #467 :)

(option only appears in systems that already have sound)

![image](https://cloud.githubusercontent.com/assets/211358/20846603/5c911cd8-b8c2-11e6-85cf-31b70036239d.png)

**Comment by averissimo** [comment]
1.4.0 released

**Comment by nerijus** [comment]
@averissimo, this works:

$ git fetch origin
$ git checkout origin/master
$ rm -rf app/ node_modules/ dist/
$ npm install
$ npm run gulp && npm run electron app

But if I do npm run gulp deploy:linux-x64 and try to run ./yakyak from dist/yakyak-linux-x64:
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'hangupsjs'
    at Module._resolveFilename (module.js:455:15)

Deleted whole /home/nerijus/.npm directory, did not help.

**Comment by averissimo** [comment]
Do you have the following structure in `./node_modules` AND `./app/node_modules` AND `./dist/yakyak-linux-x64/resources/app/node_modules`

- `hangupsjs`
    - `lib`
        - `client.js`

**Comment by nerijus** [comment]
First 2 - yes, but there is no node_modules directory in dist/yakyak-linux-x64/resources/app.

**Comment by nerijus** [comment]
Aha, it works if I run npm run gulp deploy:linux-x64 after npm run gulp.

**Comment by averissimo** [comment]
it should do everything needed, it has those dependencies so that we never deploy anything without being compiled. (for deploy only there are targets deploy:linux-x64**:nodep**)

It seems as gulp does not wait for dependencies to finish to start packaging, or not all targets wait for asynchronous methods to finish to mark as finish :\

this is a semi-bug that will have to be corrected when gulp 4 is released :)

how people find this bugs is beyond me but thanks a lot!!

**Comment by averissimo** [comment]
I said "beyond me" because I remember doing this on purpose when refactoring the packaging method and testing it.

**And now I just confirmed that it does not work!!**

I guess at the time I was using gulp4 that does not allow this, before reverting to current 3.9.1

**Comment by averissimo** [comment]
Can you guys confirm two behaviors I think I have corrected? 

@Silveran @nerijus and/or any other person that's interested :)

1. If opened long enough, or a in some scenarios the conversation would scroll up
1. When switching between conversations, messages appear and then seem to move a bit (up or down)

Are you experiencing this?

**Comment by averissimo** [comment]
**Screencast to better explain 2**

Solution I found was to move conversation down! stick to bottom and grow up (second screencast)

### Without correction:

![outzjdh6sk616](https://cloud.githubusercontent.com/assets/211358/20897342/d8e18b0c-bb19-11e6-97e6-739214cde9bc.gif)

### With correction

![outs4owqy9u5h](https://cloud.githubusercontent.com/assets/211358/20897540/aa59af66-bb1a-11e6-9076-6c5b62f32cc6.gif)

**Comment by averissimo** [comment]
@nerijus I believe using runSequence #487 will solve the problem you found

Already merged and in master :)

:)

ps. `npm install` should be run first to install new npm module

**Comment by averissimo** [comment]
@nerijus (again lol)

Hope I didn't step over by submitting the pull request immediately, if you were going to pick this up then I apologize

but this is also the reason why the linux-x64 binaries don't have any node_modules, as this platform/arch is the first to be built!!

**Comment by nerijus** [comment]
Thank you, it's OK now, `npm install && npm run gulp deploy:linux-x64` builds correct binary.

**Comment by averissimo** [comment]
yay!
