### ISSUE TITLE
Update README with new packaging method

### ISSUE THREAD

**Issue by averissimo** [yakyak/yakyak#466]

**Comment by kwrobel** [comment]
Any chance of including some build instructions for macOS? I'd like to try this new version 1.4.0 but have no clue how to build it and what the requirements are. I have macports installed and can grab "packages" that way.

**Comment by averissimo** [comment]
sounds good!!

To get it running you need:

- npm
- node (I use 6.7.0)
- git (to clone the repository)

I think that will be it.

1. clone the repository `git clone https://github.com/yakyak/yakyak.git`
1. `cd yakyak`
1. install modules by running `npm install`
1. `git checkout 1.4.0` checkout 1.4.0 branch that has the new code
1. `npm run gulp` to compile the code to javascripts (it's written in coffescript)
1. `npm run electron app` to run the application

note: you can always run compile and run with one command `npm run gulp && npm run electron app`

it would be awesome if you could validate this instructions in MacOSX :)

@kwrobel before you can have it running in your machine you can try the new 1.4.0 beta4

**Comment by seeker44** [comment]
@averissimo I actually grabbed the latest beta build and got it running no problem on Mac OS X Yosemite following the readme instructions for development. Specifically, the following:

With npm and git already installed

1. Downloaded the latest tar.gz
2. Unpacked to desired location (~/Applications, in my case)
3. npm install
4. npm run gulp
5. npm run deploy 

The resulting .app package has run fine so far. I did this in response to the protocol change by google because my cask-installed instance stopped working.

**Comment by averissimo** [comment]
@seeker44 my bad then!! Should have checked readme before that reply.

Topic still holds as deployment 'structure' changed and to create win32 binaries wine is a requirement

**Comment by averissimo** [comment]
And thanks for pointing that out :)

**Comment by kwrobel** [comment]
Thank you both. I do not have npm installed. So I will do that tomorrow and then follow those instructions. I will give feedback since I am on a newer version of macOS (Sierra) things might still break (slightly).

**Comment by averissimo** [comment]
@kwrobel feel free to share your experience and don't hesitate on ask for help if you get crazy errors :)

npm actually comes with node.js (my bad)

-----

Just updated the readme: 00584bf3cb639182b00728dff84ebcf0c564731e

closing this issue

**Comment by kwrobel** [comment]
Hi. Just reporting back that I have issues getting YakYak to build on my Mac. Here's a paste of the output of the npm build command: http://pastebin.com/9ZLXq4s9

**Comment by averissimo** [comment]
don't worry, that's expected... optional libraries that are not really required (they are install as some module might need it)

I have the same output, as should everyone else :)

![image](https://cloud.githubusercontent.com/assets/211358/20842900/12b66a20-b8b1-11e6-8629-96c7e1ae7fe1.png)

**Comment by kwrobel** [comment]
Thanks. I figured I would not have been able to continue with the other steps had there been serious errors.

**Comment by averissimo** [comment]
@kwrobel if you want to test the pull requests you can open their page via github.com

Click on command line instructions

and pull to the current branch (or create a new branch to test it)

![image](https://cloud.githubusercontent.com/assets/211358/20845496/4cd52726-b8bd-11e6-805e-b1a2d10a487c.png)

Just recently discovered this, I used to do it much more complicated. If you already know this, please ignore :)
