### ISSUE TITLE
No Mac binary release of 1.40

### ISSUE THREAD

**Issue by PSiAU** [yakyak/yakyak#468]
The Mac binary release of 1.40 is missing.
Would be great if someone could compile it :)

**Comment by averissimo** [comment]
should be up tomorrow :)

beta4 is a nice fallback until 1.4.0-mac is built and uploaded *(no difference between the two releases)*

**Comment by averissimo** [comment]
other than the 1.4.0 will become the official one :)

**Comment by PSiAU** [comment]
Awesome! Thanks for the reply Andre!
