### ISSUE TITLE
Fails to connect.

### ISSUE THREAD

**Issue by duckinator** [yakyak/yakyak#470]
Earlier today, YakYak was working, then it just said "Not connected" all the time and refuses to reconnect no matter what I do. Including reinstalling it.

I tried updating to 1.3.2 (from https://github.com/yakyak/yakyak/releases/tag/v1.3.2), and it still says the same thing.

Using YakYak 1.3.2 on Windows 10 x64.

(Also, in 1.3.2's yakyak-win32-x64.zip, ./version says "v1.2.5" for some reason? I even tried downloading and extracting it twice just to be sure.)

**Comment by PSiAU** [comment]
You need to update to v1.4. Google has changed their hangouts protocol and earlier versions will no longer connect.

**Comment by jesusr** [comment]
@PSiAU I am Mac user and there's no 1.4 OS X prebuilt version ;)

**Comment by PSiAU** [comment]
There is, use the darwin zip for 1.4 beta 4 which is the same as the final 1.4 version which according to Andre should be available tomorrow. I'm using it myself on a Mac and it's working great.

**Comment by drewwells** [comment]
built v1.4.0 and put it here 

https://bintray.com/drewwells/generic/download_file?file_path=yakyak-osx.app.zip
sha256: 4598c4a318e46cd5aee4b8aff93a994aa6f790543f845f2b425a4dac654f56f5

**Comment by drewwells** [comment]
Anybody know why there isn't a build from source version of yakyak in homebrew? All I found was a cask which depends on prebuilt os x binaries: https://github.com/caskroom/homebrew-cask/tree/master/Casks

**Comment by drewwells** [comment]
PR open for a homebrew formula https://github.com/Homebrew/homebrew-core/pull/7477

**Comment by duckinator** [comment]
thanks @PSiAU.

**Comment by davibe** [comment]
officially released 1.4.0

**Comment by drewwells** [comment]
anybody know why the homebrew formula is emitting a vanilla Electron app?

```
    system "npm", "run", "deploy:darwin-x64"
    prefix.install "dist/darwin-x64/YakYak.app"
    bin.install_symlink prefix/"Yakyak.app/Contents/MacOS/YakYak"
```
This works fine when I do it manually, but I'm getting some kind of electron.app via homebrew.

**Comment by drewwells** [comment]
the arch targets do not run `gulp`
