### ISSUE TITLE
[1.4.0] No Notifications?

### ISSUE THREAD

**Issue by oitsjustjose** [yakyak/yakyak#473]
So, I literally installed YakYak today for the first time and so far I'm _incredibly_ pleased!! The one thing I can't figure out is why none of the notifications are working. Any thoughts?

Here's what my notifications settings are currently at:

![ss 2016-12-02 at 11 08 03](https://cloud.githubusercontent.com/assets/3887324/20856725/5624bc02-b8e4-11e6-82c2-548f8248b1a3.png)

Any suggestions would be awesome. Thanks!!

**Comment by davibe** [comment]
maybe your conversation is muted ? can someone else test this on windows ?

**Comment by oitsjustjose** [comment]
Nope, I checked, all conversations I'm receiving messages on are set to receive notifications.

**Comment by averissimo** [comment]
Working in Windows 7

![selection_00285](https://cloud.githubusercontent.com/assets/211358/20860138/fad15f88-b968-11e6-8e3b-9afb0732add3.png)

**Comment by averissimo** [comment]
but from windows 8 and above a different system is used

**Comment by davibe** [comment]
so basically node-notifier is not compatible with windows 8+ ?

**Comment by averissimo** [comment]
It should be, it just uses a different notification system

**Comment by oitsjustjose** [comment]
So 1.4.1 doesn't seem to work either, on neither my laptop nor my desktop. In fact, the notifications don't work for my roommate on 1.4.0 on OS X either - are you supposed to install something else before installing YakYak? I feel like we're missing a dependency, but I've installed NodeJS.

**Comment by averissimo** [comment]
YakYak is self contained, you should only need the binaries.

Can you open the Inspector (via YakYak menu, or Ctrl+Alt+i) and see if there are any errors?

**Comment by mliq** [comment]
Just want to chime in to confirm notifications work fine for me on OSX 10.11.6, YakYak 1.4.0.

**Comment by oitsjustjose** [comment]
Not seeing any errors. Unless this is different from Chrome's usual inspector, the Console isn't throwing any errors when receiving a message.


![ss 2016-12-05 at 02 56 50](https://cloud.githubusercontent.com/assets/3887324/20900136/2725c9b4-bafb-11e6-9713-47bdd0b62fde.png)

**Comment by averissimo** [comment]
No errors :\

I have no clue on what this could be. Can you confirm or test the following?

1 - Open the Inspector, switch for the console tab and write/paste the following:

`require('node-notifier').notify('Something should appear')`

It should create a notification, and please copy here the result.

2 - Are you always using the same account to login?

3- Are the notifications "On" in the webinterface of hangouts? (see image below)

![outrz95xr313w](https://cloud.githubusercontent.com/assets/211358/20902112/97fa93fe-bb2d-11e6-8177-e17d91ffb789.gif)

ps. thanks @mliq

**Comment by oitsjustjose** [comment]
No dice

`require('node-notifier').notify('Something should appear')
WindowsToaster {options: Object, domain: null, _events: EventHandlers, _eventsCount: 0, _maxListeners: undefined}Growl: Growl(options)Notification: WindowsToaster(options)NotificationCenter: NotificationCenter(options)NotifySend: NotifySend(options)WindowsBalloon: WindowsBalloon(options)WindowsToaster: WindowsToaster(options)_events: EventHandlers_eventsCount: 0_maxListeners: undefineddomain: nulloptions: Object__proto__: EventEmitter
`

**Comment by averissimo** [comment]
run: 

`require('node-notifier').notify('caca', function(err){console.log('err', err);})`

Can you take a screenshot of the result?

Then run

`new require('node-notifier').WindowsToaster({fallback: true}).notify('caca', function(err){console.log('err', err);})`

**What exactly is you OS?** if windows 10 try:

![image](https://cloud.githubusercontent.com/assets/211358/20904063/d6e335f0-bb35-11e6-9773-37e4db4021e5.png)

then try all this an screenshot it please


```
new require('node-notifier').Growl({fallback: true}).notify('caca', function(err){console.log('err', err);})
new require('node-notifier').WindowsBalloon({fallback: true}).notify('caca', function(err){console.log('err', err);})
new require('node-notifier').NotifySend({fallback: true}).notify('caca', function(err){console.log('err', err);})
new require('node-notifier').NotificationCenter({fallback: true}).notify('caca', function(err){console.log('err', err);})
```

**Comment by oitsjustjose** [comment]
Wow. It took me 3 days to figure out what it was.

This is the worst ID10T error I think I've ever had.

I thought you were creating your own notifications, not using the built-in Windows ones. I keep those off normally (now enabled and working fine)....

So yeah. This was completely my fault. Notifications work as intended... just maybe slap this in the README? If I had paid any attention to _how_ this was supposed to be working, I would've been able to save you the time. Sorry :|

**Comment by averissimo** [comment]
LOOOOOOOL

Would this be cool?

![image](https://cloud.githubusercontent.com/assets/211358/20904546/f0328266-bb37-11e6-8197-bfe05589fd42.png)

**Comment by oitsjustjose** [comment]
That would be perfect.

this.facepalm()
