### ISSUE TITLE
Option to start yakyak automatically

### ISSUE THREAD

**Issue by markwoon** [yakyak/yakyak#478]
I'd live to see an option to start yakyak up automatically when signing into the OS.

**Comment by averissimo** [comment]
if someone wants to pick this up https://www.npmjs.com/package/auto-launch

**Comment by wjcarpenter** [comment]
I don't know about other OSs, but most modern flavors of Linux desktops let you set your own list of auto-start applications. I use that together with the "start minimized to tray" option (right click the tray icon to find that).
