### ISSUE TITLE
Menu not working

### ISSUE THREAD

**Issue by Georgeto** [yakyak/yakyak#48]
The menu is not working, if you are not logged in.
When I select any option from the menu, I get the following error message.

![menuerrorlogout](https://cloud.githubusercontent.com/assets/9250103/9222735/7d4814e6-40f4-11e5-884f-73c61a574a66.PNG)

**Comment by algesten** [comment]
hm. we shouldn't have a menu at this point. perhaps there's a way of not showing it until we're logged in?

**Comment by davibe** [comment]
i added 'loggedin' view state used to disable some menu items before the login. Not sure i got all of them.
