### ISSUE TITLE
Unread messages counter issue

### ISSUE THREAD

**Issue by Silveran** [yakyak/yakyak#481]
With the last 1.4.1 prebuilt version on Mac OS Sierra, I got an issue about the number of unread messages.
When I receive one message, the counter shows `20+` over the profile pics in the conversation list.

<img width="29" alt="screenshot 2016-12-04 a 18 08 22" src="https://cloud.githubusercontent.com/assets/10518880/20867804/b7182d6e-ba4c-11e6-903f-8bd4a127d5da.png">

**Comment by averissimo** [comment]
Known bug, **already solved but not included in the release**, thanks for reporting!!

:)

 see #476
