### ISSUE TITLE
Pre-Built macOS app

### ISSUE THREAD

**Issue by notverypc** [yakyak/yakyak#482]
Just wondering why there's not a Pre-Built macOS app available for the current release.
Thanks.

**Comment by PSiAU** [comment]
There is, it's the darwin binary.

**Comment by notverypc** [comment]
Why the change?

**Comment by averissimo** [comment]
we changed packaging method, I didn't realise it was called osx.

I'm changing the method so that in future releases they are called osx :)

thanks for reporting!! :)

**Comment by davibe** [comment]
for 1.4.0 you can download the version with `*darwin*` in the name

for 1.4.1 we will restore the previous naming convention with `*osx*` in it
