### ISSUE TITLE
Emoji not displaying correctly

### ISSUE THREAD

**Issue by PSiAU** [yakyak/yakyak#485]
When I try to use this emoji 🙋‍♂️, it shows up as 
![capto_capture 2016-12-05_11-58-30_am](https://cloud.githubusercontent.com/assets/2519639/20870801/47b5841c-bae2-11e6-8f53-e8774606a273.png)

Running v1.4.1 on Mac.

**Comment by Silveran** [comment]
By the way, is it possible to have smileys 20-30% bigger on mac ?? They look very tiny on retina screens

**Comment by averissimo** [comment]
we display emoji as they are received, those complex emoji are special sequences that need to be recognized and displayed somehow

tested some libraries but couldn't get that emoji to work with them

**Comment by averissimo** [comment]
@Silveran emoji is just text, I don't know of a way to increase the size of emoji only (at least with the way we are handling emoji)

![image](https://cloud.githubusercontent.com/assets/211358/21430863/e81c45c6-c85c-11e6-9fd0-513d0443510c.png)
