### ISSUE TITLE
Feature Request: Allow to drag-and-drop images from browser.

### ISSUE THREAD

**Issue by l00mi** [yakyak/yakyak#490]
The drop event seems already to arrive. It contains a html snippet with the link to the image, if not mistaken. The image needs to be loaded and provided to Hangout similar to the local ones.

**Comment by averissimo** [comment]
this is the line that should read it if someone wants to pick this up

`element.src = clipboard.readImage().toDataURL()`

https://github.com/yakyak/yakyak/blob/master/src/ui/dispatcher.coffee#L259
