### ISSUE TITLE
Feature Request: Allow Option to Specify Network Device

### ISSUE THREAD

**Issue by Diorik** [yakyak/yakyak#491]
I use "ForceBindIP" on several applications so that I can use them from within a work environment, by forcing those apps to use our less restricted WiFi. However, because of how YakYak uses child processes, this isn't a viable work around. 

It would be extremely helpful if the app allowed either at the command line an IP address for the preferred socket binding, or even as a post launch configuration to set preferred network device (e.g. run once, configure, restart). I'm not a Java developer, but it looks like any kind of socket or connection handling is being handled by other libraries - hopefully those allow you to specify.

**Comment by averissimo** [comment]
I guess this should be done in https://github.com/yakyak/hangupsjs which is the library that actually connects to hangouts

and then the change should be propagated to YakYak so it's configurable

ps. YakYak runs on javascript (not java) ;)
