### ISSUE TITLE
Requires high perf GPU on MBP which drains battery faster

### ISSUE THREAD

**Issue by hmistry** [yakyak/yakyak#492]
I tried this app v1.4.0 and discovered it requires the high performance GPU on my MBP (OS X El Capitan). I think requiring high performance GPU for a chat app is excessive and an unnecessary battery drain when I'm on the go.

Please see if you can avoid this requirement so we can enjoy your app without the high penalty of battery life. Try to take advantage of app nap and other power saving things when the app is in the background or minimized as well.

**Comment by davibe** [comment]
@hmistry does chrome browser require gpu too ?

**Comment by Silveran** [comment]
Here for me on Sierra (Macbook Pro 2016)
<img width="259" alt="screenshot 2016-12-07 a 17 01 49" src="https://cloud.githubusercontent.com/assets/10518880/20975184/f37d0186-bc9e-11e6-91ac-7b34687ffaee.png">

**Comment by hmistry** [comment]
@davibe Chrome doesn't. The only time Chrome I've seen requires the dedicated GPU is if you visit google maps page, but once you close the tab, its switches back to the integrated GPU. Safari does this too.

@Silveran Does your machine have the Radeon GPU along with the Intel 550? If it doesn't, then you won't see the switching.

**Comment by Silveran** [comment]
@hmistry it's the 13", only one GPU

**Comment by faxe78** [comment]
i see the same on the new mbp 2016 15 inch. there are two yakyak helper processes one of them has a higher energy impact. 

as long as the window is open, also open in the background, there is a high energy impact, if i minimize the window the yakyak helper process goes most of the time to zero.

**Comment by davibe** [comment]
My last commit avoids using the Gpu. I need confirmation by someone who has GPU because i don't. I don't know if it's because of my commit or because of upgrading to electron 1.4.12 but the background "Yakyak Helper" process went from 10% to 3% CPU in my latest test.

**Comment by hmistry** [comment]
Tried but running gulp fails. See error below:

```
H-MacBook-Pro:yakyak-master hm$ npm run gulp

> yakyak@1.4.1 gulp /Users/hm/Downloads/yakyak-master
> gulp

[11:05:01] Requiring external module coffee-script/register
/Users/hm/Downloads/yakyak-master/node_modules/electron-packager/index.js:3
const common = require('./common')
^^^^^
SyntaxError: Use of const in strict mode.
  at exports.runInThisContext (vm.js:73:16)
  at Module._compile (module.js:443:25)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Users/hm/Downloads/yakyak-master/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/hm/Downloads/yakyak-master/gulpfile.coffee:15:14)
  at Object.<anonymous> (/Users/hm/Downloads/yakyak-master/gulpfile.coffee:1:1)
  at Module._compile (module.js:460:26)
  at Object.loadFile (/Users/hm/Downloads/yakyak-master/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/hm/Downloads/yakyak-master/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Liftoff.handleArguments (/Users/hm/Downloads/yakyak-master/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/Users/hm/Downloads/yakyak-master/node_modules/gulp/node_modules/liftoff/index.js:198:16)
  at module.exports (/Users/hm/Downloads/yakyak-master/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.<anonymous> (/Users/hm/Downloads/yakyak-master/node_modules/gulp/node_modules/liftoff/index.js:190:9)
  at /Users/hm/Downloads/yakyak-master/node_modules/gulp/node_modules/liftoff/index.js:164:9
  at /Users/hm/Downloads/yakyak-master/node_modules/gulp/node_modules/v8flags/index.js:108:14
  at /Users/hm/Downloads/yakyak-master/node_modules/gulp/node_modules/v8flags/index.js:36:12
  at /Users/hm/Downloads/yakyak-master/node_modules/gulp/node_modules/v8flags/index.js:47:7
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3


npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "gulp"
npm ERR! node v0.12.4
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! yakyak@1.4.1 gulp: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yakyak@1.4.1 gulp script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yakyak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yakyak
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yakyak
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hm/Downloads/yakyak-master/npm-debug.log
```

**Comment by faxe78** [comment]
it is not using the gpu, it using a lot of battery in general as long as the window is not minimised. it seems like the open window keeps refreshing itself maybe more often then necessary?

**Comment by averissimo** [comment]
@hmistry you need node v4 or above _(v6 works fine with me)_ for running yakyak since we moved to new packager (you're using v0.12)

**Comment by hmistry** [comment]
@averissimo that's the first thing I thought and upgraded node using brew but it still showed as 0.12 when I do `node --version`. If I do `brew info node`, I see version 7.2.1. Do you know what's going on?

**Comment by averissimo** [comment]
@faxe78 i think the initial report was about using the gpu, it would be good to see if that was corrected with @davibe 's commit

about the window refreshing, it really does a lot, i count about 46 in #513 up to when the normal interface appears

@hmistry sorry, not a mac user, can't help you there

**Comment by davibe** [comment]
@faxe78 the window is not refreshing, it is not redrawing at all. The process that uses sometimes more cpu is not the renderer process.

**Comment by davibe** [comment]
I think i found the reason. It's an infinite css animation. Tomorrow I will check how to make it right :)

**Comment by faxe78** [comment]
@averissimo for me it is corrected i don't see it gpu usage on the mbp 2016

@davibe sounds great a big thx.

**Comment by hmistry** [comment]
@davibe I confirmed its not using the dedicated GPU. 

I saw you disabled the HW GPU acceleration which works though I wonder if there's a middle ground where you use the HW GPU acceleration but not the dedicated one. This way you get smooth scrolling with low cpu usage without the dGPU power drain. I suspect that certain css animations (thinking 3d transforms) or webGL/openGL or some library might be pushing it over the edge... this requires more time then you may have and your fix is a good fix till we discover the in between solution. 😃 

FYI - these guys had the same issue
https://github.com/adobe/brackets/issues/5028

maybe helpful? http://stackoverflow.com/questions/26356769/test-if-hardware-acceleration-has-been-enabled-for-a-css-animation

**Comment by davibe** [comment]
@hmistry try to fetch my last commit, then remove the line that disables hardware accelleration and see if you're happy with it. I am testing too.

- I can see while scrolling that using hw acceleration produces slightly lower cpu usage
- When idling with the window in the foreground i get 0% usage
- I don't have a dedicated GPU, just the intel one so i don't know if something else still triggers it

**Comment by hmistry** [comment]
@davibe Done. Here is my findings:
1. I don't remember what my CPU usage was before the animation fix but its low enough to ignore.
2. It's uses the integrated GPU which is good.
3. I commented out the disable hardware acceleration and it caused the dedicated GPU to turn on. 
4. One caveat to 3 above, is if the sign in to google account is displayed, it uses the integrated GPU whether I just opened the app to that login screen or I've been using the app and I logged out of it to the login screen. The switch to dGPU happens after I enter my username and it goes to the enter password screen. Once I'm on the enter password screen, it's using the dGPU.

BTW, I just tried the Atom editor and it doesn't use the dGPU... but it's a different app + ui.

Thanks for looking into this and fixing it. I'm sure many people will be pleased to see their battery life improve as a result of your work. 😃

**Comment by davibe** [comment]
@hmistry can you quantify the battery life impact of dGPU ? you can inspect amperage in System Information, or just wait a bit and see the estimated discharge time.

Since I don't have dGPU it's very difficult for me to debug this. If i had it i would probably try to comment out css rules until i find the source of problems.

Atom is not all that different. Of course they are not doing it in their spare time :P

**Comment by hmistry** [comment]
@davibe I tried that but didn't get very good results. The amperage varied from 950-1150mA and the time remaining from 6:20-7:30 hrs and it didn't matter whether I was using the integrated GPU or the dGPU. I'm not sure if this is a good/valid test, at least in the ways I tried. It was a good idea.

In general, whenever the dGPU turns on, I loose 2-3 hrs of battery life. I also wonder if once an app requires a dGPU, does the entire system switch over and choose to use that there by increasing the drain??? I think a better way to test is to see if you can use Xcode's instruments (energy, gpu profilers) to measure the app's performance. I'm not that proficient at using all those instruments.

If Atom's not that different, then maybe some one from that team won't mind sharing what they did about dGPU?

**Comment by davibe** [comment]
Yes, i am quite sure when switching to dGPU the entire system switches to it.

btw
https://discuss.atom.io/t/atom-on-a-rmbp-requires-the-dedicated-gpu/4418/4

**Comment by davibe** [comment]
They fixed by adding that flag in Info.plist but we already have it

**Comment by davibe** [comment]
http://electron.atom.io/docs/all/ they say
"""
GPU accelerated
GPU accelerated rendering means that the GPU is used for composition. Because of that the frame has to be copied from the GPU which requires more performance, thus this mode is quite a bit slower than the other one. The benefit of this mode that WebGL and 3D CSS animations are supported.

Software output device
This mode uses a software output device for rendering in the CPU, so the frame generation is much faster, thus this mode is preferred over the GPU accelerated one.

To enable this mode GPU acceleration has to be disabled by calling the app.disableHardwareAcceleration() API.
"""

**Comment by hmistry** [comment]
Very interesting tradeoffs. Doing a search on that plist switch, revealed a number of threads where people found it didn't work for some and worked for others. Anyways, at least you found a solution for this... yay! 😃

**Comment by averissimo** [comment]
Closing this issue as with @davibe improvements CPU/GPU usage comes to a bare minimum

hurray!! 🎆 

if you feel there is still a problem, please comment and/or reopen

**Comment by Ke-** [comment]
Sorry to necro this, however I just discovered why my MBP 15" 16GB was over heating / fans at 100%
 — it was Gitter forcing use of the discrete GPU. 

This seems overkill, a chat app in OSX shouldn't force / require this.

[https://www.dropbox.com/s/8j5uy8djimb6ro3/bad-gitter.png?dl=1](url)
