### ISSUE TITLE
Feature Request: option to bring window to front when new message arrives 

### ISSUE THREAD

**Issue by norbitheeviljester** [yakyak/yakyak#493]
Hi,
it would be great if yakyak had a feature that allows it to come to the front of the screen (come into focus) whenever a message arrives. 
Rationale:
I usually work on 3 monitors which makes it quite easy to miss notifications of incoming messages. I would prefer the client to pop up in front of my face so that I see the messages as soon as they arrive.

**Comment by davibe** [comment]
Sounds VERY aggressive. I would never use it for sure :P

**Comment by norbitheeviljester** [comment]
I'm not saying it should be on by default but I do believe it is a useful
feature. I know it has been implemented in other im clients often. From the
top of my memory Yahoo messenger and pidgin.
It's a feature that is most useful for clients that spawn a window per
conversation but it has its usage here too.
I tested yakyak on Ubuntu with unity and Linux mint with cinnamon. On both
these os the notification system is subpar to windows imho. It doesn't
allow for persistent notifications or some kind of special effect that
would make them visible.
When working with multiple monitors it is easy to miss a notification that
lasts only a couple of seconds on a different monitor than the one you are
focused on.
If you do not like the idea of a window conning to focus then maybe some
kind kind of other visual effect that would make new messages more visible?




Norbert Nogacki

**Comment by averissimo** [comment]
The tray icon turns from gray to green when there are unread messages. (if you activate the tray option)

![image](https://cloud.githubusercontent.com/assets/211358/20981013/c55d9188-bcaa-11e6-8886-027d5876a2c2.png)

![image](https://cloud.githubusercontent.com/assets/211358/20981018/c7a2fbf4-bcaa-11e6-97c6-42d1ce557d98.png)

**Comment by averissimo** [comment]
but something as you said would be easily implemented.

Adding a persistent option and checking it when a new message appears to see if window should be focus.

If you want help implementing this I can give some pointers where stuff is :)

**Comment by nowayyy36** [comment]
I would definitely use that option too :)

**Comment by averissimo** [comment]
if someone wants to start developing for YakYak, this is a good way to do it ;)

Creating a new option requires:

1. Create a persistent option in localStorage (see begining of `viewstate.coffee`)
1. Add a function to change value also in `viewstate.coffee` (see for instance `setConvertEmoji`)
1. Add an action in `dispatcher.coffee` (see `convertemoji` as an example)
1. Create a new menu option in `menu.coffee` (`Convert text to emoji` is again a good example)
1. Bring window to focus during action `chat_message` in `dispatcher.coffee`
    - make sure it only does that if new option is true

ps. to bring the window to focus you might use `require('electron').remote.getCurrentWindow().focus()` (or use directly remote... if remote variable is already set, usually is)

pps. not sure if you would need to make sure window is already visible first.

**Comment by Sakarias-Longhorn** [comment]
in **\resources\app\ui\dispatcher.js** at line **64** add : 
```
  handle('chat_message', function(ev) {
    if (entity[ev.sender_id.chat_id] == null) {
      entity.needEntity(ev.sender_id.chat_id);  
    }
    conv.addChatMessage(ev);
	//REFOCUS FIX
	mainWindow = remote.getCurrentWindow();
	mainWindow.show();
	viewstate.setSelectedConv(ev);
	
    return notify.addToNotify(ev);
  });
```

Note : This enables the option by default with no checkbox to disable it, simple implementation.

**Comment by averissimo** [comment]
@Sakarias-Longhorn very cool!!

could you be interested in adding this as a general option?

**Comment by Rone777** [comment]
> in **\resources\app\ui\dispatcher.js** at line **64** add :
> 
> ```
>   handle('chat_message', function(ev) {
>     if (entity[ev.sender_id.chat_id] == null) {
>       entity.needEntity(ev.sender_id.chat_id);  
>     }
>     conv.addChatMessage(ev);
> 	//REFOCUS FIX
> 	mainWindow = remote.getCurrentWindow();
> 	mainWindow.show();
> 	viewstate.setSelectedConv(ev);
> 	
>     return notify.addToNotify(ev);
>   });
> ```
> Note : This enables the option by default with no checkbox to disable it, simple implementation.

is there a way to add this and KEEP the notification sound on? adding this works bringing it to front but it also turns off notification for it.
