### ISSUE TITLE
Integrate video calls in app

### ISSUE THREAD

**Issue by Quezako** [yakyak/yakyak#494]
Hello,

Very nice app here!
But when I join a video call with 8+ people, Chrome starts to slow my system down.
It would be great to have an in app video call, instead of html5 video, which uses much RAM and CPU.

**Comment by davibe** [comment]
IT would be the same since yakyak is an electron app and electron is an app container based on chrome itself.

**Comment by pierrebeaucamp** [comment]
I'm actually really interested in having video and audio calls integrated in yakyak. I'm using Firefox as my primary browser and the plugin required to use Hangouts on Firefox is pretty much abandoned at this point (As of right now, you can only use Hangouts on 32-bit versions of Firefox before v52).  I don't want to install Chrome only to do video calls.
