### ISSUE TITLE
Every message in group chat shows icon of those who have seen the message

### ISSUE THREAD

**Issue by rwcee** [yakyak/yakyak#495]
*OS*: OSX 10.11.6
*Build*: YakYak v1.4.1

*Issue Screenshot*: 
<img width="703" alt="screen shot 2016-12-07 at 6 26 11 am" src="https://cloud.githubusercontent.com/assets/847332/20965963/1daabfe2-bc46-11e6-818b-8be87152adae.png">

*Expected Behavior*: Only show user icon on message that which was most recently seen.

**Comment by averissimo** [comment]
Yeah, it's not very optimized, we've tried to show only last one, but it was buggy and reverted to this one.

You can track development on this on my branch called `feature-ui-pretiffy`

**Comment by averissimo** [comment]
If someone knows how to get (via css) the last element of a certain type over the document then that would be really nice :)

:last-chid and :last-of-type only work with same parent. The structure so far is something like this. And we need to capture last `.seen`

```
.ugroup
    .umessage
    .seen
.ugroup
    .umessage
    .seen
.ugroup
    .umessage
    .seen
```

Closest solution so far was searching for last one after DOM is generated and only show that one. 

But as we scroll back history it started to show two and hiding the "real" last one

**Comment by averissimo** [comment]
@davibe is the man!! solution has been merged to master branch (not yet in any of the releases)

In case there's a newer message from the other party, his 'seen avatar' is NOT shown (as it would be below his own message)

![image](https://cloud.githubusercontent.com/assets/211358/21019356/125cc22a-bd68-11e6-8dbf-973cf05e52e4.png)

**Comment by rwcee** [comment]
@davibe @averissimo :: Awesome! Thank you for the incredible turn-around time. Looking forward to this going out in the newest release!

**Comment by davibe** [comment]
;)
