### ISSUE TITLE
User's initials with colors (instead of gray)

### ISSUE THREAD

**Issue by averissimo** [yakyak/yakyak#496]
![image](https://cloud.githubusercontent.com/assets/211358/20972681/976c31b6-bc8d-11e6-8d70-6cde839ceff9.png)

**Comment by averissimo** [comment]
will be tracked in a branch called `feature-ui-pretiffy`

**Comment by davibe** [comment]
haha you're really having fun

**Comment by averissimo** [comment]
merged
