### ISSUE TITLE
ElemetaryOS Loki - Does Not Run

### ISSUE THREAD

**Issue by ocnios** [yakyak/yakyak#497]
EDIT: 64bit version worked once I did a --reinstall of libxtst6

Wasn't able to tar -xvf then cd and run ./yakyak
I got a few messages about missing libraries I was able to apt-get and fix but now I'm stuck on this.

ocnios@OCNIOS-VIZIO:/Downloads/yakyak-linux-ia32$ ./yakyak
./yakyak: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory
ocnios@OCNIOS-VIZIO:/Downloads/yakyak-linux-ia32$ apt-file search libXtst.so
libxtst-dev: /usr/lib/x86_64-linux-gnu/libXtst.so
libxtst6: /usr/lib/x86_64-linux-gnu/libXtst.so.6
libxtst6: /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
libxtst6-dbg: /usr/lib/debug/usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
ocnios@OCNIOS-VIZIO:~/Downloads/yakyak-linux-ia32$ sudo apt install libxtst6
[sudo] password for ocnios: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxtst6 is already the newest version (2:1.2.2-1).
The following package was automatically installed and is no longer required:
  libostree-1-1
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by averissimo** [comment]
@ocnios the requirements to run the framework we use are here:

https://github.com/electron/brightray/blob/master/brightray.gyp#L4

**Comment by averissimo** [comment]
from this comment: https://github.com/electron/electron/issues/6945#issuecomment-241968955

**Comment by ocnios** [comment]
I got it running, but thank you! I love YakYak, just wish there were some better color themes.

**Comment by averissimo** [comment]
@ocnios You can create them yourself ;)

if you want to try to create a new schema I can give some tips:

**The best way to iterate is to do it in the open app directly**: Start by opening the Inspector and find in the sources tab. There find `app.css`

![image](https://cloud.githubusercontent.com/assets/211358/21052997/70dbb100-be1f-11e6-9a5d-b2581c212e0a.png)

Inside the `app.css` file, find: `html.dark`. Tweak the colors selected in the schema you have selected at the moment

I'm using the default, so I would tweak `html` (which has the default colors) as the image below show . All changes in this file show in real time in the yakyak window, **but are not persistent!!**

After you are satisfied with a color schema or want to save your results, you have to copy that to somewhere else and then submit a pull request (if you never done that before, it's really easy)

![image](https://cloud.githubusercontent.com/assets/211358/21053105/d5604f0a-be1f-11e6-8373-bf27ebf328ee.png)

ps. yakyakgreen is something not in the binaries, so just overlook that :)
