### ISSUE TITLE
Where is the call button?

### ISSUE THREAD

**Issue by Feichtmeier** [yakyak/yakyak#498]
Awesome update! Runs very well now on Ubuntu Linux 16.04.1 4.4 Kernel
But where is the call button?

**Comment by averissimo** [comment]
No call button, this a chat messaging application :)

**Comment by Feichtmeier** [comment]
Oh that is sad. It would be enough to have a Button Which opens a Hangout in Chrome :/ can't you add that?

**Comment by davibe** [comment]
when there is an incoming call we suggest to open chrome by givin the user a link se we could do the same for "call". I think. It's "just" a matter of figuring out the link and see where to put the button.

**Comment by Vzor-** [comment]
It seems strange that you can receive calls but not place them.
