### ISSUE TITLE
HiDPi Support

### ISSUE THREAD

**Issue by afonso360** [yakyak/yakyak#50]
Using yakyak on a 3200x1800 13" (~276 ppi) screen results in everything being too tiny, almost unreadable.

Here's a screenshot:
![screenshot from 2015-09-01 00-37-59](https://cloud.githubusercontent.com/assets/1357143/9593045/e982555c-5041-11e5-954d-8afb99145e0a.png)

Opening the inspector and appending `zoom: 2` to the `body` css rules seems to fix the issue.
Screenshot after:
![screenshot from 2015-09-01 00-38-43](https://cloud.githubusercontent.com/assets/1357143/9593067/16db6908-5042-11e5-95c0-8c86780df3b8.png)

yakyak version: latest git
Arch Linux 64-bit with 4.2.0-rc8 kernel
Gnome 3.16.3

**Comment by maxkueng** [comment]
May be related to atom/electron#1150

**Comment by afonso360** [comment]
`gsettings get org.gnome.desktop.interface scaling-factor` does report as 0

**Comment by afonso360** [comment]
Adding `"zoom-factor": 2.0` to the BrowserWindow parameteres also fixes the issue, would the best way to detect a HiDPI screen be:

1. Calculate solely based on resolution as in the below comment
https://github.com/atom/electron/issues/615#issuecomment-116366096
Which doesn't seem very reliable.

2. Add a command line switch that changes the zoom-factor.
The issue with this is that there doesn't seem to be a command line parser in the code.

**Comment by algesten** [comment]
i wouldn't mind a 1x/2x switch in the menu. if that's what it takes.

**Comment by maxkueng** [comment]
Isn't it possible to somehow detect which zoom factor to use? Adding a manual switch seems weird and also non tech savvy will probably not find it right away.

**Comment by maxkueng** [comment]
Maybe it's possible using `window.devicePixelRatio`? I don't have a HiDPi screen so I can't try it out. Or maybe simply adding a "viewport" meta tag could help.

```html
<meta name="viewport" content="width=device-width" />
```

**Comment by afonso360** [comment]
I added the meta tag to src/index.html, and if i remove the `zoom-factor` everything is still tiny.
`window.devicePixelRatio` is set to whatever i put into `zoom-factor` so i don't think it will solve it.
I couldn't find any api on node.js or coffescript or electron to report a dpi setting, maybe i missed it.

**Comment by davibe** [comment]
added zoom in/out menus and shortcuts. Maybe not a definitive fix but should work and be simple to use. Zoom factor is saved to localStorage.

**Comment by algesten** [comment]
@davibe you go!!

**Comment by afonso360** [comment]
Well good news, it works, and it presists across reboots, but when closing the app I get the following error

Uncaught Exception:
TypeError: Cannot read property 'forceClose' of null
    at BrowserWindow.<anonymous> (/home/afonso/Projects/yakyak/app/main.js:362:21)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:169:7)

and afterwards

Uncaught Exception:
TypeError: Cannot set property 'forceClose' of null
    at EventEmitter.<anonymous> (/home/afonso/Projects/yakyak/app/main.js:86:34)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.<anonymous> (/home/afonso/Projects/yakyak/app/main.js:75:18)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)

**Comment by davibe** [comment]
bohf i don't think its related

**Comment by afonso360** [comment]
Should i open a new issue, the commit fixed the second error but the first is still happening

**Comment by davibe** [comment]
Please, try now. If something is still broken let's open a new bug

**Comment by afonso360** [comment]
Error fixed!
