### ISSUE TITLE
copy/paste of links does not work

### ISSUE THREAD

**Issue by nerijus** [yakyak/yakyak#502]
On Linux if I press right mouse button on the received link and choose Copy, it does not get copied to the clipboard - I cannot paste it with neither Ctrl+V nor Shift+Ins nor middle mouse click.

**Comment by averissimo** [comment]
yes, I think the context menu is only registered for the selection.

That'd be a cool enhancement

**Comment by nerijus** [comment]
https://github.com/sindresorhus/electron-context-menu could something from here be used? It has Copy Link.

**Comment by averissimo** [comment]
yeah it works really nice :)

the one I don't like is that it hides copy/cut/paste when randomly clicking in the message pane.

it should grey out the options if not selected as it does with the input

![image](https://cloud.githubusercontent.com/assets/211358/21058435/d72bc06a-be35-11e6-8606-e36c7537ee08.png)

![image](https://cloud.githubusercontent.com/assets/211358/21058439/da7aec28-be35-11e6-899f-656aa670d896.png)

![image](https://cloud.githubusercontent.com/assets/211358/21058441/dca31e80-be35-11e6-9e65-2c57b5689908.png)

**Comment by averissimo** [comment]
![image](https://cloud.githubusercontent.com/assets/211358/21058476/02623142-be36-11e6-8bc6-b71b5d4bd886.png)

**Comment by nerijus** [comment]
Could you please share your changes?

**Comment by averissimo** [comment]
on my fork under branch `feature-context`

**TODO:**

- [ ] needs to update overall paste behaviour to always paste to message-input

I modified paste, so that when in a conversation, it pastes the content to the message-input.. which is where we want to paste. Still has some duplicate code for paste so that needs to be cleaned.

**In the end I didn't like the module,** as we couldn't rewrite some of the defaults menus such as paste.

What do you think?

**Comment by averissimo** [comment]
ps. "save" image and "copy link" need to be tested in Mac OS X

**Comment by nerijus** [comment]
We don't have to use module, just Copy link is enough for me :)

**Comment by nerijus** [comment]
Thanks, your branch feature-context is good for me!
Just src/ui/views/contextmenu.coffee has line
contextMenu = require('electron-context-menu')
If I comment it out, it runs.

**Comment by averissimo** [comment]
oops, correcting it, but should work fine

**Comment by averissimo** [comment]
submited pull request #503
