### ISSUE TITLE
Names of people in hangouts overlap the dots in top right

### ISSUE THREAD

**Issue by PSiAU** [yakyak/yakyak#505]
Hangouts with a lot of participants causes the names to run into the three vertical dots in the top right.
Running v1.4.1 on macOS 10.12.1

**Comment by davibe** [comment]
if you can, please, attach a screenshot

**Comment by PSiAU** [comment]
Here it is, although i've blurred out the names.

![capto_capture 2016-12-12_01-56-02_am](https://cloud.githubusercontent.com/assets/2519639/21097866/c380b660-c0ba-11e6-8293-9b2164b2d71e.png)

**Comment by averissimo** [comment]
![image](https://cloud.githubusercontent.com/assets/211358/21098322/902900a6-c060-11e6-8faf-cbe4fe3f1924.png)
