### ISSUE TITLE
yakyak.exe reported as trojan in Windows Defender (win10)

### ISSUE THREAD

**Issue by sinisadruzeta** [yakyak/yakyak#506]
It started happening since YakYak  v1.4.1 (maaaybe the one before, not sure) version. Windows Defender report is below.

Category: Trojan
Description: This program is dangerous and executes commands from an attacker.
Recommended action: Remove this software immediately.
Items:
file:C:\Apps\YakYak\yakyak.exe
Get more information about this item online. -> [https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fPeals.A!cl&threatid=2147690472&enterprise=0](https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fPeals.A!cl&threatid=2147690472&enterprise=0)

Thanks for YakYak, I love it.

**Comment by averissimo** [comment]
Thanks for reporting, are you installing it from github yakyak/yakyak?

**Comment by sinisadruzeta** [comment]
Yes, I downloaded it from [https://github.com/yakyak/yakyak/releases](https://github.com/yakyak/yakyak/releases).

**Comment by averissimo** [comment]
As far as I know, YakYak should only communicate with the outside for two reasons

1. hangouts server via hangupsjs module to get data.
1. and with github.com to find the lastest released version.

`yakyak.exe` itself is the executable from electron (the framework we use to build the app)

**does windows defender also detects the same trojan with other electron-based apps?** (if you have any installed, of course :) )

**Comment by averissimo** [comment]
if you don't have any other app install can you try electron barebones

official release in link below:

https://github.com/electron/electron/releases/download/v1.4.10/electron-v1.4.10-win32-x64.zip

**Comment by davibe** [comment]
This is very funny :D

**Comment by sinisadruzeta** [comment]
OK, I've tried installing electron and scanning again both electron and yakyak and now Windows Defender had no problem with them. Could be that Windows Defender updated its malware definitions in the meantime, or just that it does not work consistently. :)

I think we can say that the problem has gone away. For now. :)

**Comment by averissimo** [comment]
LoL nice to hear :)

if it happens again, try using the electron app to see if it also pops up, or is yakyak specific, but hopefully never again ^^

I'm closing the issue, thanks for reporting and the feedback
