### ISSUE TITLE
Conversation switching keyboard shortcuts incorrectly displayed in OS X

### ISSUE THREAD

**Issue by vnaylon** [yakyak/yakyak#508]
In v1.4.1, the OS X shortcuts shown in the View menu for "Previous Conversation" and "Next Conversation" are incorrect.

Because the shortcut is Command-up or Command-down, I’d expect to see up and down arrows in the menu. 

Instead, the menu shows the symbol for Tab, which would lead users to believe the correct shortcut for switching conversations is Shift-Command-Tab or Command-Tab (which in OS X for will switch apps).

<img width="263" alt="screenshot 2016-12-12 13 58 17" src="https://cloud.githubusercontent.com/assets/109213/21118510/11a2c380-c073-11e6-8458-96bd7f787b48.png">

**Comment by averissimo** [comment]
@vnaylon does the (Shift+)Command+Tab work? I guess this is the official shortcut as it is the one that is visible :)

The other shortcut is defined directly in the code (`input.coffe`), no idea why this is being done in 2 places

I guess being a hidden shortcut is not good UI policy, maybe we should converge to just a single one that's advertised in the menu. thoughts @davibe, @vnaylon ?

![image](https://cloud.githubusercontent.com/assets/211358/21142894/2ad15398-c13c-11e6-8e89-20341297d62c.png)

![image](https://cloud.githubusercontent.com/assets/211358/21143170/877bdcc0-c13d-11e6-8552-f9fba9d932d5.png)
