### ISSUE TITLE
YakYak suddenly unable to connect

### ISSUE THREAD

**Issue by pablocruz23** [yakyak/yakyak#511]
A couple weeks ago, Yakyak stopped connecting with my Gmail account. Nothing changed with the account. Now, there's a message in the upper right that switches between "Connecting" and "Not Connected." The rest of the screen is blank. There are no options available anywhere in the UI to do anything about this problem.

I tried deleting Yakyak and reinstalling it, but that made no difference.

**Comment by averissimo** [comment]
@pablocruz23 Have you reinstalled using 1.4.0 or 1.4.1 pre-release?

They are the only versions working since December 1st, when google changed the protocol

**Comment by pablocruz23** [comment]
Excellent, thanks for the heads-up. I've downloaded 1.4.0 and now it's working again!
