### ISSUE TITLE
notification that a login from ios device was made

### ISSUE THREAD

**Issue by wkjid10t** [yakyak/yakyak#515]
I installed the app on windows 64 bit. Then after logging into my gmail account on the app. I got a notification that a new device has logged into my account. Which was correct, it was my windows machine. But right after that I got an additional notification that an ios device also logged into my account. 

I am assuming that you are emulating an ios device somewhere in the app?

I removed the ios device from my device list in google security console, and the app doesn't seem to be working. I just want to make sure that having it show up as an ios device is actually correct?

**Comment by averissimo** [comment]
some users experience this :\ see #104

**Comment by davibe** [comment]
this is an unofficial client which has to do hacky things to get things done. Yes yakyak does present itself as an iOS device.
