### ISSUE TITLE
Incorrect name in "Missed call" dialog.

### ISSUE THREAD

**Issue by duckinator** [yakyak/yakyak#517]
When I miss a call, it says "Missed call from &lt;my name&gt;." This has happened at least twice.

(It should be "Missed call by &lt;caller's name&gt;.")

Using YakYak 1.4.0 on Windows 10 x64.

**Comment by davibe** [comment]
thanx

**Comment by averissimo** [comment]
The correction for this should be at `src/views/notification.coffee`
