### ISSUE TITLE
Unable to install using Homebrew

### ISSUE THREAD

**Issue by NOTSOGEEKY** [yakyak/yakyak#528]
Just download the Mac version and double clicked the file and allowed it to open from unidentified developers.

The YakYak screen shows just a blank white screen with nothing on it. 

<img width="731" alt="screen shot 2017-01-02 at 5 21 05 pm" src="https://cloud.githubusercontent.com/assets/24874350/21588756/e77c2184-d10f-11e6-9f68-4828432effd4.png">

**Comment by kusmierz** [comment]
same here...

**Comment by averissimo** [comment]
which version is installed with Homebrew?

I'm not sure who the maintaner of the package is, but latest version should be 1.4.0 (with a 1.4.1 pre-release)

**Comment by NOTSOGEEKY** [comment]
It says Version 1.4.12. Do I still have to install Homebrew? I tried the Homebrew method of installation and then found you have a Mac installer package and tried that. 

If you want me to try the Homebrew method, please provide more detailed instructions how.

**Comment by averissimo** [comment]
1.4.12 means it still is using our framework versioning instead of the app itself

Can you please try to install via the official release

https://github.com/yakyak/yakyak/releases

Unzip and run YakYak

**Comment by NOTSOGEEKY** [comment]
Tried exactly that. Downloaded the Mac OS version and tried installing. Nothing. Blank white screen.

**Comment by averissimo** [comment]
Also with the 1.4.1 pre-release? This pre-releasewill show an error window with a link to open the inspector.

If you can, install this one, open the inspector (via the link) and take a screenshot of the "console tab"

**Comment by averissimo** [comment]
1.4.1 pre-release should show an error window with a link to open the inspector.

Can you try that version, open the inspector and take a screenshot of the Console tab?

or just open the inspector with your current yakyak version (access via the menu) and take the screenshot

**Comment by averissimo** [comment]
@NOTSOGEEKY ?
