### ISSUE TITLE
Feature Request - provide contact info on new conversation page

### ISSUE THREAD

**Issue by thenextdon13** [yakyak/yakyak#529]
Hello-
One thing that has been annoying with hangouts was the disassociation of contact info (specifically email address) and user names.

This was frustrating because duplicate names (i.e. the same person with accounts on 2 different domains) were nearly impossible to differentiate.  

I see more recent versions of hangouts  this (by providing the email address under the name), but yakyak does not do anything simlar.

So, if possible, please add contact info (email address) to contacts resolved in the 'new conversation' user search box.  

many thanks

**Comment by thenextdon13** [comment]
Looks to be working, thank you!

**Comment by averissimo** [comment]
You can thank @lonvarscsak for his great work!
