### ISSUE TITLE
[Bug][macOS] Audio notifications don't respect change in output device

### ISSUE THREAD

**Issue by danmandle** [yakyak/yakyak#532]
On El Capitan, YakYak outputs audio notifications on the original audio device even after switching the audio output device through System Preferences > Sound.

**Comment by averissimo** [comment]
Do you experience this when using custom sound? _(or the other way around)_

ps. option to use custom sound is in `view -> popup notification -> use custom..`

**Comment by danmandle** [comment]
Ok, so things got a little more complicated now... I was experiencing the issue on 1.4.0. I downloaded and replaced the app with 1.4.1 and now, not only do I have no sounds, but most of the menu items are disabled. See attached screenshot. A restart may solve the problem, but I can't do that right now.
![screen shot 2017-01-04 at 2 43 57 pm](https://cloud.githubusercontent.com/assets/1851630/21660350/4c7ea372-d28c-11e6-9a13-dbfa7859e360.png)

**Comment by averissimo** [comment]
two lines were removed by mistake when correcting a diffrerent bug lol

master already has everything and we'll update 1.4.1 binaries tomorrow

**Comment by averissimo** [comment]
binaries have been updated

can you check now?

**Comment by danmandle** [comment]
Using the YakYak custom sound DOES respect the audio device selection. However, the default still does not.

**Comment by averissimo** [comment]
It makes sense as the default uses the system's notification.. 

I guess that's what you have to change in the sound settings (should be called `Notification Center`)

We don't handle notifications in YakYak, we use a module called `node-notifier` that then uses different sub-systems depending on the OS.

I think this issue should be closed as this is not a YakYak bug, but is OS-dependent

**Comment by averissimo** [comment]
The custom sound, disables the default notification sound and just plays "our" melody. This is controlled by YakYak and that's why it works :)
