### ISSUE TITLE
Messages not being sent

### ISSUE THREAD

**Issue by mreynolds0404** [yakyak/yakyak#536]
Messages sent through YakYak remain gray and are never sent.  New messages from other person are received and messages sent from other clients (e.g. Hangouts app on phone) show up in the chat in YakYak.

macOS Sierra 10.12.2 (16C67)
YakYak 1.4.1

**Comment by AndrewJDR** [comment]
I can confirm this as well, but for me it's more specific:
When sending to google voice (SMS) contacts with yakyak, they turn grey and are never received by the recipient.
When sending to regular hangout contacts (not google voice), everything behaves as expected and messages are received by the recipient.

Is this what you observe as well, @mreynolds0404, or are you seeing this problem for regular hangouts contacts as well?

**Comment by AndrewJDR** [comment]
The particularly nasty thing about this bug is that the message sent from yakyak shows up in the official Hangouts client as though it had been successfully sent even though it hasn't been.

**Comment by AndrewJDR** [comment]
Ah, I see that this is probably a dupe of #330 but @mreynolds0404 can confirm whether this is for all contacts or just sms contacts.

**Comment by mreynolds0404** [comment]
In my case, these were Hangouts clients, and the messages sent from YakYak did not show up in the official Hangouts client.

**Comment by averissimo** [comment]
was the `connecting` notification appearing in the top right corner?

**Comment by mreynolds0404** [comment]
It's not happening any the moment, will check when it does happen again.

**Comment by skawaii** [comment]
I'm seeing the same thing as @AndrewJDR. When sending an SMS to a Google Voice contact, the message remains light gray in YakYak. The message shows up in the the official Hangouts app/client. This took me a long time to figure out that the messages weren't actually being sent, because of this.

The `connecting` notification is not appearing in the top-right corner.

**Comment by averissimo** [comment]
@skawaii sending sms is not fully supported, we need a developer that uses that functionality of hangouts to figure it out

**Comment by skawaii** [comment]
@averissimo Understood. I just wanted to lend my voice to the issue.

**Comment by averissimo** [comment]
thumbs up!! I've been dodging this for a while, but I do have a question for sms users.

if you can please reply to my new comment in #330 (and move that issue discussion there)

**Comment by dragos** [comment]
This is definitely a problem. I have to restart YakYak every hour most days, or else my messages don't get delivered. Play hangout users, no SMS.

**Comment by averissimo** [comment]
@dragos which version are you using? can you try v1.4.2 (pre-release)?

another thing, where is the first exception thrown? _(file and number, should be in the right side of the console)_

**Comment by dragos** [comment]
I'm on 1.4.1, I'll give it a try tomorrow. Actually, the exception is always there after startup, even when the application works well.

**Comment by averissimo** [comment]
try this 1.4.2 with extra logging for sending messages: https://github.com/averissimo/yakyak/releases/tag/v1.4.2-536

I would ask you to start yakyak from a command line.

Once YakYak stops sending messages I'd ask you to:

- Send one :)
- Open the inspector and see if these two lines are there

![image](https://cloud.githubusercontent.com/assets/211358/22520879/e965be50-e8ad-11e6-9df2-e6a44863a103.png)

- Command line log should also have:

![selection_00514](https://cloud.githubusercontent.com/assets/211358/22520927/19609684-e8ae-11e6-8cf7-c0f7a9af9958.png)

ps. this is the first time I'm debugging this type of error, so this might have some iterations :)

**Comment by averissimo** [comment]
pps. client_generated_id should be the same number and `segs` should include the content of the unsent message

**Comment by dragos** [comment]
I am using 1.4.2 for the last few days and haven't seen this error yet. I'll post back if it happens again.

**Comment by averissimo** [comment]
Current v1.4.2 might have solved this by sending an available signal to hangouts on every connection-related event.

Can't stress enough the 'might', as it would be awesome, but not intended lol

**Comment by amoeba** [comment]
New YakYak user and I'm seeing this. However, I am only seeing this when talking to a person using a corporate Google account (Google Apps for Domains?) and not someone using Hangouts via GMail. I didn't see anywhere in the readme about this not being support so hopefully I didn't miss that. My message sent via YakYak appear gray in YakYak and _do not_ show up ever in the GMail Hangouts interface. I'm on Mac OS Sierra 10.12.3.

I see this with the 1.4.2 stable and also with https://github.com/averissimo/yakyak/releases/tag/v1.4.2-536.

Is there some debug output I could put in here that would be helpful?

**Comment by robpetrin** [comment]
I'm seeing this, and it's preventing me from using YakYak.

As others have stated, I receive the SMS I sent from YakYak on all of my devices, but the recipient does not. Interestingly, when I click "View details" on my phone, it shows ME as the recipient, not the person I'm in the conversation with. This would explain why the text shows up on my devices, but the recipient doesn't report receiving it. 

Could this be a break in the case, as I'm seeing this issue in a lot of places without resolution.

**Comment by averissimo** [comment]
@robpetrin this sms related issue is being tracked in a different issue #330

I believe with the client that we're using, the messages are sent to a conversation (id) and not to a specific recipient.

Can you post your comment there? It might be useful when someone picks the sms stuff

@amoeba I'll try testing this later with a google apps account that I have
