### ISSUE TITLE
error on startup: Cannot find module 'autosize'

### ISSUE THREAD

**Issue by sinistral** [yakyak/yakyak#538]
v1.4.13

![screen shot 2017-01-06 at 11 17 46](https://cloud.githubusercontent.com/assets/388984/21728138/d6361322-d401-11e6-9ed4-10fa26662225.png)

**Comment by averissimo** [comment]
Thanks for reporting.

We've just corrected the binaries, can you download 1.4.1 release again?

ps. by the way, can you give some feedback on the error window?

* was it helpful?
* to much text?
* is there something that could be added?

it's something new :)

**Comment by sinistral** [comment]
The new binaries for the 1.4.1 release work!  Thanks for the quick response.

I found the error page helpful; I appreciated the links to the Inspector and the GitHub issues page, which made it easy to submit the issue.
