### ISSUE TITLE
[Windows 10] pin-unpin breaks taskbar context menu

### ISSUE THREAD

**Issue by msphair** [yakyak/yakyak#540]
If you pin to taskbar, then unpin from taskbar, the next time you right click on the taskbar item you only get a "close" option instead of the full options with "pin to taskbar". You need to close the program and re-open it in order to pin it again.

**Comment by averissimo** [comment]
__Does this happen with other apps?__

I don't think we have any windows specific taskbar behaviour. It could be an `electron` bug (YakYak's framework)
