### ISSUE TITLE
Should we be worried about the Google Hangouts API Closing?

### ISSUE THREAD

**Issue by danmandle** [yakyak/yakyak#541]
I saw this story: https://www.engadget.com/2017/01/06/apps-that-rely-on-google-hangouts-wont-work-after-april-25th/

Looks like Google is closing the Hangouts API.

**Comment by Nefari0uss** [comment]
Here's the link on the Hangouts API page: https://developers.google.com/+/hangouts/support-faq

**Comment by NReilingh** [comment]
@Nefari0uss That seems to indicate that what's going away is the ability to do video calls via API. No idea if those are the same endpoints used by YakYak for text chat.

There are some other articles that may help to complete the picture:

* https://blog.google/topics/google-cloud/google-and-slack-deepen-partnership-help-teams-work-better-together/
* https://cloud.googleblog.com/2016/09/intelligent-tools-built-for-teams.html (end of article)

So it's abundantly clear that Hangouts is going to be an enterprise-focused video meeting product, and Allo/Duo are the consumer-focused text and video chat products. So the question is, what happens to the enterprise-focused text chat product? Does it go away? Does it turn back into GChat? Or are enterprises just supposed to buy Slack now?

**Comment by averissimo** [comment]
We don't use this Hangouts API in YakYak and according to https://github.com/tdryer/hangups/issues/293 we shouldn't be worried

yakyak/hangupsjs handles all communications between YakYak and google is based on tdryer/hangups.. and if they aren't worried I guess we should not be either ;)

**Comment by NReilingh** [comment]
Indeed — no need to be worried about YakYak not working after April 25th... But perhaps we can be a _little_ bit worried about whether text chat is part of hangouts in the future at all.

**Comment by davibe** [comment]
We are doing this for fun in our spare time and it's working because of the fun part. Google can shut us out any time, which is fun too in it's own way. So far the community has been able to keep up with changes and there is no obvious reason to think otherwise.

Worrying is a stop-energy which can make things less fun which in this case means breaking them.. so the answer to the questiuon is: NO 😄 

The discussion however has been interesting. Let's keep track of what happens.

**Comment by abe312** [comment]
maybe move to skype? They do have up to 25 people conference calls lol
