### ISSUE TITLE
Content not subpixel antialiased

### ISSUE THREAD

**Issue by gdamjan** [yakyak/yakyak#542]
Running yakyak 1.4.0-3 (AUR package on ArchLinux), it uses electron 1.4.13-1 from official Arch package.

The content text in yakyak is not subpixel antialiased. The menus on the other hand ARE subpixel antialiased.

At the same time, atom using the same electron dependency has subpixel antialiasing everywhere.

This is from Help -> About:
![screenshot_20170108_162119](https://cloud.githubusercontent.com/assets/81654/21750910/8660b334-d5be-11e6-844c-4d8aa909c4dd.png)

**Comment by gdamjan** [comment]
A word from the Help -> About in Atom. subpixel antialiasing can be easily seen. 

![screenshot_20170108_162334](https://cloud.githubusercontent.com/assets/81654/21750925/d52380aa-d5be-11e6-9774-fd6ca86b778e.png)

**Comment by brendanlong** [comment]
Seems like a problem with Electron: https://github.com/electron/electron/issues/6344

**Comment by gdamjan** [comment]
I did comment on that issue there. But at the same time it doesn't happen in Atom using the same Electron.

**Comment by gdamjan** [comment]
https://github.com/electron/electron/issues/6344#issuecomment-420371918
