### ISSUE TITLE
Leaking content in `convlist`

### ISSUE THREAD

**Issue by refack** [yakyak/yakyak#543]
in `convlist` message content is leaking between two `conv`s 🤔
Green circled word (כן Hebrew) is last line in `conv`
Yellow marked line (with the ® char) is realted to next `conv`
![yakyak screenshot 2017-01-09 002 markedup](https://cloud.githubusercontent.com/assets/96947/21774227/d9c5f36c-d65f-11e6-8847-f2a94cadf2ba.png)

**Comment by davibe** [comment]
It took a while but now i remember you :)
You're the guy from node4good/formage which i used briefly at work. I remember i also bothered you about some issue i had with it. What goes around comes around! 

Thank you for your report, I will have a look.

**Comment by refack** [comment]
an other one
![yakyak screenshot 2017-01-10 002](https://cloud.githubusercontent.com/assets/96947/21829137/73b26570-d762-11e6-9733-ec9c8a0c1506.png)
This time grabs some HTML https://gist.github.com/refack/0bc4e6732226da6e1d20cb1b934ca653

**Comment by davibe** [comment]
I am not able to reproduce yet

**Comment by refack** [comment]
I assume It a mix of unicode (®) ( 😍😍😍😘😘😘💖💖💖💕💕💕)  and Hebrew (?את הזמנת לי בורקס בבלו אפרון).
I'll try to trace/debug

**Comment by refack** [comment]
Can I get a hint, as to what's the entry point to the client process?

**Comment by davibe** [comment]
I have 2 users. If you can provide an exact sequnce to send from yakyak->hangouts and from thangouts->yakyak i can try.

I tried to copy-paste messages from your gist dump but was not lucky.

**Comment by davibe** [comment]
Can you please check if you have some kind of exception on "replaceChild" when this happens ? Thank you

**Comment by refack** [comment]
Not exception in console. my current assumption is it's a parsing issue in
`hangupsjs`

**Comment by refack** [comment]
seems like `ec1c6b4` with the `twemoji` fix resolved this, but I keep watching
