### ISSUE TITLE
Initials on some badges are not showing correctly

### ISSUE THREAD

**Issue by PSiAU** [yakyak/yakyak#547]
The badge with the initials on it are not showing correctly on the Mac version. In my case, there's only one conversation with the person named JK, but it's showing up for a whole bunch of other people.
![capto_capture 2017-01-10_02-02-05_pm](https://cloud.githubusercontent.com/assets/2519639/21792858/cfd1ba1c-d740-11e6-8c74-9dcfa00d2676.png)

**Comment by averissimo** [comment]
Please update to 1.4.1 (pre-release) and check if problem still persists.

ps. you seem to be using an older version that may lack some improvements on initials (at least the colored background)

**Comment by PSiAU** [comment]
Whoops I made a mistake, I am in fact on 1.4.1

**Comment by averissimo** [comment]
are you sure? those badges should look like:

![image](https://cloud.githubusercontent.com/assets/211358/21829586/e2c7a8ae-d78e-11e6-98c8-21081182b186.png)

anyway, can you open the Inspector and see if there is any error being thrown in the console tab?

**Comment by PSiAU** [comment]
I'm 100% positive i'm on 1.4.1
![capto_capture 2017-01-11_11-02-57_am](https://cloud.githubusercontent.com/assets/2519639/21829989/d8f76a3a-d7ed-11e6-8c5c-b0a0a593a9b2.png)

And yes there are errors in the console:
![capto_capture 2017-01-11_11-05-00_am](https://cloud.githubusercontent.com/assets/2519639/21829997/e7fa7072-d7ed-11e6-81e5-dcfd6b137bb3.png)

**Comment by averissimo** [comment]
sorry for insisting

those errors are relative to images that yakyak cannot retrieve so no luck there.

- is this problem recent?
- can you inspect some of the wrong initials' html elements using the inspector and see if they all have the same `data-id` and `initials` _(see screenshot 1)_
- does the html element have a `fallback` class? _(see screenshot 2)_

### Screenshot 1

![image](https://cloud.githubusercontent.com/assets/211358/21830551/60323772-d795-11e6-8062-20cd87c0b48f.png)

### Screenshot 2

![image](https://cloud.githubusercontent.com/assets/211358/21830587/b359866c-d795-11e6-9323-cc530f6c190d.png)

**Comment by PSiAU** [comment]
That's ok, happy to provide you with as much info as you need.
1) This was a recent problem, maybe as off v1.4.1 or 1.4 I can't remember exactly.
2) All the incorrectly displaying initials have different data-initials and data-id. Those values are correct but the actual HTML value is wrong.

![capto_capture 2017-01-11_11-46-29_am](https://cloud.githubusercontent.com/assets/2519639/21830846/c7cd2a28-d7f3-11e6-864f-13c0d9c5708b.png)

3) No fallback class is present on any of them.

**Comment by averissimo** [comment]
lol that is one strange element.

It should not have the `src` property and having conflicting initials is beyond me.

I'll probably ask you to test something soon

Thanks for reporting :)

**Comment by PSiAU** [comment]
Confirming that v1.4.2 has fixed the issue.
Many thanks guys and keep up the great work! :)

**Comment by averissimo** [comment]
@davibe how did you find that it would solve the problem? I'm in awe

**Comment by davibe** [comment]
I don't know. Some contents require authentication (cookies) and this may include user images. I fixed this for attachment (videos) and this got fixed too

**Comment by averissimo** [comment]
still the generation of initials and html element is not correct, I'm reopening it because of that

**Comment by davibe** [comment]
I think i wanted to close another one that was about images not bein fetched but I wrote the wrong number 🤣

**Comment by averissimo** [comment]
can't reproduce problem with initials, maybe it wasn't real
