### ISSUE TITLE
Something wrong with checksum for 1.4.1 ?

### ISSUE THREAD

**Issue by clapeyre** [yakyak/yakyak#550]
Hi there,

trying to install on mac using brew, says something is wrong with the checksum for 1.4.1. Tried twice, I get this error:

```bash
$ rm /Users/lapeyre/Library/Caches/Homebrew/Cask/yakyak--1.4.1.zip
$ brew cask install yakyak
==> Downloading https://github.com/yakyak/yakyak/releases/download/v1.4.1/yakyak-1.4.1-osx.zip
######################################################################## 100.0%
==> Verifying checksum for Cask yakyak
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 84ea0423d7262df947a3ae9162c75ba7f0d5d5451fd05e6e13bd8c921c76bacb
Actual: 8a65fbb2b15d9805341571a2d7aed60f68e2839932b77706fb6363b9bfc1c5e9
File: /Users/lapeyre/Library/Caches/Homebrew/Cask/yakyak--1.4.1.zip
To retry an incomplete download, remove the file above.
```

Strange, as I see in Homebrew that the formula is supposed to be up to date with 1.4.1

```bash
$ cd /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks
$ git log -1 -- yakyak.rb
commit 275a8efaf9fce34eaff49a60bdcd0fc2e83a2532
Author: Nick Butler <nick@codeindulgence.com>
Date:   Sun Jan 8 01:22:04 2017 +1100

    Update yakyak to 1.4.1 (#28726)
    
    * Fix checksum for yakyak
    
    * Update yakyak to 1.4.1
```

but I do agree with the sum being wrong:

```bash
$ shasum -a 256 /Users/lapeyre/Library/Caches/Homebrew/Cask/yakyak--1.4.1.zip
8a65fbb2b15d9805341571a2d7aed60f68e2839932b77706fb6363b9bfc1c5e9  /Users/lapeyre/Library/Caches/Homebrew/Cask/yakyak--1.4.1.zip
```

The archive seems OK though, I opened it and I get a working 1.4.1 app.

**Comment by davibe** [comment]
maybe we have updated the binary before release and the maintainer of the formula had already calculate the hash before in the attempt to publish a pre-release on homebrew.

I don't remember who is maintaining the homebrew formula.

**Comment by davibe** [comment]
How do i fix the brew formula ?

**Comment by clapeyre** [comment]
Oh well that's easy: replace the current sha256 checksum, which is:
`84ea0423d7262df947a3ae9162c75ba7f0d5d5451fd05e6e13bd8c921c76bacb`

by the accurate one:
`8a65fbb2b15d9805341571a2d7aed60f68e2839932b77706fb6363b9bfc1c5e9`

**Comment by clapeyre** [comment]
Oh wait, that's probably not what you meant...
Apparently this should have solved the problem, but was done on the wrong tarball? caskroom/homebrew-cask#28726

**Comment by davibe** [comment]
@averissimo this is why we should not swapping binaries once released. Next time we need to hotfix we create a new release number

**Comment by averissimo** [comment]
Ok!! good to know

**Comment by davibe** [comment]
I sent a PR. I close this in the meantime
