### ISSUE TITLE
Error on launch - Ubuntu 14.04

### ISSUE THREAD

**Issue by balihoo-mthurston** [yakyak/yakyak#551]
When launching the prebuilt 1.4.1 binary in ubuntu 14.04, I get a message "Possible Fatal Error on main process" notification in the main window. 

If I launch from the command line, the following is displayed.
`hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
Error on YakYak window:
 { columnNo: 60,
  error: {},
  lineNo: 85,
  msg: 'Uncaught TypeError: Cannot read property \'available\' of undefined',
  url: '/home/balihoo.local/mthurston/source/thirdparty/yakyak-linux-x64/resources/app/ui/dispatcher.js' } 
--- End of error message in YakYak window.
`

Let me know what logs you need.

**Comment by davibe** [comment]
Wait 10 minutes after this comment so that the binaries get refreshed then try to download 1.4.2 pre-release and let us know if this still happens. Thank you!

**Comment by balihoo-mthurston** [comment]
This no longer occurs in 1.4.2 pre-release.
Thanks!
