### ISSUE TITLE
New lines in message disappears

### ISSUE THREAD

**Issue by KusioST** [yakyak/yakyak#552]
![yakyak](https://cloud.githubusercontent.com/assets/25057693/21884798/17020f0c-d8b5-11e6-90cb-26a04c25895a.jpg)
On left message in YakYak on right oryginal from gmail.

**Comment by davibe** [comment]
which version are you using ? i am using 1.4.2 pre-release and this is the same screenshot

<img width="268" alt="screenshot 2017-01-12 18 34 16" src="https://cloud.githubusercontent.com/assets/123929/21900895/e19885c6-d8f5-11e6-8504-15b37d64fc72.png">

**Comment by averissimo** [comment]
Can't replicate it either

![outa2byey9vyo](https://cloud.githubusercontent.com/assets/211358/21913687/d35c1736-d925-11e6-9ac7-7c5bd9d216bc.gif)

**Comment by davibe** [comment]
I also tried copy-paste of a text. I close this for now.

**Comment by davibe** [comment]
Find a way to help us reproduce the issue :)

**Comment by KusioST** [comment]
You say something like "it works at my pc" and close my issue. I don't think that is a good way for improving software quality. 
I use Windows 8.1.  What else can by usefull for You?

**Comment by averissimo** [comment]
Can you provide a link to a zip of your compiled folder for me to try and replicate that in windows 7?

**Comment by averissimo** [comment]
nevermind, I was able to reproduce the problem

__How to replicate:__ Send a message with newlines via the android Hangouts app

@davibe I've sent you one

**Comment by averissimo** [comment]
@KusioST can you test the fix in #558 ?

```
git checkout -b averissimo-fix-line-breaks master
git pull https://github.com/averissimo/yakyak.git fix-line-breaks
```

**Comment by KusioST** [comment]
Thanks for Your attention. I will test it when I will be next to the computer..

What should I do? Just pull this new data and overwritte files in my YakYak folder?

**Comment by averissimo** [comment]
this 2 commands will create a new branch called `averissimo-fix-line-breaks` from master and pull the pull request.

when you want to go back to master, just do `git checkout master`

**Comment by KusioST** [comment]
OK. I got it, but I use windows version from this link:
https://github.com/yakyak/yakyak/releases/tag/v1.4.1

I don't know coffeescript. I just install SourceTree, download repo and try to execute commands from instruction:
$ npm install
$ npm run deploy
but nothing happens. Probably I need to install something before.

**Comment by averissimo** [comment]
Ohh as you said you use the latest from github, I thought you were building from source.

Please try v1.4.2 (pre-release). It has the fix included

**Comment by KusioST** [comment]
My bad. I download from here, but I donwloaded zip package for Windows.

Today I tested version with hotfix. Now new lines work correctly. I checked old conversation and do some new.

Thank You for resolve my problem.

**Comment by averissimo** [comment]
You're welcome and this solves the problem for the whole community.

Again, thanks for reporting!
