### ISSUE TITLE
Save zoom level

### ISSUE THREAD

**Issue by haluzpav** [yakyak/yakyak#554]
There is an option to Zoom in and out the whole UI (not just font). It would be good, if the selected level was saved and then loaded on next program start.

It could also be automatically set based on Windows' global scale settings or just on display's DPI.

**Comment by averissimo** [comment]
When zooming in it also zooms the images, what else are would you like to be "zoomed"?

![image](https://cloud.githubusercontent.com/assets/211358/21992183/675bf1ba-dc0d-11e6-8f7c-1622074de2f7.png)


![image](https://cloud.githubusercontent.com/assets/211358/21992187/69f1a852-dc0d-11e6-9c16-c366557ab714.png)

**Comment by averissimo** [comment]
however, it does not save the zoom level for the next startup. I didn't have time to support since making some changes in the menu to use default actions.

**Comment by averissimo** [comment]
sorry, I misread your initial comment :)

ignore my screenshots
