### ISSUE TITLE
A way to disable making alt toggle the menu.

### ISSUE THREAD

**Issue by that1communist** [yakyak/yakyak#556]
I use a window manager on linux called i3, and as a result i'm having to push alt a lot, and every time i push it when the window is selected, it toggles the menu, which is slightly annoying, having a way to disable this functionality, rebind the key to reveal the menu, or just keep the menu permanently there, would be great.

Thank you for all the hard work!

**Comment by that1communist** [comment]
Sorry to post here again, but is there any way I could do this just for myself? could someone point me to where alt is in the code, and could it just be changed to alt+m, which is pretty standard on linux, and would not mess up most peoples setups?

**Comment by averissimo** [comment]
can you see if pull request #479 works for you?

**Comment by that1communist** [comment]
@averissimo No, that doesn't fix the issue at all.

On release, alt always toggles the menu. Simply binding this to alt+m or something would entirely fix this behavior for me.
