### ISSUE TITLE
Periodic disconnect/reconnect problems

### ISSUE THREAD

**Issue by kk7ds** [yakyak/yakyak#56]
On 1.1.0, every few minutes, I get the "Not Connected" notification in the top right of the main window, followed by "Connecting". It seems to reconnect each time, but if messages arrive in the vicinity of this cycle, they show up on my phone but not yakyak for a while.

I'm on a wired ethernet connection, with lots of other things going on at once, so I think I can safely say that it's not actual network interruption causing the issue.

**Comment by ArchieT** [comment]
When I autostart it (in tray), when I click on the icon yakyak shows "Not Connected", when I click on "Not Connected" it changes to "Connecting" and after a few seconds "Connecting" also disappears.

**Comment by averissimo** [comment]
is this still an issue?

**Comment by kk7ds** [comment]
It was when I gave up on yakyak, but that was almost a year ago. Feel free to close from my perspective.

**Comment by averissimo** [comment]
I'm sorry about that. There have been many improvements since last year.

Maybe you can give it another go ;)

Closing this issue
