### ISSUE TITLE
The emoji for ":-)" / ":)" is mapped incorrectly and displays incorrectly

### ISSUE THREAD

**Issue by smkent** [yakyak/yakyak#562]
In Google Hangouts, typing `:-)` or `:)` translates to this: ![smiley-correct](https://cloud.githubusercontent.com/assets/2831985/22180497/a1090836-e026-11e6-8a78-42baf4539556.png)

Here's that emoji in the Hangouts emoji list (in Gmail):

![gmail-hangouts](https://cloud.githubusercontent.com/assets/2831985/22180538/6c957962-e027-11e6-96ca-74350fdbfcd3.png)

In yakyak, typing `:-)` or `:)` in the compose message box results in: ![smiley-incorrect](https://cloud.githubusercontent.com/assets/2831985/22180502/b93b9b80-e026-11e6-9985-bfad4c1428dd.png)

In addition, messages sent in Hangouts using that emoji (![smiley-correct](https://cloud.githubusercontent.com/assets/2831985/22180497/a1090836-e026-11e6-8a78-42baf4539556.png)) aren't displayed correctly in yakyak. For example:

![yakyak-message](https://cloud.githubusercontent.com/assets/2831985/22180525/1a3f8e64-e027-11e6-85c4-ddb77124e59a.png)

This is also the same in yakyak's emoji selector:

![yakyak-selector](https://cloud.githubusercontent.com/assets/2831985/22180549/a7ead58e-e027-11e6-9394-9ddcd4c5adb7.png)

**Comment by averissimo** [comment]
The mapping is done in `emojishortcode.coffee`

```
    ":)":"\ud83d\ude03",
    ":-)":"\ud83d\ude03",
```

It would be just a matter of changing :) to the "right" one.

The second problem you talk about is related to the font and not yakyak itself

Open http://getemoji.com/ in Chrome and you see the same thing happening with that emoji. I guess that is why the mapping is with ![image](https://cloud.githubusercontent.com/assets/211358/22297482/5205c3e0-e315-11e6-9dd8-3d369c755fc2.png)

**Comment by repros** [comment]
Hello smkent,

how did you make it to get those nice google emojis to yakyak emoji selector as shown in the picture above? I have only those awful ones coming from zip file and I am really not sure how to switch to these nice ones.

Please advise, otherwise I have to stop using YakYak. I want to have emojis same as when using hangouts in Chrome. I am running Windows 7 x64.

Thanks.

**Comment by smkent** [comment]
> Hello smkent,
>
> how did you make it to get those nice google emojis to yakyak emoji selector as shown in the picture above? I have only those awful ones coming from zip file and I am really not sure how to switch to these nice ones.
>
> Please advise, otherwise I have to stop using YakYak. I want to have emojis same as when using hangouts in Chrome. I am running Windows 7 x64.
>
> Thanks.

I didn't modify yakyak's emoji selector. I'm using version 1.4.2 on Linux, does yours look different?

**Comment by smkent** [comment]
@averissimo:

> The mapping is done in emojishortcode.coffee
>
> ```
>     ":)":"\ud83d\ude03",
>     ":-)":"\ud83d\ude03",
> ```
> It would be just a matter of changing :) to the "right" one.

I believe the correct escape sequence for `emojishortcode.coffee` should be `\u263a`, which is what `:relaxed:` is currently set to. If I type `:relaxed:` in the message compose window, yakyak converts it to the regular smiley Unicode character and it shows up as the standard smile emoji in Google Hangouts (![smile-correct](https://cloud.githubusercontent.com/assets/2831985/22180497/a1090836-e026-11e6-8a78-42baf4539556.png)).

I found the font file in the repository at `src/ui/css/noto-color-emoji/NotoColorEmoji.ttf`. I tried replacing it with an updated version [downloaded from here](https://www.google.com/get/noto/), but the emoji was still missing in yakyak. Does the font need to be modified with the missing image? (Is that easy / possible?)

**Comment by repros** [comment]
@smkent 

> I didn't modify yakyak's emoji selector. I'm using version 1.4.2 on Linux, does yours look different?

I am using latest release 1.4.1 (from [here](https://github.com/yakyak/yakyak/releases)) on W7 x64 and unfortunately I am having these very small and ugly ones:

![image](https://cloud.githubusercontent.com/assets/25402299/22423961/9e2e7bbc-e6f4-11e6-940d-b2b437b69a72.png)

I would really much prefer those you are having, but not for the price to switch to Linux :-) Is there a way please?

**Comment by averissimo** [comment]
I think that due to a windows specific issue, twemoji is used directly

**Comment by averissimo** [comment]
Twemoji was removed in a recent commit, can you try re-installing release v1.4.2 and test it out?

_note:_ install noto color emoji first from google https://www.google.com/get/noto/help/install/

**Comment by averissimo** [comment]
Twemoji was removed in a recent commit, can you try re-installing release v1.4.2 and test it out?

_note:_ install noto color emoji first from google https://www.google.com/get/noto/help/install/

**Comment by repros** [comment]
@averissimo thanks for hint. Unfortunately I have problem with installation of noto color emoji. In translation Windows says: 

"Unable to install NotoColorEmoji.ttf" The file NotoColorEmoji.ttf most probably is not a valid font. 

This happened when trying to right-click and Install on the TTF file. Same while dragging the file into Fonts in Control Panel. Only when I copied the file directly to C:\Windows\Fonts it copied the font file but I think it didnt install as I can see the ttf file only present in Directory, not in the list of installed fonts when browsing Fonts in Control panel. 

With this status I still tried to run v1.4.2 (downloaded now) and the result is even worse:

![image](https://cloud.githubusercontent.com/assets/25402299/22430947/29f39d42-e710-11e6-9d4d-c22583f2b51e.png)

**Comment by averissimo** [comment]
@repros tried it in my windows 7 VM and it fails quite miserable :\

I was able to replicate your error message, and tried alternate solutions, but it seems like colored emojis are not supported (without hacks and as we use them in YakYak) until Windows 8.1

We might need to bring back twemoji as a fix __if we are supporting windows 7__

If we do that, I'd like first to hear from a windows 8.1 and above if emojis are supported out of the box with this v1.4.2

**Comment by averissimo** [comment]
I think it would be better to create an exception for windows 7 and 8, instead of all windows versions (as it was until now)

**Comment by averissimo** [comment]
@repros let's move this discussion to #568

@smkent are you sure the new version has that updated emoji? I've also tried to update it, but it fails as you say

**Comment by averissimo** [comment]
@smkent https://github.com/googlei18n/noto-emoji/issues/90

Compiled from source has the same output, although the image file exists

**Comment by repros** [comment]
@averissimo thanks for your reply. it looks like I should wait for some solution/or next version of YakYak, right? or no way for me under W7? not sure what you mean under exception :-)

**Comment by averissimo** [comment]
@smkent the guys in noto-emoji were super helpful!!

check out the latest PR with the solution

**Comment by averissimo** [comment]
closing it, as it will be merged soon

@smkent please reopen if you find any bug, and thanks for reporting!! :)

**Comment by repros** [comment]
downloaded 1.4.2 today again, still black/white emoji. looks like i should wait :-)

**Comment by averissimo** [comment]
@repros track issue #568 for more information

Also been discussing in the comments of the commit that removed twemoji: https://github.com/yakyak/yakyak/commit/ec1c6b41583e712d3c2316f9812f7c832feeca34
