### ISSUE TITLE
Minimizing and then closing yakyak while the tray icon is active prevents yakyak from restoring

### ISSUE THREAD

**Issue by smkent** [yakyak/yakyak#563]
Steps to reproduce:

* Enable the yakyak tray icon
* Right-click the yakyak tray icon and make sure "Close to tray" is enabled
* Minimize yakyak
* Close the yakyak window from the taskbar (right-click and select Close)
* Click the yakyak tray icon

Expected behavior: yakyak restores normally

Actual behavior: yakyak does not restore, and the yakyak tray icon is unresponsive. Right-clicking the tray icon no longer produces the context menu. yakyak must be killed 

This seems to happen on both versions 1.4.1 and 1.4.2. I'm using the 64-bit version on Linux Mint with MATE. This behavior reproduces both with compiz and metacity.

**Comment by davibe** [comment]
@averissimo it's  linux thing, it's yours :D

**Comment by averissimo** [comment]
yeah I know :p already installed mate and I'll test it soon :)

**Comment by averissimo** [comment]
Real bug from electron, submitted it there https://github.com/electron/electron/issues/8525

**Comment by smkent** [comment]
I noticed that Slack on my work computer exhibits this same bug. I looked at Slack's about info and it says it also uses electron, so this being an electron bug seems plausible.

**Comment by averissimo** [comment]
I was able to reproduce it with a blank electron app as submitted in the electron's issue.

We'll have to wait for them to fix this :\
