### ISSUE TITLE
Tray icon does not turn green when new messages arrive

### ISSUE THREAD

**Issue by smkent** [yakyak/yakyak#566]
I'm using yakyak version 1.4.2 on Linux (both Linux Mint 17 and 18, binary compatible with Ubuntu 14.04/16.04, respectively).

If I have unread messages when I start yakyak, the tray icon is green and changes to gray when I read all of the unread messages (correct behavior).

If I have no unread messages when I start yakyak, the tray icon is gray (correct behavior).

If I receive a new message after yakyak is running, the icon does not change from gray back to green (bug).

(Filing a new issue for this, as requested in #432.)

**Comment by averissimo** [comment]
Screenshot showing that tray icon is not being updated

![selection_00498](https://cloud.githubusercontent.com/assets/211358/22434863/bad25fba-e715-11e6-9b47-ed76b6b6d761.png)

**Comment by averissimo** [comment]
should be solved in #567

**Comment by averissimo** [comment]
closing, as PR will be merged soon :)

again, thanks for reporting!! I was experiencing the same, but wasn't sure if it was my crazy build as it was not being reported
