### ISSUE TITLE
Emojis are appearing black & white in windows 7

### ISSUE THREAD

**Issue by averissimo** [yakyak/yakyak#568]
YakYak: v1.4.2
OS: Windows 7

This continues (slight off-topic) discussion in #562 

![image](https://cloud.githubusercontent.com/assets/25402299/22430947/29f39d42-e710-11e6-9d4d-c22583f2b51e.png)

@repros tried it in my windows 7 VM and it fails quite miserable :\

I was able to replicate your error message, and tried alternate solutions, but it seems like colored emojis are not supported (without hacks and as we use them in YakYak) until Windows 8.1

We might need to bring back twemoji as a fix if we are supporting windows 7

If we do that, I'd like first to hear from a windows 8.1 and above if emojis are supported out of the box with this v1.4.2

I think it would be better to create an exception for windows 7 and 8, instead of all windows versions (as it was until now)

**Comment by averissimo** [comment]
@repros we should fix this before the next release to maintain the status quo in Win7

Hopefully improving in Win 8.1 and 10 (supporting the Noto Color Emoji, out of the box)

Info to remind me later:

This could be achieved by adding twemoji support for win32 releases until 6.3 (where color emojis are supported)

https://msdn.microsoft.com/en-us/library/windows/desktop/ms724832(v=vs.85).aspx

**Comment by averissimo** [comment]
@msphair can you try current pre-release version in windows 10 and see if the Noto Color Emoji is being used? (i.e. hangouts style emojis)

**Comment by msphair** [comment]
@averissimo Cannot test because of https://github.com/yakyak/yakyak/issues/576

**Comment by msphair** [comment]
![image](https://cloud.githubusercontent.com/assets/1900880/22599852/23ea814c-e9ed-11e6-9603-c95398a6cba7.png)

Not great. Nothing shows up.

**Comment by averissimo** [comment]
Can you check the output of the Inspector's console?

plus I gotta get my hands on a windows 8.1 or/and 10 VM :)

**Comment by averissimo** [comment]
Got my hands on a Win10 and saw that nothing really appears. (same with console)

It is a stupid behavior, as the font itself cannot be installed, but electron accepts it (when win7 does not) but as it is not usable it creates an empty palette.

Good news is that windows default font can be used without any problems :)

We just have to find a way to detect the OS and prevent the installation of NotoColorEmoji in windows.

**Comment by averissimo** [comment]
@msphair can you test this build: https://github.com/averissimo/yakyak/releases/tag/v1.4.2-win10

It should remove the NotoColorEmoji font when using windows and default to 'Segoe UI Emoji'

**Comment by msphair** [comment]
Looks like it's fixed.

_I'm fine testing stuff out  (don't think I volunteered though, I just started posting issues =P). That being said, I've got my own software to write, so don't be upset when I'm not really responsive._

**Comment by repros** [comment]
hi should I still wait? or what is the situation around emoji in win7 now? thanks

**Comment by repros** [comment]
still nothing for win7?

**Comment by averissimo** [comment]
nop, sorry

**Comment by svandragt** [comment]
Still a problem.

**Comment by Kylir** [comment]
I confirm - Still a problem on Windows 7.

**Comment by JulesSauvinet** [comment]
:)

**Comment by hronir496** [comment]
I confirm - Still a problem on Windows 7, YakYak v1.5.1 (latest)
