### ISSUE TITLE
Any plans for OTR?

### ISSUE THREAD

**Issue by kingflurkel** [yakyak/yakyak#57]
Hi,

I was wondering if you're planning to do OTR in the future. Would that be a good thing to work on?

**Comment by algesten** [comment]
we haven't planned anything, but I'm
not against it. it is a feature of the protocol after all. how would you envisage it working? is it a setting per conversation or something you activate message by message?

**Comment by kingflurkel** [comment]
https://github.com/arlolra/otr
We could use this library. It should handle the OTR request and encrypt the messages. I'll try to get this working. Keep you posted.

**Comment by algesten** [comment]
Oh. That's a different OTR to the one I thought of :D ... Basically the google hangouts protocol has an OTR-flag setting for each message that, I think, makes it so that those messages are not recorded in any history. It doesn't however do any encryption. See flag here https://github.com/algesten/hangupsjs#sendchatmessage

If we do add encryption, it would be the first extension that is not compatible with bog standard google. That is probable worth a discussion of whether we want to go there. @davibe?

**Comment by maik-kulbe** [comment]
If there was encryption put into the client, there should be a switch to turn it off as well as a test whether this even makes sense with the client of the conversation partner - I've tried to use OTR on hangouts(over GTalk/XMPP back in the days) and most people get really annoyed if you send them gigantic OTR messages when they cannot decrypt them - and some people don't even know what that big strange textblob is supposed to mean...

**Comment by mkzero** [comment]
If there was encryption put into the client, there should be a switch to turn it off as well as a test whether this even makes sense with the client of the conversation partner - I've tried to use OTR on hangouts(over GTalk/XMPP back in the days) and most people get really annoyed if you send them gigantic OTR messages when they cannot decrypt them - and some people don't even know what that big strange textblob is supposed to mean...

**Comment by davibe** [comment]
@algesten It's an advanced feature. I am more concerned with the basics. If someone manages a proper pull requests i got nothing against merging it.

It does not sound very straightforward. OTR is something that needs to be enabled and negotiated (with custom messages ?) on a per-conversation basis. It can be enabled and disabled at will during the same conversation. The client should remember the conversation setting. If i remember correctly it's even possible that one person has it enabled while the other does not and they should still be able to talk. Not sure how this can work with groups (more than two people).
