### ISSUE TITLE
Typing a URL right before a close parenthesis results in the parenthesis incorrectly being added to the link target

### ISSUE THREAD

**Issue by smkent** [yakyak/yakyak#573]
Frequently I type messages in this format:

> Check out this thing (at http://example.com/)

Google Hangouts doesn't append the trailing ) to the URL:

![hangouts](https://cloud.githubusercontent.com/assets/2831985/22538460/56b89d10-e8c7-11e6-9759-0d4ff327429f.png)

yakyak does, which usually results in the link target being broken (since it's different than intended):

![yakyak](https://cloud.githubusercontent.com/assets/2831985/22538474/688a964c-e8c7-11e6-8bba-260125109837.png)

The second and third lines are incorrect; for example the Test 2 link target is `http://example.com/)` instead of the intended `http://example.com/`

yakyak's URL detection in composed messages should be updated to exclude trailing parentheses immediately following a URL.

(As a sidenote, Github's markdown renderer does the correct thing with these types of URLs -- see the example message near the top.)

**Comment by smkent** [comment]
I looked slightly deeper. yakyak seems to pass of URL parsing to [gajus/url-regexp](https://github.com/gajus/url-regexp), which exhibits the same behavior. The URL parsing regex just consumes characters until a whitespace character is found: https://github.com/gajus/url-regexp/blob/master/src/url-regexp.js#L56

I'm not sure what the correct solution is here. url-regexp hasn't been updated since 2015, is the project still active? Are there any other URL parsing libraries that yakyak should consider using?

**Comment by averissimo** [comment]
https://github.com/kevva/url-regex seems to do the trick

**Comment by averissimo** [comment]
@smkent can you see if the implementation is correct?

I also added support for links in messages without protocol. Example: `www.github.com`

**Comment by smkent** [comment]
This is definitely an improvement but it's not handling all the cases correctly. I wrote a more detailed comment on #573.
