### ISSUE TITLE
windows 10 1.4.2 pre-release freezes windows explorer

### ISSUE THREAD

**Issue by msphair** [yakyak/yakyak#576]
when I try to start it, explorer locks up and i have to kill explorer through task manager

**Comment by averissimo** [comment]
crap, v1.4.1 works?

**Comment by averissimo** [comment]
I can't figure out how this change in font would impact explorer

Link for v1.4.1

https://github.com/yakyak/yakyak/releases/tag/v1.4.1

Link for a custom build of v1.4.2 (with a previous version of electron 1.4.10)

https://github.com/averissimo/yakyak/releases/tag/v1.4.2-win10

**Comment by msphair** [comment]
Whoops. Looks like it was on my end. Smart Screen was preventing it from booting up (and preventing the older executable that I upgraded over from being deleted). Once I killed Smart Screen it booted up fine.

**Comment by averissimo** [comment]
ahh cool!! I'm closing the issue then

**Comment by msphair** [comment]
@averissimo I think this should be re-opened. With the release you sent me in #568 every time I close down YakYak, and then try to re-open it, `SmartScreen` starts up and blocks YakYak from re-opening. I end up having to manually kill `SmartScreen` and then YakYak opens up.
