### ISSUE TITLE
Reading/focusing a message does not dismiss Android

### ISSUE THREAD

**Issue by axxelh** [yakyak/yakyak#577]
Using YakYak the read status of messages does not appear synchronized as it does with the Hangouts web client. When a message is focused in the web client it marks the message as read on Android (dismissing the related notification).

YakYak doesn't appear to perform this status sync, leaving the message unread on Android (and presumably other clients).

**Comment by averissimo** [comment]
Can't reproduce this with either gmail hangouts client and android.

Conversation is marked as read correctly.

YakYak 1.4.2
Android 15.0.14110477

**Comment by axxelh** [comment]
I've done more testing, and I think the bug title is correct (Android dismissal), but my original comment is wrong by focusing on read status.

If I focus a conversation in YakYak, I do see the read status indicator on Android change (conversation is no longer bold). However, the associated notification is not dismissed. Focusing the same conversation in the web client both changes the read status and dismisses the notification.

Are the read status and notification status separate states? It seems only one is cleared.

**Comment by averissimo** [comment]
Seems "stupid" if they are separate states :)

I'll try to replicate this as soon as I can

**Comment by averissimo** [comment]
Can't reproduce. Did I miss any step on my test?

__System:__

- Open private browser with test account
- Open YakYak with main account
- Have main account setup in an android (4.4.2 -- Wiko)

__What I've tested:__

- Sent message from test account to main
- Unlocked phone to see if a notification was appearing
  - It was!
- Focused on conversation in YakYak
- Unlocked phone again to see that notification disappeared
  - It did!

**Comment by axxelh** [comment]
Thanks for testing, that's the basic sequence I'm using where it doesn't work, with a few caveats:

- I'm not unlocking the phone. I have Hangouts notifications set to show on the lockscreen, where they will dismiss when read in the web client (but not YakYak). That said, unlocking the phone has no effect for me on dismissing the notification.

- Today paying close attention I did see some notifications dismiss automatically, but not the majority (perhaps 1 in 10). One thing that is very different in my usage than your test is the number of messages received. The "stuck" notifications are when the sender has sent me multiple recent messages prior to my focusing YakYak. Is there some aspect of the read status that needs to be cleared per-message?

- "Focusing" the message in YakYak is somewhat vague for me. In some cases I'm in an active conversation in YakYak (i.e. the YakYak window is foreground, with the chat displayed in the pane). So the messages appearing as undismissed Android notifications are part of an active stream of conversation, not a one-off message.

I'll continue to try to narrow the repro case.

**Comment by averissimo** [comment]
I believe internally the read status is not per message, once the conversation is focused we say that to google and they return a last_read_timestamp

So I should test:

- Send several messages from test account to main
- See in phone if there is a new notification
- Focused on conversation in YakYak
- See in phone (unlocked stage) to see that notification disappeared

(do same test while yakyak conversation is already focused)

-- will do this later if you think this is a good scenario

**Comment by axxelh** [comment]
That sounds right, except I'd like to see you check with the phone locked and the notification on the lockscreen. I'm suspicious that the dismissal happens differently when Hangouts is in the foreground on the unlocked phone.

Also, is there any log I can capture here that might make the timing more clear? I'm happy to debug, just unsure where to start.
