### ISSUE TITLE
Option to disable animated conversation thumbnails

### ISSUE THREAD

**Issue by kethinov** [yakyak/yakyak#58]
Okay first thing's first, this app is cool! I'm gonna use it as my day to day hangouts client for a while, as it's already superior to Adium/Pidgin in my book. :D

The first thing on my wish list: I'd love an ability to disable animated conversation thumbnails. Yes I've got one of _those_ people on my contact list. ;)

**Comment by kethinov** [comment]
I've been poking around with the inspector and looking at Google's API and I have a possible solution.

Here's what I've learned:

Example profile pic: https://lh5.googleusercontent.com/-R7AuYVncPys/AAAAAAAAAAI/AAAAAAAAAIw/incUIqFokok/photo.jpg

That is @algesten's profile pic from the unit tests. With the URL constructed that way, you see the full size pic. If the user uploads an animated gif as their profile pic, that URL will be animated, despite ending in "photo.jpg" because the file returned from the server will in fact be a gif.

Nothing I found in the Google API seems to allow for disabling animations directly, but I did find an indirect way to do it. The UI in the app hardcodes profile pic sizes to 50x50 in the CSS. Accordingly, there is a Google API to request a "photo.jpg" sized at exactly 50x50.

e.g. https://lh5.googleusercontent.com/-R7AuYVncPys/AAAAAAAAAAI/AAAAAAAAAIw/incUIqFokok/photo.jpg?sz=50

Notably, when you request the profile pic using that method, that disables the animation.

It seems a way to offer the option to disable animated profile pics would be to request the image using the `?sz=50` flag. This would also have the side benefit of improving performance for anyone using this option (it would consume less bandwidth).

If anyone has any advice for how I could actually implement the setting, I'd be happy to submit a PR. Coffeescript is not my forte though so I don't even know where to begin.

All I can tell so far is that these 3 files have references to "photo.jpg":

- https://github.com/yakyak/yakyak/blob/46a78648ee63307883bfb079d9b2c65120bf0dc3/src/ui/views/convadd.coffee
- https://github.com/yakyak/yakyak/blob/165ca5831bf885e896cd814570e30a8c81ad1d43/src/ui/views/convlist.coffee
- https://github.com/yakyak/yakyak/blob/46a78648ee63307883bfb079d9b2c65120bf0dc3/src/ui/views/messages.coffee

And that if I wanted to add a checkbox to turn this feature on/off via the native menus I'd probably want to do it here:

- https://github.com/yakyak/yakyak/blob/11f17b505ee8a019fc928b11bb050b1df13d057b/src/ui/views/menu.coffee

What's not immediately clear to me is if I add an option to menu.coffee, how do I flag a global preference and then check for it in the various UI files where "photo.jpg" is referenced so that I can add an if statement to check for the preference and display a different "photo.jpg" depending on how the preference is set?

**Comment by arnriu** [comment]
@kethinov Check it out, please feel free to ask any question ;)

**Comment by kethinov** [comment]
I just tested that PR and it works great. Thanks!

**Comment by averissimo** [comment]
closing as this was implemented by @arnriu :)
