### ISSUE TITLE
YakYak named 'Electron' in Windows 10 Task Manager

### ISSUE THREAD

**Issue by clrg** [yakyak/yakyak#580]
Problem described in title. :)

Severity: as minor as it gets!

**Comment by averissimo** [comment]
thanks for reporting!

**Comment by davibe** [comment]
strange. Electron-packager bug ?

**Comment by averissimo** [comment]
probably need to add some properties (see PR #583)

https://github.com/electron-userland/electron-packager/issues/30

solved with

https://github.com/electron-userland/electron-packager/pull/63

**Comment by averissimo** [comment]
@clrg can you test current pre-release v1.4.2 it has been updated with PR  #583 that could fix this issue

it can be found: https://github.com/yakyak/yakyak/releases

cheers!

**Comment by averissimo** [comment]
@clrg can you test current pre-release v1.4.2?

**Comment by clrg** [comment]
It works properly in terms of it appears in the Task Manager as YakYak. However now I'm getting a random shortcut 'toast' appearing in my start menu which seems to be from the YakYak folder.

**Comment by averissimo** [comment]
It is something that has been reported in the past and is related to notifications (a fallback notification system)

**Comment by averissimo** [comment]
closing as the issue is solved
