### ISSUE TITLE
Window stays off screen after transition from dual display to single display remote desktop

### ISSUE THREAD

**Issue by alienlike** [yakyak/yakyak#581]
On Windows 10, if I transition from my dual display setup at work to a single display remote desktop connection, I can no longer use YakYak because the window remains off screen.

None of these tricks bring the window back into view:
- `Shift+Right Click` > Move
- `Win+Shift+Arrow`
- Restarting the app

**Comment by averissimo** [comment]
hummm, this could be as YakYak tries to restore the position of the window and does it off screen

**Comment by davibe** [comment]
we should check the bounds of the window are inside the bounds of the screen before restoring.
