### ISSUE TITLE
right click on windows 10 taskbar shows "Electron"

### ISSUE THREAD

**Issue by msphair** [yakyak/yakyak#582]
![image](https://cloud.githubusercontent.com/assets/1900880/22714855/4a64273e-ed43-11e6-9fe5-7f50ff7d684e.png)

**Comment by msphair** [comment]
to fix it I needed to "unblock" it: https://www.tenforums.com/tutorials/5357-unblock-file-windows-10-a.html

**Comment by averissimo** [comment]
v1.4.2 newest build should fix this.

**Comment by averissimo** [comment]
Does it still appear as Electron with latest build of 1.4.2 prerelease?

**Comment by classicboss302** [comment]
I was seeing the same thing, and the latest build no longer shows Electron.

**Comment by averissimo** [comment]
thanks @classicboss302 for the feedback, closing
