### ISSUE TITLE
Online presence dot in dark theme is very hard to see

### ISSUE THREAD

**Issue by classicboss302** [yakyak/yakyak#585]
It needs to stand out more, rather than being black on a dark background. It could be a colorful border around it or making it stand out more on its own.

**Comment by averissimo** [comment]
@classicboss302 can you propose a pair of colors (inside and border) :)

**Comment by classicboss302** [comment]
I would lean towards using the original colors as that keeps things consistent and would stand out fairly well. I think a border would only be needed if the color wasn't changed to something that stood out. In that case, a white border would provide contrast and help it stand out.

**Comment by averissimo** [comment]
How about

Normal sidebar

![image](https://cloud.githubusercontent.com/assets/211358/22743885/dc1c7662-ee1b-11e6-9cee-c253ee30b138.png)

Hover/Selected conversation

![image](https://cloud.githubusercontent.com/assets/211358/22743901/ee5b137e-ee1b-11e6-9cfa-be6f220d612f.png)

**Comment by classicboss302** [comment]
That looks good to me. Much easier to see.

**Comment by averissimo** [comment]
pull request #586 

thanks for reporting :)
