### ISSUE TITLE
No Contact List

### ISSUE THREAD

**Issue by mauricecox** [yakyak/yakyak#588]
would be nice if there was a contact list. I can't see/search for my friends.

**Comment by stealthgyro** [comment]
I would like to add as a google fi user, I have a bunch of phone numbers for SMS instead of contact names.

**Comment by averissimo** [comment]
@mauricecox can't you add using the + button on the bottom left?

@stealthgyro YakYak does not support google fi very well, we need a dev that uses it in a regular basis ;)

**Comment by marsh3gbsd** [comment]
Contact list would be awesome!  It would be great to be able to have a list that doesn't constantly move around.
