### ISSUE TITLE
Failure to Load

### ISSUE THREAD

**Issue by CHoorel** [yakyak/yakyak#590]
I have three installations of the most recent build using different accounts and they are all stuck at "loading".  They worked at first but after a few minutes they all went to loading. Different networks in different goegraphic locations as well.

**Comment by CHoorel** [comment]
I had success connecting to accounts that have a long chat history, but the accounts I was trying to use had never chatted with anyone.
As soon as I sent an invite to chat with someone from the browser, YakYak logged in immediately.  On another account that was hanging, the instant someone else sent me a message it logged in.  Must be looking for some sort of connection history to verify hangouts.

**Comment by averissimo** [comment]
Strange scenario but valid one.

Yakyak also lacks support to accept invites I think :\
