### ISSUE TITLE
FEATURE REQUEST: Video chat and share screen would be great impovement

### ISSUE THREAD

**Issue by ladafiala** [yakyak/yakyak#591]
I'm using hangouts as my main instant messenger. The present state of application is great, but I used to provide suport to mostly my family via videochat. So I would appreciate if anybody with the needed knowledge could add this feature to this project. Thank you Láďa

**Comment by fulltrucker** [comment]
Agreed, even if it was simply a button or icon that would initiate a video chat with that person in a browser. I believe this is how the Hangouts Chrome app currently works?
