### ISSUE TITLE
show status as online or show last seen timestamp

### ISSUE THREAD

**Issue by veasnalkj** [yakyak/yakyak#592]
Can YakYak report that I am online?  For users using anything other than the new hangouts app, I appear to be offline when I'm using YakYak, although I will still receive messages sent to me.

**Comment by darrenmcentee** [comment]
Similar to me, some of my contacts show an online status, even though i know they are offline.

**Comment by averissimo** [comment]
Different bugs you guys are reporting :)

@veasnalkj yours is probably a duplicate of #167 that I'm attempting to correct in #596

@darrenmcentee i've noticed yours recently with some of my test contacts being online (which haven't been online for more than a week)

**Comment by veasnalkj** [comment]
Thank you!  Yes, you’re correct.  Mine appears to be the same as #167.  Also, thanks for the response.  Just found YakYak about two weeks ago and I’m really enjoying using it.  Great product.

Lucas

**Comment by averissimo** [comment]
@darrenmcentee this should be fixed in latests v1.4.2 pre-release, please try it.

Closing this issue as @veasnalkj is a duplicate of #167
