### ISSUE TITLE
URL parsing problem

### ISSUE THREAD

**Issue by nerijus** [yakyak/yakyak#593]
I paste URL http://www.maps.lt/map/default.aspx#q=Pociuno%20g, then I click it in yakyak, http://www.maps.lt/map/default.aspx is opened.

**Comment by averissimo** [comment]
this is a bad conversion of the google redirect to a link, it seems to be scrapping the `#` portion

**Comment by averissimo** [comment]
This should be fixed by pull request #604 

Nice catch!

**Comment by nerijus** [comment]
It seems there is still a bug. If I open http://www.maps.lt/map/default.aspx#q=Pociūno%20g, it opens http://www.maps.lt/map/default.aspx#q=Poci%C3%85%C2%ABno%20g
