### ISSUE TITLE
Forgetting user names in user list

### ISSUE THREAD

**Issue by a-maze-d** [yakyak/yakyak#594]
For some reason the user list is sometimes forgetting about the users in the list and instead of showing the name of the person just shows `unknown`. Usually there are quite a few names that disappear.

It is possible to get the names back, but for that every single name needs to be clicked on (and the conversation opened). Once that's done the `unknown` name changes in the list back to the correct user name

**Comment by averissimo** [comment]
Can you provide a screenshot?

**Comment by a-maze-d** [comment]
I tried that while creating the ticket... but I only got an error back. So here is a picture (I took the part that does not contain sensitive information)
As you can see it impacts both the Favorite and the Recent list

Let me know if you need any more information

Cheers
Maze

**Comment by averissimo** [comment]
Can you upload the screenshot in github.com? _when doing it via email it does not show it_

![image](https://cloud.githubusercontent.com/assets/211358/23071791/71d141b2-f527-11e6-9803-98bc5bb0a285.png)

**Comment by a-maze-d** [comment]
![screen shot 2017-02-16 at 16 38 25](https://cloud.githubusercontent.com/assets/988563/23074663/6778a13a-f4ee-11e6-91c3-eebc0c09a094.png)

**Comment by a-maze-d** [comment]
System is MacOS (10.12.2), I have the impression that it happens especially after sleep/hibernate/restart/...

**Comment by averissimo** [comment]
can you open the inspector (ctrl + alt + i) and screenshot the console tab?

**Comment by a-maze-d** [comment]
I think a screenshot is overkill: It only states:
```
YakYak local version is 1.4.1, released version is 1.4.1
```

As you probably have realized from the screenshot, I have disabled all visual gimmicks in the name list, i.e. only the name is shown

**Comment by averissimo** [comment]
Lol ok, are these your options?

![image](https://cloud.githubusercontent.com/assets/211358/23075943/51d22638-f536-11e6-9db3-2601dd147c10.png)

I'll try to test on the next couple of days, but if it is dependant on Mac OS then it's @davibe territory :p

**Comment by a-maze-d** [comment]
yes those are my options:
![screen shot 2017-02-20 at 01 44 09](https://cloud.githubusercontent.com/assets/988563/23119755/57af5bc8-f70e-11e6-95ba-a81f43a34167.png)

**Comment by lcrist** [comment]
Also on Mac (10.11.6) using current stable build and most users are unknown, even my favorites. I can create a new conversation with them including their names, pictures, etc.  but existing ones just show Unknown? 

![screen shot 2017-04-09 at 2 04 41 pm](https://cloud.githubusercontent.com/assets/2856367/24839733/1532f750-1d2e-11e7-9bb3-da422d15fe48.png)

<img width="912" alt="screen shot 2017-04-09 at 2 07 12 pm" src="https://cloud.githubusercontent.com/assets/2856367/24839732/151c82b8-1d2e-11e7-8100-7a3b31963e21.png">

**Comment by a-maze-d** [comment]
Not sure why the stale bot marked this one as inactive and even closed it :-( This is still an issue and looking at the last comment it sounds like I'm not the only one that run into it :-(

ping @averissimo You answered/looked at the issue. Anything you want me to do to move this ahead?

**Comment by nsubtil** [comment]
I noticed this happens to me as well. Certain SMS contacts show up as a phone number only, while Hangouts displays a name.

**Comment by averissimo** [comment]
@nsubtil SMS contacts are shown as numbers, as that is the information we get from the hangouts server.. I think some different API must be called to get this information :\

@a-maze-d sorry for the lack of feedback, I'm kinda out of ideas on how to debug this as no error seems to appear on the inspector's tab

We've added a silent feature showing which contacts don't want to be seen in the inspector as the second screenshot from @lcrist shows. Can you check if after the "Unkown" contacts appear this list also shows "Unknown" ?

@davibe have you ever experienced this on Mac?

**Comment by averissimo** [comment]
@a-maze-d do you still get this?

if so, please try this release with extra debug symbols: https://github.com/averissimo/yakyak/releases/tag/v1.5.0-extra-debug

Start it from the command line with `yakyak --debug` or `./yakyak --debug` (depending on your Operating System

**Comment by a-maze-d** [comment]
Yes, I still get it. I'll install it next week.

**Comment by averissimo** [comment]
*(Oopps, hitted comment before finishing...)*

It will start with the inspector open, and you can see in the `console` tab many lines with `Conversation_list` prefix.

When you get `unknown` users, please:

- expand the last `Conversation_list`
- expand what I guess will appear as the `unkown` entry (in my screen shot is not unknown, but "João", the other participant in the conversation)
- expand the `entity` entry under the unknown
- expand the `participant` entry under the unkown

![image](https://user-images.githubusercontent.com/211358/35183157-9d3d424c-fde1-11e7-8403-383c14ee7bf8.png)

**Comment by a-maze-d** [comment]
Ok.

What's the best way to install it?

**Comment by a-maze-d** [comment]
Looked at it. I only now see you made a new release. Thx. Will install it

**Comment by a-maze-d** [comment]
Here the result:
![image](https://user-images.githubusercontent.com/988563/35189210-4bbc296e-fe46-11e7-9e18-fbf0d0f65e31.png)

**Comment by a-maze-d** [comment]
I'm happy to debug it more (set a breakpoint, if you help me to understand the general flow:
* here is a good place to put a breakpoint? 
* where should the name come from? I guess it's cached somewhere, or?

Interesting is that some conversations seem to be "unknown" but actually they are known like this one:
![image](https://user-images.githubusercontent.com/988563/35189344-c9889182-fe48-11e7-920b-ffade439619f.png)

As mentioned earlier, when clicking on the conversation the correct name is retrieved and unknown gets replaced with the correct details. Maybe the later case is one of those?
