### ISSUE TITLE
Windows 8.1 /w 1.4.2 - volume mixer icon oversized

### ISSUE THREAD

**Issue by draeath** [yakyak/yakyak#597]
As you can see in this screenshot, the icon is rendered oversize in the volume mixer, leading to some... interesting effects when YakYak is running.

![2017-02-18_1205](https://cloud.githubusercontent.com/assets/987449/23095118/a5b129ec-f5d2-11e6-9165-cee0cbfd19f0.png)

**Comment by averissimo** [comment]
lol

**Comment by averissimo** [comment]
This has been fixed in newest build of 1.4.2

I've tested in Windows 7, please let us know if it is solved

ps. using 32px icon in Windows (we were previously using 512px)
