### ISSUE TITLE
context menus

### ISSUE THREAD

**Issue by algesten** [yakyak/yakyak#6]
at least for cut/copy/paste

"There also are no context menus. I can't right-click to copy or paste in the message box."

**Comment by maxkueng** [comment]
I was looking for a "Copy link location" today when I tried to right-click a link. Context menus would be cool.

**Comment by PMiner** [comment]
https://www.sitepoint.com/building-custom-right-click-context-menu-javascript/

**Comment by averissimo** [comment]
implemented!
