### ISSUE TITLE
Consider using electron-builder for packaging

### ISSUE THREAD

**Issue by brendanlong** [yakyak/yakyak#601]
I found this after finishing my rpm/deb pull request. [electron-builder](https://github.com/electron-userland/electron-builder) can generate a bunch of package formats (including all of them that you currently generate) with significantly less code than you're using now.

> Numerous target formats:
>  * All platforms: 7z, zip, tar.xz, tar.lz, tar.gz, tar.bz2, dir (unpacked directory).
>  * macOS: dmg, pkg, mas.
>  * Linux: AppImage, snap, debian package (deb), rpm, freebsd, pacman, p5p, apk.
>  * Windows: NSIS, Web installer, AppX (Windows Store), Squirrel.Windows.

It also automates signing and uploading releases, if that's useful to you.

**Comment by averissimo** [comment]
That would be awesome!!
