### ISSUE TITLE
New Language - Hebrew

### ISSUE THREAD

**Issue by ozbarshalom** [yakyak/yakyak#606]
Hello,
This issue is to mention a new translate for YakYak - Hebrew

**Comment by ozbarshalom** [comment]
I have already translated YakYak to Hebrew, which branch should I push this to ?

**Comment by averissimo** [comment]
master!

**Comment by ozbarshalom** [comment]
I don`t have any permissions to push to Master branch..

**Comment by averissimo** [comment]
Ohhh sorry I misread your question.

You don't have permission to any branch, __you should create a pull request__ against master

See section "Creating the pull request" of  [this article](https://help.github.com/articles/creating-a-pull-request/#creating-the-pull-request) if you don't know how to.
