### ISSUE TITLE
Task Tray Icon Tiny on Linux Mint 18

### ISSUE THREAD

**Issue by sulbig** [yakyak/yakyak#610]
As the title suggests, the task tray icon for YakYak is tiny on Linux Mint 18 (see attached screenshot). Is there a way I can change the icon?

![tiny_yakyak_icon_on_linux_mint_18](https://cloud.githubusercontent.com/assets/20894156/23335324/f508ffdc-fb78-11e6-83c6-ae02897c3b02.png)

**Comment by sulbig** [comment]
I forgot to mention in the original comment that I am using version 1.4.1 on Linux Mint 18.1 (Cinnamon).

I know nothing about Electron apps, but I think I just figured it out. I had to change lines 23 and 24 of yakyak-linux-ia32/resources/app/ui/views/trayicon.js...

from:
```
   trayIcons = {
      "read": path.join(__dirname, '..', '..', 'icons', 'icon-read.png'),
      "unread": path.join(__dirname, '..', '..', 'icons', 'icon-unread.png')
    };
```

to:
```
    trayIcons = {
      "read": path.join(__dirname, '..', '..', 'icons', 'icon-read@2x.png'),
      "unread": path.join(__dirname, '..', '..', 'icons', 'icon-unread@2x.png')
    };
```

I then quit and relaunched the application, and the resulting read and unread icons match the size of my other task tray icons. Yea!

![fixed_yakyak_icon_on_linux_mint_18](https://cloud.githubusercontent.com/assets/20894156/23335448/53d6dc94-fb7b-11e6-802f-5a6c7eec1396.png)

**Comment by averissimo** [comment]
@sulbig great debugging, that's the exact fix!

This was reported a few days ago in #600 and I guess we already implement your fix in version 1.4.2 pre-release (or master branch)

We used a slightly bigger image than the @2x, __can you confirm that the solution works in Mint?__ (hopefully it won't appear huge :) )

ps. that's how you start understanding YakYak if you ever feel like helping out we welcome pull requests :)

**Comment by sulbig** [comment]
I just downloaded and tried the current master (thank you for the excellent README.md!). It appears the task tray icon is slightly larger than the rest (see screenshot below). I believe the `@2x` icons were sized better on my computer.

![yakyak-big-icon-on-linux-mint-18](https://cloud.githubusercontent.com/assets/20894156/23443228/f73efffa-fdf2-11e6-901d-ad03b637c615.png)

I saw where @mcanonic mentioned having a HiDPI monitor in #600. I too am using a HiDPI monitor at 3840 x 2160, and have my user interface scaling set to "Double (HiDPI)" in the Cinnamon DE.

If the icon sizing is potentially variable per user's OS or display configuration, perhaps this could be a user adjustable setting in the app.

**Comment by averissimo** [comment]
Do you have git skills?

try my branch called fix-trayicon-border and see how it looks

```
$ git checkout -b averissimo-fix-trayicon-border origin/master
$ git pull https://github.com/averissimo/yakyak.git fix-trayicon-border
$ npm install # if not already done
$ npm start
```

**Comment by sulbig** [comment]
I just tried the fix-trayicon-border branch. Could maybe have a tiny bit more border space, but it's looking better. Below is how it looks on my computer.

![fix-trayicon-border-test](https://cloud.githubusercontent.com/assets/20894156/24592633/7d36a68e-17df-11e7-98e2-c91fe2f09072.png)
