### ISSUE TITLE
online status in Pidgin (or other XMPP based apps)

### ISSUE THREAD

**Issue by mcanonic** [yakyak/yakyak#611]
Hi, 
my buddies from pidgin are not able to see me with "online" status. Are you going to fix it?
Thanks,
Massimo

**Comment by averissimo** [comment]
Hey,

Contacts are showing as online in google official hangouts clients and non-official. I think pidgin still uses the old and great XMPP before google switched to a proprietary protocol

I tried using last week, but could not login via pidgin, I guess we'll need a developer that can use XMPP and is able to figure this out

----

Some notes:

I guess the first step would be to use [hangups](https://github.com/tdryer/hangups) python client to login and see if the user is online on pidgin.

This is important, as our hangouts library is a child of this one, and if they can we can too!

If not, then that's kinda bad news as Hangouts is a proprietary protocol, so it would be required to reverse engineer what needs to be sent to the server to make the user visible in xmpp-based clients

**Comment by averissimo** [comment]
@mcanonic I changed the title a bit to reflect the contents..

I hope it's ok, if not please change it back or to a more correct description of the problem

**Comment by mcanonic** [comment]
The status is ok since even my buddies with empathy see me offline or with a weird status.
