### ISSUE TITLE
Feature Request: Initialize new conversation using keyboard shortcuts

### ISSUE THREAD

**Issue by stdavis** [yakyak/yakyak#613]
I'd love to be able to start new conversations without having to use the mouse. Something like:
1. `cmd+n` would open the start new conversation view.
1. The focus should be placed in a search box where I can begin typing the name(s) of my contact(s). `return` should add them to the conversation.
1. `cmd+return` would open the new conversation and place focus in the message box to allow me to type the first message.

This seems to fit into the new v2 mockups in #605.

Thanks for the great project!

**Comment by thumphreys** [comment]
Or if I could just type "@stdavis what's up duder" and it starts a new convo with stdavis and sends "what's up duder"

I'd like to help, but I don't know coffee script or webstack at all. :( ...maybe I'll learn.

**Comment by duttaditya18** [comment]
It would be amazing if this could be implemented.
