### ISSUE TITLE
Cannot see stickers sent by Chrome client

### ISSUE THREAD

**Issue by TauZero** [yakyak/yakyak#619]
YakYak 1.4.2, prebuilt binary

When receiving a sticker sent by someone using the standard Chrome client, only a small empty line is displayed. [example](http://i.imgur.com/TZ2UUsw.png)

If that user follows up immediately with a text comment, the empty line seems to disappear (i.e. there is no extra empty line). If I respond first, then the empty line remains.

**Comment by averissimo** [comment]
I confirm this, thanks for reporting!

**Comment by Beaupedia** [comment]
This one has been driving me a little crazy, the total loss of stickers. Thanks for reporting.

**Comment by Beaupedia** [comment]
Not really stale, it's definitely still happening.

**Comment by DavidJSmart** [comment]
This is still happening in 1.4.3.

**Comment by ao-copado** [comment]
I'm running 1.4.4 and stickers don't show up.

**Comment by averissimo** [comment]
added pinned tag so it won't be classified as inactive

Pull requests with fixes to this are welcome :)

**Comment by davibe** [comment]
@averissimo if you're not working on this assign it to me and send me a sticker :)

**Comment by averissimo** [comment]
Done! I'll review the assigned features and change them to reflect the reality :)
