### ISSUE TITLE
Hide on close instead of exit [OSX]

### ISSUE THREAD

**Issue by m1h4** [yakyak/yakyak#62]
Its common practice that applications which you want running in the background (like chat clients) don't exit when you click on the "close" title bar button but instead just hide the window (you quit the app by using the menu bar quit command or pressing its keyboard shortcut Command + Q).

**Comment by JavierQuerol** [comment]
+1

**Comment by davibe** [comment]
I think it's already like that isn't it ?

**Comment by davibe** [comment]
it's just not released, so it's going to be there in the next release :)
