### ISSUE TITLE
YakYak.desktop example on wiki is not valid

### ISSUE THREAD

**Issue by headius** [yakyak/yakyak#621]
I have successfully installed YakYak and I am now using it as my primary Hangouts client. Kudos on a great, simple, standalone app.

However I ran into trouble with the example YakYak.desktop file on the wiki at https://github.com/yakyak/yakyak/wiki

* The "Add" line is not valid .desktop syntax and until I removed that the file was not valid. I think this was an attempt to say "add these lines below" but it's all part of the same block of code. I can fix that myself, but wanted to clarify intent here.
* The binary files do not have icons in the same place as the source distribution, so I had to hunt around a bit. I ended up configuring mine to point at YakYak/resources/app/icons/yakyak-logo.svg.

My complete YakYak.desktop is provided below. Note I have not tried to build rpm/deb files, and it's possible they do this correctly.

```desktop
#!/usr/bin/env xdg-open

[Desktop Entry]
Name=YakYak
GenericName=YakYak
Comment=Electron App from git
Path=/usr/share/applications/YakYak
Exec=/usr/share/applications/YakYak/yakyak
Terminal=false
Type=Application
X-GNOME-Autostart-enabled=true
Icon=/usr/share/applications/YakYak/resources/app/icons/yakyak-logo.svg
Name[en_US]=YakYak
```

Again, kudos on a great app. I'm glad someone finally did this.

**Comment by headius** [comment]
Oh, other issue: the exec line in the example is wrong and needs to be a full path to the yakyak executable.

**Comment by headius** [comment]
Revised YakYak.desktop with a useful Comment:

```desktop
#!/usr/bin/env xdg-open

[Desktop Entry]
Name=YakYak
GenericName=YakYak
Comment=Chat client for Google Hangouts
Path=/usr/share/applications/YakYak
Exec=/usr/share/applications/YakYak/yakyak
Terminal=false
Type=Application
X-GNOME-Autostart-enabled=true
Icon=/usr/share/applications/YakYak/resources/app/icons/yakyak-logo.svg
Name[en_US]=YakYak
```

**Comment by davibe** [comment]
i updated the wiki trusting you 100%

**Comment by averissimo** [comment]
yakyak does not install to any specific directory in linux if I'm not mistaken, shouldn't it be something like:

?

what are you using to install?

```
Path=/home/my-username/some/folder/path/yakyak/
Exec=/home/my-username/some/folder/path/yakyak/yakyak
```

**Comment by headius** [comment]
@averissimo I did not see any canonical way to install yakyak until after I had just grabbed a prebuilt Linux tarball. I used the wiki to get it manually installed as a GNOME app and ran into this issue.

I installed yakyak under my applications dir just because I didn't know a better place. If there's a canonical place, that should be used in the .desktop file for packages, of course.

**Comment by headius** [comment]
@davibe @averissimo I generified the paths in the wiki a bit.

**Comment by averissimo** [comment]
yeah i understand your dilema, many places to place it `/opt/yakyak` or `/usr/local/yakyak` or `/usr/local/lib/yakyak`

Your changes seems great!

If we are able to switch our build framework to output deb, rpm, etc.. then this would become much better. There's a ticket open with that, hope someone picks it up!

**Comment by mxyzplx** [comment]
Just wanted to add to this:

If you want to have YakYak appear in your menu, in the YakYak.desktop file, add this line under Type=Application;

`Categories=Network;WebBrowser;`

Then the app will appear under the Internet options in your menu.

**Comment by averissimo** [comment]
@mxyzplx thanks, updated the wiki :)
