### ISSUE TITLE
Win 32 version not working?

### ISSUE THREAD

**Issue by DavidJSmart** [yakyak/yakyak#622]
Hi, I've downloaded 1.4.2, 1.4.1 and 1.4.0 of YakYak onto my wife's XP computer.  I downloaded the win32-ia32.zip version, which I assume should be OK for XP.  Windows reports that it's not a 32-bit program.  I also tried the win32-x64.zip version, with the same result.  

Should YakYak work with Windows XP?

**Comment by averissimo** [comment]
YakYak does not support Windows XP

Our underlying framework only support Windows 7 and up, see response here: https://github.com/electron/electron/issues/5676#issuecomment-221249905

**Comment by DavidJSmart** [comment]
Thanks for the response.  One more reason I need to get my wife's new PC up and running.  (It's sitting there.  I'm just being lazy.  :-)

**Comment by averissimo** [comment]
lolol!! I have the same problem with a Vista computer, hope to get some motivation soon
