### ISSUE TITLE
Archived hangouts are not hidden

### ISSUE THREAD

**Issue by DavidJSmart** [yakyak/yakyak#623]
I have two archived hangouts.  These are not shown on any of the Google Hangouts programs/apps (except when I look for archived hangouts).  However, they are shown in YakYak and I can't find a way of hiding the archived groups.

Am I missing something?

**Comment by davibe** [comment]
we don't have a way to reveal archived conversations so they just remain there for the moment. Feel free to improve this an submit a pull request

**Comment by DavidJSmart** [comment]
Thanks for the reply.  I'll do that.
