### ISSUE TITLE
what is the user-agent string?

### ISSUE THREAD

**Issue by wjcarpenter** [yakyak/yakyak#624]
This is mostly a matter of curiosity. I was checking my Google account security settings and was surprised to find recent activity from an iOS device (I have no iOS devices). I'm pretty sure it's yakyak that triggers that. It claims to be Chrome 53.x. I poked around the sources a little bit but didn't turn up any info.

**Comment by davibe** [comment]
yes, yakyak fakes a iOS client when it connects. This is an unofficial client so it does dirty things to get the job done.
