### ISSUE TITLE
Messages not being received

### ISSUE THREAD

**Issue by classicboss302** [yakyak/yakyak#626]
Sometimes while chatting with somebody, they will send a message that I get on my phone, but not in YakYak. Restarting YakYak will show the messages in the history. 

I am using the latest 1.4.2 client on Windows 10.

**Comment by davibe** [comment]
not all connected clients are updated at the same time. It's possible that if you waited a bit longer the message was going to arrive.

If not then maybe there was a connection problem but either way it's difficult to track it down without more information or a reliable way to reproduce it.
