### ISSUE TITLE
User Thumbnails on SMS Conversations

### ISSUE THREAD

**Issue by cwilli34** [yakyak/yakyak#63]
I use hangouts a lot for SMS conversations from work.  The Chrome Hangouts app doesn't combine the accounts, but the app on Android does, so when I chat from my phone, I have to pick which account of that person I want to talk to, their phone (SMS), or their Google account.  Both the Chrome app and the phone app syncs the thumbnails for those users in my contacts.  

Right now I am just seeing a lot of the blue default thumbnail icons.  It would be great to be able to sync up these thumbnails to the appropriate user contacts, whether they are SMS or Google accounts.

**Comment by algesten** [comment]
i have no idea even where to start doing such a thing

**Comment by victorstuber** [comment]
@algesten In hangouts on the web, my sms conversations don't have avatars, but it does show the name of the person I'm talking to. Yakyak only shows the phone number. Isn't there a way to retrieve the name from hangouts?
