### ISSUE TITLE
Toggle accounts

### ISSUE THREAD

**Issue by mitchwillman** [yakyak/yakyak#634]
It would be nice to be able to toggle between different google accounts.

**Comment by davibe** [comment]
If you expect multiple accounts to be connected at the same time (i.e. receiving notification of account 1 while using account 2) this is a duplicate of #13 

If you suggest to have completely separated accounts and logging in one by one this could be easier to do but I am not sure how much appealing it would be

**Comment by justinsalsburey** [comment]
+1
