### ISSUE TITLE
Animated gifs are sent without animation

### ISSUE THREAD

**Issue by albert-prv** [yakyak/yakyak#636]
When copying or dragging an animated gif from the browser, the gif is sent without animation

**Comment by averissimo** [comment]
this is an upstream problem :\ the framework that we use (elecron) does not support gif

![image](https://cloud.githubusercontent.com/assets/211358/25015781/34feb23c-2075-11e7-9ddd-dc216451946e.png)

I think it works if the file is uploaded using the upload selector, can you test this? @albert-prv

**Comment by nitrocode** [comment]
@albert-prv I noticed this too when copying gifs from giphy into yakyak. 

@averissimo I uploaded a [gif](http://i.imgur.com/Odcl6Of.gif) and it worked as expected. Kind of a pain though. 

Here is the trackable issue https://github.com/electron/electron/issues/5078
