### ISSUE TITLE
bug - requesting history on initial sign in

### ISSUE THREAD

**Issue by dhniels** [yakyak/yakyak#637]
Not sure if you'll be able to replicate the bug but on the first opening of the app and authenticating, chat histories would not load and this status was persistent until i quit and relaunched the app, at which point it would then work appropriately and load chat history.
![screen shot 2017-03-23 at 3 22 09 pm](https://cloud.githubusercontent.com/assets/7034022/24271111/8f66a142-0fdd-11e7-87ee-66ef89905796.png)

**Comment by averissimo** [comment]
can you open the inspector and see if there is any exception?

have you tried switching conversations and return to this one?
