### ISSUE TITLE
Page up, page down, home, end key, and up/down arrow key support in conversation view

### ISSUE THREAD

**Issue by kethinov** [yakyak/yakyak#64]
Page up, page down, home, end key currently do nothing in the conversation view. It would be nice to have them scroll the conversation view in a manner similar to other chat clients.

The up/down arrow keys cycle through previous messages, which is good when the input box is focused, but it should scroll the conversation view up and down when the conversation text is focused.

**Comment by maxkueng** [comment]
I'm not sure it's a good idea to override the behavior of the home, end, left, right keys when the input box is focused. They all serve a purpose when writing text. Home and end are to jump to the beginning or end of a line, and the up and down keys are for moving between lines when editing multi-line or line-wrapped text. Changing their behavior may frustrate a lot of users (including me).
