### ISSUE TITLE
Support for hangouts built-in ascii emotes

### ISSUE THREAD

**Issue by jwhipp** [yakyak/yakyak#641]
This is a feature request to support the Google Hangouts text emotes such as /tableflip or /facepalm.

As semi comprehensive list can be found in this news article:

https://www.engadget.com/2016/09/23/google-hangouts-adds-emoticon-shortcuts-for-easy-table-flipping/

**Comment by averissimo** [comment]
can you build yakyak? I'm quite sure that you can just add this to src/ui/emojishortcode.coffee and then change the emoji regex expression src/ui/util.coffee
