### ISSUE TITLE
Feature Request: Unseen indicator for messages

### ISSUE THREAD

**Issue by Viper007Bond** [yakyak/yakyak#642]
When viewing a conversation, it's not easy to tell which specific messages are new since last viewing. For example if I have it minimized to my tray and then open it, the conversation that opens is just shown in front of you and you're required to remember which messages you have read and which you haven't.

Potential solutions include different message colors for unseen messages or a horizontal line across the window showing where you last left off.

**Comment by averissimo** [comment]
this would be a cool feature!!

There is a last_seen_timestamp information that is accessible in the client API (what we use to set the 'others' avatar in the conversation.

This could be used somehow and remembered for a while _(even after it is updated)_
