### ISSUE TITLE
Fails to connect on debian testing

### ISSUE THREAD

**Issue by dougunder** [yakyak/yakyak#645]
I can't get it to load. This is the output
Hangs at either connecting or loading contacts
hugh@peanut:~$ /opt/yakyak-1.4.2-linux-x64/yakyak 
Gtk-Message: Failed to load module "atk-bridge"
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
2017-04-06 10:59:14 INFO subscribe failed ETIMEDOUT

**Comment by averissimo** [comment]
@dougunder are you using a brand new account without any hangouts conversations?

**Comment by dougunder** [comment]
No, existing account with years of history.
I installed the dep to make the atk-bridge warning go away.

Still not loading

**Comment by averissimo** [comment]
there is another issue from way back that was related to a proxy issue #88 - could it be related?

2. 

If not, try the first 'dumb' approach that is to remove `~/.config/yakyak` directory to see if it was a corrupted file

3.

Can you add a line with `client.loglevel('debug');` in yakyak/resources/app/main.js after line 52

and run it again which should output more debugging information.. then copy it here and don't forget to __censor your personal information from the log__
