### ISSUE TITLE
Font gets larger when changing colour scheme

### ISSUE THREAD

**Issue by Cam0Cow** [yakyak/yakyak#646]
The font size menu still shows the size as it was before (medium).

Version 1.4.2 on Mac OS

**Comment by jwhipp** [comment]
I see this behavior on WIndows 10 and Linux, as well.  You can reset the font size just by selecting the font size again after changing the scheme.

**Comment by eternalstarfire** [comment]
I am seeing this issue on YakYak v1.5.3 Windows 10 64-bit.
