### ISSUE TITLE
"A JavaScript error occured in the main process"

### ISSUE THREAD

**Issue by slikts** [yakyak/yakyak#650]
win10, yakyak-1.4.2-win32-x64
Uncaught exception: Syntax error

This went away after I deleted `%appdata%\yakyak`.

**Comment by averissimo** [comment]
please report it back if it evers happens again. with more information on the exception (location in code, what were you doing, anything relevant)

**Comment by slikts** [comment]
I would have reported it if there had been any more information.

If it helps, the problem started after I had to power cycle my PC, so it might be a corrupted file.

**Comment by NotSoShaby** [comment]
I got the same error.  
worked fine yesterday, don't recall doing anything special. 

![image](https://user-images.githubusercontent.com/26500236/32050912-49bf3d42-ba5b-11e7-87a0-3c7909561e52.png)
