### ISSUE TITLE
Logout does not work

### ISSUE THREAD

**Issue by inliquid** [yakyak/yakyak#653]
On my Windows 10 system this function just does not work. Nothing happens when pressed.

**Comment by davibe** [comment]
have you tried 1.4.2 pre-release ?

**Comment by inliquid** [comment]
Well, I'm using 1.4.2 release.

![](https://i.gyazo.com/96d8c010f5f73ae2ed384d3193358d1e.png)

**Comment by averissimo** [comment]
nice @davibe !
