### ISSUE TITLE
Conversation font bold after upgrade to 1.4.3

### ISSUE THREAD

**Issue by joshuacant** [yakyak/yakyak#657]
System: Windows 10 x64

Hi, after upgrading to 1.4.3 from 1.4.2 the font seems very bold. I've attached an image showing a sample message, at the "Medium" size with no zoom applied. I'm not sure if this is intentional or not, but I kinda liked it the way it was. Thanks to all the contributors for all your hard work, and I like the new borderless window a lot.

![capture](https://cloud.githubusercontent.com/assets/1975723/25058079/f02a9534-2143-11e7-9918-7a330af9d05e.PNG)

**Comment by xamphear** [comment]
Hi, not trying to be a pest, but I don't want this to get autoclosed. I've gotten used to the bold font since it's been 3 months now, so if this change was intentional then go ahead and close the ticket as wont-fix.

**Comment by averissimo** [comment]
not intencional, this is actually pretty strange

**Comment by joshuacant** [comment]
At this point, I'm completely used to it. If no one else is reporting it, it could be something unique to my installation causing it. I'm going to close the issue.
