### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by mshaler** [yakyak/yakyak#66]
After authenticating with Google on the pre-built Mac OS X binaries:

Uncaught Exception:
SyntaxError: Unexpected token }
    at Object.parse (native)
    at loadFromFile (/Applications/Yakyak.app/Contents/Resources/app/node_modules/hangupsjs/node_modules/tough-cookie-filestore/lib/filestore.js:148:32)
    at new FileCookieStore (/Applications/Yakyak.app/Contents/Resources/app/node_modules/hangupsjs/node_modules/tough-cookie-filestore/lib/filestore.js:14:5)
    at Client.module.exports.Client.doInit (/Applications/Yakyak.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:183:49)
    at new Client (/Applications/Yakyak.app/Contents/Resources/app/node_modules/hangupsjs/lib/client.js:102:12)
    at Object.<anonymous> (/Applications/Yakyak.app/Contents/Resources/app/main.js:33:12)
    at Object.<anonymous> (/Applications/Yakyak.app/Contents/Resources/app/main.js:350:4)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)

**Comment by kethinov** [comment]
I've seen this too.

**Comment by rbaert** [comment]
I'm seeing the same issue on Windows 7 64bit

**Comment by ihabunek** [comment]
Same on Win10. After dismissing the error two yakyak.exe processes remain hanging and need to be killed.

**Comment by averissimo** [comment]
can anyone describe the procedure to reproduce this error?

**Comment by rbaert** [comment]
For me all I do is right click on yakyak.exe and select Open.  during startup I get the error message and I'm left with two processes running, but no UI.

**Comment by averissimo** [comment]
seems like a syntax error in some node module :\

**does this happen with latest version v1.3.3?**

does it still happen if you remove/rename the `yakyak` configuration folder in the path below (this is where all YakYak definitions are stored, so you'll need to re-authenticate):

![image](https://cloud.githubusercontent.com/assets/211358/20309906/ba0a1bbe-ab41-11e6-83b1-a173fc213708.png)

**Comment by averissimo** [comment]
@rbaert can you try 1.4.0-beta3

see #451 for the download link

**Comment by averissimo** [comment]
closed due to lack of feedback

please try 1.4.0 before reopening this issue

**Comment by hypercube33** [comment]
This happened to me on Windows 10 x64, 1703 using YakYak 1.4.3 - same exact symptoms.

**Comment by averissimo** [comment]
It seems like a problem from a library yakyak uses, @davibe what do you think?

@hypercube33 does it happen often? how do you solve it?

**Comment by Riebart** [comment]
This started happening to me on Windows 10 1703 (15063.608) a day or two ago. Wiping the install folder and unpacking the latest beta results in identical behaviour.

Steps to reproduce:
- Try to run YakYak.exe (1.4.4 x64)

Expected behaviour: YakYak opens
Actual behaviour: An error popup with "A JavaScript error occurred in the main process. Uncaught exception: SyntaxError: Unexpected token"

**Comment by fishzle** [comment]
A workaround to delete %APPDATA%\yakyak\Cookies* and then you can re-login and yakyak will start.

These are the 3 files to delete.
```
LastWriteTime           Length Name
-------------           ------ ----
10/11/2017   2:56 PM     11264 Cookies
10/11/2017   2:56 PM         0 Cookies-journal
13/11/2017   4:54 PM      4094 cookies.json
```
Yes, cookies.json is all in lowercase, the others are in Sentence Case. I didn't touch any other files.

Windows 10.
Yakyak 1.4.3.

If i compare a working yakyak vs a non-working yakyak.
I see that a working yakyak has XML in cookies.json and is 4159 bytes
I see the broken yakyak has cookies.json filled with NULs and is 4094 bytes.
