### ISSUE TITLE
Notification pop-up position

### ISSUE THREAD

**Issue by antosheek** [yakyak/yakyak#661]
Hello, sorry if this isn't the right way to ask, but is it possible to move the pop-up notification from top right to bottom right, like most software does, including original hangouts?
Didn't find it in the options.

used on windows.

Thanks!

**Comment by averissimo** [comment]
We use Windows native notification methods, not sure if this can be done.

with versions >=  8
https://github.com/mikaelbr/node-notifier#usage-windowstoaster

< windows 8

https://github.com/mikaelbr/node-notifier#usage-windowsballoon

__Which windows version are you using?__

ps.

![image](https://cloud.githubusercontent.com/assets/211358/25147894/ea5750c2-2470-11e7-9e33-96da70c28ba8.png)

**Comment by antosheek** [comment]
I use windows 8.1 .) 
I know the original google hangouts popped on right bottom, chrome does etc.

**Comment by averissimo** [comment]
We use a third party library that handles the notifications in each platform _(windows, mac os x and linux)_ and have little control on how they do this. 

We like this solution as it gives native notifications in each operating system without any additional work. 

However this also makes it less flexible to be configured. Probably the original google hangouts implements it from scratch (or via Chrome) and as such moved it to the bottom right :\

**Comment by antosheek** [comment]
Ah, so nothing ot do with that. Well, I guess I can get used to it. Thanks for the replies :-)
