### ISSUE TITLE
Basic Keyboard Functionality

### ISSUE THREAD

**Issue by thumphreys** [yakyak/yakyak#669]
Can we get a hotkey for "add new conversation"? When it goes to the new conversation page, can we focus the search box so we can start typing. Currently you have to click the plus, then click the search box.

Ideally, you can hotkey to add new conversation and just start typing the person's name, hit enter, then start typing a msg to that person. 

This seems like its the natural flow of using a chat program. Setting this stuff up should be pretty easy, right?

(also, is there a way to only see people you "know" in the new conversation selection list. I keep getting a bunch of people I don't know.)

**Comment by averissimo** [comment]
That part of the interface needs a revamp, I agree with you on all points!!

**Comment by thumphreys** [comment]
Awesome, If I knew coffee script. I'd dive in:)
