### ISSUE TITLE
Add swedish language

### ISSUE THREAD

**Issue by Sjoo90** [yakyak/yakyak#673]
Add swedish language

**Comment by averissimo** [comment]
Can you translate it?

All you need is to translate the right part of following json file:

for example _(in Portuguese)_:

     "description": "Cliente de Desktop para Google Hangouts",

https://github.com/yakyak/yakyak/blob/master/src/locales/en.json.template

**Comment by Sjoo90** [comment]
Hi!
I have already translated it, but I cannot commit and push it to master?

Skickat från min iPhone

**Comment by averissimo** [comment]
You can submit a pull request from your fork of the project.

Do you know how to do it?

If not here are the steps:

- Create a fork of yakyak/yakyak
- Add a remote in your local git repository to the newly created fork
  - `$ git add remote sjoo90 <http/ssh link to fork>`
- Push changes to your fork
- Create a pull request from those changes
  - https://help.github.com/articles/about-pull-requests/

__As an alternative you can share here a link to the file and I'll push the changes__

**Comment by Sjoo90** [comment]
Now i think I have solved it i right way :)

Skickat från min iPhone
