### ISSUE TITLE
'Do not save history' feature is not working with YakYak

### ISSUE THREAD

**Issue by inliquid** [yakyak/yakyak#675]
In Hangouts chat it is possible to turn off saving of chat history. It seems that when the feature is on, hangouts just periodically cleans up messages from chat, so they can resist for just few hours or 1-2 days. However when these messages sent via YakYak they seem to stay forever. Maybe there should be some special flag or something. The chat setting is only available in Hangouts web/mobile app. 

See also https://github.com/yakyak/yakyak/issues/664

**Comment by inliquid** [comment]
Wow please don't close.

**Comment by LuizJa** [comment]
Actually I was here to say exactly the same but I was looking first in the previous issues before to make sure other people have the same problem.
Yes, even though the chat, one-to-one or a group one is marked as history off it keeps the record but only if people are using yak yak.
For instance. I have a multichat with other 4 people, 3 of them uses hangouts via web and other one and I uses yak yak, all of us have the history off but only the messages typed used yak yak aren't deleted. I don't know if it is an issue or you didn't simple configure it.

**Comment by averissimo** [comment]
Yakyak does not respect the "of the record" property of a conversation.

I'm waiting on something to run, I'm going to give it a go and try to solve it now :)

**Comment by averissimo** [comment]
done in #769 .. compile and test it or wait until it is merged and included in the pre-releases :)

closing the issue, please continue the discussion there
