### ISSUE TITLE
Connectivity Issues

### ISSUE THREAD

**Issue by jwhipp** [yakyak/yakyak#677]
I'm seeing a lot of connectivity issues with YakYak today (which also happens to be the API take down day), wondering if anyone else is seeing them?

It's restricted to YakYak, nothing else on my machine is having any network issues, so I've been able to rule out my own network as a suspect.

**Comment by jwhipp** [comment]
Forgot to note that, even when connectivity is there, I see delays in sending.   Like it's having trouble to connecting to an api gateway or w/e it is you connect to.

**Comment by averissimo** [comment]
I saw that yesterday being unable to send messages.. had to restart yakyak and worked fine since.

I'll also try to monitor this

**Comment by jwhipp** [comment]
Well it's been almost a week and the problem hasn't happened so I guess it was just that particular day so I think we can close this out.
