### ISSUE TITLE
Sent images always saved to Google Photos account

### ISSUE THREAD

**Issue by mantismu** [yakyak/yakyak#678]
Would love an option to stop the app from saving every image sent through the client to my Google Photos account. I happened to check my Google photos account after using YakYak to find every silly meme or screen shot I'd sent sitting there in my Camera library.

**Comment by averissimo** [comment]
I believe this an hangouts feature, not much that can be done as the images are stored in google photos

do you think there's an alternative? I don't enjoy this either for the same reasons :)

**Comment by RSchwoerer** [comment]
I just noticed this today. I'm not sure this is a hangouts feature. 
A quick test by closing yakyak and just using 'https://hangouts.google.com/' does not upload any images sent to 'https://photos.google.com/'.

Is this something yakyak is doing directly, or maybe a "feature" of the API being used?

**Comment by averissimo** [comment]
it's probably a feature of API being used, which was retro-engineered.

Maybe there's a way to flag it, a good starting point would be to see if tdryer/hangups has any option for it
