### ISSUE TITLE
Title bar dot menu draws over contact name in small window size

### ISSUE THREAD

**Issue by jwhipp** [yakyak/yakyak#680]
I've only seen this on the Windows version, I am on Windows 10.   I recently updated YakYak, and I have always have used it in a small Window.   As of v1.4.3 the DOTs menu now draws over the contact name when the window size is small.

My suggestion, make the contact name always stay just to he left of the dots menu, so it would move with the screen size below a certain threshold or just keep it just to the left of the dots all the time.

I think it would look nice to have the contact name just to the right of the three line menu as well, either way.  
![dots menu in title](https://cloud.githubusercontent.com/assets/556332/25677918/20a35ac8-3005-11e7-87df-4e8ecbba602a.PNG)

**Comment by averissimo** [comment]
I can confirm the bug also in linux when window is very narrow.

You are noticing it on this update because we went borderless on windows thanks to @Sazpaimon great work

We need to figure out a way of tweaking the css to avoid this type of overlap

**Comment by Sazpaimon** [comment]
Yeah I knew this would be a problem going in, but I wasn't sure how many people would actually have their window that thin. I can try looking into it this weekend.

**Comment by jwhipp** [comment]
I didn't see this on Linux, for me the latest build continues using the Mutter provided title bar (at least in Gnome Shell).

**Comment by Sazpaimon** [comment]
That's intentional, only Windows will draw the window like this (see #211). Linux will draw the window border due to the unpredictability of how different window managers handle borderless windows.

**Comment by jwhipp** [comment]
I gave this some thought, it actually likely doesn't matter on Linux what window manager is being used.  You could do a little detection then provide your own borders just like this app does:

![selection_001](https://cloud.githubusercontent.com/assets/556332/26261528/bee3b4cc-3c8e-11e7-98c8-c49502f2ad9a.png)

App shown is Google Desktop Music Player: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-
