### ISSUE TITLE
Connecting...

### ISSUE THREAD

**Issue by cjohnson92** [yakyak/yakyak#681]
I cannot seem to establish a connection between the program and Google. After entering in my credentials, I am in a perpetual connecting phase with no option to reenter account information or otherwise. 

OS: Windows 10 N
YakYak v14.4.4 and v1.4.3 

What I have tried:

- Uninstall and reinstall with different versions
- Disabled all firewalls
- Installed on my macbook (macOS sierra) with same results, except I can access navigation for the program to logout and try the connection again or a different account (did both which yielded the same results)

Any and all help would be greatly appreciated!

**Comment by zaphod777** [comment]
check this issue
https://github.com/yakyak/yakyak/issues/640

**Comment by roncemer** [comment]
I'm having the same problem.  Just installed the newest version two days ago, and it looked as if it was going to work.  Now it just hangs at "Connecting" with the three animated dots below it.

Come on, folks.  Can't we get a WORKING Hangouts client for Linux?  You know, something reliable, because I need this for my work.

**Comment by zaphod777** [comment]
You need to have at least one chat in hangouts before connecting. Go to the web ui and start a chat with anyone and then it should connect.

**Comment by averissimo** [comment]
@roncemer does @zaphod777 tip solves the problem?

if not can you press `Ctrl + Alt + I` and check if there are any exceptions on the console tab

**Comment by gluons** [comment]
Me too. Just install this in my (K)ubuntu laptop via snap. And get "Connecting..." forever.

Nothing in devtools console.
![_001](https://user-images.githubusercontent.com/4688092/32039769-06e0044a-ba59-11e7-9db2-82e0e80e93c4.png)
