### ISSUE TITLE
macOS: Spell checking while typing

### ISSUE THREAD

**Issue by marculein3000** [yakyak/yakyak#683]
This is probably more of a question: Is it possible running Yak Yak on macOS to activate spelling correction of the OS?
THX

**Comment by conceptualspace** [comment]
yes,

`"chromium-args": "--enable-spell-checking"`

**Comment by tiagonunocosta** [comment]
Where can i put this line ? Thanks

**Comment by conceptualspace** [comment]
needs to go in package.json

**Comment by ruzz311** [comment]
I've added the property to my package.json and tried running it ```npm run electron app``` and also tried building it ```npm run deploy:darwin``` and I do not get any spell-checking.   Runs and builds successfully and logged in fine.  

![instruction unclear](https://cdn.meme.am/cache/instances/folder237/63955237.jpg)

**Comment by conceptualspace** [comment]
oops had a brain freeze and forgot yakyak is electron-based and not nwjs-based

evidently that command line switch is not supported in electron (https://xwartz.gitbooks.io/electron-gitbook/content/en/api/chrome-command-line-switches.html)

looks like electron has a low level way of implementing spellcheck support:

**Comment by conceptualspace** [comment]
also for reference https://github.com/electron/electron/issues/3189

**Comment by ylluminate** [comment]
Thanks for those references. This is a super important function to have implemented. Seems like we need to put some pressure upstream to show that at least people really are looking for this. Same thing plagues Rambox.

**Comment by averissimo** [comment]
duplicate of #61 , please continue discussion there :)
