### ISSUE TITLE
convert (y) to thumbsup emoticon before sending message

### ISSUE THREAD

**Issue by robkorv** [yakyak/yakyak#684]
Hi, I just switched to yakyak and it's great.

Are you interested in converting some chars to their emoticon alternative before sending the message. For example in WhatsApp and the Google Hangouts webclient, (y) gets converted to :+1:.

Would be great if yakyak would mimic this behavior. I'm sure there are more to add but (y) is the one I use frequently.

Tnx for yakyak :smile:

**Comment by averissimo** [comment]
This will be available in 5-15 minutes in the v1.4.4 prerelease :)
