### ISSUE TITLE
Windows 10: Duplicate Notifications on Single Message (v1.4.4)

### ISSUE THREAD

**Issue by daniel-nicholson** [yakyak/yakyak#685]
I've noticed that when one of my contacts messages me, the notification  has been duplicated after "x-ing" it out or a few seconds of inactivity. Just today, notifications are now being tripled on a single message. Yak Yak v1.4.4 is minimized on the taskbar. 

Unfortunately I can't capture a screenshot as the message gets replaced with a new message after the old one is x'd or timed out.

**Comment by ptitboogy** [comment]
Hello I have the exact same things.
How can we help you to solve this issue?

**Comment by danbob** [comment]
I just noticed the same problem on Linux (Ubuntu 17.04 x64). Looks like it happens on macOS as well per #663.

**Comment by averissimo** [comment]
We are updating the external libraries soon _(including the notification)_ with one of the pending pull requests.

I hope this will solve this problem.

**Comment by averissimo** [comment]
Can someone try v1.5.0 (pre-release)?

**Comment by Scott-Cam** [comment]
I'm using V1.5.1 and having this issue on and off, seems to go away after reboot for a while and then starts again (hours/days after restarting the PC)

**Comment by DerEros** [comment]
Still seeing the issue with 1.5.4 on Windows 10.
