### ISSUE TITLE
[Linux Mint 18.1][yakyak 1.4.4 prebuilt binary] Does not run without sudo

### ISSUE THREAD

**Issue by clxcoltz** [yakyak/yakyak#687]
On Linux Mint MATE 18.1/amd64, running ./yakyak just returns... nothing (straight back to command line). Strangely sudo ./yakyak or gksudo ./yakyak works well, but for obvious reasons it's a bad idea to run my preferred chat client as root all the time. Since there's no output I don't even know where to look for clues, any idea? 

In case it helps, terminal output from sudo ./yakyak: 

hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0

**Comment by tsogkas** [comment]
I have been facing the same problem (UbuntuGnome 16.04) when trying to connect from work. Could it be anything firewall-related?

**Comment by averissimo** [comment]
super strange.. can you try to run the following commands:

(if this still persists)

```
killall yakyak
killall yakyak
./yakyak --debug
killall yakyak
killall yakyak
./yakyak --debug
```

**Comment by tsogkas** [comment]
Thanks @averissimo. Indeed the problem was that ~/.config/yakyak was owned by root. I fixed that and now it's working!

**Comment by averissimo** [comment]
@clxcoltz the problem that you have should be the same, reopen the issue if it not :)
