### ISSUE TITLE
View options not saved after logout

### ISSUE THREAD

**Issue by uman242** [yakyak/yakyak#688]
View options - 
- view->show tray icon
- view->conversation list
- view->pop-up notifications
are not saved after logout. I have to set it again after next login.
Win7 x64 YakYak v.1.4.4

**Comment by uman242** [comment]
well, maybe I should refresh this issue somehow

**Comment by averissimo** [comment]
can you check the developer console to see if there are any exceptions being thrown

1. Ctrl + Shift + I (and then open the browser tab)
1. Switch that option and then see if anything appears in the console tab

Try renaming/removing the yakyak folder (this could be some permission issue) at `'C:\Users\<User>\AppData\Roaming\yakyak`

**Comment by uman242** [comment]
I deleted 'C:\Users\<User>\AppData\Roaming\yakyak and run Yakyak, then I did logout-login
Did You mean this console?
![screenshot - 2017-09-19 10_34_29](https://user-images.githubusercontent.com/22954424/30583140-6f65eef8-9d26-11e7-86f2-58032708ec1c.png)
Windows console shows this
![screenshot - 2017-09-19 10_36_11](https://user-images.githubusercontent.com/22954424/30583158-7baa4f60-9d26-11e7-9c22-d15265cb2e5d.png)

It didn't work.

**Comment by averissimo** [comment]
exactly those two consoles :) 

anything appears below `connected 0` ?

**Comment by averissimo** [comment]
It does not seem to be any exception being thrown.
