### ISSUE TITLE
Notification removal

### ISSUE THREAD

**Issue by flexbed** [yakyak/yakyak#689]
I'm using YakYak v1.4.4 on Ubuntu 16.04 with Gnome-shell v3.18.5 and noticed that desktop notifications aren't removed when you open/focus YakYak window, causing that when "notification center" is open, there's countless notifications from already "read" messages.
For the sake of clarity, I'll try to make an example out of Spotify notifications:
When a new song starts playing a notification appears, if it's not clicked but the Spotify main window is focused notifications are removed.
Sorry if it's not clear, I'm not native English speaker.

**Comment by dhitchcock** [comment]
It's clear, and bugs me too.

![screenshot from 2017-06-27 11-58-03](https://user-images.githubusercontent.com/2146072/27600049-486e7424-5b30-11e7-910b-0c569dd5166b.png)

those are not all separate conversations, that's just one conversation with one person.

**Comment by danbob** [comment]
It looks like this is an issue with the node-notifier library: https://github.com/mikaelbr/node-notifier/issues/188

**Comment by flexbed** [comment]
I believe that the app should withdraw the notification when focused, as opposed as being transient.
At least that's the behaviour I'm familiar with.

PS: I'll take a shot to fix/add the code if someone point me in the right direction.

**Comment by averissimo** [comment]
node-notifier module really needs an update in yakyak, the version we are using is very old ( https://goo.gl/x3KrV5 )

I believe the call to generate notifications is here: https://github.com/yakyak/yakyak/blob/master/src/ui/views/notifications.coffee#L80

**Comment by averissimo** [comment]
pull request #760 should solve this

**Comment by eigoor** [comment]
Installed with the changes from the pull request and so far it looks good. I will report back after I've used it some more.

**Comment by flexbed** [comment]
I'm too busy right now to test it, anyway, I'll close the issue when the pull request gets merged. Right?

**Comment by averissimo** [comment]
I don't like keeping two issues opened at the same time, let's move further conversation to the pull request and close this for now.

If after the pull request the problem still happens then it can be reopen or a use a new one.
