### ISSUE TITLE
Linked google voice number.

### ISSUE THREAD

**Issue by DanaMW** [yakyak/yakyak#690]
When I send text to a text number with my linked google voice number through yakyak the message shows in yakyak greyed out like it was not sent yet. It DOES show in my account in say a browser hangouts box in gmail (Firefox) - but never arrives to the person intended. Is this a short coming of yakyak, a bug or intended? I imagine you don't support the voice number in any fashion since i cant pull up contacts other than someone listed as a hangout contact. Since I am new to your fine program I am trying to work out its limitations to see where to go from here. Thanks for the program and any info your willing to provide.

**Comment by ZackBoe** [comment]
Been seeing this occasionally.  
Interestingly, messages via YakYak show up in Hangouts as being "to" myself, whereas messages sent via Hangouts itself are "to" the proper recipient. Dunno if this is related, but thought it'd be worth mentioning.

![yakyak-gvoice](https://cloud.githubusercontent.com/assets/904055/26476496/4c759afa-418d-11e7-9d02-74af2bc5b811.png)

**Comment by DanaMW** [comment]
Yes this happens when i used it with my voice number but I assumed it was just the behavior of the program. Any sent or received text also includes a user entry for myself.

**Comment by timothynott** [comment]
I see this behavior as well. The message is getting to Hangouts, but it is not also sent back to the originating phone number.

[Parrot](https://github.com/avaidyam/Parrot) has this figured out, so perhaps their approach can be implemented.

**Comment by that1communist** [comment]
This should not be closed, because this is still a major bug.

**Comment by averissimo** [comment]
There's a pull request that should help with google voice.

Can someone test it out? I can also build the binaries

**Comment by nsubtil** [comment]
I see this as well. Would be happy to test the new branch, but I'm not set up to build.

@averissimo, can you post a link to a build I can use?

**Comment by averissimo** [comment]
@nsubtil see this post: https://github.com/yakyak/yakyak/pull/738#issuecomment-330591692

Please provide feedback in that page instead :)
