### ISSUE TITLE
Messages with only images not sending notifications

### ISSUE THREAD

**Issue by Refrash** [yakyak/yakyak#691]
If a message is received that has no text, only an image, no notification will come up, including the sound. The official Hangouts extension will, however send a notification.

**Comment by averissimo** [comment]
@Refrash pull request #775 solves this, can you build and test it?

Cheers,

**Comment by Refrash** [comment]
I actually don't know how to do that. Sorry, I'm new to GitHub and I'm not well versed in coding.

**Comment by averissimo** [comment]
Try this release :)

https://github.com/averissimo/yakyak/releases/tag/v1.4.4-notifications

**Comment by Refrash** [comment]
That seems to fix it for me. Thanks!
