### ISSUE TITLE
Pasting text breaks UI

### ISSUE THREAD

**Issue by jeffgaynor** [yakyak/yakyak#694]
Pasting more than 15-20 lines of text breaks the UI. The only way to recover is to restart the app. See attached screenshot.

<img width="700" alt="yakyak_and_new_issue_ _yakyak_yakyak_and_inbox_ _jgaynor1_gmail_com__12_530_messages_" src="https://cloud.githubusercontent.com/assets/508871/26694678/d9ecc7ec-46cd-11e7-8ed0-ae58b8acbfb9.png">

**Comment by hypercube33** [comment]
I've seen this too, thought it was related to PS code but this makes sense.

**Comment by averissimo** [comment]
Should be solved __today__ in the pre-release v1.4.4 :)
