### ISSUE TITLE
Request: Option to disable Mac OS X dock icon bounce

### ISSUE THREAD

**Issue by matkam** [yakyak/yakyak#696]
It would be great to be able to disable the Mac dock icon bonce. The pop up notification is enough.

**Comment by averissimo** [comment]
@davibe osx is your thing :p

**Comment by Behodar** [comment]
Any news on this? I ended up building my own copy of 1.4.4 without the bounce, but I've just updated to 1.5 and it's back... and there doesn't seem to be an option to stop it.

**Comment by Behodar** [comment]
Still there in 1.5.1 :(

For anyone else that wants to disable this, you need to edit Contents/Resources/app/ui/views/notifications.js line 123, changing flashFlame(true) to flashFrame(false).

**Comment by Behodar** [comment]
I've just updated to 1.5.10 and the bounce is back, and there's no longer an 'app' directory under Contents/Resources. How do you disable bouncing in this version?

**Comment by averissimo** [comment]
We need someone to add this option to the interface. The temporary fix should be the same as you commented above.

**Comment by Behodar** [comment]
The temporary fix isn't the same as there is no longer a notifications.js file. It seems that maybe everything's been bundled into a single file called app.asar but I'm not sure how to open/edit it (I've tried a couple of editors and they both choke on its enormous size).

**Comment by averissimo** [comment]
I've added this option on  a test build, please test if the option works, it's under view -> notifications -> Flash/bounce icon on new messsages

https://github.com/averissimo/yakyak/releases/tag/v1.5.12-bouncy-icon-option

**Comment by Behodar** [comment]
That's done it. Thank you very much!
