### ISSUE TITLE
Support corporate proxies by allowing users to specify a trusted SSL root certificate

### ISSUE THREAD

**Issue by ivanatpr** [yakyak/yakyak#698]
For people behind HTTPS corporate proxies yakyak currently does not work. These proxies will dynamically generate replacement SSL certs for HTTPS connections which use the company's own root certificate, which is included as a trusted root certificate in the system-wide cert store of all of the company's PCs. 

Since yakyak does not appear to use the systemwide cert store, the connection to hangouts fails, causing an endless loops where it seems like yakyak tries to connect, fails, closes (crashes?), and then automatically starts up again and tries again, repeating the same pattern. 

In order for this to work, if yakyak isn't going to use the systemwide cert store, then there needs to be a way for users to specify a trusted cert. An example of this Firefox, which keeps its own cert store but allows you to import certs into it.

**Comment by averissimo** [comment]
thanks for reporting this.. yakyak itself does not implement or specify any store, this is done via npm request module under hangupsjs (the underlying library)

are you using a linux or mac? (i'm not 100% sure about windows) 

if so, starting yakyak from a command line with the following should force the use of the proxy

```
$ HTTP_PROXY='<http proxy>' HTTPS_PROXY='<https proxy>' yakyak
```

note, it might require the full path to yakyak as in `/path/to/yakyak`

**Comment by vmus** [comment]
This worked for me. https://stackoverflow.com/a/21961005/1283098

**Comment by Curros** [comment]
@vmus where you change the code?

**Comment by vmus** [comment]
@Curros, in `resources/app/main.js`:
```
app.on('ready', function() {
  process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```
or just start with `NODE_TLS_REJECT_UNAUTHORIZED=0 ./yakyak`
