### ISSUE TITLE
Can't create new conversation via keyboard (an error has occurred)

### ISSUE THREAD

**Issue by dsemaya** [yakyak/yakyak#699]
I like Yakyak a lot but the process of creating new message threads has been challenging for me.

In iMessage you can create a new conversation by typing command-N, then start typing the person's name, then pressing return to confirm that person, then pressing the tab key to begin typing the message.

In Yakyak there appears to be no way to initiate a new message from the keyboard (command-N or otherwise).  

Once you press the green plus button (the worst part of material design) the keyboard focus isn't even in the search field, so you have to click a second time within the "search people" box.  

Then when the results come in they appear below the box which moves it upwards, making the results a moving target.  Ideally the box would be at the top of the window to begin with like iMessage.  

From there you still need to click on a participant.  In fact, if you press the tab key while typing in that box it immediately throws "an error has occurred" message up that seems to require relaunching the app to remove.  

If you don't make that mistake you still need to click on the participant, then click on OK, before you can start typing your message.  

Shouldn't this all be doable via the keyboard?

Thanks for listening.

**Comment by averissimo** [comment]
it should!

this part of yakyak should be revamped :\

looking for volunteers :)
