### ISSUE TITLE
Unify menu templates

### ISSUE THREAD

**Issue by maxkueng** [yakyak/yakyak#70]
This issue came out of a discussion in PR #47.

We currently have two different menu templates with >90% the same content. One for OSX and another one for all other platforms.

It would be nice if they could be unified into one template with platform-specific exceptions. Using the `CommandOrControl` accelerator could be of great help. It automatically uses `Command` on OS X and `Control` on Linux and Windows. Maybe there could be some kind of DSL to create the menu.

**Comment by davibe** [comment]
I wrote that i think. I found it not worth trying to abstract all of that. You can try though, just submit a pr if you do
