### ISSUE TITLE
Can't login using Google App Passwords

### ISSUE THREAD

**Issue by devhen** [yakyak/yakyak#700]
I can't login using app passwords generated on this page

https://security.google.com/settings/security/apppasswords

Are they not supported? Thanks

**Comment by averissimo** [comment]
Seems like a no :\

Yakyak hangouts backend must use some api that does not allow for those.

**Comment by devhen** [comment]
This is a big problem IMO. I would love to use yakyak. As it stands, there's no way I'm typing my Google password into a 3rd party application. It needs to support app passwords.

**Comment by Stonehawk** [comment]
... Yeah. Bump. This isn't cool. Is there truly no way to code around this?
