### ISSUE TITLE
My messages showing in two different conversations

### ISSUE THREAD

**Issue by cron410** [yakyak/yakyak#702]
I am in two different group hangouts and this tuesday, most of my replies in one hangout were duplicated into another group hangout, however the timestamps of the erraneous messages show a week prior (i think). This had not happened previous to using YakYak. I can send screenshots of the messages privately. I am using 1.4.4 after upgrading from 1.4.3

**Comment by averissimo** [comment]
@cron410 this is super strange, it is still happening?

**Comment by cron410** [comment]
Sorry I forgot to update the ticket. I haven't used yakyak for months now. I can try again on that same computer. Windows 10 x64 with native display scaling on by default.

**Comment by averissimo** [comment]
No other reports so it must be one of those strange flukes.

If you wish to give yakyak another go, please try :)

otherwise close the issue and this is here for reference in case it happens again
