### ISSUE TITLE
Large string without spaces will push the entire conversation

### ISSUE THREAD

**Issue by sneila** [yakyak/yakyak#705]
https://beemapp2.s3.amazonaws.com/2230840f-6265-4c6c-98b7-577abade09a0.jpg

self explanatory.

**Comment by averissimo** [comment]
@sneila could you provide a string for testing, I can't replicate

**Comment by sneila** [comment]
Unfortunate, it was a copy paste of an error message in the Chrome console. 
It's a string that can not be escaped/just look at the picture above, or try something like this:
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[['[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[//'//'[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]

**Comment by averissimo** [comment]
I asked for it because I could not replicate, same with that example, it breaks into several lines without a problem

![screenshot from 2017-09-19 16-39-17](https://user-images.githubusercontent.com/211358/30601161-2cb6fbb4-9d59-11e7-9c13-dc4c09ab5de6.png)

**Comment by sneila** [comment]
Hi, the error still persists on OSX:
http://b3.ms/lrXMD8GQMb1j
this i tested yesterday before i sent the string to you.

I also have the latest version:
http://b3.ms/06j9dDLW9abK

**Comment by averissimo** [comment]
Wow!!

I just replicated this on v1.4.3 downloaded from releases, but not when compiling from the source.. Which is very strange.

This problem (whatever it is) is corrected in prerelease v1.4.4 , can you confirm?

**Comment by sneila** [comment]
Yes, 1.4.4 seems to sort this out. Yeee :)
Thank you for the hard work.

**Comment by averissimo** [comment]
Cool, closing the issue
