### ISSUE TITLE
Pin conversation

### ISSUE THREAD

**Issue by marsh3gbsd** [yakyak/yakyak#706]
It would be amazing if you could pin conversations with specific people to the top of the list.  That way the commonly used ones don't move around.

**Comment by slackerbob** [comment]
You can "Favorite" conversations, using the 3 dot drop down, then selecting Favorite.

All your favorite conversations are pinned to the top, exactly like you're asking for.

**Comment by averissimo** [comment]
great answer @slackerbob 

closing the issue
