### ISSUE TITLE
Re-order conversations?

### ISSUE THREAD

**Issue by augmentedfourth** [yakyak/yakyak#707]
The Web client lets you pin conversations to the top, order by who's currently logged in, etc. Can YakYak implement that? I'm on OSX, but that probably doesn't matter for this particular feature request.

**Comment by augmentedfourth** [comment]
Any help here? Is this even possible? I'd like to keep this issue alive if there's a chance of implementing conversation re-ordering/grouping in YakYak.

**Comment by marsh3gbsd** [comment]
Pinning is available.  If you select a conversation, click the three dots, you can "Favorite" the conversation.  

Allowing different sorting than alphabetical in favorites and timestamp in recent would be an amazing addition.

**Comment by augmentedfourth** [comment]
OK, that's helpful. But what I'd really like is to see a list of who's active/online, like I get in Adium. For YakYak, I guess the best way to get that is to allow ordering by status.

**Comment by averissimo** [comment]
Humm kinda related to #733 

Something like group offline contacts in bottom _(of both pinned contacts and general)_ ?

**Comment by augmentedfourth** [comment]
Yes, offline at bottom would do this. It even seems that sometimes the green dot in YakYak isn't even accurate in telling me who's logged in and who isn't. I guess it might be something to do with the XMPP implementation when some contacts are logged in via Adium or other chat clients.
