### ISSUE TITLE
No Notifications in Windows 10

### ISSUE THREAD

**Issue by stonedonajax** [yakyak/yakyak#708]
Hello,

We aren't getting any notifications for new messages in Windows 10.

The notification options are enabled in the menu.

Is anyone else having this problem?

Regards,
stonedonajax

**Comment by DalaiDan** [comment]
Same Issue on OS Build 15063.413

**Comment by anirbanmu** [comment]
Yes I'm seeing this issue as well.

**Comment by iamacarpet** [comment]
This can be fixed by updating node-notifier to the latest.

They fixed the issue by switching the library they used for Toast Popups on Windows to a better supported one.

I've created a fork with the fix, plus some additional stuff for our use with G Suite.
https://github.com/a1comms/yakyak/commit/95b267622a5beb8903e0a51922cc80a7e502c8a5

**Comment by averissimo** [comment]
@iamacarpet great work!!

__can you create a pull request with changes?__ :)

can you explain the purpose of the last commit? (whether user is part of organization)

**Comment by iamacarpet** [comment]
Hello @averissimo,

Sure, it gives a different highlight to users within your Google Apps organisation / domain when searching for people, as our users are coming from Skype for Business where when you search you only get internal people, so we wanted to make it easier for them to find only internal people, even if we can't limit the search to only internal.

**Comment by averissimo** [comment]
Really great work with the pull request, I've added some comments there :)

**Comment by Catscratch** [comment]
Please merge the Pull Request.

**Comment by Catscratch** [comment]
Hey. Btw. even with this "patch" notifications are still not working for me. Using latest version of Windows 10 x64.
