### ISSUE TITLE
Error: invalid_scope

### ISSUE THREAD

**Issue by hcarrasc** [yakyak/yakyak#709]
Running Yakyak first time in a Windows PC 32 bits its give the follow error:

> **Error: invalid_scope** Not authorized to request the scopes: [https://www.google.com/accounts/OAuthLogin]

```
client_id=936475272427.apps.googleusercontent.com
scope=https://www.google.com/accounts/OAuthLogin
redirect_uri=urn:ietf:wg:oauth:2.0:oob
response_type=code
```

**Comment by averissimo** [comment]
This is super strange.

which version of yakyak? try the latest or the last pre-release please

This bug was supposed to be solved last september
