### ISSUE TITLE
Request: Classic Hangouts layout

### ISSUE THREAD

**Issue by cjrobe** [yakyak/yakyak#710]
Man, this app is slick. Really nice work.

I would love if there was an option to have the classic Hangouts before it was "appified." You know, with the contacts list and the separate tiny window for each chat you have open that can expand or retract.

![old-hangouts](https://user-images.githubusercontent.com/5606066/27385084-5f797da6-565f-11e7-80a6-bf977f117b41.jpg)

I don't talk to many people at a time so I love just having that tiny little window in the corner and I don't have to alt-tab to the large Hangouts window.

Thanks and hope you consider!

AKA classic chat layout. Where each chat can open in its separate

**Comment by hypercube33** [comment]
I second this too, since 99% of the hangout users will be into this.

**Comment by averissimo** [comment]
this is a duplicate of #370

_short version:_ sorry, current developers don't really like it.. we welcome and would accept pull requests for this functionality thought!! (keeping an option to switch between the two types
