### ISSUE TITLE
Google for Business account login failure

### ISSUE THREAD

**Issue by musasabi** [yakyak/yakyak#711]
I tried to log in using my work GMail address (works with pidgin, etc) and got the following error message:

`login: programmatic auth`
`connected 0`
`Error on YakYak window:`
` { columnNo: 18,`
`  error: {},`
`  lineNo: 126,`
`  msg: 'Uncaught TypeError: Failed to execute \'appendChild\' on \'Node\': parameter 1 is not of type \'Node\'.',`
`  url: '/usr/share/yakyak/resources/app/node_modules/trifl/lib/view.js' } `
`--- End of error message in YakYak window.`

I'm using 1.4.3, specifically, [this](https://aur.archlinux.org/packages/yakyak/) pacakge.

Also, this error hangs up the UI completely, even upon restart. To get back to a functional state (with my personal account) I had to reinstall yakyak all together.

**Comment by mosspaper** [comment]
Also getting the same issue

**Comment by averissimo** [comment]
Crap, #518 for reference...

Can you describe when this is happening, on login, when opening a conversation, opening the details of a conversation, you get the picture.
