### ISSUE TITLE
Possible to mute sounds?

### ISSUE THREAD

**Issue by cfjedimaster** [yakyak/yakyak#713]
I don't want to mute notifications, I simply want to mute any and all sounds. I know I can mute individual conversations, but I still want the visual feedback. I just want YakYak to be quiet. ;)

**Comment by cfjedimaster** [comment]
I'm sorry - this appeared to be a Windows notification. I disabled it. One oddity though and it may be a real bug - in Windows the app shows up as "toast".

**Comment by averissimo** [comment]
Toast is a fallback system for displaying notifications :)

There is an option to mute sounds, view -> popup notifications -> disable sound in notifications

I'm closing the issue :)
