### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by ylluminate** [yakyak/yakyak#714]
A good way to get more adaptation for the app might be to create a Homebrew formula that allows easy installation and updating of the app for macOS:
https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

**Comment by ylluminarious** [comment]
@ylluminate Looks like it's available as a cask: https://github.com/yakyak/yakyak/wiki#mac-os-x-alternative

**Comment by jlp78** [comment]
`brew cask install yakyak`

**Comment by ylluminate** [comment]
Very cool guys. Thanks. Unfortunately it's a version behind at 1.4.3 @ylluminarious @jlp78...

**Comment by jlp78** [comment]
1.4.3 is the release version.  1.4.4 is tagged as pre-release.
