### ISSUE TITLE
Can't sign in yakyak 1.4.3 osx?

### ISSUE THREAD

**Issue by samk14824** [yakyak/yakyak#716]
<img width="932" alt="screen shot 2017-06-28 at 1 03 29 am" src="https://user-images.githubusercontent.com/29746740/27622606-c2001dc0-5b9d-11e7-8ec9-9a4fcb445c62.png">
Just downloaded it and verified access via google 2 step but it keeps saying connecting and wont open? I'm new to Mac, am I missing something?

**Comment by DavidBabel** [comment]
Same here, not working on Mac Anymore

**Comment by DavidBabel** [comment]
![image](https://user-images.githubusercontent.com/5599375/28258276-a84b27b6-6ad0-11e7-92bc-5fdea6a1685d.png)

**Comment by averissimo** [comment]
can you guys try: https://github.com/yakyak/yakyak/releases/tag/v1.4.4-connecting

I've been having this problem for a while but I thought it was due to my crappy connection... seems like something else

ps. if there are no binaries, just wait around 15 minutes

**Comment by szabooimre** [comment]
same issue with me. Just installed 1.4.3 on High Sierra, and it keeps connecting forever.

**Comment by averissimo** [comment]
The first thing you should try is to delete the yakyak directory on `~/Library/Application Support`

~ represents the home folder *(if I'm not mistaken)*

Second

Try the 1.4.4-connecting binaries in the releases.

Third

If all of the above does not solve it, then open the terminal and start the yakyak application using `-debug` and take a screenshot of the terminal.
