### ISSUE TITLE
Screen Wake-Up During Sleep Upon Notification 

### ISSUE THREAD

**Issue by bcai** [yakyak/yakyak#717]
When using an external Apple monitor hooked up to a Macbook Pro via Thunderbolt cable, I find that after I have put the laptop to sleep that YakYak occasionally wakes up the screen upon receipt of a new message and displays the YakYak notification (to the top right). The monitor subsequently goes back to sleep after a few seconds.

**This reveals the message content in the notification on the monitor to any person who by chance may come across this event and is a potential privacy issue.**

I am currently using OS X El Capitan 10.11.6.

**Comment by ideaman924** [comment]
I haven't checked this behavior yet, but if YakYak uses the Notification Center to send out notifications, then it's not the problem of YakYak itself but rather Apple's macOS.

If YakYak uses a proprietary way of displaying notifications then yes this issue would be a problem.

FYI, if it's number 1 I think there was a way to not show notifications when the screen was being mirrored or something in System Preferences. Just my two cents to check there.

**Comment by bcai** [comment]
Awesome, I never realized that you can control notification options of different applications on Mac OS. I will uncheck "show notifications on lock screen" for YakYak and will update this thread if I continue to see the same screen wake-up issue in the future.

**Comment by averissimo** [comment]
@ideaman924 you are right, we are using node-notifier to avoid having to support multiple systems.

Can we close this issue?
