### ISSUE TITLE
Notifications not shown

### ISSUE THREAD

**Issue by nkmittal** [yakyak/yakyak#719]
I have been using yakyak for about 6 weeks by now on my Apple (MacOS Sierra 10.12.3). Sometimes I see that it does not show the notification of a new message neither in pop-up on the top right corner nor in yakyak icon on the bottom bar. With this behavior I am missing out on new messages when I am away from my laptop.

**Comment by averissimo** [comment]
all types of notifications or just specific (such as images, videos)

**Comment by nkmittal** [comment]
All types...and it happens at least once in a day.

**Comment by mark-e-mark** [comment]
Same experience on my Ubuntu laptop (16.04). I'm using it with Hangouts. All features work except Pop-up notifications.

**Comment by sosguthorpe** [comment]
I am running Kubuntu and was also not receiving any popups in KDE. After a little digging I noticed that the notifications on the Linux versions use the node-notifier module which in turn requires 1 of 2 libraries to be present on the system. In short to solve this problem on (K)Ubuntu run:
```
apt-get install libnotify-bin
```
**_Note:_** In KDE you also need to make sure you have a notification widget in the task bar or you won't see any notifications.

If you prefer you can install notify-osd which sets out to improve the appearance of all notifications system wide:
```
apt-get install notify-osd
```
Hope this helps people that were in the same situation.

**Comment by crash83k** [comment]
I have both of those libraries installed and I'm still not receiving the notification on Ubuntu 16.04 with Gnome 3.14.

Are the notifications only working for Unity?

**Comment by pankajshipte** [comment]
Same issue for ubuntu 16.04 unity desktop. I also have both notify-osd & libnotify-bin.

**Comment by sosguthorpe** [comment]
I have only tested with KDE desktop. I only have libnotify-bin installed and that works for me. If you have both libraries installed it will attempt to use notify-osd I think. So try removing that library if you can. The libnotify-bin will cause a notification to appear where the rest of your system notifications appear. In KDE this requires a system-tray widget to be enabled and visible, otherwise you get no popup notifications at all. I don't know whether there are similar caveats for unity.

**Comment by lukeallister** [comment]
I am also having this issue (snap package on linux mint). The program icon turns red, but the notifications don't come through anywhere (with libnotify enabled and the yakyak icon in taskbar).
