### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by GamerClassN7** [yakyak/yakyak#724]
on win 8.1 Notifications are displayed even if the window is visible which sometimes complains me the job would be super if the window is open so you only report the sound to the message.

PS: Will you in future implement Floating style Widget ?
like this: http://d0od.wpengine.netdna-cdn.com/wp-content/uploads/2014/10/hangouts.jpg

**Comment by averissimo** [comment]
Do you mean just visible or only if focus? (it could be visible but burried behind other windows)

This could be a nice improvement :)

Floating style widget is a no, see #370 for the full discussion
