### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by DanLauer** [yakyak/yakyak#725]
This seems to have shown up after a Windows 10 updates installed last night. Running YakYak 1.4.3 on Windows x64.

A screen shot is here: http://i.imgur.com/uwmXr4H.png

Text of the error: 
---
A JavaScript error occurred in the main process

Uncaught Exception:
SyntaxError: Unexpected token

**Comment by infool7** [comment]
Have you tried deleting your Preferences file from %appdata%\yakyak folder?

https://goo.gl/HE7ooD

**Comment by DanLauer** [comment]
I may have overreacted, but I just ditched the whole folder from AppData. Brilliant! It worked.

Thank you @infool7 !

**Comment by cout** [comment]
I ran into this same issue.  Wiping AppData fixed it, though of course I had to sign in again.  Is it possible this is related to two-factor authentication?

**Comment by dheeris** [comment]
Same issue here, and can confirm a fix.
Tried first to delete the Preference file from '<user dir>\AppData\Roaming\yakyak' as @infool7 suggested. Didn't work. I then deleted the entire yakyak folder. That worked, meaning I don't know how much really is needed to delete, but the entire folder does work.
Like @cout stated I also had to log in again. I also have two-factor authentication.

**Comment by neico** [comment]
Delete the 3 `cookies` files inside the AppData folder, this forces the App to request the login data again, fixing this error.

My guess is that `refreshtoken.txt` isn't being read correctly or so causing the auth token to expire

**Comment by ccpwcn** [comment]
![tim 20180701114903](https://user-images.githubusercontent.com/5465756/42130946-4bbca794-7d27-11e8-8f0b-5c8a480a09d4.jpg)
I can't find any description of this error on Google. What's wrong with this error?
我无法从谷歌上搜索到任何这个错误的描述信息，这个错误到底是怎么回事？
