### ISSUE TITLE
Application crashes upon pasting large bodies of text

### ISSUE THREAD

**Issue by stacksjb** [yakyak/yakyak#731]
I can reliably & repeatedly crash latest version of YakYak by pasting a large body of text into the message window.

For example, go to http://coolsig.com/proverbs5.html and select all & copy the page, then paste into the message box.

**Comment by averissimo** [comment]
Can you open yakyak using the command line and copy here the error if it .

And which operating system and version are you using?

I can't replicate it with latest pre-release 1.4.4

![outccsltasmxs](https://user-images.githubusercontent.com/211358/28708087-242fbdee-737b-11e7-87b2-ac7397554843.gif)

**Comment by stacksjb** [comment]
I am running 1.4.4 on Mac OS X

The entire app does not crash, but I get the attached screenshot:

<img width="1510" alt="screenshot" src="https://user-images.githubusercontent.com/2865491/28730910-03cb025c-738f-11e7-99e3-af94228e3671.png">

I am forced to re-load the app to regain full functionality.

I checked the messages console but the following are the only ones that are there:

`Failed to decode downloaded font: file:///Applications/YakYak.app/Contents/Resources/app/ui/css/noto-color-emoji/NotoColorEmoji.ttf
index.html:1 OTS parsing error: Not a valid font data
/Applications/YakYak.app/Contents/Resources/app/ui/version.js:36 YakYak local version is 1.4.4, released version is 1.4.3
/Applications/YakYak.app/Contents/Resources/app/ui/models/viewstate.js:104 Warning: could not retrieve message input to store.`

**Comment by stacksjb** [comment]
Can you give me instructions on how to launch or get more detailed debug info?

**Comment by uwu-uwu** [comment]
Windows 7/10 64 bit, doesn't crash when pasting huge bodies of text but it DOES make the emojis list pop up

**Comment by averissimo** [comment]
This is corrected in yesterday update of v1.4.4 prerelease :)

**Comment by averissimo** [comment]
this was an UI bug

it was not a real crash, the app just showed something that is hidden for fatal failures in the startup :)
