### ISSUE TITLE
Yakyak quietly dropping messages

### ISSUE THREAD

**Issue by Cutriss** [yakyak/yakyak#734]
I have two issues in yakyak which I suspect are related. I've typed some messages to a friend, and then later came back to the window to discover they were never sent, and are completely missing from the conversation.

Today, just after I experienced that issue again, I experienced another case where messages were not sent correctly, but at least they still show up in Hangout (without the black text confirming they were sent).

![image](https://user-images.githubusercontent.com/638297/29220388-e4207a54-7e88-11e7-96ae-dc5652a4fa99.png)

And in Hangouts showing the missing content:

![image](https://user-images.githubusercontent.com/638297/29220420-f9487fb2-7e88-11e7-9d8c-edeb38887200.png)

I didn't get an error message or anything in yakyak, the messages went in as grey, and then just silently vanished.

**Comment by anjit6** [comment]
I'm facing the same problem. I'm on Mac OS X 10.12.6.

**Comment by uwu-uwu** [comment]
Same on windows 10 64 bit.

**Comment by mbinkhorst** [comment]
Chiming in. I'm on Mac OS X 10.12.6.

**Comment by jjt** [comment]
Same here, MacOS 10.12.6

**Comment by 5tefano** [comment]
Same. MacOS 10.12.6

**Comment by bk800** [comment]
Hi, 
All messages are dropping for me using yakyak since 8/16.  I'm stuck using gmail.  Hope you can fix this soon.  Yakyak is the best!

![image](https://user-images.githubusercontent.com/21371147/29645039-b6dbd006-882f-11e7-8dce-eeaa13f5da88.png)

**Comment by JasonQG** [comment]
Also seeing this in Windows 7 64-bit

**Comment by austelly** [comment]
Same on windows 10 64 bit.
It used to work perfectly until a couple of weeks ago.

**Comment by mbinkhorst** [comment]
Updating my post: it seems to work fine now for several days. Could have been a network/routing hiccup somewhere? I have changed DNS providers, am no longer on Google's DNS. (OS X 10.12.6)

**Comment by bk800** [comment]
Still does not work for me, (Windows 7 64bit)  Yakyak v1.4.3

**Comment by nayefc** [comment]
Same for me, happens every time.

**Comment by averissimo** [comment]
wow, this was a big problem, it is still happening?

If so can someone try the latest pre-release, it was updated today with something that could help in crappy networks

**Comment by bk800** [comment]
Tried the 1.4.4 pre-release, and it still drops every message.  Thanks for the help

**Comment by averissimo** [comment]
This is for hangouts messaging, not involving sms/google voice, right?

If so can you guys:

- Open Yakyak via the command line and screenshot it after writing in a conversation some messages and confirm that some messages have been dropped?
- Also, open the developer pane (Ctrl + Shift + I) and see if some error shows in the console tab

thanks

**Comment by bk800** [comment]
Yes, it is using hangouts messaging.  Not using SMS/google voice.

=======CMD LOG=========
D:\Downloads\YakYak-win32-x64>YakYak.exe

D:\Downloads\YakYak-win32-x64>
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
==================
![image](https://user-images.githubusercontent.com/21371147/30570891-ed6c42f4-9c98-11e7-808d-c1bb0d18897f.png)
==================

Nothing happens when I hit "Ctrl+Shift+I"

**Comment by bk800** [comment]
More Info:  I tried logging out of the account I usually use and logging into a different google account.  Yakyak is working using that account account. (same machine).  If I switch back to my normal account, the problem returns.  Tried deleting the C:\Users\briank\AppData\Roaming\yakyak folder.  Did not help.

The only difference between the two accounts (that I know of) is that it is a google based account provided through my company.  
-Thanks

**Comment by averissimo** [comment]
My bad, the shortcut is Ctrl + Alt + I

This is really strange, as if it was a company policy the behavior would always be the same.

Can you build yakyak from source? There's something that you can try to help debugging, but it's not in the released binaries

**Comment by bk800** [comment]
From the Console tab, I have three errors categories:

1)  E:\Downloads\YakYak-win32-x64\resources\app\ui\models\viewstate.js:104 **Warning: could not retrieve message input to store.**
(I also saw this one when using the account that works)

2) E:\Downloads\YakYak-win32-x64\resources\app\ui\version.js:36 **YakYak local version is 1.4.4, released version is 1.4.3**

3) E:\Downloads\YakYak-win32-x64\resources\app\ui\dispatcher.js:94 setpresence: **User 'unknown' does not show his/hers/it status Object**
----------

Are there direction on building?  I as able to get the code.  I installed coffee script for windows as it seemed like it might help.  Never used coffee script before.

**Comment by averissimo** [comment]
Alternative with binaries already compiled: https://github.com/averissimo/yakyak/releases/tag/v1.4.4-debug

and run in the console `yakyak --debug` or `./yakyak --debug` depending on the Operating System

To compile from source these are the instructions:

- download the repository using git (or download the [debug branch](https://github.com/yakyak/yakyak/archive/debug.zip) code)
- have node.js installed
  - if using node v8.* install npm version 5.2: `npm install -g npm@5.2`
- on the directory install all dependencies: `npm install`
- compile and run yakyak: `npm start`

Having yakyak successfully running then:
- quit yakyak
- checkout the code _(if using git)_ 
- run: `npm run debug` 

This will give a lot more debugging information in the console.

**Comment by averissimo** [comment]
Those 3 error categories are expected:

1. is just a warning that can be ignored _(it is for restoring the input when switching conversations)_
2. Version check
3. Information on which users have their status public

**Comment by bk800** [comment]
Thanks for the build.  I ran it and sent a few messages, which were dropped.  See attached
[yakyak_debug_issue734.txt](https://github.com/yakyak/yakyak/files/1318939/yakyak_debug_issue734.txt)

**Comment by averissimo** [comment]
Wow, many problems there :O I've corrected one of them and added some debugging on a strange error with cookies.json

Can you try again with the same binaries? _(they've been updated)_

**Comment by bk800** [comment]
Okie, here you go: 
[yakyak_debug2_issue734.txt](https://github.com/yakyak/yakyak/files/1323119/yakyak_debug2_issue734.txt)

**Comment by devimauz** [comment]
I have the same problem.

**Comment by averissimo** [comment]
I think that the operating system is having some problem with reading / opening file   `C:\Users\<youruser>\AppData\Roaming\yakyak\cookies.json`

@bk800 :

- Can you see if this file exists and it has some content _(don't copy it here as it could be used to enter the account)_
- Can you try running yakyak as an administrator (i.e. the same procedure but using a _(Command Line as Administrator")_?

**Comment by averissimo** [comment]
@devimauz can you try running the binaries ( https://github.com/averissimo/yakyak/releases/tag/v1.4.4-debug ) from command line with `./yakyak --debug`

**Comment by bk800** [comment]
@averissimo Yes, the cookies.json file exists, and has about 4kb of data.

I tried the experiment on the PC @ work (Win7) and also @ home (Win 10).  In both cases, all messages are still dropped.  However, in Win 7 I usually sees this error box.  I did not see it in Win10:

![image](https://user-images.githubusercontent.com/21371147/31007644-10754cf8-a4b6-11e7-9e00-19aefcacc7ef.png)

Here are the logs of the cmd prompt ran in Administrator mode:
[Yakyak_debug3_Win7_issue734.txt](https://github.com/yakyak/yakyak/files/1343672/Yakyak_debug3_Win7_issue734.txt)
[Yakyak_debug3_win10_issue734.txt](https://github.com/yakyak/yakyak/files/1343671/Yakyak_debug3_win10_issue734.txt)

**Comment by lennonrich** [comment]
Could be unrelated but just wanted to add my voice. Last night I was having some really bad DNS issues and noticed that YakYak was greying the messages when my DNS would stop responding, and when the DNS came back the message was dropped.

**Comment by larskotthoff** [comment]
I'm having issues with this as well (also sometimes with messages being sent but not showing up). This seems to be caused by connection issues, i.e. the client frequently tells me that it's connecting and sometimes (often when I move between places and have different IP addresses/DNS servers) I have to restart yakyak to be able to connect again.

**Comment by calvertdw** [comment]
Still happening to me on 1.4.4.

**Comment by KingJam** [comment]
I still have this problem in 1.4.4. Has it been addressed in 1.5?

**Comment by jjt** [comment]
Same problem here in 1.5.0, MacOS 10.13.3. It often drops incoming messages for me too.

**Comment by nrvale0** [comment]
Not stale. Happens here after less than a few minutes of app start.

yakyak-1.5.0-1.x86_64

**Comment by chipx86** [comment]
This is still happening for me as well. Started again just a couple days ago.

**Comment by urania277** [comment]
This is happening for me as well, especially with sending images. Restarting somehow resets things.
