### ISSUE TITLE
Links don't open in browser right away [v1.4.3]

### ISSUE THREAD

**Issue by jjt** [yakyak/yakyak#737]
When clicking on a link, YakYak seems to wait for the link to resolve before opening in a browser. This violates the principle of giving immediate user feedback when an action is taken.

The solution would be to do as almost every other application does and open the link in a browser immediately upon clicking.

To test, try this link from YakYak. It introduces a 10s delay before redirecting to google.com:
http://slowwly.robertomurray.co.uk/delay/10000/url/http://www.google.com. See attached gif of behaviour, where I clicked on the link in YakYak and it took over 10 seconds for my action to result in any feedback.

![aug-17-2017 21-18-43](https://user-images.githubusercontent.com/399469/29444093-afcad1b0-8391-11e7-8ef5-272677cd0f96.gif)

**Comment by slackerbob** [comment]
I can confirm this also happening in Arch Linux.

**Comment by averissimo** [comment]
10s delay :o 

we do perform some stuff in the background.. one of my first contributions to yakyak was to remove the google.com redirect link for non-google links ... but that is just a regular expression operation and it should be really fast

**Comment by averissimo** [comment]
the delay exists because we are loading the link in Yakyak itself to get an authenticated link _(for cases where it is private to the user)_ and this has to be done inside Yakyak as it is the only app that is guaranteed to be authenticated and has permission.

This is really needed for videos shared in a conversation

However, I believe that non-google links are always prefixed by a google redirect and can skip this :p, so I'll send a pull request to try to avoid this for links outside google :)

**Comment by averissimo** [comment]
@jjt @slackerbob can you guys test #767 pull request?

**Comment by jjt** [comment]
Ooh nice, will try that out!

**Comment by jjt** [comment]
@averissimo That seems to do the trick! It's funny because something about a new tab opening up instantly when I click a link feels better to me, even though I know I have the same amount of waiting either way :p

**Comment by averissimo** [comment]
:) I understand the feeling, what do you think about the UI when opening a google link, such as a picture or video?

There the delay must happen, but I've added a 3second notification

**Comment by jjt** [comment]
I'll have to test it out, as we don't normally use google images/videos. Will report back.

**Comment by davibe** [comment]
@jjt did you try ?

**Comment by jjt** [comment]
Hi, sorry for the delay! Links to photos.app.goo.gl work correctly with a slight delay (to be expected), and other links open in a browser immediately.
