### ISSUE TITLE
User icon not shown in notifications

### ISSUE THREAD

**Issue by miguel-nunes** [yakyak/yakyak#740]
I think it should be a good improvement the notifications have the user icon.

I'm trying to implement this but it's the first time I'm seeing a Node code alive :)

I'll study a little more. If I have some success, I'll let you guys know!

Cheers,

--
Miguel Nunes

**Comment by averissimo** [comment]
See notification.coffee , that's where the notification is generated using node-notifier module

There is an image option that could be used for what you want Miguel. I believe that the only hurdle is that it needs to be an absolute path

Good luck, looking forward to see your work :)
