### ISSUE TITLE
Can I get this into Ubuntu Software?

### ISSUE THREAD

**Issue by OctoPenguin** [yakyak/yakyak#741]
YakYak is hard to install. Seriously. Can I attempt to get it into Ubuntu Software? Or even Snap it?

**Comment by PMiner** [comment]
You could compile YakYak for your OS yourself. See: https://electron.atom.io/docs/all/#build-instructions-linux

**Comment by PMiner** [comment]
I don't have Linux at the moment, but I could quickly install ubuntu on a test computer if somebody wants me to compile this.

**Comment by OctoPenguin** [comment]
Can I take this as a yes? I can easily put it in Software

**Comment by PMiner** [comment]
I think yes? If you follow the Linux compiling instructions, it should work. I'm not sure about getting it into ubuntu software though.

**Comment by PMiner** [comment]
have you tried compiling yet? @OctoPenguin

**Comment by averissimo** [comment]
@OctoPenguin if you add to our build process you are more than welcome!! the snap pull request you created is something that the community will definitely benefit

I think we just need to make sure that it is an automated process... no more building and uploading manually :p

**Comment by Pharmasolin** [comment]
@averissimo this issue can be closed/solved
https://snapcraft.io/yakyak
Install in ubuntu with `sudo snap install yakyak` command
