### ISSUE TITLE
How can I help translating?

### ISSUE THREAD

**Issue by zubaki91** [yakyak/yakyak#745]
Hello, I find this project very useful and I'd like to contribute by translating in italian, but I'm new to github and I don't know how to add a file to the repository and have it approved.
Can anyone help me? Can I simply upload a file and it will be added to the repository?

Edit: I tried to upload a file (it.json from the locales) but it tells me that i need push privileges...

Edit 2: I managed to create a pull request. it seems it was a simple matter... I am sorry for wasting time...

**Comment by averissimo** [comment]
Great work, we'll look into the pull request soon :)
