### ISSUE TITLE
Only 1px of scrollbar clickable when windowed

### ISSUE THREAD

**Issue by bupkis** [yakyak/yakyak#748]
When clicking the scroll bar, only the leftmost pixel is clickable before Windows switches to the horizontal resize cursor. (Using yakyak 1.4.4 win32 x64 on Windows 10)

![image](https://user-images.githubusercontent.com/10007918/29838949-8989f46c-8cb1-11e7-8ce4-5f3d22f23ceb.png)

![image](https://user-images.githubusercontent.com/10007918/29838958-8decf1da-8cb1-11e7-8eb6-d5f8257acc4c.png)

**Comment by averissimo** [comment]
In linux I think several pixels are clickable, we would welcome a windows developer to tackle this issue :)

**Comment by awesley** [comment]
Hello!  I have YakYak on my Windows laptop and Windows desktop and have been able to repro it on the laptop.  I wonder if it has more to do with some settings in Windows to be "helpful" to users.

There are alternate fixes that could be explored.  Increasing the width, or increasing just during hover, etc.  

What are your thoughts?

**Comment by awesley** [comment]
@bupkis Are you using a laptop with a touchpad?

**Comment by averissimo** [comment]
@awesley, both solutions would be great to avoid this.

I think increasing during hover is a bit more difficult to implement, but an awesome one :)

**Comment by automagnus** [comment]
Would also appreciate a solution to this. Experiencing the same problem.

**Comment by arusahni** [comment]
The scrollbar is completely unclickable for me in KDE:

![Screenshot](https://user-images.githubusercontent.com/139487/35484679-2d1cad22-0421-11e8-9697-f9eafbbd9e90.png)

(I have my KWin border size set to "Tiny").

**Comment by arusahni** [comment]
I am still experiencing this issue.
