### ISSUE TITLE
down arrow doesn't clear message

### ISSUE THREAD

**Issue by msphair** [yakyak/yakyak#75]
standard usage is to hit up to go to previous messages in history and down to go to more current messages, getting up to either a blank field or what you had in there previously.

current interaction is if you have anything in the message box, up goes to the beginning of the message. If it's blank, up puts in the last sent message. Down goes to the end of the message. So there's no way to go up to get to previous messages and then go down to get to an empty box as is the behavior in places like Terminal.

**Comment by algesten** [comment]
we removed the broken history thing.

**Comment by msphair** [comment]
This still happens in v1.3.0
