### ISSUE TITLE
Add Video Call Support

### ISSUE THREAD

**Issue by Mrtops** [yakyak/yakyak#750]
Hi, can you please add integrated support for video calls into the app?

**Comment by PMiner** [comment]
Even if it just opened a new call where you could invite people would be better than nothing.

**Comment by TheDumbKnight** [comment]
Absolutely need the call feature!

**Comment by Antairez** [comment]
+1 Even if it means opening up a new chrome window it will still be very helpful.

**Comment by azjezz** [comment]
+1

**Comment by joshlewis** [comment]
I totally agree, it would be wonderful to get _some_ kind of video calling integration. Even basic integration.

The very first thing I noticed about the app after it opened the first time, other than "Hey, there's my list of chats." was "Where's video calling?" It's a glaring omission. Not saying it's simple to add, but that it's a very desirable feature.

**Comment by gsbhasin123** [comment]
We need it. +1
