### ISSUE TITLE
Translate into Japanese

### ISSUE THREAD

**Issue by jefu7** [yakyak/yakyak#751]
Hello. I will be happy to work on a Japanese translation.  I don't know how to use GitHub (I signed up just so I could send this note).  But I am very grateful to have a MacOS Hangouts client!

Please let me know how I can help.  If you can send me the list of strings in English, I'll work on translating them into Japanese.

Jeff

**Comment by PMiner** [comment]
https://github.com/yakyak/yakyak#how-can-you-help\

First, you need to clone YakYak to your computer, then you add a file called "JP" or whatever the 2 letter code for Japan is, and copy paste the English version, to the Japanese one, then edit all the strings to be Japanese. then create a pull request to merge your fork. if you need more GitHub help, download GitHub desktop, desktop.github.com, because there is a tutorial in the beginning. cheers!

**Comment by jefu7** [comment]
Thanks!

Okay, I’ll give it a go. This is like a trip into the wilderness for me, but let’s see what I can do…

Thanks.

Jeff

On Sep 2, 2017, at 1:27 AM, Saturn Software <notifications@github.com> wrote:

https://github.com/yakyak/yakyak#how-can-you-help\ <https://github.com/yakyak/yakyak#how-can-you-help%5C>
First, you need to clone YakYak to your computer, then you add a file called "JP" or whatever the 2 letter code for Japan is, and copy paste the English version, to the Japanese one, then edit all the strings to be Japanese. then create a pull request to merge your fork. if you need more GitHub help, download GitHub desktop, desktop.github.com, because there is a tutorial in the beginning. cheers!

**Comment by jefu7** [comment]
Hi there. I've translated all the strings. The file is attached. Might someone help me get this added to the main program (yes, I have never done anything like this before, but do want to help!).

(Sorry, I had to zip it before github would let me attach it to this note.)

I hope this is useful.  Sorry not to be able to do everything right myself to add it!


[jp.json.zip](https://github.com/yakyak/yakyak/files/1272163/jp.json.zip)

**Comment by jefu7** [comment]
Hi there.  Can someone please help me get my jp.json file up into the "Pull Request" queue?  I've been trying and trying, both online and in the desktop program. I can't get my head around how to create a new repository with the clone, add jp.json and then create a Pull Request. And I've tried... and read help files... and tried...

Thanks.

**Comment by averissimo** [comment]
Closing the issue as the translation has been merged and included in the pre-release

Thanks @PMiner for the help! and @jefu7 for the fantastic translation, it's pretty awesome to use Yakyak with japanese characters :)

**Comment by jefu7** [comment]
André, I had a look at the newest version (on my Mac) and a few items are not showing translations in the menus (screenshots attached).

I think I provided translations for two of these items (emoji and full screen), but now see that I'm missing one for "Use System Date Format".  Here's the current code.

        "edit": {
            "title": "編集",
            "undo": "元に戻す",
            "redo": "やり直し",
            "paste": "ペースト",
            "cut": "カット",
            "copy": "コピー",
            "copy_image_link": "イメージのリンクをコピー",
            "copy_link": "リンクをコピー",
            "copy_image": "イメージをコピー",
            "select_all": "すべてを選択",
            "language": "言語 (Language)",
            "dateformat": "Use system date format"
        },
        "view": {
            "title": "表示",
            "emoji": "絵文字に変換",
            "hide_dock": "ドックのアイコンを隠す",
            "fullscreen": "全画面表示",

I'm happy to add a translation for Use system date format ("システムの日付形式を使用する") -- should I edit, commit and a new Pull Request, or do you want to add it?

I don't know how to fix the emoji and full screen translations.

Happy to help... I'll follow your lead.

Thanks.

Jeff

![screen shot 2017-09-13 at 10 58 35 am](https://user-images.githubusercontent.com/31531480/30396360-3c6ca4a8-987e-11e7-8cef-0270ae7c9017.png)
![screen shot 2017-09-13 at 10 58 43 am](https://user-images.githubusercontent.com/31531480/30396361-3c7a4540-987e-11e7-9e3b-d24742d235d1.png)
