### ISSUE TITLE
Show names in group chats

### ISSUE THREAD

**Issue by omarjordanf** [yakyak/yakyak#753]
I work for an organisation that requires all users to have the same display picture. Group chats are hard to use in Yakyak as it only shows display pictures, and no names. is it possible to add this functionality in further builds?

**Comment by averissimo** [comment]
This is a funny one, would showing the display picture with first and last initial suit, or really show the full name?

**Comment by omarjordanf** [comment]
Initials in the avatar would be a HUGE improvement for sure. Names would be better, but I'm not fussy 😂

**Comment by averissimo** [comment]
#770 should fix this, please continue conversation in the pull request :)
