### ISSUE TITLE
Chrome Native drag and drop support restricted

### ISSUE THREAD

**Issue by slimpyman** [yakyak/yakyak#755]
while the web version of hangouts, and the chrome hangouts extension supports multiple drag and drop elements, (webm, m4a, mp3, jpg, gif, avi etc) it seems the only thing we can drag and drop into a conversation is BMP, which is a very antiquated propriatry windows format.

**Comment by averissimo** [comment]
Currently it only supports images, at least jpg and png are supported.

Can I suggest you change the title of the issue to "Support drag and drop for avi, mp3, m4a, ..." ?
