### ISSUE TITLE
Multiscreen Issues

### ISSUE THREAD

**Issue by cgallaty** [yakyak/yakyak#757]
In Windows 10, I have two monitor setups. My home office has a monitor above the 'main' one. When I am remote I have a portable that I use. Yak Yak seems to save the absolute position on the virtual desktop and restore that.... even if that is well off of the existing physical screen space. Short term, could there be a setting to just reset the position on startup? (i.e. not save screen position from previous run. ) Longer term it would be nice if the window would just note that it is off of the visible screen on startup and move itself to somewhere where it can be seen.

**Comment by averissimo** [comment]
Thanks for reporting this, I believe we tried fixing this recently right @davibe ?

Which version of Yakyak are you using @cgallaty ?

**Comment by cgallaty** [comment]
I'm on 1.4.3 (which claims in the About that it's the latest.) As I said, I cycle through a number of configurations depending on where I am and I always tend to throw chat/music/etc to a secondary window. I would be happy to just restart and move in the short term. As is, I tend to just going into settings and physically move a screen to go fetch the window if I need it. (Usually it's faster to just go to Hangouts in one of the many open browser windows though.)

**Comment by averissimo** [comment]
@cgallaty , thanks for the feedback

can you try this pre-release called v.1.4.4-position : https://github.com/yakyak/yakyak/releases/tag/v1.4.4-position and see if works

I'll only have access to an external monitor on Monday, so at least until then it will have to wait unless you can test it :)

**Comment by cgallaty** [comment]
No love. I moved the app to a screen, closed Yakyak, then disconnected the screen, reopened the app and it was still on the missing screen. Now, if I leave Yakyak on, and disconnect the screen, then it seemed to move the window, so that's good. It seems its a glitch in the startup position.

**Comment by averissimo** [comment]
closing Yakyak as in quitting the application or just closing to tray?

**Comment by cgallaty** [comment]
Closing the application and reopening it. It seems it's not checking to see if there is screen to display on before it moves the window to the staring position.

**Comment by averissimo** [comment]
Can you see if this release solves your problem?

https://github.com/averissimo/yakyak/releases/tag/v1.4.4-position _(this link will have files in 5 to 10 minutes from the writing of this comment)_

I believe my changes won't allow the window to be placed offscreen _(or even between screens)_
