### ISSUE TITLE
Link message box to conversation

### ISSUE THREAD

**Issue by msphair** [yakyak/yakyak#76]
If I type a message into the message box but don't send it and i switch to a different chat, the message stays there.

Can the contents of the message box be linked to a conversation?

**Comment by kethinov** [comment]
+1

This is something I've been meaning to mention as well.

**Comment by maxkueng** [comment]
+1

This is also the way the Hangouts app does it, IIRC.

**Comment by algesten** [comment]
would be nice

**Comment by xedef** [comment]
+1

**Comment by averissimo** [comment]
#458 should implement this.

previous values are stored in `viewstate` object

I believe I tested with all options to switch conversation:

- clicking on a conversation
- selecting on menu
- keyboard shortcut

If i missed any please let me know :)

**Comment by averissimo** [comment]
done! from 1.4.0
