### ISSUE TITLE
Japanese Translation - three items not displaying (Mac OS)

### ISSUE THREAD

**Issue by jefu7** [yakyak/yakyak#763]
André, I had a look at the newest version (on my Mac) and three items are not showing translations in the menus (screenshots attached).

I think I provided translations for two of these items (emoji and full screen), but now see that I'm missing one for "Use System Date Format".  Here's the current code.

        "edit": {
            "title": "編集",
            "undo": "元に戻す",
            "redo": "やり直し",
            "paste": "ペースト",
            "cut": "カット",
            "copy": "コピー",
            "copy_image_link": "イメージのリンクをコピー",
            "copy_link": "リンクをコピー",
            "copy_image": "イメージをコピー",
            "select_all": "すべてを選択",
            "language": "言語 (Language)",
            "dateformat": "Use system date format"
        },
        "view": {
            "title": "表示",
            "emoji": "絵文字に変換",
            "hide_dock": "ドックのアイコンを隠す",
            "fullscreen": "全画面表示",

I'm happy to add a translation for Use system date format ("システムの日付形式を使用する") (it wasn't in template I used originally) -- should I edit, commit and a new Pull Request, or do you want to add it?

I don't know how to fix the emoji and full screen translations.

Happy to help... I'll follow your lead.

Thanks.

Jeff

![screen shot 2017-09-13 at 10 58 35 am](https://user-images.githubusercontent.com/31531480/30396360-3c6ca4a8-987e-11e7-8cef-0270ae7c9017.png)
![screen shot 2017-09-13 at 10 58 43 am](https://user-images.githubusercontent.com/31531480/30396361-3c7a4540-987e-11e7-9e3b-d24742d235d1.png)

**Comment by averissimo** [comment]
## suggest emoji on typing

I've updated the latest ja.json (and all other transalation files) to include the suggestemoji string.

## Use system date format

Also updated that in all translation files

## Fullscreen

This seems to be a bug of some sorts in Mac OSX, can you try other translations to see if the same string is also untranslatable?

## Start dictation and Emoji & Symbols

This is something Mac OS X or the framework that we use does automatically... There is still no translation for these ones

**Comment by averissimo** [comment]
if you want to finish the japanese translation, do the same steps as you did before to create the patch-1 branch

you just have to get the latest version from the Yakyak repository. This is usually done via a `pull` action

Then create patch-2 _(or some other branch)_, perform the changes and then create another pull request :)

**Comment by jefu7** [comment]
Got it.  But I have a question first...

I'm not sure how to deal with the two emoji commands... would you please confirm so I don't mess it up again?

![two emoji commands](https://user-images.githubusercontent.com/31531480/30404534-5631895a-98a4-11e7-84ed-aaadd7bd7854.png)

**Comment by jefu7** [comment]
Hi André.  I made the changes (in the online editor -- I can't figure out the pull action or how to upload files I edit offline) and, added the missing bits, and did a pull request.   Fingers crossed it works this time!

**Comment by averissimo** [comment]
again great work!!
