### ISSUE TITLE
Supporting RTL

### ISSUE THREAD

**Issue by perpi** [yakyak/yakyak#77]
It does not support RTL as Google/[Telegram](http://telegram.org) can!

What is auto-RTL? Ability to recognize the language (specially first character) to switch typing direction automatically from default to right-to-left or vice versa in the field and showing sent messages in the correct direction: RTL/ltr.

Some RTL languages: Arabic, Hebrew, Kurdish, Persian, etc.

**Comment by royts** [comment]
+1

**Comment by algesten** [comment]
duplicated of #33
