### ISSUE TITLE
Add option to start yakyak minimized

### ISSUE THREAD

**Issue by Aventura5** [yakyak/yakyak#771]
I would like to be able to pass an option to yakyak so that it will start minimized to the notification tray, right now if I auto start it I get a maximized yakyak window whenever i turn on my computer. Also, when you check the "Open on Startup" option, the .desktop file that gets created just calls electron, not yakyak.

**Comment by averissimo** [comment]
If you right-click the tray icon you can set the "start minimized" option

It's kinda hidden and I've been meaning to move those options to the "standard menu system"

Last time I tested open on startup it was working, but thanks for reporting, I'll test again soon :)

**Comment by Aventura5** [comment]
Oh, thanks. Now that you told me I remembered that I had used that a
long time ago on a different distro. It would be nice for YakYak to have
a settings screen rather than deeply nested drop down menus. Here is the
.dexktop file i get when I check Open on Startup:

`~/.config/autostart/electron.desktop`

```desktop
[Desktop Entry]
Type=Application
Version=1.0
Name=electron
Comment=electronstartup script
Exec=/usr/lib/electron/electron
StartupNotify=false
Terminal=false
```

**Comment by averissimo** [comment]
Are you trying to activate this when running from source?

https://github.com/Teamwork/node-auto-launch/issues/48

Unfortunately this option only works when running from a binary and never from source.

**Comment by averissimo** [comment]
the settings panel is a Wish list item!! We'd love if someone worked on it :)

**Comment by averissimo** [comment]
No longer hidden, it should now appear in the View menu.. that is amounting to the "Options" menu -_-

![image](https://user-images.githubusercontent.com/211358/35177573-ef8a50be-fd80-11e7-9da8-b128adabacb1.png)
