### ISSUE TITLE
On macOS, closing the window should not quit the application

### ISSUE THREAD

**Issue by cgatesman** [yakyak/yakyak#776]
When you close the window, it quits the entire application.  This is abnormal for an application on macOS.

**Comment by cgatesman** [comment]
Ah.  I found a "Close to tray" option that makes it behave in the way I expected.  However, this option is only available if you turn on "Show tray icon".  Good thing I dug around.  Seems weird this option is hidden there when it still works when "Show tray icon" is disabled.

**Comment by cobrabr** [comment]
I agree with @cgatesman, and the same behaviour occurs on Win7.

**Comment by PiFi** [comment]
same occurs on elementary os (linux, debian, ubuntu, etc.)

**Comment by davibe** [comment]
I am using the latest 1.4.4 pre-release (https://github.com/yakyak/yakyak/releases) . When i close the window it does not close yakyak. Can you please confirm @cgatesman ?

**Comment by cgatesman** [comment]
Yes.  This is behaving correctly, now, with 1.4.4.  👍
