### ISSUE TITLE
copy into conversation appears twice.

### ISSUE THREAD

**Issue by jima80525** [yakyak/yakyak#78]
I'm on linux mint 17.2  64-bit.  
It appears that if I do a ctrl-V in a conversation that the pasted text is inserted twice.  This is consistent (happens every time).

**Comment by maxkueng** [comment]
Hi. This has already been reported in issue #27 and been fixed in PR #60.

The fix will ship with the next release of YakYak which will probably happen very soon.

**Comment by jima80525** [comment]
Awesome!  Sorry that I didn't search for this before entering a new bug.  My bad.  Thanks!
