### ISSUE TITLE
Dates shown as MM/DD/YYYY despite computer settings

### ISSUE THREAD

**Issue by DavidJSmart** [yakyak/yakyak#784]
Win 7, YakYak 1.4.3. YakYak is showing dates in US format regardless of computer locale settings and ignoring the "use system date format" in its own settings being ticked or unticked. (My own locale uses DD/MM/YYYY.)

**Comment by DavidJSmart** [comment]
This is still a problem.

**Comment by DavidJSmart** [comment]
This is still a problem.

**Comment by DavidJSmart** [comment]
This issue still exists as far as I know.

**Comment by DavidJSmart** [comment]
No it’s not stale.

**Comment by survivor303** [comment]
Problem with win10 language English/US and regional English (Finnish).
Days are marked as MM/DD/YYY. They should be marked as DD/MM/YYY and also we have a problem with time format, it is AM/PM on Yakyak, even my system should use 24h time format. The setting "Use system date format". Doesn't understand English (Finnish) setting at all and ignores the system values.

Version what I use is latest beta/test release: 1.5.4
