### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by GamerClassN7** [yakyak/yakyak#785]
![2017-10-18](https://user-images.githubusercontent.com/22167469/31717847-d8f19bbc-b40d-11e7-9357-a353f1d2c729.png)

**Comment by xrasod** [comment]
Second. Running version 1.4.4

Can't launch application. Same error. 
Redownloaded and unzipped. The new download then throws this error. 
![yakyak_2017-10-19_09-11-56](https://user-images.githubusercontent.com/6340507/31758430-b0060238-b4ad-11e7-8a4a-a34a98f0b01a.png)

**Comment by Yezariael** [comment]
Same here with version 1.4.3 and 1.4.4 both freshly downloaded and unzipped.

**Comment by reformstudios** [comment]
This was working fine but stopped working today with the same error. 1.4.4
I've just installed 3dsmax 2018, so that might have updated something about my javascript?

**Comment by Yezariael** [comment]
@reformstudios I don't use 3ds max and didn't install any software. A friends of mine has got the same issue and didn't change something as well.

**Comment by markwoon** [comment]
Try deleting AppData folder and restart.

**Comment by Yezariael** [comment]
@markwoon Yeah, that worked for me! Thanks for the hint!

**Comment by reformstudios** [comment]
@markwoon Brilliant, thank-you!

**Comment by Talyrius** [comment]
I've experienced this error as well.

**Comment by averissimo** [comment]
Is someone still experiencing this? (i.e. still occurred after deleting the yakyak configuration directory)

If so please run from the terminal and then copy the output here.

**Comment by Talyrius** [comment]
Deleting the AppData fixes it. However, that doesn't prevent it from happening again in the future. It's happened three separate times for me now.

**Comment by Talyrius** [comment]
Not stale.
