### ISSUE TITLE
Mac: Text replacements not working

### ISSUE THREAD

**Issue by Behodar** [yakyak/yakyak#786]
In System Preferences/Keyboard/Text, you can set up text replacements (there's a default one where typing "omw" will expand to "On my way!").

However, YakYak doesn't seem to respect these replacements; I have many set up in there but none of them work in YakYak. Is this able to be fixed?

I'm running the 1.4.4 pre-release on MacOS 10.12.6.

**Comment by RandyWalker** [comment]
Issue confirmed.

YakYak: 1.4.3
macOS: 10.13.3

**Comment by Behodar** [comment]
Thanks for reminding me of this issue. I just tried the 1.5 pre-release and it doesn't work there either.

**Comment by Behodar** [comment]
This is still not working in 1.5.3.
