### ISSUE TITLE
Jumping icon on OSX?

### ISSUE THREAD

**Issue by bramadams** [yakyak/yakyak#79]
Hi,

Would it be possible using CoffeeScript/Electron to make the Yakyak icon jump up from the dock in OSX as notification?

BA

**Comment by davibe** [comment]
yes but if we do it needs to be configurable because it would be very annoying for most power users. We are still working on having a "preference" panel so.. nice suggestion and i hope we will get there at some point

**Comment by ironcladlou** [comment]
As described in #44 (comment), I'd like an option to enable dock icon bouncing. When using a hidden dock and with notification banners disabled, there's currently no way to be actively notified of new messages.

**Comment by davibe** [comment]
bouncing on every single new message received ? it seems overkill to me but could work for someone.

I am about to release 1.1.3. In this version you will have the possibility to show a menubar icon. The icon will turn red when you have unread messages. Would this be a decent compromise for you ?

**Comment by averissimo** [comment]
@ironcladlou @bramadams what do you guys think?

**Comment by ironcladlou** [comment]
With the menu bar icon indicator now working well in OSX in both normal/dark modes, I no longer care much about the bouncing dock icon. Thanks for asking!

**Comment by averissimo** [comment]
@bramadams?

i'm closing this as there are alternatives, if you still feel this is an issue please reopen it :)
