### ISSUE TITLE
When i close YY i need an option to stay running in panel with (Y) icon(hide to panel) vs closing for good

### ISSUE THREAD

**Issue by Ntemis** [yakyak/yakyak#790]
What description says.
Add option to close app but keep running in the background -> sent to Y icon in panel vs closing for good

**Comment by mturley** [comment]
Yes!  Bonus points for also having the icon display a dot on it when there are unread messages.

**Comment by Ntemis** [comment]
Stale= you don't give a shit, so app goes to trashbin in my site of view

**Comment by davibe** [comment]
@Ntemis which os are you using ?

**Comment by Ntemis** [comment]
Ubuntu 16.04.3 with MATE desktop 1.18

**Comment by PiFi** [comment]
No need to be rude to the developers. I'm sure they are very busy.

**Comment by averissimo** [comment]
@Ntemis have you tried:

1. Click on `View` -> `Show tray icon`
1. Right click on the tray icon and check `Close to tray`

I have a pending pull request to centralize all this options on the `View` menu (  #840 ) which will help a bit

**Comment by frz-dev** [comment]
The method provided by @averissimo is actually the solution to the issue.
