### ISSUE TITLE
Support for phone calls?

### ISSUE THREAD

**Issue by orschiro** [yakyak/yakyak#791]
What a great app which I heard about [1]! :-)

Is it possible to add support for phone calls?

Thank you!

[1] http://www.omgubuntu.co.uk/2017/10/yakyak-opensource-google-hangouts-desktop-app

**Comment by calvertdw** [comment]
This one is a deal breaker for me. Hate having chrome installed, but hangouts doesn't work in Firefox or Edge, so I have to keep a chromium installation sitting around just for Hangouts. Best part of Project Fi is being able to call from your PC.

**Comment by averissimo** [comment]
Sorry guys, but there's no plan to add phone calls support.

If someone wants to code, we'll merge it.

**Comment by averissimo** [comment]
closing as it is a duplicate of an open issue: #750
