### ISSUE TITLE
Memorizing last window position and size

### ISSUE THREAD

**Issue by Videonauth** [yakyak/yakyak#792]
I'm running yakyak on Ubuntu 17.10 with vanilla gnome on Xorg.
Since I have a multi monitor setup in 99% of the time the yakyak window appears on the splitting line of two monitors leaving it part on one and part on the other.

An option maybe to make it remember its last position and size would be very good.

**Comment by flair-paul** [comment]
I have a related issue.  When switching from one multi-monitor to another, the window position is remembered, but off the screen.  

In Windows 10, using Cascade windows, Show windows stacked or Show windows side by side didn't reveal the YakYak window.  Right-clicking while holding down shift doesn't bring up the menu with 'Move' in it.

In the end, the only way I was able to retrieve the window was using Alt + Space + M to move it in to view.

**Comment by averissimo** [comment]
Can you guys test this release?

https://github.com/averissimo/yakyak/releases/tag/v1.4.4-position

It should fix window position but it was lacking feedback

**Comment by Videonauth** [comment]
Is that code as well in 1.5.0? or only in that particular version?

**Comment by averissimo** [comment]
Still only in that particular version, if someone could confirm that it works I will merge it.

Up until now, only my tests show it works

**Comment by Videonauth** [comment]
O.k. will test it and report back.

**Comment by Videonauth** [comment]
Seems to do what it is supposed to do. just moved and closed my window several times and it was re-opening on the exact position i closed it on.

**Comment by averissimo** [comment]
The bug that this build was going to solve is in the case where you have multiple monitors.

When closing the window or app and reopening after unplugging the monitor it was in, it was supposed to reopen in a new position on an available monitor.

**Comment by averissimo** [comment]
nevermind, your original comment was exactly this scenario.. sorry I lost track of the issue you reported :)

**Comment by Videonauth** [comment]
Well i have  Triple monitor setup where the third one is not always on (power wise, but connected) and I had the Yakyak client always pop up on the shear-line between two monitors so one half was on Monitor one and the rest half was on monitor two. This is why I opened this issue :) but 1.4.4 seems to fix that.

**Comment by averissimo** [comment]
I realized that almost as soon as I clicked comment and backtraced it immediately :)

Already created the pull request and I am merging it now :)

Thanks for reporting and feedback!
