### ISSUE TITLE
Clicking the tray icon does not open the window

### ISSUE THREAD

**Issue by Nohus** [yakyak/yakyak#798]
I set YakYak to minimize to the tray icon when closing, but I cannot show the window again by clicking the tray icon. I have to right click and select "Toggle minimize to tray". Clicking notifications also doesn't open the conversation or the window on KDE Plasma 5.

**Comment by PMiner** [comment]
did you press "toggle close to tray?"
I think this should be on by default, but it isn't.
-- 

-PiFi 🍍

**Comment by Nohus** [comment]
Yes, it makes closing minimize to tray instead of closing, which is what I want. But then I cannot show the window again by clicking the tray icon. Clicking the tray icon does nothing and I have to use the context menu.

**Comment by PMiner** [comment]
if yakyak is minimized to tray, when opening yakyak, it either crashes or
closes.
-- 

-PiFi 🍍

**Comment by JPRuehmann** [comment]
I have this problem to, The toggles work as expected but the Window can only oppened by right Click on the Icon and clicking minimize to tray. Not by clicking the Icon.

**Comment by sosguthorpe** [comment]
This issue is related to a known issue within the libappindicator package. https://bugs.launchpad.net/ubuntu/+source/libappindicator/+bug/522152

It is also discussed here: https://github.com/vector-im/riot-web/issues/3133

I managed to solve this by uninstalling the affected library on Kubuntu:
```
apt-get remove libappindicator1
```

This also fixes the problem with the Icon being too big within the KDE tray.

**Comment by JPRuehmann** [comment]
Sorry
I can´t remove libappindicator1 because of the following dependencies,

google-play-music-desktop-player vivaldi-snapshot vivaldi-stable

Is there another Solution?

**Comment by sosguthorpe** [comment]
Not really, as an app indicator can only open its menu. It can't perform any other action. It is a known limitation and is even documented within the electron documentation for the "Tray" object itself.

https://xwartz.gitbooks.io/electron-gitbook/content/en/api/tray.html

See the section **platform limitations**.

**Comment by JPRuehmann** [comment]
I think that is just a cosmetic problem.
But the Menu Entry should at least give the right Info.
Restore, but Minimize
And it should Display the right Icon in the Tray.
Thanks,

**Comment by sosguthorpe** [comment]
Yes the wording on the tray menu probably does need changing to something more suitable. The Icon is actually the correct Icon, but it hasn't been scaled to fit the correct size. The Icon I see on KDE is this one:
https://github.com/yakyak/yakyak/blob/master/src/icons/icon-read_128.png
But I only see the bottom of the "Y" which makes it look like a filter Icon.

**Comment by JPRuehmann** [comment]
THanks, that explains it.
Will there be an Update in the near future?

**Comment by sosguthorpe** [comment]
I'm afraid I'm not a developer of the application and can not answer that question.

**Comment by JPRuehmann** [comment]
ok

**Comment by averissimo** [comment]
@sosguthorpe can you show a screenshot on how it looks on kde? do you want to give it a go and try to fix it?

How about the original issue, i got kinda lost reading through the comments :)

The click to tooggle is dependent on the operating system, in unity for example it did not work and it would always show the "right" click menu

**Comment by JPRuehmann** [comment]
https://github.com/yakyak/yakyak/issues/807

**Comment by averissimo** [comment]
thanks @JPRuehmann and @sosguthorpe ! let's continue that discussion on #788

**Comment by sosguthorpe** [comment]
@averissimo The referenced issue above shows how it looked for me. The original issue here is that the "App Indicator" specification doesn't support left-click events to be caught so while the libappindicator lib is present it won't work. I have posted a [workaround within a comment](https://github.com/yakyak/yakyak/issues/788#issuecomment-356240149) on the referenced issue #788.

**Comment by frz-dev** [comment]
There's something I don't get. The tray icon actually opens the window when using the Chrome hangouts client. And it does despite the libappindicator1 package is installed.

So there must be a way

**Comment by sosguthorpe** [comment]
@frz-dev Not for me it doesn't. Just installed the chrome extension and left-clicking does nothing. I have to right-click and select "Google Hangouts". This is in KDE Plasma 5

**Comment by frz-dev** [comment]
I'm on Ubuntu 16.04, with Unity desktop.

**Comment by frz-dev** [comment]
Didn't notice that the whole discussion was about KDE. 
However, the issue is present in Unity as well, as I can't open the windows by just clicking the tray icon.
Nonetheless, the same worked with Chrome plugin.
