### ISSUE TITLE
Implement a way to be able to start a voice or video call with someone

### ISSUE THREAD

**Issue by Speentie8081** [yakyak/yakyak#799]
Implement a way to be able to start a voice or video call with someone

This would be a very handy feature, as of right now from what I understand all you can do is accept / reject incoming calls. I would like a way to actually call someone personally using this client, maybe clickable icons next to the 3 dots icon, by the way I am running Windows if it matters.

![image](https://user-images.githubusercontent.com/12576827/32108510-8efd5af0-baf7-11e7-98eb-0af2fe2f8cc3.png)

To the left of the 3 dots icon in that screenshot is where I believe it should be.

**Comment by PMiner** [comment]
I agree. that would be a great place for it.
-- 

-PiFi 🍍

**Comment by dogopupper** [comment]
it's absurd that this is the only alternative for a hangouts app without the use of chrome. since it can handle incoming calls, I suppose it's not hard to implement starting calls or joining group calls - e.g. a hangouts link opening yakyak. if there's an outline of what needs to be done I could devote some time on implementing it.

**Comment by acca** [comment]
+1

**Comment by Serhansolo** [comment]
Well I guess it is time to have some new activity...! It is strange that this functionality is not yet implemented! Is it not one of the key features of Hangouts ?

@Admins why is it not still in the code app?

**Comment by daddydeadpool** [comment]
I'm throwing in on this as I also feel this is a needed feature!

**Comment by Speentie8081** [comment]
This stale bot isn't a good implementation for github issues

**Comment by raanraan** [comment]
+1

**Comment by Speentie8081** [comment]
Fix your stale bot

**Comment by mattg629** [comment]
Great for Linux Mint users too!  Want to avoid Skype at all costs!

**Comment by azjezz** [comment]
+1

**Comment by ZaheenJ** [comment]
I need this feature. I hated the bright white in hangouts while using chrome. That's why Yakyak is so great. This is the last thing that Yakyak needs and it will be complete

**Comment by WasabiCannon** [comment]
+1 for support for calls.

**Comment by Austcool-Walker** [comment]
I also wish this feature existed.
