### ISSUE TITLE
sound notifications

### ISSUE THREAD

**Issue by algesten** [yakyak/yakyak#8]
in which case do we want it?

"Any way we can get sound notifications for new IMs? Other than that this is off to a great start! Keep it up!"

**Comment by davibe** [comment]
I would say we can do sound for unmuted conversations with toggle menu like conversation thumbs (off by default, persisted).

**Comment by algesten** [comment]
sounds good. now we just need to figure out how to play sounds in electron.

**Comment by webdevbrian** [comment]
Hey that was my suggestion -- sweet!! 

I fiddled with the source and have a basic working example of it -- but I'll see what you guys come up with, it's pretty straight forward / simple.

Thanks!

**Comment by algesten** [comment]
Hey! I don't think anyone is looking at it. Please show me the way! :D

**Comment by webdevbrian** [comment]
Hey Martin! Will do! Give me today / tomorrow to jump on it, I have a huge client project right now that's been pretty daunting.

Will post in a bit!

**Comment by algesten** [comment]
cool!

**Comment by webdevbrian** [comment]
After looking at it ... I really don't want to share this ... :-/ ... pretty gross / bad coding

New to coffee script so most of it was a hack job, sorry. Though I did just duplicate / modify what I saw for the "chat notifications" and "notification_level" got me going down the right path.
