### ISSUE TITLE
How to set status as "available" or "away"?

### ISSUE THREAD

**Issue by bramadams** [yakyak/yakyak#80]
Hi,

Does Yakyak have functionality to set someone's state as "available", or what should be done to implement this? My colleagues told me my status is always "unavailable" when I'm using Yakyak.

BA

**Comment by davibe** [comment]
It's something missing. Would love to see pull requests. @algesten may have some ideas about how it could be done.

**Comment by williamsjj** [comment]
This is a real pain.

**Comment by darrenmcentee** [comment]
This is one of the reasons I can't use YakYak right now until this is 100% fixed. 
@averissimo any chance this can be put higher up the priority list. There's no indication of online status when chatting. It's a show stopper for me, as i need to know specific contact are available :)
Thank you,
Darren.

**Comment by averissimo** [comment]
Hi @darrenmcentee

It is currently possible to view which contacts are online and which aren't as they should have a green dot in their avatar (see the first screenshot)

If you open the inspector (Ctrl + Alt + I) you can also see which users are not advertising their online status -- second screenshot

![image](https://cloud.githubusercontent.com/assets/211358/25241441/e80859f0-25ed-11e7-948a-378c1e3b4ed8.png)

![image](https://cloud.githubusercontent.com/assets/211358/25241514/30f71c14-25ee-11e7-8295-8d9b72d9ed9b.png)

p.s. green dot color may vary with the theme

**Comment by darrenmcentee** [comment]
Thanks @averissimo ,
My issue here is that i know 3 people that are online, they all have a green status on Gmail browser chat, in Trillian windows app, and Hangouts on Android, but in yakyak, they never show the online green status.
Also, will yakyak show an orange away status?
My gmail/google handle is darren dot mcentee if you want to drop me an email, i will show you exactly what i mean.
Thanks.

**Comment by averissimo** [comment]
so this is a new problem! :)

Can you check if those contacts available on gmail/etc.. are on the inspector list as _'*** does not show his/hers/it status'_ ?

**Comment by averissimo** [comment]
if so please expand the object as much as you can (ignoring the _proto_ keys)

**Comment by darrenmcentee** [comment]
ok @averissimo, i did some tests... a few times, with the same results.
With 2 contacts in Gmail browser chat, and yakyak. See attached (gmail left, yakyak right.)
You'll see the 2 x green statuses in gmail, for both contacts. But in yakyak, only one green.
The inspector doesn't have either contact listed. 
![untitled-2](https://cloud.githubusercontent.com/assets/2485782/25268823/1b3002e0-2672-11e7-9f66-229cf2513943.png)

**Comment by averissimo** [comment]
please try this build and expand Nicola's object as the screenshot shows.. please censor the user_id as no one needs to know that :)

https://github.com/averissimo/yakyak/releases/tag/fix-presence-0.1

![image](https://cloud.githubusercontent.com/assets/211358/25281400/2f446a0e-26a5-11e7-8e97-63ca1588d328.png)

**Comment by darrenmcentee** [comment]
I tested again, Nicola is showing now with green online status.
inspector item:
![2017-04-21_15-35-15](https://cloud.githubusercontent.com/assets/2485782/25282465/7757eb4c-26a8-11e7-9701-2eb4b72c3cf1.png)

**Comment by averissimo** [comment]
Try to find one of your contacts that is not showing in YakYak and is showing.

My guess is that sometimes these contacts are only on `mobile: true` and `available` is set to false

ps. I can't replicate this with any of my contacts, that's why I'm asking :)

**Comment by darrenmcentee** [comment]
Ah I think I see what's going on here. The opposite is happening now, my contact goes offline in gmail, but then still shows as online green in yakyak. Once I close yakyak, and reopen it, the correct status is shown.
I think the statuses are not getting updated in real-time, but maybe it's currently coded like that?
A yakyak restart seems to show the correct status at launch, but then not getting updated?

**Comment by darrenmcentee** [comment]
Do you think real-time friend status changes will be applied to an update soon @averissimo 
Thanks,
Darren.

**Comment by averissimo** [comment]
someone needs to understand how to get that information from the server and update it.

I'll try to pick this up as it is an important issue, but not in the next week :\

if someone else wants to dab in yakyak and figure this out.

my hypothesis so far is that we are taking this information from the initial connection and that's it.

we either need to call `querypresence` for each user from time to time, or use another wrapper method that gets more data at once (such as `syncrecentconversations`)

**Comment by darrenmcentee** [comment]
Any update on this guys? Do you think real-time friend status changes will be applied to an update soon @averissimo
Thanks,
Darren.

**Comment by chronodm** [comment]
Is this issue about setting your own status or displaying friend status? It seems to change topics as of @darrenmcentee's comment on April 20.

**Comment by parthagar** [comment]
Would love to see a solution for this.
