### ISSUE TITLE
RPI 3 DEB package

### ISSUE THREAD

**Issue by sergioad** [yakyak/yakyak#802]
Hi friend, could you make a deb for Raspberry pi? I use UbuntuMATE 16.04 on it as my primary PC since certain day in wich my laptop ceased to function and I will say: I miss a good looking and modern IM client

**Comment by PiFi** [comment]
can you not install snaps? on the Ubuntu website, it says that ubuntu mate supports snaps. yakyak is already on the snap. "sudo snap install yakyak"

**Comment by sergioad** [comment]
does it works on the piś cpu?

**Comment by averissimo** [comment]
@sergioad you can try:

- install `node`
- Downloading the source and enter the directory
- run `npm install` and `npm start`

I'm not sure if it runs, but you can try

Also, you may want to install ` apt-get install libgtk2.0-0 libnotify4 libgconf2-4 libnss3 `

from: https://www.reddit.com/r/raspberry_pi/comments/3k5xrq/electron_on_raspberry_pi/

**Comment by sergioad** [comment]
Ok, thanks

**Comment by averissimo** [comment]
If you do, please give some feedback in this issue!

It may help someone else in the future :)
