### ISSUE TITLE
Google voice integration

### ISSUE THREAD

**Issue by n0use** [yakyak/yakyak#81]
Hello - this app seems pretty awesome, but the way I use the hangouts app (on my android device and the chrome app) is configured such that I can send messages to actual phone numbers, originating from google voice#.

It seems like this feature is lacking currently in yakyak - are there plans to bring it in? If so it would totally kill any need I had for the hangouts chrome app.....

thanks!
--
John  jnn@synfin.org

**Comment by davibe** [comment]
There is currently no plan for this. The few time we have is spent on issues rather than features.
Thank you for bringing it up though. Will think about it in the future.

**Comment by Jimi-James** [comment]
+1 for this one, even if it's only someday

**Comment by GreyAsteroid** [comment]
After the hangouts chrome extension got "updated" I started looking for an alternative and was really excited when I found yakyak until I realized it didn't have this functionality. Really hoping this gets added.

**Comment by DrDMoney** [comment]
It would be great if you could just rename the contacts inside the add if importing from google voice would be too difficult.

**Comment by averissimo** [comment]
@DrDMoney this is being tracked in this issue: #232

but to sum it up, none of the current developers uses google voice, so we would need someone that uses it and will be willing to develop yakyak :)

**Comment by CodeAbuser** [comment]
I use google voice and some experience with CoffeeScript and NodeJS. If you guys wanted to point me in the right direction for where to start looking in regards to fixing this functionality, I would be willing to fork the code and take a look.

**Comment by averissimo** [comment]
@hawksprite seems to have found a solution and is preparing the PR, you can find part of the right direction in his comments

Yakyak send messages via dispatcher.coffee with `sendmessage` handle.

From @hawksprite comments, I understand that we need to check in that step (or before) if it is a google voice contact and then send with the ipc message the type of contact that it is.

in `main.coffee` where the ipc message is received before sending to hangupsjs client, it needs to change `delivery_medium` to the type of contact it has received (BABEL or GOOGLE_VOICE)

I'm guessing this would be it, but I don't have google voice and it would be difficult for me to fix this :)
