### ISSUE TITLE
rpm deploy error

### ISSUE THREAD

**Issue by nerijus** [yakyak/yakyak#813]
$ npm run gulp deploy:linux-x64:rpm

> yakyak@1.4.4 gulp Electron/yakyak
> gulp "deploy:linux-x64:rpm"

[18:40:10] Failed to load external module coffeescript/register
[18:40:10] Requiring external module coffee-script/register
[18:40:11] Using gulpfile Electron/yakyak/gulpfile.coffee
[18:40:11] Starting 'deploy:linux-x64:rpm'...
Possible problem with rpm yakyak-VERSION-linux-ARCH.rpm -- (exit with 1)
[18:40:11] Finished 'deploy:linux-x64:rpm' after 42 ms

npm ERR! Linux 4.13.11-200.fc26.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "gulp" "deploy:linux-x64:rpm"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! yakyak@1.4.4 gulp: `gulp "deploy:linux-x64:rpm"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yakyak@1.4.4 gulp script 'gulp "deploy:linux-x64:rpm"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yakyak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp "deploy:linux-x64:rpm"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yakyak
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yakyak
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     Electron/yakyak/npm-debug.log
[npm-debug.log](https://github.com/yakyak/yakyak/files/1467639/npm-debug.log)

**Comment by averissimo** [comment]
@brendanlong

What are the requirements other than fpm?

This is something that works on my laptop but not on Travis CI.

**Comment by brendanlong** [comment]
Hm the log output is pretty unhelpful, but one thing that might be missing is that the RPM deploy depends on the tar.gz file already existing I think, so maybe it's an ordering thing?

`fpm` alone should be enough though :\
