### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by Rudloff** [yakyak/yakyak#814]
Hello,

It would be nice to have a Debian package for yakyak.

**Comment by OctoPenguin** [comment]
I myself am working on this and have actually submitted a pull request to the developers for a package using Canonical's Snappy platform.

**Comment by averissimo** [comment]
they are now being built with newer releases, from 1.5.0 and up. Thanks @OctoPenguin

**Comment by Rudloff** [comment]
That's great! Thanks!
Is there any plan to provide a repository so it can easily be updated with `apt upgrade`?

**Comment by averissimo** [comment]
That would require someone to step up to create and maintain the repository.

Sorry for the non-committing answer.
