### ISSUE TITLE
ffmpeg.dll missing for 64bit 1.4.3+

### ISSUE THREAD

**Issue by Mavarice** [yakyak/yakyak#817]
In the 1.4.3 and 1.4.4 versions the 64 bit version on windows complains about a missing ffmpeg.dll file and won't run once extracted. However the 32 bit versions have no issues.

Computer specs:
OS Name: Microsoft Windows 10 Pro
--
Version: 10.0.16299 Build 16299
Other OS Description: Not Available
OS Manufacturer: Microsoft Corporation
System Manufacturer: MSI
System Model: MS-7A33
System Type: x64-based PC
Processor: AMD Ryzen 5 1600X Six-Core Processor, 3600 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date: American Megatrends Inc. 4.50, 9/20/2017
SMBIOS Version: 3

**Comment by averissimo** [comment]
v1.4.4 seems to work now as well as v1.5.0, **please reopen if this happens again**

Thanks for letting us know, this might be related to the version of the packager we used in v1.4.3 and that snapshot of v1.4.4

**Comment by averissimo** [comment]
v1.4.3 binary was updated as well.
