### ISSUE TITLE
turns history on

### ISSUE THREAD

**Issue by mwotton** [yakyak/yakyak#82]
Not exactly sure why or how, but yakyak seems to turn history on: this is a bit of a problem for secure chats that are meant to be ephemeral.

**Comment by algesten** [comment]
how do we reproduce this?

**Comment by lamelas** [comment]
Having the same issue. Sending a message from YakYak to a chat where message history is turned off, the message is sent with history turned on. Let me see if I can fix it and send a pull request.

**Comment by playerzero** [comment]
Steps to reproduce:

1. Start a new conversation via hangouts.google.com or the official Hangouts "app" (Chrome extension). 
2. Turn off history:
    * In web view, select the Gear icon in top right, then uncheck Hangout History then click OK.
    * In Chrome "app" select the 3 dots icon in top right, then Options, uncheck Hangout History, then OK.
3. Exchange some messages.
4. After some time, the message history will disappear (i have not been able to determine how much time, and login out and back in does not do it - sorry this step is so vague).
5. Return to this conversation in YakYak and exchange some more messages.
6 History will not disappear :(

IMO, it would be best if YakYak could provide access to this setting in the upper-right menu alongside Notifications, Favorite, and Details (or under Details?). But i think it's crucial to at least honor the history setting as set in Hangouts.

**Comment by danpoulin** [comment]
Still having an issue with this. Any idea if it will be fixed?

**Comment by playerzero** [comment]
Is there an understanding of what would need to be done?

**Comment by averissimo** [comment]
When building the message to be sent, check the 'on the record' status of the conversation.

This is the line that forces all messages to be kept in history: https://github.com/yakyak/yakyak/blob/master/src/ui/models/userinput.coffee#L48

I'm currently behind a stupid setup that does not allow me to run yakyak and solve this in the short term, I can help with my knowledge of yakyak if someone wants to give this a go :)

**Comment by averissimo** [comment]
can someone test pull request #769 

it should implement the fix for this

I'm closing the issue, please continue discussion there

**Comment by averissimo** [comment]
it does not allow to change the status though, pull requests are welcome (and there are already issues with this feature request)
