### ISSUE TITLE
Minimize or Reduce to tray when close the app ?

### ISSUE THREAD

**Issue by LeDistordu** [yakyak/yakyak#821]
It would be nice if there could be three options when closing the application:

- Minimize (Taskbar)
- Reduce in tray
- Close (Default)

Thank for your work

**Comment by averissimo** [comment]
@LeDistordu where do you suggest to add this?

**Comment by Minkiu** [comment]
Hi @LeDistordu I just found out today, but i believe that what you want can be enabled by:

Right click tray icon > Close to tray

Cheers.
