### ISSUE TITLE
SMS Messages Stay Grey

### ISSUE THREAD

**Issue by hawksprite** [yakyak/yakyak#822]
When sending an SMS message or MMS message (Either through Google Voice or Google FI) they stay Grey as if still attempting to send after successfully sending.

More images and a more detailed description of the issue will accompany this soon.

**Comment by averissimo** [comment]
try the new 1.4.4 version that already has the code that you helped develop.

We want to release this as 1.5.0 in the next few days if there are no problems

**Comment by gleitz** [comment]
@averissimo I'm on 1.4.4 which fixed the Gray messages issue, but I'm sure there are other bug fixes coming in 1.5.0. Let us know when it is released!

Thx :)

**Comment by averissimo** [comment]
Cool! I'm closing it then

**Comment by JawnZ** [comment]
I get this issue all the time. I'm on 1.5.4

This happens on SMS for Google Voice, both 1-on-1 and Group Texts.

The weird part is that the messages still show up when I go to Gmail and look at hangouts directly, but the recipient never receives the message that is gray on Yak-yak
