### ISSUE TITLE
Messages sometimes not appearing

### ISSUE THREAD

**Issue by arcooke** [yakyak/yakyak#823]
I'm having an occasional issue with messages not going through to Yakyak.  Unfortunately, no special circumstances to help reproduce.. it just happens randomly sometimes.

See below.  Left is yakyak, right is a screenshot from my phone.  The message about the 660Ti didn't come through on yakyak. I was actively using yakyak (not my phone) when it happened this time. 

![screenshot from 2017-11-27 17-07-14](https://user-images.githubusercontent.com/6278400/33294361-e8ebd15c-d395-11e7-8423-a5c31e0245c8.png)

I'm using yakyak 1.4.3 on Solus 3

**Comment by mdellabitta** [comment]
I have this problem too, and occasionally the app needs a restart to see any new messages. It's pretty much killed my ability to use the app.

**Comment by fraimondo** [comment]
I can confirm here. My messages are not going out. Just stay gray forever.

**Comment by mdellabitta** [comment]
I'm now running the app from the CLI using a github checkout / build and `npm run electron app --debug` to see if I can see any output when this situation happens.

**Comment by stanleymilgrim** [comment]
I have also been encountering this issue intermittently. It's a hit or miss with outgoing messages with zero notification errors. I rolled back to version 1.4.3 from 1.4.4 but have noticed this issue on both versions.

**Comment by mdellabitta** [comment]
I think a big chunk of this might end up being that no major errors are displayed when your network connection is shoddy and YakYak can't recover.

I'm in a place with a really bad Internet connection. In the foreground, there wasn't much indication that there was a problem, but in the shell, I was seeing this.

https://gist.github.com/mdellabitta/21ac1d7a99ccc7b5850548af9c09da5a

**Comment by arcooke** [comment]
@mdellabitta Thanks for digging into this

Connection issues might cause this in some instances, but I don't think that was what caused it for me.  I'm hard-wired on a very reliable fiber connection.

Something still could be causing a network interruption somewhere in the mix but I don't think it's necessarily connection quality, at least based my setup

**Comment by dzeidzei** [comment]
I just had issue of my messages not getting sent. In my case cause was probably usage of VPN some time before I noticed the issue. Yakyak has previously handled these situations just fine.

**Comment by mdellabitta** [comment]
@arcooke YakYak is keeping a socket going, and if that socket fails, it tries to recreate it. In my case, even after I reestablished my network connection and confirmed it was working, YakYak was still unable to reestablish the connection, and there wasn't an indication in the UI that this was happening. Not saying this is the only problem, but it's definitely *a* problem if it happens regularly.
