### ISSUE TITLE
Feature Request - X Button minimize to SysTray

### ISSUE THREAD

**Issue by rtSketo** [yakyak/yakyak#825]
Is it possible to have an option for X button to function as the Esc Key when Tray Icon is enabled?

Thanks!

**Comment by rtSketo** [comment]
Oh I just found it after searching the issues.
I wasn't expecting Tray menu to have more options.

I think it would have been more user-friendly if the option was in the app menu.
I'll leave the request open just in case you want to consider that.

I was waiting for such an app for years and I just found out about YakYak.
Thank you so much for the great work. Keep it up!

**Comment by averissimo** [comment]
Glad you found it (both app and options)

Having them all in a single place would definitely improve experience.
