### ISSUE TITLE
Uploads not working

### ISSUE THREAD

**Issue by lernerd** [yakyak/yakyak#83]
It just remains on the progress info forever...
![screen shot 2015-11-16 at 11 24 09 am](https://cloud.githubusercontent.com/assets/1086613/11184132/abf11f26-8c54-11e5-8529-6e86b0e829cc.png)

Great app :smiley: thanks!

**Comment by jhrv** [comment]
+1

**Comment by kethinov** [comment]
I am seeing this issue as well. It used to work, and now it doesn't suddenly even though I haven't updated the app.

My guess is the API yakyak uses in hangups is probably broken now and needs to be updated.

**Comment by lernerd** [comment]
Exactly my case too @kethinov , agreed

**Comment by jimeh** [comment]
same issue here too :)

**Comment by lernerd** [comment]
It looks like it has been dealt with in hangupjs https://github.com/algesten/hangupsjs/issues/35

**Comment by lernerd** [comment]
Ok, I've change package.json to include the latest hanupsjs, but it's still not working.
I've done some debugging and when I upload it enters what looks like an infinite loop of failed uploads:
![screen shot 2015-11-18 at 10 50 41 am](https://cloud.githubusercontent.com/assets/1086613/11242770/85101f62-8de2-11e5-87ec-6f94713d8dcc.png)

Darn, failed to capture the response, but it says something like "denied".
Hope this is useful... thanks!

**Comment by jimeh** [comment]
I got it working locally by simply hacking `node_modules/hangupsjs/lib/client.js` in my installed app, changing this:

```javascript
IMAGE_UPLOAD_URL = 'http://docs.google.com/upload/photos/resumable';
```

to use HTTPS:

```javascript
IMAGE_UPLOAD_URL = 'https://docs.google.com/upload/photos/resumable';
```

Quick work around till a new hangupjs version is published.

@lernerd I tried the same thing as you initially, just pulling in hangupsjs from the master branch, but cause the JS files aren't part of the repo, YakYak seemed to end up with old JS files in the final app I built.

**Comment by lernerd** [comment]
Awesome @jimeh ! I'll try it out, thanks ヽ༼ຈل͜ຈ༽ﾉ

**Comment by davibe** [comment]
@algesten can you do this in hangupjs ? seems straightforward if i understood correctly

**Comment by jhrv** [comment]
tested @jimeh 's workaround, worked perfectly :)

**Comment by jimeh** [comment]
@davibe It's already done in in hangupjs here: https://github.com/algesten/hangupsjs/pull/34

However there's no new package version of hangupjs published to npm yet, which makes it quite tricky to pull it into YakYak via package.json (the repo only contains CoffeeScript, so a git dependency doesn't work). Hence I opted to just manually patch my installed copy of YakYak for now.

**Comment by davibe** [comment]
ok but @algesten is the developer of hangupjs and I think i can persuade him to nom-publish the thing

**Comment by algesten** [comment]
done. we have hangupsjs 1.2.0
