### ISSUE TITLE
Support for archive conversations

### ISSUE THREAD

**Issue by wlonk** [yakyak/yakyak#830]
Apologies if this is a duplicate, or already possible, but I'd love to be able to archive old conversations and remove them from the sidebar list.

Thanks!

**Comment by Splix76** [comment]
Add me to the list of those asking for archived conversation support. I like a nice clean chat window only showing what I need to handle currently, archived views allow this. 

Really like yakyak so far, shifted back to FireFox as my primary browser this week and there is no good addon client out there, yakyak fits the bill nicely.

**Comment by averissimo** [comment]
+1

This could be a good entry point for someone wishing to develop on Yakyak!

Should only need to verify if there is some field in conversation object that identifies it as an archived conv.

**Comment by The-Bob** [comment]
~~Definitely needed, don't know why this was closed.~~

Edit: there's an open pull request that closed a duplicate of this, but it's been waiting for merge since Jan 2018? #855

**Comment by icsjolinger** [comment]
I would like this as well.  Kind of doesn't allow for usable view of the conversations that are important... otherwise you have to favorite them all.

**Comment by averissimo** [comment]
This feature *(or bug fix, depending how you look at it)* is available since the beta release of v1.5.5 beta-rolling

**Comment by icsjolinger** [comment]
I just installed Mac OS version 1.5.5 beta.  I do not see where the Archive feature is located.  I don't see it in any docs here either.
Can you explain where to find?
