### ISSUE TITLE
cookies.json corruption

### ISSUE THREAD

**Issue by arcooke** [yakyak/yakyak#831]
Found another corruption issue in `~/.config/yakyak/cookies.json`.  Yakyak refused to start up, yelling about the cookies file. I opened it up and the file looked like a mess of garbage data.  So I deleted the file and relaunched and it fixed the problem.  Corrupt `cookies.json` is attached as a .txt

[cookies.txt](https://github.com/yakyak/yakyak/files/1555751/cookies.txt)

Yakyak 1.4.4, on Ubuntu MATE 17.10

```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at loadFromFile (/home/<me>/yakyak-linux-x64/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:149:32)
    at new FileCookieStore (/home/<me>/yakyak-linux-x64/resources/app/node_modules/tough-cookie-filestore/lib/filestore.js:14:5)
    at Client.module.exports.Client.doInit (/home/<me>/yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/client.js:188:68)
    at new Client (/home/<me>/yakyak-linux-x64/resources/app/node_modules/hangupsjs/lib/client.js:102:12)
    at Object.<anonymous> (/home/<me>/yakyak-linux-x64/resources/app/main.js:48:12)
    at Object.<anonymous> (/home/<me>/yakyak-linux-x64/resources/app/main.js:523:4)
    at Object.<anonymous> (/home/<me>/yakyak-linux-x64/resources/app/main.js:527:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

**Comment by averissimo** [comment]
That is strange, please report back if it happens again *(try to remember if there are steps that can be done to reproduce it)*

Been using yakyak for more than a year and it never happened to me.

**Comment by arcooke** [comment]
I don't know how I could reproduce it, I only noticed the problem upon startup when Yakyak failed to launch.  I don't know what event triggers it to become corrupted in the first place so I can't really reproduce it.  Yakyak knows when it's writing something to the cookies file.  I, as a user, don't have a clue.  

It seems some json validation would be the best approach to capturing the issue as it happens.

I don't think this should be closed.. it's a valid issue.  And it doesn't seem I'm the only one having it

#647 looks to have the exact same issue
#736 possibly related

**Comment by KyleFromKitware** [comment]
Happened to me too. In my case, my computer crashed because of a bug in VirtualBox while Yakyak was running. My cookies.json file has been corrupted multiple times because of this.

**Comment by TheDavidJohnson** [comment]
Yep. My machine hung (for reasons unrelated to YakYak) and I noticed YakYak didn't start automatically on reboot like I normally have it set to do (actually, to be more precise: it's set to start on _login_ ).

Clicking on my YakYak icon in GNOME just produced a spinning circle. (I'm currently running YakYak on Ubuntu 18.04.1 LTS)

Attempting to run YakYak from the command line produced an error message like this:

```
Uncaught Exception:
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
```

So, after finding this thread and reading @arcooke's comments about the `~/.config/yakyak/cookies.json` file, I found that mine was full of crap as well.

### Here's how I solved the problem on Ubuntu

1. Opened a terminal (Ctrl+Alt+T)
2. Changed to my user profile's config directory for yakyak: `cd ~/.config/yakyak`
3. Renamed cookies.json (just to make a backup): `mv cookies.json cookies-bad.json`
4. Re-ran YakYak from my GNOME desktop (you can try it from the command line to see if you get any other errors: `yakyak`)

When I re-launched YakYak, I had to login to my Google account, which was no big deal. It ran perfectly.
