### ISSUE TITLE
Support for Markdown

### ISSUE THREAD

**Issue by unclvito** [yakyak/yakyak#832]
How about support for markdown? Moving from slack to hangouts is a big bummer due to lack of formatting support. imagine chatting with a team of developers and all of the code you paste in look terrible. markdown would help.  (funny, as I type this in github, just below the input box is the comment 'Styling with Markdown is supported')

**Comment by averissimo** [comment]
I agree!!

We are currently replicating hangouts as best as we can, and the client doesn't support markdown :\

Yakyak does perform formatting when it receives from a hangouts client *(such as bold italic)* but cannot in our end to the same.

We would welcome pull requests that supported markdown in some way :)

**Comment by FSund** [comment]
I think some features from Markdown could be brought over easily, like the codes for bold and italic, which can just be converted regular bold/italic (which is supported by Hangouts).

**Comment by yuvalif** [comment]
maybe this could be reopened?
google chat now support markdowns like code snippets.
