### ISSUE TITLE
iOS Emjois appear as boxes

### ISSUE THREAD

**Issue by andromedastudios1** [yakyak/yakyak#833]
Hello, 
Issue is exactly as described. Google Voice is linked to Hangouts, and when emojis from an iPhone running iOS 11 are sent, the emjois show as boxes.

![image](https://user-images.githubusercontent.com/18728114/34082785-4783e3e6-e32a-11e7-926f-5df29e3d630d.png)

**Comment by averissimo** [comment]
does this appear as boxes in hangouts web client? (inside gmail)

**Comment by andromedastudios1** [comment]
sorry for the late reply, but no, it does not.

>
>
>

**Comment by davibe** [comment]
@andromedastudios1 which OS are you using when running Yakyak ?

**Comment by andromedastudios1** [comment]
Using Windows 10 Fall Creators Update 64-bit.

**Comment by andromedastudios1** [comment]
Sorry did not see that last part in my email. Usually use hangouts with GV so will test and get back to you shortly @davibe

**Comment by andromedastudios1** [comment]
Issue somehow fixed itself, so I'm not really sure what to say. Closed the issue. Sorry about that!
