### ISSUE TITLE
MMS(photos) not received by recipient when in Group MMS Chat or Individual MMS

### ISSUE THREAD

**Issue by aputtapa000** [yakyak/yakyak#834]
This occurs mainly in group chats however noticed this with individual recipients as well(sometimes it takes a very long time 30 mins+ to be received but usually never delivers). It is very quick on normal hangouts but does not work in YakYak at all. Ending up having to resend using web client or phone(hassle).

**Comment by averissimo** [comment]
I don't think we support MMS in google voice.

I think most of the developers that contribute to yakyak are from Europe and do not have access to this feature in hangouts.

We updated pre-release v1.4.4 today with better support for replying to sms, but would appreciate if someone worked on mms :)
