### ISSUE TITLE
Port yakyak to meetfranz

### ISSUE THREAD

**Issue by pengi** [yakyak/yakyak#838]
I guess that it shouldn't be too much (even though it will be some) work to port yakyak to work within meetfranz

https://github.com/meetfranz/plugins

https://meetfranz.com/

This is since both are web views.

Doing so will make it possible to simplify for users using multiple chat protocols

**Comment by pengi** [comment]
I havn't looked that much at the franz API, but it would probably be great help for #13

**Comment by davibe** [comment]
Franz just opens a webview to the already existing mobile web pages of each service. Yakyak on the other hand has its own hangout js client implementation (which runs outside of the webview process) and all the UI code is custom. They are using very different approaches. I can't imagine how yakyak could integrate into Franz. That being said #13 would still present the same challenges
