### ISSUE TITLE
Emoji Suggestion Completion

### ISSUE THREAD

**Issue by zpolygon95** [yakyak/yakyak#841]
When typing a message, I have the instinct to just hit <kbd>enter</kbd> when the emoji I want is the first one in the list of suggestions. For example, typing `:lau` suggests only :laughing: -- I type <kbd>enter</kbd>, and my conversation partner is immediately sent literally `:lau`. It's not very intuitive to type <kbd>tab</kbd> to select the only suggestion in a list, *then* hit <kbd>enter</kbd> to select it.

In a somewhat related issue, I believe <kbd>shift</kbd>+<kbd>tab</kbd> should advance the selected suggestion in reverse order. For example typing `:l` suggests :laughing:, :business_suit_levitating:, :lips:, :lipstick:, and :lion:. Typing <kbd>tab</kbd> select :laughing:, and <kbd>tab</kbd> again selects :business_suit_levitating:. <kbd>shift</kbd>+<kbd>tab</kbd> at this point should select :laughing:, but instead continues on to select :lips:.

Is this functionality wanted by anyone else?

**Comment by averissimo** [comment]
@clementlamoureux what are you thoughts on this?

**Comment by averissimo** [comment]
I'm with you on shift+space *(although I never used it before you pointed it out)*

Not sure about your first suggestion, as there is a case were it would not be the best solution: *when writting `:)` the first suggestion is not the `:)` emoji, but a pig instead 🐷

I would guess the suggestion list would have to have exact matches on first suggestion for your suggestion on automatic selection, but it could require an extra action to remove suggestion *(such as escape key)*

Adding something for the discussion, for me it is intuitive that <kbd>space</kbd> should also select the emoji

**Comment by PiFi** [comment]
Yes, this would make the emoji system much more intuitive. This type of behavior is expected since it is in many other programs as well.
