### ISSUE TITLE
When will 1.5.0 be full release

### ISSUE THREAD

**Issue by plessbd** [yakyak/yakyak#847]
Any time frame for when 1.5.0 will be considered an release instead of a pre-release

Was trying to get homebrew updated (https://github.com/caskroom/homebrew-cask/pull/42507#issuecomment-356001285) and they noticed that it was a pre-release.  I didnt even notice, and could swar I got a message about an update in the previous version.

**Comment by averissimo** [comment]
There seems to be a bug with history retrieving *(when scrolling to the top of the conversation it retrieves history until beginning of time)*

This is quite nasty and requires fixing or undoing something before a stable version is released.
