### ISSUE TITLE
electron-installer-flatpak doesn't support windows

### ISSUE THREAD

**Issue by isavegas** [yakyak/yakyak#848]
A hard dependency on the electron-installer-flatpak NPM package breaks run/build process on Windows.

**Comment by averissimo** [comment]
A specific target or during `npm install` ?

**Comment by isavegas** [comment]
@averissimo During npm install. It still breaks during run due to unconditional require, even if you remove the entry in package.json. I was able to work around it by removing the entry in package.json, as well as the reference in gulpfile.coffee.

**Comment by averissimo** [comment]
Created issue upstream to help figure this out 

https://github.com/endlessm/electron-installer-flatpak/issues/20

**Comment by averissimo** [comment]
as I'm not really a node ninja that knows how to best deal with this situations :) if you have a suggestion I'm all ears

**Comment by isavegas** [comment]
I was thinking it could be a good idea to move it to the [optional dependencies](https://docs.npmjs.com/files/package.json#optionaldependencies) package.json object, try/catch loading the dependency in the gulpfile, and switch on the current platform, throwing away the error on windows and giving the user a warning on Mac/Linux.

I can throw together a PR later today.

**Comment by averissimo** [comment]
Sounds good to me, I'd really appreciate if you could send the PR

**Comment by isavegas** [comment]
After wrestling with Github, Git, and NPM, I finally managed to open a second pull request with only the edits required to fix the Windows workflow. Unfortunately, changing the package.json force updated packages in package-lock.json on `npm install`.
