### ISSUE TITLE
1.5.0 Pre Release New SMS and Delete SMS issues

### ISSUE THREAD

**Issue by G0ldeneye007** [yakyak/yakyak#850]
Recently switched to Hangouts and YakYak with the demise of AIM, and new to GitHub so apologies if I've done this bug wrong.

Two issues I've found in version 1.5.0 Pre Release.  Both were actually there in 1.44 as well. I'm using Windows 10 and replicated the issue on both the 32 and 64 bit binaries. 

First, it doesn't seem possible to create new SMS message/conversations through the application.  When clicking the + symbol to start a new conversation, no matter how I type in a phone number, all it does is open a new conversation that doesn't go anywhere.  This conversation does appear in hangouts while in browser, but it is just labeled as "Empty Hangout".  I've tried creating conversations in the following formats:
+15551234567
(555) 555-1234
1 (555) 555-1234
5551234567

Second, it does not appear possible to delete any conversation. When clicking details, if the button says "Leave Conversation" it will work.  If it says "Delete Conversation", it will kick you to the first conversation in your list, but won't delete the one you tried to delete.

Tried running YakYak on the command line, but it doesn't appear to provide anything helpful.  When attempting to delete conversations or create new SMS convos, nothing appears in the command line.  I've included my output anyways. Happy to provide any additional information or do some testing to do my part in getting the app working properly. 

hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
hdisconnect
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
syncrecent

**Comment by averissimo** [comment]
For the first problem I'll have to appeal to someone that uses google voice to try to solve it. I'm from Europe and don't have access or use it.

Regarding the second one I was able to replicate it, but as soon as I introduced some debugging it solved it. Super strange.

**Comment by averissimo** [comment]
@G0ldeneye007 can you test the following build? please provide feedback so I can merge the code *(or fix it if it does not solve)

https://github.com/averissimo/yakyak/releases/tag/v1.5.0-%23850

If your problem still persists, please run yakyak from command line as: `yakyak --debug` from its directory and copy here the log.

(please remove any identifying information if there is such as links)

----

From what I understand, the delete event was not being received from the server. Adding a logging step it delays the call just a tiny bit that seems to be sufficient for everything to run smoothly.

It should not solve the issue, but it does.

**Comment by G0ldeneye007** [comment]
@averissimo  Will do when I get home.  Currently at work using a Windows 7 machine, and it seems to work fine here. May only be a Windows 10 thing.

**Comment by averissimo** [comment]
Wow, this loops should not be happening. Call to delete conversation happens only once regardless of how it runs out.

Does this only occur in sms conversations or is it the same with normal hangouts?

**Comment by G0ldeneye007** [comment]
Happens with both SMS and regular hangout, and again only on Windows 10.  Works perfect on Windows 7.

**Comment by averissimo** [comment]
There shouldn't be any dependence on the OS.

I'll try to corrupt the api call to see if I can replicate `ERROR_UNEXPECTED`

**Comment by PiFi** [comment]
I could not replicate the second problem, and I'll look into the SMS creation if I get time.
