### ISSUE TITLE
NEW LOGO

### ISSUE THREAD

**Issue by sachoosaini** [yakyak/yakyak#857]
I want to contribute in the form of a new logo. If a developer wants I can send it.

**Comment by arkany** [comment]
Hey there @sachoosaini , what does the new logo look like?

**Comment by sachoosaini** [comment]
@arkany  well  i will make it if you guys want it.

**Comment by averissimo** [comment]
please check #21 and #249 as current logo came from this discussion :)

**Comment by sachoosaini** [comment]
@averissimo yeah great..i will try to make something. Current logo is very decent too.

**Comment by sachoosaini** [comment]
@averissimo
![yayak sample logo](https://user-images.githubusercontent.com/10970138/37251378-0445b2ce-2535-11e8-9351-27eba10ac87e.png)
