### ISSUE TITLE
CPU usage on Kubuntu 17.10

### ISSUE THREAD

**Issue by petr-nehez** [yakyak/yakyak#858]
I am running the app for few days only but from what I can see in System Monitor, YakYak's CPU usage is much higher than Slack's or Skype's. 
I would say that YakYak' usage is 6 times higher than Slack's usage.
Any idea how to improve?

**Comment by averissimo** [comment]
last time we visited this issue it was cut to almost nothing.

@davibe you picked this last time, care to revisit? ou let us know how to do a performance check via some tool?

**Comment by petr-nehez** [comment]
FYI - I am now working on Manjaro KDE (kernel 4.14.16) and I checked 3 apps (all of them started at the same time in the following order). Here are the values for CPU usage after approx 50 minutes:

- Skype: 14 seconds,
- Slack: 23 seconds,
- YakYak: 36 seconds.

So on Manjaro it looks like not a big deal but still it consumes 2x more CPU than Skype.
