### ISSUE TITLE
Duplicate command under View to toggle fullscreen

### ISSUE THREAD

**Issue by jimeh** [yakyak/yakyak#86]
- Version: built from master as of 24aa929ae23746a41d3cd094bf382610270cc3af
- OS: OSX 10.11.1

It seems Electron is adding it's own "Enter/Exit Full Screen" commands to the View menu, along with the "Toggle Full Screen" command YakYak defines itself.

![screen shot 2015-11-19 at 13 18 13](https://cloud.githubusercontent.com/assets/39563/11271808/738e5996-8ec0-11e5-8240-8d99846af400.png)
![screen shot 2015-11-19 at 13 18 48](https://cloud.githubusercontent.com/assets/39563/11271812/7bd8910c-8ec0-11e5-93d4-bca58b9bc2d7.png)

**Comment by algesten** [comment]
can't see this one now.
