### ISSUE TITLE
Javascript error occured in the main process. V1.5.0

### ISSUE THREAD

**Issue by andromedastudios1** [yakyak/yakyak#869]
![image](https://user-images.githubusercontent.com/18728114/35778409-773ebe42-0983-11e8-97bf-812d7c015ce4.png)

Image explains it all
Unpacked to C:\Program Files\YakYak\YakYak.exe
Windows 10 Pro Fall Creators Update

**Comment by andromedastudios1** [comment]
Furthermore, when attempting to launch main.js: 
![image](https://user-images.githubusercontent.com/18728114/35778465-2ece32a4-0984-11e8-811e-656ca22eaa6a.png)
Looks like there were some issues while compiling the binaries.

**Comment by noloman** [comment]
exactly the same here, with Windows 10

**Comment by MatthiasVets** [comment]
I also have this error. This occurred after windows update

**Comment by andromedastudios1** [comment]
I wonder if this is a signing issue? Do you know after which update this happened? Not really sure about how Windows Update works, as I used Ubuntu for many years then had to switch to Windows.

**Comment by crockerrd** [comment]
I'm getting this error as well. Windows 10.

**Comment by andromedastudios1** [comment]
@averissimo @davibe you guys have any idea why this error is popping up. Even if I use a stable release, such as 1.4.1, this error still happens.

**Comment by dextersarus** [comment]
So not sure which file it was, but found a similar issue with a google music desktop app, deleting the yakyak folder in %appdata%\Roaming solved the issue for me.

**Comment by andromedastudios1** [comment]
will try, thanks.

**Comment by andromedastudios1** [comment]
boom. problem solved.

**Comment by englishmatt** [comment]
While it is true you can delete the %appdata%\Roaming directory (I've been doing this for a number of weeks now), it doesn't exactly resolve the issue. *Why* do I have to keep doing this? I feel like the requisite configuration files is getting corrupted. Requiring the end user to delete a directory to get the tool working again probably isn't a "solution" in the strictest sense. Might want to think about reopening?

**Comment by andromedastudios1** [comment]
Yes I do see what you mean, the problem returned after a reboot. Will
reopen.

--
Best,
Dev Singh

**Comment by andromedastudios1** [comment]
paging @averissimo @davibe
