### ISSUE TITLE
Links won't open properly

### ISSUE THREAD

**Issue by kleiren** [yakyak/yakyak#871]
I am using the app v1.4.3 in ubuntu 16.04.
When i click on a link in any conversartion, a new empty chrome browser tab is opened, but the link is not loaded.
Any workaround or setting i am missing?

Great work by the way :)

**Comment by tonyzorin** [comment]
Same for Mac 1.4.4

**Comment by dmitrychuba** [comment]
Same for macOS 10.13.3  - v 1.4.3
