### ISSUE TITLE
messages are not sent 

### ISSUE THREAD

**Issue by jad00gar** [yakyak/yakyak#873]
New user to yakyak. running the latest version on mac.
when I send messages from the application they show up on the list in light gray color and never show up on my web client or to the recipient. If I send a message from webapp or if someone sends me a message it shows up on the client.

Please advise

**Comment by jad00gar** [comment]
![screen shot 2018-02-06 at 11 21 21 am](https://user-images.githubusercontent.com/36205977/35879291-a84f1ce0-0b2f-11e8-905e-ca2f6c5194f0.jpg)

here is a screenshot of how it looks. light gray message sent from yakyak didn't arrive in my web chat window or to recipient

**Comment by PiFi** [comment]
is it a google voice message? also what version are you using?

**Comment by tonyzorin** [comment]
I have the same. Can't tell how exactly to reproduce, restarting the app helps though.

**Comment by dustinjlandgraf** [comment]
I have been experiencing the same issue. I can't determine what will trigger it. I continue to receive new messages, and my responses will appear in order, but the text will remain slightly dimmer. If I quit and re-launch, my responses will be gone from the conversation.

**Comment by cjcobb23** [comment]
I also have this issue. running v1.5.3 on Ubuntu 18.04.2 LTS

**Comment by JawnZ** [comment]
I'm getting this issue as well: 

v1.5.4 on Windows

Only happens with google voice messages, but it's pretty frustrating :/
