### ISSUE TITLE
Possible fatal error on main process

### ISSUE THREAD

**Issue by gerjomarty** [yakyak/yakyak#875]
Issue encountered on macOS 10.11.6. Signing in with a G Suite Google account. This was the v1.5 release.

Error is encountered at start-up.

```
$ /Applications/YakYak.app/Contents/MacOS/YakYak
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
Error on YakYak window:
 { columnNo: 5,
  error: {},
  lineNo: 81,
  msg: 'Uncaught TypeError: Parameter "url" must be a string, not object',
  url: 'url.js' }
--- End of error message in YakYak window.
```

Please let me know if you need any other information. Thanks for looking.

**Comment by hentercenter** [comment]
Also happening on Windows 10, normal Google Account, 1.4.3

**Comment by tonyzorin** [comment]
Same here but in the middle of working. Restarting the app helps.
![image](https://user-images.githubusercontent.com/20819916/36498341-0e310f52-174f-11e8-8f31-3dd77056ee03.png)

**Comment by draydah** [comment]
Seems to happen after successfully opening a link and then trying to open another link later on.

Uncaught TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:81:11)
    at Object.urlParse [as parse] (url.js:75:5)
    at getImageUrl (/Applications/YakYak.app/Contents/Resources/app/ui/util.js:239:18)
    at href (/Applications/YakYak.app/Contents/Resources/app/ui/views/messages.js:546:18)
    at /Applications/YakYak.app/Contents/Resources/app/ui/views/messages.js:503:16
    at Array.forEach (native)
    at format (/Applications/YakYak.app/Contents/Resources/app/ui/views/messages.js:502:18)
    at /Applications/YakYak.app/Contents/Resources/app/ui/views/messages.js:408:9
    at unnest (/Applications/YakYak.app/Contents/Resources/app/node_modules/tagg/lib/tagg.js:89:29)
    at tagf (/Applications/YakYak.app/Contents/Resources/app/node_modules/tagg/lib/tagg.js:125:9)

**Comment by masterdam79** [comment]
Also on Ubuntu 18.04 (installed as snap package)

**Comment by cobrabr** [comment]
Happens to me as well, all the time, mainly on Win7 x64. It also causes the `X` button/link to be unclickable when it happens.

**Comment by averissimo** [comment]
see #993 

I'm moving discussion there as it has you fix suggestion.

**Comment by curtisgibby** [comment]
Two years later, I'm still seeing this error. And all three issues that I've found related to this problem (#875, #1224, #993) have been closed. Sometimes clearing the `cookies.json` helps, and sometimes it doesn't. Can we get an actual fix put in place?
