### ISSUE TITLE
YakYak Windows triggers PUBG BattleEye

### ISSUE THREAD

**Issue by valdipietro** [yakyak/yakyak#876]
19:18:58: Starting BattlEye Service...

19:19:02: Launching game...
19:20:21: Note: File blocks can be ignored if they don't cause problems with the game.
19:20:21: [INFO] Blocked loading of file: "C:\Program Files\YakYak-win32-x64\YakYak.exe". 

Not sure what I should do. Or why this get's triggered.

**Comment by Ezerbeth** [comment]
Honestly this is a battleye issue. It blocks a bunch of software this way. It blocks synergy (a mouse/kb sharing tool) the same way. You should post on their forums and/or request it be whitelisted.
