### ISSUE TITLE
Message field big amounts of texts pasting

### ISSUE THREAD

**Issue by tonyzorin** [yakyak/yakyak#877]
When I paste some logs to the message field to send to my colleague

![image](https://user-images.githubusercontent.com/20819916/36150976-9df8edb4-10d6-11e8-9df6-25bc01afe535.png)

And if to delete the text it will be like this:

Had to hide some data :)
![image](https://user-images.githubusercontent.com/20819916/36151174-5ccb5c4a-10d7-11e8-8482-40f54c2dd11c.png)

**Comment by PiFi** [comment]
strange. I though this bug was fixed already. are you using 1.5.0? also this is probably a duplicate of #731

**Comment by tonyzorin** [comment]
This on if fixed, my bad, downloaded 1.5.0, but checked on the old package (1.4)
