### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by mikeb3408** [yakyak/yakyak#878]
Hello, 

I came across this app today and am very excited to try it but I am unable to get it install on my 64 bit Windows 10 machine.

I have downloaded your latest release and unzipped the package, I then clicked the .exe file and it typically thinks for a few seconds but ends up doing nothing. 1 time it gave me a type of blue screen and restarted my computer.

Any ideas?

**Comment by PiFi** [comment]
try running it from command prompt. to do this, hold down shift+right click and press the open command prompt here button. then begin typing the name of the executable (ex: yakyak.exe ) and press tab to autocomplete. then see if an error message shows.
