### ISSUE TITLE
Multiple accounts add

### ISSUE THREAD

**Issue by tonyzorin** [yakyak/yakyak#879]
Hangouts for iPhone supports multiple accounts, when someone sends to the second account I have to use my phone to reply. Any plans to support it?

**Comment by PiFi** [comment]
sounds like it would take a lot of work, and the developers are stretched thin. you are better off trying to sandbox different instances.

**Comment by renatocn** [comment]
Congrats for the work so far, nice app.

It could be great to have multiple accounts.

The last thing to be able to quit Adium.

**Comment by kwade00** [comment]
There is an enhancement request: #13

**Comment by davibe** [comment]
duplicate of #13
