### ISSUE TITLE
No login on version 1.1.1

### ISSUE THREAD

**Issue by caneta** [yakyak/yakyak#88]
Hi!
I have downloaded the latest stable version 1.1.1 and when I run yakyak from a terminal I get the following:
![yakyak-1 1 1-login-issue](https://cloud.githubusercontent.com/assets/4066659/11334049/b3733d3c-91d2-11e5-815d-fb6b7f3e1182.png)

Yakyak opens correctly, but I cannot insert my credentials because no login form is shown...yakyak window simply starts with a connection attempt which times out:
```
user@host:/home/candini/Scrivania/yakyak$ ./yakyak 
hconnect
2015-11-23 10:59:47 INFO fetchPvt failed ETIMEDOUT
connect_failed
```
Any ideas?

**Comment by davibe** [comment]
is your connection working ?

**Comment by caneta** [comment]
Yes, it does and I'm using hangouts through my web browser using Gmail interface right now...

**Comment by davibe** [comment]
Which OS are you running it on ?

**Comment by caneta** [comment]
```
user@host:~$ uname -a
Linux host 3.16.0-53-generic #72~14.04.1-Ubuntu SMP Fri Nov 6 18:17:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by davibe** [comment]
linux 64 Hm. Can you open the inspector with ctrl+alt+i and check for errors in the webconsole?

**Comment by caneta** [comment]
Sure:
![yakyak-1 1 1-login-issue_2](https://cloud.githubusercontent.com/assets/4066659/11334604/6a870276-91d6-11e5-8c60-aafbdb77b1bc.png)
No errors, apparently...

**Comment by davibe** [comment]
I don't have a linux machine here. I will try to find one to investigate this. Could be related to the new electron.

**Comment by caneta** [comment]
Ok, so I'll waiting for some update...thanks for your quick response!

**Comment by davibe** [comment]
i tried on the laptop of a friend and its working. Damn.

**Comment by caneta** [comment]
Ok.
What I don't understand is why yakyak starts a connection without having any credential.
This is not the first time I'm trying to use yakyak: is it possible for me to have an hidden file with my Google credentials somewere, a `.yakyak.conf.something`, maybe broken, used to attempt login? Or is there a way to force yakyak to ask login data at startup?

**Comment by davibe** [comment]
Yes. I don't know the exact path in case of Linux but you can have a look in ~/.config there should be something holding your credentials.

The application connects to google right away because the login screen is fetched from google.

**Comment by caneta** [comment]
I cleaned with `rm -fr /home/candini/.config/yakyak && rm -fr /home/candini/.cache/yakyak` but did not work because in the end it was a proxy setting problem on my machine.
I switched from Ubuntu to Xubuntu few days ago and the new interface did not preserved the proxy configuration. Setting it inside `/etc/environment` did the trick.
Thank you for the support!

**Comment by davibe** [comment]
Ahah ok it was just your proxy setting. Good to know !!
