### ISSUE TITLE
Client Unexpectedly quits

### ISSUE THREAD

**Issue by wildn0rth** [yakyak/yakyak#880]
Both on my machine and my wife's Mac's (both 13 inch Macbook Pros running 10.12.6) the Yak Yak 1.5.0 client unexpectedly quits several times a day. Doesn't seem to be any particular thing we are doing to replicate the bug. 

Also, just installed on my iMac running Sierra.....same thing.

**Comment by PiFi** [comment]
try to have the inspector console open when it crashes and see if you notice anything strange.
