### ISSUE TITLE
Can't reply to new conversations

### ISSUE THREAD

**Issue by Norzman** [yakyak/yakyak#886]
When someone opens a new conversation with me or adds me to a group conversation I am unable to reply to that conversation until I restart yakyak. an error message pops up every time this happens.

**Comment by tonyzorin** [comment]
Have the same on 1.5 for macOS

**Comment by dikodahan** [comment]
I have the same as well. 1.5 with MacOS

**Comment by Norzman** [comment]
Forgot  to mention this but this happens to me on Windows 10 and Linux Mint. I went back to 1.4.4 and don't have this issue at all.

**Comment by Norzman** [comment]
Installed 1.5.1 today.
Not sure if the problem has been resolved yet or not
