### ISSUE TITLE
Error in Win10

### ISSUE THREAD

**Issue by foornath** [yakyak/yakyak#894]
Everytime I've recently tried to launch the program, I've gotten this message. Re-downloaded the zip and still having the same issue. 

![image](https://user-images.githubusercontent.com/20993789/37611328-4d75a028-2b5f-11e8-9f10-7da7a0a8342f.png)

**Comment by AdamBryantSkybox** [comment]
Same issue, except been having it for months.

**Comment by oblivion2k** [comment]
Same, been happening for about a week now.

**Comment by kso-ch** [comment]
Same here :(

**Comment by kso-ch** [comment]
Close all open instances, and delete "AppData\Roaming\yakyak".
This will allow the app to launch, but will not fix the issue, it will reoccur after rebooting
