### ISSUE TITLE
Many instances of toast.exe

### ISSUE THREAD

**Issue by D661** [yakyak/yakyak#896]
I sometimes end up with many instances of toast.exe running. Currently I have 40. Some of them are over a week old. By looking at the command line for each process, I can see the message that each instance was for, and each one is for a different message. They just never exit until I exit YakYak.

This should probably get logged as a separate issue, but if I get a bunch of messages when I'm away from the computer, when I return and unlock the screen, I get a popup for each message (one at a time, not all at once). Even opening YakYak to the conversation generating the popups doesn't make them go away, I have to sit and wait for each one to time out, or else click on each one. I mention this here because I've been wondering if these are the popups that are responsible for the stuck toast.exe instances. I'll try to keep an eye on this and see.

YakYak v1.4.3 
Windows 10

![image](https://user-images.githubusercontent.com/37595336/37677284-d714324e-2c37-11e8-958e-cc3085e4d58f.png)

**Comment by D661** [comment]
Still happening with 1.5.0 (except now it's SnoreToast.exe instead of toast.exe).

**Comment by averissimo** [comment]
duplicate of #887 , let's talk there
