### ISSUE TITLE
Windows 10 Stuck at "Connecting"

### ISSUE THREAD

**Issue by matthewlswanson** [yakyak/yakyak#897]
Every morning when I come into work the client shows "Connecting" and I have to quit the program and restart. Running Windows 10 LTSB and version 1.5.0 of YakYak. It works all day until the next morning.

**Comment by abarragan** [comment]
Same here. Exactly the same output when running on CL. Debian 9.

**Comment by CaroleReynolds** [comment]
I have not had any connecting issues until today - Win 10 64bit - I started with YakYak 1.4.3 and then tried 1.5.0 with the same "connecting" result. Tried running windows updates and restarting - still "connecting". I removed my yakyak app data folder and reconnected to google - still stuck on "connecting". Help!?

**Comment by dostillevi** [comment]
Confirmed Basby's fix resolves this issue.

**Comment by rexman316** [comment]
Signed up just to say thanks Basby, that worked a treat.

**Comment by jalean11** [comment]
Also signed up to say @Basby 's fix worked for me also.  Thanks!

**Comment by CaroleReynolds** [comment]
@Basby YOU kind sir are AWESOME - Thank you! Works like a charm.

**Comment by stelladev** [comment]
@Basby 's solution worked for me as well! Thank you!

**Comment by boulderbri** [comment]
@Basby - thanks - worked for me too

**Comment by SirePi** [comment]
@Basby thanks a lot!

**Comment by fulii** [comment]
i can confirm that this resolves the issue on OSX high sierra and yakyak 1.5.0
path is: /Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js

**Comment by davibe** [comment]
1.5.0 has this solution applied, thx

**Comment by dostillevi** [comment]
Just noting I needed to apply this fix to 1.5.0
