### ISSUE TITLE
white bar

### ISSUE THREAD

**Issue by ThienJP** [yakyak/yakyak#901]
![screen shot 2018-03-26 at 5 13 53 pm](https://user-images.githubusercontent.com/2656801/37915140-17666f70-3119-11e8-87c2-6e1d608e807a.jpg)

as in the screenshot provided a white bar appears between chat window and conversation list. you can see it on every color scheme and it's overly thick

**Comment by jeffrypig23** [comment]
I too have this issue. Ruins the dark theme on macOS 😒

**Comment by jeffrypig23** [comment]
Bot please

**Comment by davibe** [comment]
PRs welcome :)
