### ISSUE TITLE
YakYak v1.5.0 in Win 10 window buttons are missing on About screen

### ISSUE THREAD

**Issue by aplocher** [yakyak/yakyak#902]
While the About screen is shown, the window control buttons in the top-right are missing (Maximize/Restore, Minimize, and Close).  The top-left menu still allows the user to quit and Alt-F4 still works.

![image](https://user-images.githubusercontent.com/1132447/38135190-a82b47ec-33cb-11e8-830a-311670bf5b47.png)

**Comment by davibe** [comment]
is this present in 1.5.0 release ? can anyone else confirm it ?
