### ISSUE TITLE
App window shows up almost entirely off-screen on startup

### ISSUE THREAD

**Issue by loisaidasam** [yakyak/yakyak#905]
Happens on every app launch

YakYak v1.4.3
OSX 10.13.3

**Comment by loisaidasam** [comment]
bummer 😿

**Comment by averissimo** [comment]
@loisaidasam try updating to a more recent version of yakyak v1.5.1

**Comment by loisaidasam** [comment]
Aha, I wasn't keeping up with releases.

So far so good, thanks @averissimo !!!

**Comment by averissimo** [comment]
you're welcome :)
