### ISSUE TITLE
Missing messages

### ISSUE THREAD

**Issue by Chrismarsh** [yakyak/yakyak#908]
I have noticed that messages will be missing from the YakYak client (seen on OSX, and Linux). The messages correctly appear on hangouts.google.com and in the gmail chat overlay. Closing and reopening yakyak shows the missing messages.

![missing-message](https://user-images.githubusercontent.com/630436/38688421-453b8a64-3e36-11e8-8b32-97b59d6e23c4.jpg)

**Comment by Chrismarsh** [comment]
This is still happening on macOS with 1.5.1

**Comment by davibe** [comment]
did you find a way to reproduce this issue ?

**Comment by Chrismarsh** [comment]
Unfortunately no. It just seems to randomly happen after a while.
