### ISSUE TITLE
Suggestion for X button - Hide instead of close

### ISSUE THREAD

**Issue by lucamosca1** [yakyak/yakyak#911]
Env - Ubuntu 16.04
Just like other chat applications (skype for example), the X button could just hide the application instead of closing it. The user can close the application from the try

Just a suggestion of usability, feel free to close it if not interested.

Cheers
Luca

**Comment by jakubsuchybio** [comment]
Dunno if on Linux version too. But on windows version, when you go to settings you can turn on this behaviour of hiding instread of turning off.
