### ISSUE TITLE
"About YakYak" pops up whenever I click on any link/image/profile icon.

### ISSUE THREAD

**Issue by JaredDiCioccio** [yakyak/yakyak#915]
As demonstrated here....

![Attached image](https://user-images.githubusercontent.com/633075/39764560-e1bacf4a-52ad-11e8-9c68-56213bf3abc4.png)

Whenever I click on an image in a chat, or someone's profile icon, or any hyperlink in a chat message, the link opens as normal but that "About YakYak" popup appears every single time. 

On YakYak v1.5.0, Windows 10 64bit version 1703 build 15063.0

**Comment by Behodar** [comment]
Same here with 1.5.1 on Mac.

**Comment by davibe** [comment]
:D this bug is nice!

**Comment by HomerSp** [comment]
Fixed in https://github.com/yakyak/yakyak/commit/2e167d693812659092ba9da88693eb76af84edb2
