### ISSUE TITLE
Mac OS 10.13.4 YakYak 1.5.0 stopped connecting

### ISSUE THREAD

**Issue by akholodenko** [yakyak/yakyak#921]
Messages were slow to send. Uninstalled / re-installed latest available v1.5.0 DMG. Now will not connect at all.

![image](https://user-images.githubusercontent.com/2487237/40196260-d7cca80a-59c4-11e8-9f14-79384afd76fa.png)

**Comment by eblanchette** [comment]
Same here

**Comment by akholodenko** [comment]
dupe of https://github.com/yakyak/yakyak/issues/919

**Comment by akholodenko** [comment]
as mentioned in the other issue:

macOS High Sierrra 10.13.4

/Applications/YakYak.app/Contents/Resources/app/node_modules/hangupsjs/lib/init.js

html = html.replace(/</?script>/gm, '');
to
html = html.replace(/</?script.*?>/gm, '');

**Comment by elliotchance** [comment]
Actually that is a syntax error (from the extra `/`). This worked for me:

```
html = html.replace(/<\/?script.*?>/gm, '');
```
