### ISSUE TITLE
stuck in connecting

### ISSUE THREAD

**Issue by madtorq** [yakyak/yakyak#923]
I have yakyak running on my osx laptop flawlessly, and running on windows 10 for a couple months, flawlessly, same gmail account. suddenly this morning it said "connecting/not connected" on my windows machine... would not connect. I tried logging out, tried uninstalling and deleting userdata folder... I can sign in, it sends the 2 factor code to my phone, I input it into the app and then it just sits at the white CONNECTING screen now forever and will not move past that. 

Still working fine on my osx laptop. Any ideas? This started randomly this morning, there have been no windows updates in the last couple days.

**Comment by scottchristian** [comment]
Yep, happens for me as well

**Comment by patrickchalkley** [comment]
Also experiencing on macOS 10.13.4. Started happening yesterday on 18/05/18. I'm signing in to a GSuite account, with SSO managed by Okta.

Troubleshooting attempted:
- Deleting the YakYak.app bundle and replacing with a fresh copy of 1.4.3 - no change, still stuck at Connecting
- Deleting the ~/Library/Application Support/yakyak folder - Prompted to log back in, but still gets stuck at Connecting...

**Comment by leoliger** [comment]
I am getting the same issue on Windows 10 Enterprise Build 16299. Tried deleted the yakyak folder within /AppData still no luck. Removed and reinstalled with fresh copy and deleted the \AppData\Roaming\yakyak folder nothing. I know I have used this yesterday just fine.

**Comment by zcmack** [comment]
[did you try the fix suggested here?](https://github.com/yakyak/yakyak/issues/919)

**Comment by leoliger** [comment]
@zcmack Yeah, tried the html fix, received json java error, scrapped the current install and re-installed the downloaded zip copy, and deleted the AppData folder. Still had connecting error at with the change. Tried the other method where to download the nee pre-build 1.5.0 and change the html file there as well. Made sure that no previous yakyak process was running and deleted the AppData folder. Still trying to connecting hang.

**Comment by frazor** [comment]
for later readers, the fix in #918 worked for 1.4.4 as well. The #919 prbably works as well.
I'm on MacOS, but OS shouldn't matter once you locate your init.js file.

**Comment by madtorq** [comment]
yep, confirmed the fix in 918 worked for me as well. thanks guys.
