### ISSUE TITLE
connect_failed SyntaxError: Unexpected token <     at Object.bind.out

### ISSUE THREAD

**Issue by mgurreta** [yakyak/yakyak#927]
The App hangs on startup, I'm seeing the following error on the terminal. (YakYak v1.5.0 for OS X)
hangupsjs issue:
https://github.com/yakyak/hangupsjs/issues/92

**Comment by PinkFreud** [comment]
I'm seeing the same here with yakyak 1.5.0 on linux x86-64.

**Comment by PinkFreud** [comment]
Upon further digging, https://github.com/yakyak/yakyak/issues/918 has a fix already.

**Comment by clintfred** [comment]
For those just looking for a fix, see: https://github.com/yakyak/yakyak/issues/918#issuecomment-389772323
