### ISSUE TITLE
Directions to bad icon info?

### ISSUE THREAD

**Issue by DanaMW** [yakyak/yakyak#928]
Sorry for just putting it out here i searched for a good while for an issue i saw back a while ago. Could someone direct me to a fix for bad tray icon on Linux  64 bit Fedora here. Looks lovely as this. :) Thanks
![yakyak](https://user-images.githubusercontent.com/12940577/40275512-d030943e-5ba5-11e8-86d7-98af82617d10.jpg)

**Comment by FFDA** [comment]
I have the same issue. It looks like it uses not appropriate size icon for the task bar.
I'm running Fedora 28 KDE. And if I expand (stretch?) taskbar upwards a bit the icon is shown as it should be.

**Comment by FFDA** [comment]
As I mention in previous post that edit in /opt/yakyak/resources/app/ui/views/trayicon.js made did not make icon look completely normal and it was bugging me all the time. Today I had some time to google around and found solution that make icon to look as it should.

One needs to edit `~/.local/share/applications/com.github.yakyak.YakYak.desktop` file and add `XDG_CURRENT_DESKTOP=Unity` to the beginning of Exec line. Whole line looks like this in Fedora 28 KDE + newest flatpak of yakyak:

`XDG_CURRENT_DESKTOP=Unity /usr/bin/flatpak run --branch=master --arch=x86_64 --command=yakyak --file-forwarding com.github.yakyak.YakYak @@u %U @@`

BTW, as far as I understand it is electron issue and not yakyak's or KDE. At least that's the concencus.

**Comment by DanaMW** [comment]
The first listed fix was good enough for me. Thank you for putting it in here.
