### ISSUE TITLE
Does not work with 2-factor security enabled.

### ISSUE THREAD

**Issue by ddmytrenko** [yakyak/yakyak#93]
Holds on a blank screen after entering the username.

**Comment by faizanahemad** [comment]
Worked in my case. Though I had to restart the app after auth.

**Comment by zpalffy** [comment]
I just installed today and 2-factor worked with no issues... no restart required in my case.

**Comment by SangSatori** [comment]
Fails with black screen here too - I'm running Linux x64 release on Arch Linux.
![screenshot from 2015-12-20 10-42-49](https://cloud.githubusercontent.com/assets/5672728/11917221/dee79e74-a706-11e5-8550-72fe2956f035.png)

What OS are you running, @ddmytrenko?

**Comment by ddmytrenko** [comment]
@SangSatori I'm running OSX.

**Comment by SangSatori** [comment]
Error message happen here whether I try to interact with the app/exit from the state. Otherwise it's either white or black blank screen too.

**Comment by Derimagia** [comment]
On my Windows 10 machine, 2 Factor Authentication works without any issues.

**Comment by SangSatori** [comment]
It works for me now both on Windows 10 and Arch Linux too. I'm not sure what has changed.

**Comment by mhogerheijde** [comment]
2-factor auth works for me on Ubuntu 15.10, x64, using binary build 1.1.1.

**Comment by Derimagia** [comment]
Confirming this also works on my Macbook. I think this can be closed.

**Comment by davibe** [comment]
ok, ty

**Comment by sdustinh** [comment]
I have this same problem with Ubuntu 14.04 x64 using build 1.1.2. I get the code from Google but the 2FA screen remains blank. Restarting the app will repeat the process with the same result. I don't think it's related but for what it's worth this is what is in the `err.txt` file:

```
2015-06-01 9:32:04 ERROR subscribe failed { [Error: Unknown SID]
  code: 400,
  message: 'Unknown SID',
  body: '<HTML>\n<HEAD>\n<TITLE>Unknown SID</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Unknown SID</H1>\n<H2>Error 400</H2>\n</BODY>\n</HTML>\n' }
```

**Comment by toupeira** [comment]
Same here with 1.1.3 on Debian sid x64, I can enter username and password and then I get a blank screen which is sometimes white and sometimes black. Sometimes there are also glitches in the menu bar:

![workspace 1_001](https://cloud.githubusercontent.com/assets/6501/12983815/4a783b54-d0eb-11e5-9319-3d77d6ba4232.png)

I'm using Xorg 1.18.1 with integrated Intel Haswell graphics.

**Comment by juandelgadoinc** [comment]
same issue for me, ubuntu gnome 16.04, yakyak 1.2.0, but i still got it to work by doing this: username -> password -> in the blank screen i typed the code from authy/sms and then i hit the <enter> key (the field is focused automatically) -> another blank screen where i hit <tab> and then the <enter> key, and then it signed in succesfully and everything worked fine

**Comment by jonlandrum** [comment]
I had this issue, too, but can confirm that @juandelgadoinc's solution works
