### ISSUE TITLE
Duplicating instances upon exec/init starting via default launcher

### ISSUE THREAD

**Issue by ninetyfivenorth** [yakyak/yakyak#931]
So, as of say... maybe a week give or take, I have been having this awful bug pop up and rear its teeth and antennae (lol) whenever I have been attempting to use (and only use) YakYak. This issue seems to display multiple windows of the same wrapper and/or multiple instances of the same executed script/app. Here is a screen-shot of the duplicating exec/init start upon using default launcher. (...like none of us could use our imaginations to have been able to accurately depict this within our own minds haha... oh well--being thorough I suppose);

![screenshot_2018-05-23_14-27-02](https://user-images.githubusercontent.com/31463232/40444380-41bd0cb0-5e97-11e8-948a-8e0268bfaca7.png)

Also, here's a look at my terminal upon attempting to use a previously configured compiled .deb rather than attempting to rebuild and troubleshoot that way myself and rely on you folk's faith within the repository official release(s) of an .deb of YakYak;

```
yakyak/now 1.5.0 amd64 [installed,local]
  "Chat client for Google Hangouts"
```

```
sudo dpkg --install yakyak-1.5.0-linux-amd64.deb
[sudo] password for artik: 
Selecting previously unselected package yakyak.
(Reading database ... 392867 files and directories currently installed.)
Preparing to unpack yakyak-1.5.0-linux-amd64.deb ...
Unpacking yakyak (1.5.0) ...
Setting up yakyak (1.5.0) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...

```

...all looks well & good from there to me... very smooth, simple, configuration of the provided Debian releases. (Of course, one would assume... does he have the correct or accurate environment & dependables necessary to correctly run YakYak--and the answer to this is indeed, yes. I have been using YakYak successfully for a very large amount of this project's lifespan). 

Thanks in advance for any answers, tips, inquiries, or suggestions.

P.S. Yes, I have done a bit of my own troubleshooting--attempting to reinstall and debug as well as upgrade any and all necessary nodejs environment requirements plus any of the pre-reqs required.

So I am stuck... and this is also an isolated bug--as this is NOT happening with any other application running this current system in use;

Operating System =
` [$ uname -a:] Linux fr3shBook 4.9.4-galliumos-braswell #1 SMP PREEMPT galliumos2 Thu Feb 23 01:58:04 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux 
`

= A Modified Peppermint 8 release Ubuntu flavored distro used currently upon an Acer Chromebook that was requiring of the "Braswell" specific "GalliumOS distro" drivers therefore kernel and linux images + firmware releases (shout out to GalliumOS team! Ya'll have been doing and have done some fantastic and efficient cooperative work on these Chromebook based projects!)

Again, thanks!

**Comment by ninetyfivenorth** [comment]
I was able to `sudo rm /home/{user}/.config/yakyak/*` and all of the contents left behind from previous dpkg -i 's I had ran attempting to re-install YakYak. So ya, just a btw bug, that shit stays in that config dir even when `sudo apt-get purge yakyak` has been ran

**You're welcome to close this issue if you would like. Thanks**

**Comment by ninetyfivenorth** [comment]
_Still_ will **not** connect to the google api services therefore YakYak is currently as written--NON-functional

**Comment by Viper007Bond** [comment]
For the connection issue, see #918.

**Comment by ninetyfivenorth** [comment]
**### {thread has been now closed.}**

Yeah I have moved on with the rest of the world'd consensus and began sticking to web apps as an overall template for my usage of these types of google services or other similar yet unaffiliated kinds of services usually available via a cellular phone application and/or web browser based connectivity. 

> **ONE WORLD-ONE ORDER**

Oops, looks to as though one might feel as if right now, it is all starting to become a bit more _concrete_ than simply a late night of one of our own's cranked on addies blowin' on headies & watching your life fall apart while you follow the spiral of hell down a rabbit hole upon YouTube and the;
```
plethora (plĕthˈər-ə)►
n.	A superabundance; an excess.
n.	An excess of blood in the circulatory system or in one organ or area.
```

of garbage mind-numbingly SHIT based content (hey, some of which--I mean--I do THOROUGHLY enjoy and am entertained by--don't get me wrong now) that for some odd reason--seems to be absolutely (stick with me, here) contrary to their "as always" or one may argue more recent/semi-recent theme to an agenda or message or directive of their own goal orientation... not to mention they had that creepy "unintentionally leaked" (they being Google) video  of the **SELFISH LEDGER** and as to what all of us could or would be lead to believe is as is that all this bullshit conspiring to accomplish God knows what, by God knows who, but certainly NOT following the agenda of say Sir. Alex Jones (who I do enjoy lol) and the lizard folks and the likes of the others... by plastering yet again might I again  emphasize the extend of the bullshit being shoveled down everyone's throats by YouTube's;
```
plethora (plĕthˈər-ə)►
n.	A superabundance; an excess.
n.	An excess of blood in the circulatory system or in one organ or area.
```

of _bullshit_ they knowingly and actively harbor, chamber, echo, etc. to whom being their viewership (a.k.a. the entire fuckin world) that seeming has zero end-time in sight--very much as so, similar to as if it (Google+YouTube+AlexJonesLizardsTrannys) were all just as this relentless, pointless, wasteful post has served purpose for, that in which this of course grammatically intentionally self-appointingly annoying to the (very slim to none) amount of readers of my post here. Ta ta and peep that shit. 

(Please do see; https://www.youtube.com/watch?v=iqUCX5rPQug or Google into it in order to find a direct source for the video itself [the website of choice being I believe named like "Verge" or some shit was and is legit and beyond my own watching of the "leak" video via their site myself, I have seen them sources on many other articles on the web... BEE TEA DOUBLE YOU xoxo peace out])  

**"Stay Gold Pony Boy, Stay Gold"**
//@ninetyfivenorth
**ig:** @shanefr0mmaine
