### ISSUE TITLE
Cannot clear unread message count

### ISSUE THREAD

**Issue by eacmen** [yakyak/yakyak#935]
No matter what I do, YakYak always reports an unread message count of 9 in the icon. I checked the actual hangouts app and it does not report any unread messages. I tried removing `~/Library/Application Support/yakyak` and it had no effect. What else can I do to clear this unread message count?

**Comment by davibe** [comment]
on osx they go away as soon as the conversation with the unread messages gets the FOCUS. If it does not happen for you i guess there must be some problem with handling of the focus event. Are you using linux or windows ? which version ? Are you using yakyak 1.5.0 ?
Thank you

**Comment by eacmen** [comment]
I am an idiot. Found the conversation causing the unread count. Apologies for wasting your time.
