### ISSUE TITLE
Error installing yakyak 1.5.1 through Ubuntu Software Center

### ISSUE THREAD

**Issue by jumpy88** [yakyak/yakyak#937]
I report in the following the details of the error reported during the installation:
Lintian check results for [...]/yakyak-1.5.1-linux-amd64.deb:
E: yakyak: maintainer-address-missing "Martin Algesten"

**Comment by tkisme** [comment]
![image](https://user-images.githubusercontent.com/5886048/40952679-cd1582d0-68ae-11e8-8f19-5507ec4342db.png)

**Comment by jumpy88** [comment]
I think the one reported by @tkisme is a different error with respect to the one I originally created this thread for. I just get that error when I install the .deb package (which is actually a warning as I can ignore it and go on with the installation), but once installed the software works just fine.

**Comment by jumpy88** [comment]
Am I the only one who got this error?

**Comment by averissimo** [comment]
did not have any problems installing via software center or via command line `sudo dpkg -i yakyak-1.5.2-linux-amd64.deb`

**Comment by coverme76** [comment]
Just to say that YakYak installs fine on Linux Solus OS. Haven't had much use for it - but it installs fine.
