### ISSUE TITLE
YakYak does not match contact to number properly for Google Voice thru Hangouts

### ISSUE THREAD

**Issue by devksingh4** [yakyak/yakyak#939]
When messages in hangouts are from a cell number (Google Voice), YakYak fails to recognize the number (xxx)-xxx-xxxx as a number and does not match the number to its contact. However, it does recognize xxxxxxxxxx as a number and correctly matches to the proper contact. I am running YakYak 1.5.1 64-bit on Windows 10 build 1803 (April 2018 Update)

**Comment by andromedastudios1** [comment]
Does anyone know in which section of the code this is handled? I will look and see what fixes I may have but I cannot see where this "parsing" is handled.

**Comment by shivknight** [comment]
This defect is preventing my general adoption of YakYak over the Chrome Hangouts app

**Comment by slvtrs** [comment]
I'm very curious about this myself. The discussion in  #232 made some progress towards integrating a contacts api, but seems to have gone dry.
