### ISSUE TITLE
YakYak not connecting on MacOS 10.13.5

### ISSUE THREAD

**Issue by ChubbyTio** [yakyak/yakyak#940]
I've looked around other issues and couldn't find a solution. I'm running MacOS 10.13.5, and I just installed YakYak for the first time. When I launch the app is stuck on "Connecting"

I've tried fixing line 59 in the init.js file to no avail.

What else can I try?

**Comment by davibe** [comment]
have you downloaded 1.5.1 ?

**Comment by ChubbyTio** [comment]
Yes. I'm running 1.5.1.

**Comment by davibe** [comment]
I updated, it works for me. Are you able to check logs ? Maybe open it from a terminal ( launching like ~/Downloads/YakYak-darwin-x64/YakYak.app/Contents/MacOS/YakYak )?

**Comment by ChubbyTio** [comment]
I'm going to try on my home MacBook Pro. I think it might be the network at work.

**Comment by ChubbyTio** [comment]
Looks like it's the network at work. It worked just fine at home.
