### ISSUE TITLE
Chat title sometimes overlaps title bar buttons

### ISSUE THREAD

**Issue by Stoppablemurph** [yakyak/yakyak#942]
Whenever a chat room has a somewhat long name and the yakyak window isn't wide enough to accommodate the whole name and the title bar buttons, the buttons will overlap into the chat name.

Example:
![yakyakbug](https://user-images.githubusercontent.com/5564311/41205349-8f929ba4-6ca6-11e8-80c5-dbcd29a15da6.PNG)

Example when window is widened:
![yakyakbug2](https://user-images.githubusercontent.com/5564311/41205353-aaf77ce8-6ca6-11e8-94e1-ec065c82f5c3.PNG)

I'm not sure if it would be better to move the chat title over in this case or to truncate it with a "..." on the end or something.

I'm not immediately sure if this is also an issue on Mac OS or Linux, but it's consistently the case with Windows 10 for me.

**Comment by MikeVensel** [comment]
This issue also occurs if you shrink the window to a width that cannot fit the name of the person or group.
