### ISSUE TITLE
JavaScript Error while starting yakyak

### ISSUE THREAD

**Issue by mfagundez** [yakyak/yakyak#944]
Hi all,

I'm facing a problem while starting yakyak v1.5.1 in my win10 laptop. After fixing the problem described in issues #927 and #918 with the workaround successfully, my client didn't work anymore. I've tried deleting and re-downloading the zip package several times but the app doesn't start: It shows an alert window with the message: "A JavaScript error occurred in the main process. Uncaught Exception: SyntaxError: Unexpected token" but I don't know how to get a trace log more verbose. 

I have tried yakyak in other win10 laptop and it works well and also with my Ubuntu computer, so I think that I have some trash from an older yakyak installation. Could you please help me in order to start using yakyak again? How can I get more details of the error? :)

Thanks in advance

BR,

Mario

**Comment by dcalisyn** [comment]
I'm running into the same problem and have followed the quick-fix in #918 as well.

**Comment by mfagundez** [comment]
Thanks for your answer dcalisyn. I've tried that fix but I understand that YakYak v1.5.1 already includes a similar fix. In both cases I receive same error (trying both x86 and x64 versions).

BR,

Mario.

**Comment by RSchwoerer** [comment]
I was able to fix this, after updating to v1.5.1 by deleting the directory `C:\Users\<user name>\AppData\Roaming\Yakyak`.

**Comment by durd** [comment]
@RSchwoerer 
That worked great, thanks! :)

**Comment by LamboJ** [comment]
@RSchwoerer Worked for me as well. Thanks!

**Comment by mfagundez** [comment]
@RSchwoerer It works!

Thank you for your help!
