### ISSUE TITLE
Any plan to support Hangout Chat ?

### ISSUE THREAD

**Issue by squalou** [yakyak/yakyak#945]
Recently (march 2018) google *again* changed its products lineup. They are now proposing 'hangout chat'.
which is somewhat compatible with Hangout, but offers many more features (essentially to fight slack, if you want my advice)

details for instance here https://www.techrepublic.com/article/google-hangouts-chat-the-smart-persons-guide/

For now Hangout Chat is missing a linux client,

that's why I'm asking : would yakyak be such a candidate for this or not at all ?

Note that I'm not asking for the feature, I'm just looking for such a client, and wondered what were the plans regarding yakyak. 

thank you !

**Comment by davibe** [comment]
no plans, sorry

**Comment by DarkMagic** [comment]
Google Hangouts will be terminated soon (Oct 2019) https://gsuiteupdates.googleblog.com/2019/01/upcoming-hangouts-service-consolidation.html

Any plan to migrate to Hangouts Chat now?
