### ISSUE TITLE
Message count not clearing on Focus

### ISSUE THREAD

**Issue by thapacman** [yakyak/yakyak#946]
I'm currently seeing the message count after switching focus to the conversation after a reinstallation of my OS. The message count clears after sending a message - though I'd prefer not to have to send a message and continually have a visual notification of a recent message I received hours ago.

The only quirk I can think of that may cause this is that I copied yakyak from the previous OS volume.
This is currently occurring on Windows 10 1803 (Build 17134.1).

I've attempted setting the application to run as administrator on start which hasn't made a difference at this stage and also ensured that no files/directories are set to read-only as can happen after copying from other system volumes.

**Comment by linuxsucks** [comment]
I am having the same issue on windows and mac.
