### ISSUE TITLE
Request to integrate the new Google Hangouts Chat

### ISSUE THREAD

**Issue by rigved** [yakyak/yakyak#949]
Hello,

Google has launched a new messaging service called Google Hangouts Chat. They have provided an official API in order to integrate it with any app:

https://developers.google.com/hangouts/chat/

The one good thing over the "old" Hangouts is that the new Hangouts Chat supports threaded conversations.

Please integrate it with YakYak.

**Comment by wilq87** [comment]
:+1:

**Comment by x-tk** [comment]
3rd

**Comment by alphachai** [comment]
This would be great. My teammates are all switching to the chat.google.com web app and can't see my messages when I use yakyak anymore.

**Comment by stealthybox** [comment]
Looks like this is a paid product.

```
You need a G Suite account to access Hangouts Chat
```
https://chat.google.com

**Comment by m-czernek** [comment]
Could someone form the maintainers confirm whether such integration would be accepted to the official codebase if provided?

**Comment by averissimo** [comment]
We welcome all pull-requests!!

I just want to suggest to keep the separation between frontend and backend. Either integrate it with current hangupsjs library or as an external one.

If you or someone else wants to pick this up, I'll try to be more active monitoring it to answer any questions.

**Comment by tseaver** [comment]
Given that classic Hangouts will be shut down this fall (https://gsuiteupdates.googleblog.com/2019/01/upcoming-hangouts-service-consolidation.html), I don't see this as a "pull requests welcome" kind of issue:  yakyak won't be usable if it doesn't accomodate the new protocol.
