### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by capcla** [yakyak/yakyak#952]
Hi,
when I open yakyak on a windows 7 64 bit, appears an error window
```

A JavaScrtipt error occured in the main process

Uncaught Exception:
SyntaxError: Unexpected token
```

**Comment by nubecoder** [comment]
Same thing on Win10 Pro.
Started today, I believe.

Win 10 info:
![image](https://user-images.githubusercontent.com/706000/44304943-5f6c1580-a320-11e8-98a1-629906586b85.png)

Actual Error window / message:
![image](https://user-images.githubusercontent.com/706000/44304951-a65a0b00-a320-11e8-8cdb-5874b00ac973.png)

**Comment by nubecoder** [comment]
Confirmed, fixed my issue as well.
Thanks for sharing!
