### ISSUE TITLE
Custom Themes?

### ISSUE THREAD

**Issue by SovereignGFC** [yakyak/yakyak#953]
I found [this](https://gist.github.com/adamzaninovich/69ab96f4f64bdfb446f505ede6a74ad5) offering a _replacement_ of the built-in material theme.  However, I'm unsure how one is supposed to create _new_ themes.

I tried just adding another section in app.css but there was no change in the list found at YakYak -> View -> Color Scheme.

**Comment by CrajyB** [comment]
I would also be more than happy to create some more themes but not sure where to add them.

If anyone can provide more information that would be great!

**Comment by Rone777** [comment]
> I would also be more than happy to create some more themes but not sure where to add them.
> 
> If anyone can provide more information that would be great!

go to Contents/Resources/app/ui/app.css scroll down and you will find osmething liek this

and you will find something like this.

```
html.material {
  --white: #202B31;
  --ghostwhite: #2d3d46;
  --lightgrey: #28353B;
  --altgrey: #2B3E41;
  --grey: #303F47;
  --darkgrey: #617E8A;
  --lightblack: #455a64;
  --black: #99B1B7;
  --green: #900F3C;
  --darkgreen: #790d32;
  --red: #900F3C;
  --darkred: #790d32;
  --link: #14a3be;
}
```
those numbers are hex color codes. Pick a theme color you never gonna use (here its material i.e. html.material )  and start changing those hex numbers to the colors you want. Restart yakyak and see the difference.

**Comment by averissimo** [comment]
That's right @Rone777 you can change one of this tags and use it on your machine.

They can also be any allowed color in css (such as `rgb( , , )` )

If you guys want to contribute the new theme to the community, the files to change are:

* the actual colors [src/ui/css/yakyak/colors.less](https://github.com/yakyak/yakyak/blob/master/src/ui/css/yakyak/colors.less)
* a new menu item [src/ui/views/menu.coffee](https://github.com/yakyak/yakyak/blob/master/src/ui/views/menu.coffee)
* and the english translation template [src/locales/en.json.template](https://github.com/yakyak/yakyak/blob/master/src/locales/en.json.template)

Then create a pull request with these 3 changes.

Check out an example for the latest theme PoP in https://github.com/yakyak/yakyak/pull/951/files
