### ISSUE TITLE
Emoji Problems :)

### ISSUE THREAD

**Issue by mliq** [yakyak/yakyak#954]
When using YakYak, typing `:)` appears as ☺, but shows to Google Hangouts users as ![image](https://user-images.githubusercontent.com/7573605/44669733-5e08b000-a9e6-11e8-9800-360c8c553a75.png).

Expected behavior would be to show ![image](https://user-images.githubusercontent.com/7573605/44669767-77116100-a9e6-11e8-88eb-8e845a34f1bf.png) in both Hangouts and YakYak. 

When a Hangouts user types `:)` it does appear correctly in YakYak as ![image](https://user-images.githubusercontent.com/7573605/44669767-77116100-a9e6-11e8-88eb-8e845a34f1bf.png).

Might relate to #562.

**Comment by elkinjosetm** [comment]
I've fixed it by replacing the shortcut for **:)** and **:-)** in `emojishortcode.js` with this:

```
":)": "\ud83d\ude0a",
":-)": "\ud83d\ude0a",
```

On Mac, the path to the file is: `/Applications/YakYak.app/Contents/Resources/app/ui/emojishortcode.js`

After the change, you just need to restart YakYak.

Hope it works.

**Comment by stealthybox** [comment]
this is the proper UTF-16 codepoint for "slightly smiling face" 🙂:
\ud83d\ude42
https://codepoints.net/U+1F642?lang=en

**Comment by averissimo** [comment]
should be available in v1.5.2 when travis finishes with the building process

thanks guys!
