### ISSUE TITLE
Error running Yakyak on 32bit Windows 7

### ISSUE THREAD

**Issue by andyg2** [yakyak/yakyak#955]
After installing Yakyak ok I get an error regarding the compatibility with the OS.

> The version of this file is not compatible with the version of Windows you're running. Check you computer system information to see whether you need an x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher

I've seen on [unrelated sites](https://support.na.sage.com/selfservice/viewContent.do?externalId=25543&sliceId=1) this may not be related directly with 32bit compatibility, is there anything I can do to fix this for Yakyak?

**Comment by averissimo** [comment]
Sorry to hear about this :\ I'm guessing this is an upstream decision from electron.

Apart from small API calls specific to linux/osx/windows in general we don't have any control in version limitations.
