### ISSUE TITLE
Bugged tray icon in KDE

### ISSUE THREAD

**Issue by arcooke** [yakyak/yakyak#956]
Very minor issue, but yakyak has a strange funnel-shaped tray icon in kde.  I'm on KDE Neon bionic testing right now.  I used the 1.5.1 prebuilt deb package.

![](https://i.imgur.com/3SQ0ei1.jpg)

The normal application launcher icon is fine, it's only a problem in the tray.

![](https://i.imgur.com/PB4pIQL.jpg)

**Comment by averissimo** [comment]
try the latest version, it should have fixed with a temporary workaround until chromium is updated in electron
