### ISSUE TITLE
Noob Issue - how to install on Windows?

### ISSUE THREAD

**Issue by kinneyja** [yakyak/yakyak#957]
Hi apologies this is a noob question but once I have downloaded and extracted in windows how do I actually install the program? I see on the read me it just mentions to Install It but no step-by-step?

**Comment by eliaspizarro** [comment]
1.- download
2.- two left clicks over yakyak.exe

**Comment by kinneyja** [comment]
Hey so that is the trouble, I downloaded the repo and unzip it but do not see any .exe file inside...?
