### ISSUE TITLE
Is there a command line interface so I can programmatically send messages?

### ISSUE THREAD

**Issue by agent00w** [yakyak/yakyak#958]
Is there a command line interface so I can programmatically send messages?

**Comment by averissimo** [comment]
Programmatically yakyak uses yakyak/hangupsjs

There is a command line interface https://github.com/tdryer/hangups/ (in python)

**Comment by agent00w** [comment]
I cannot get hang up to compile, that is how I found your project. Please share how to send an SMS with command line.

**Comment by averissimo** [comment]
not possible with yakyak

you'll have to check https://github.com/yakyak/hangupsjs
