### ISSUE TITLE
Outdated Emojis

### ISSUE THREAD

**Issue by KevDoy** [yakyak/yakyak#960]
It appears that YakYak is still using the old Google emojis and there have been a few updates since then, not just visually, but in the amount of emojis. It appears that I can't select new ones, and ones that are not on yakyak are displayed either as broken or pulls it from the system's font library.

**Comment by averissimo** [comment]
You pull request was merged, is there any more actions required?

Maybe the `views/emojicategories.coffee` needs to be updated with the new emojis.

**Comment by KevDoy** [comment]
I imagine that emojicategories.coffee is the directory used for users to point and click at the emojis they want to send. So for this to work, it theoretically doesn't need to be updated for the new emojis to show up in conversation, but will need to updated for the directory eventually.

**Comment by neico** [comment]
In fact both `src/ui/emojishortcode.coffee` and `src/ui/views/emojicategories.coffee` need a update to reflect the latest emoji's
[This](https://unicode.org/Public/emoji/12.0/emoji-test.txt) seems to be the most complete list of: https://unicode.org/emoji/charts/emoji-list.html

It would be really great if those could be updated for the next release, as I've stumbled upon some missing ones quite a few times now (goes to show how much used I am to having those lists in discord by now..)
