### ISSUE TITLE
arm64 release .. 

### ISSUE THREAD

**Issue by necrose99** [yakyak/yakyak#962]
useful as i have a few 4 gig arm64 nodes and or servers on arm64...

**Comment by averissimo** [comment]
Dependent on this bug: https://github.com/electron/electron/issues/5706

As electron does not support arm64

**Comment by necrose99** [comment]
Thier are binary electron releases , for arm64.. gentoo elselect electron
can pick versions..

Granted a few more monitors , or kvm for amd64 hosts ,
but as a convince arm64 for working on that system for extended periods not
via ssh..

**Comment by averissimo** [comment]
Ohh so it can be supoprted, can you create a pull request build an arm binary?

We'll be more than happy to merge it!!

**Comment by necrose99** [comment]
**https://github.com/electron/electron/releases/download/v9.3.4/electron-v9.3.4-linux-arm64.zip**
https://github.com/Zerx0r/Kage/issues/21  ,

kage builds on rpi64 Gentoo..  with a bit of hacking to json file as mentioned. in **[#21](https://github.com/Zerx0r/Kage/issues/21)** 

Rasberrypi-OS now offers 64bit images. 

the mentioning also can build arm7hf via the electron builder.  ie in iss.21 on kage. 

```
yarn run build --linux --arm64 --armv7l , -mwl also works apparently

(https://www.electron.build/multi-platform-build )

electron-builder -mwl / yarn run build -mwl outputs even a macos pkg...
--linux --arm64 --armv7l

```
