### ISSUE TITLE
No package.json?

### ISSUE THREAD

**Issue by abelardolg** [yakyak/yakyak#966]
Hi,
Missing package.json? : 
npm WARN saveError ENOENT: no such file or directory, open '...\yakyak-1.5.1-win32-x64\yakyak-win32-x64\package.json'
npm WARN enoent ENOENT: no such file or directory, open '...\yakyak-1.5.1-win32-x64\yakyak-win32-x64\package.json'
npm WARN yakyak-win32-x64 No description
npm WARN yakyak-win32-x64 No repository field.
npm WARN yakyak-win32-x64 No README data
npm WARN yakyak-win32-x64 No license field.

YakYak version: latest.
Node version: 10.10.0
OS Version: Windows 10 Pro
NPM Version: 6.4.1

Best regards.

**Comment by abelardolg** [comment]
Anybody there?

**Comment by averissimo** [comment]
are you running from source? as in `npm start` ?

or just the release tarball?
