### ISSUE TITLE
Left click on icon in tray bar does not open yakyak 

### ISSUE THREAD

**Issue by capcla** [yakyak/yakyak#972]
When yakyak is closed in tray bar, it can not opened by click on the icon.
For open the window of the program I must use the right click on the icon in tray bar and then on Toggle window show/hide.

I use yakyak v1.5.2 ad lxqt on debian testing

**Comment by averissimo** [comment]
I don't think this is possible anymore on linux, at least for systems that use appindicator

> When app indicator is used on Linux, the click event is ignored.

https://github.com/electron/electron/blob/master/docs/api/tray.md

We depend on electron for this functionality

**Comment by capcla** [comment]
Excuse me, but this problem there is not in v1.5.1.
Is the version of electron upgraded in v1.5.2?

**Comment by averissimo** [comment]
yes to v3.0.*

If you can find a workaround I'll be happy to merge or try to integrate

**Comment by capcla** [comment]
Ok, thanks
