### ISSUE TITLE
homebrew checksum mismatch for 1.5.2

### ISSUE THREAD

**Issue by travi** [yakyak/yakyak#973]
`brew cask outdated` showed that i was behind, so i tried to get updated to 1.5.2. however, i get a checksum mismatch error:

```
Expected: 896463e6f1c73e97575e3570f4058619400202b51ebbb6c8aaa6cc9605f6cc34
Actual:   1297446662a5efd5b6d7bfb4891cd2b8ce183993e6ba033648f7758eca852b15
```

possibly related to https://github.com/yakyak/yakyak/issues/550?

**Comment by averissimo** [comment]
It is.

In pre-releases we update the same version over and over until it is ready for "official" release, which is what is causing this error.

Anyway, I have no idea what is the standard for homebrew and disclosed the situation in the pull request https://github.com/Homebrew/homebrew-cask/pull/53105

**Comment by travi** [comment]
thanks for the quick response. i'll keep an eye on progress. 

now to figure out if i can get cask to install 1.5.1 for me :\

**Comment by travi** [comment]
just out of curiosity, is there a reason you prefer to reuse the same pre-release number over and over rather than something like `1.5.2-alpha`/`1.5.2-alpha.2`? i use this approach with npm package pre-releases so that each published release, including pre-releases is always relatable to a specific git tag. 

seems like it could help avoid issues like this here, as well?

**Comment by suschizu** [comment]
@averissimo - just made a cask-repair to v1.5.1 - sorry I've overseen the prerelease-notification

**Comment by averissimo** [comment]
Thanks  @suschizu!!

This might have started a discussion to avoid any confusions by introducing some kind of rolling suffix to the pre-releases

**Comment by averissimo** [comment]
@travi 

It would definitely avoid these issues!!

We don't have a fixed release schedule or even a semi-formal one, as when there are updates merge to master we usually update the "alpha" release.

I'm guessing the main argument for using this strategy is to de-clutter the releases page. Every tag we create generates all packages.

@davibe any thoughts on this?

**Comment by travi** [comment]
not trying to suggest how to coordinate your process, but sharing in case it is useful: i tend to keep `master` for stable releases and handle pre-releases on a branch, merging the branch to master once i consider it stable. that way `master` is also clean in case i need to slip a bug fix in before the next bigger release is ready.

**Comment by travi** [comment]
since https://github.com/Homebrew/homebrew-cask/pull/53229 got merged, i can confirm i was able to install through brew cask again. thanks for the quick resolution everyone!

i would close the issue, but since there is some conversation around preventing this issue in the future, i'll leave it open for the team to close based on that.

**Comment by varystargaryen** [comment]
Still exists with the updated version of 1.5.2, that fixes the connection to Hangouts issue.
'''
~ $ brew cask install yakyak                 
==> Satisfying dependencies
==> Downloading https://github.com/yakyak/yakyak/releases/download/v1.5.2/yakyak-
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'yakyak'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'yakyak' does not match.

Expected: bdeae777191394e21ec089b856eaca805583d70213f6f03e36d33833bcbc41f2
Actual:   84e8a6068eb2e2be0c56b14804e8ffa02cf10e7c53ee71758cd542028cccfc2f
File:     /Users/digvijayjani/Library/Caches/Homebrew/downloads/f4bf9c402112862a99e54a227c0396f00a157586e3bc9fc06218093e658210b2--yakyak-1.5.2-osx.zip

To retry an incomplete download, remove the file above.
'''

**Comment by travi** [comment]
i opened a [PR against homebrew-cask](https://github.com/Homebrew/homebrew-cask/pull/54146) by running `cask-repair`, but since that version already existed, the [build fails since the SHA changed in the PR without a version change](https://travis-ci.org/Homebrew/homebrew-cask/builds/446752924#L490). 

looks like there [are steps defined](https://github.com/Homebrew/homebrew-cask/pull/54146) for this situation. could we get a maintainer to publically confirm the [new checksum](https://github.com/Homebrew/homebrew-cask/pull/54146/files)?

**Comment by travi** [comment]
closed by https://github.com/Homebrew/homebrew-cask/pull/54151
