### ISSUE TITLE
Extra window titlebar now visible on macOS in v1.5.2

### ISSUE THREAD

**Issue by cgatesman** [yakyak/yakyak#976]
After upgrading from 1.5.1 to 1.5.2, Yakyak now has an extra visible native title bar in macOS Mojave:

<img width="1052" alt="screen shot 2018-10-21 at 12 56 07 pm" src="https://user-images.githubusercontent.com/6276072/47269848-51f62600-d531-11e8-9f61-75a3a0936a41.png">

**Comment by varystargaryen** [comment]
Same issue present on 1.5.2 while running macOS Mojave Version 10.14.1 Beta (18B67a).
![image](https://user-images.githubusercontent.com/16640749/47307988-419f8300-d5e5-11e8-8fb3-273bdd913457.png)

**Comment by zanthorn** [comment]
I have the same issue on Mojave.

**Comment by edraven** [comment]
Same with 1.5.2 on High Sierra

**Comment by StevenSeiden** [comment]
I am also experiencing this on macOS Mojave.
