### ISSUE TITLE
SnoreToast Firing, but Notifications Not Displayed

### ISSUE THREAD

**Issue by 0-SamboNZ-0** [yakyak/yakyak#984]
YakYak v1.52 ia32
Windows 10 Pro x64 Build 1809 (fresh install)

YakYak is generally working fine for me, however when I get a new message there is no notification popup displayed (despite this option being enabled).

SnoreToast.exe appears to be firing as there is an accumulation of these processes in my process list.

Performing a simple test using the following command yields no message displayed:
SnoreToast.exe" -m "test" -t "test"

Adding a '-w' switch results in the same behaviour as from YakYak (ie; a latent SnoreToast.exe process)

Anyone have any ideas why this may be happening?

**Comment by 0-SamboNZ-0** [comment]
No change in behaviour with the latest build unfortunately.  

None of those existing issues describe my problem.

**Comment by 0-SamboNZ-0** [comment]
Anyone got any more ideas?

**Comment by 0-SamboNZ-0** [comment]
Well, without any further suggestions on how to resolve this issue I'm afraid I have no choice but to uninstall YayYak and use something else because this is a real deal breaker for me.

This is a pity because I quite like it!

**Comment by averissimo** [comment]
Sorry to hear, we need a developer/volunteer that uses windows to figure this out.

**Comment by 0-SamboNZ-0** [comment]
I'd be more than happy to volunteer if you need someone to test, but I have no real dev skills.

**Comment by 0-SamboNZ-0** [comment]
As mentioned, I tried executing SnoreToast directly, but I was unable to get a message to popup correctly.
