### ISSUE TITLE
Hangs on "Connecting"

### ISSUE THREAD

**Issue by jasongorst** [yakyak/yakyak#986]
YakYak stopped updating my conversations yesterday, and after restarting it hangs on Connecting. I deleted the Application Support folder and signed back in, but it's still hung up. I checked with a colleague and after closing the app and restarting, he's also stuck on Connecting. Anyone else seeing this?

**Comment by fulltrucker** [comment]
[v1.5.2](https://github.com/yakyak/yakyak/releases/tag/v1.5.2) went from pre-release to release today, and includes fixes for what you are likely experiencing. Several folks reported this over the last couple of days, all of those reports can be viewed in the "[closed issues](https://github.com/yakyak/yakyak/issues?q=is%3Aissue+is%3Aclosed)".

Visit the [releases](https://github.com/yakyak/yakyak/releases) page to download the new v1.5.2 binary for your system.

**Comment by jasongorst** [comment]
Confirmed that it's fixed in the release version. Thanks.
