### ISSUE TITLE
Left mouse click on tray icon gives the right click's menu, instead of opening yakyak

### ISSUE THREAD

**Issue by kli0rf** [yakyak/yakyak#989]
Left click on the tray icon gives the same menu as the right click, so no way to open the messenger from the tray by double clickling.
Fedora 29 beta x64, TopIcons Plus gnome extension, yakyak-1.5.2-linux-x86_64.rpm.

That doesn't happen on Win7 x64 using yakyak-1.5.2-win32-x64.zip.

**Comment by pajew** [comment]
From this menu Minimize to try opens app window.

**Comment by kli0rf** [comment]
@pajew I ain't sure i get what you mean, but the problem is entirely with the left mouse click. It works now just as the right click - opens the right click menus. So i need to use 'toggle window show / hide' from the menu of tray icon if i want it open, which is rather inconvenient.
I'd say if there's no way to fix it quickly, it'd be better to disable left click tray menu completely until the fix is available, instead of making it work same ar right click.

**Comment by averissimo** [comment]
I think this is the case when appindicator is used under Linux, see https://github.com/electron/electron/blob/master/docs/api/tray.md

> When app indicator is used on Linux, the click event is ignored.

**Comment by kli0rf** [comment]
@averissimo Any workarounds yet?

**Comment by kli0rf** [comment]
@averissimo Any workarounds? It's really annoying... :/

**Comment by kli0rf** [comment]
Guys, seriously? No fixes for this one?

**Comment by ztoben** [comment]
@kli0rf, This is a regression within Electron itself, there is no 'fix' or workaround at the yakyak level.

https://github.com/electron/electron/issues/14941

**Comment by kli0rf** [comment]
@ztoben hmm, but skype, for example, still works the right way. Does it use the older Electron then? Perhaps yakyak could do the same?

**Comment by ztoben** [comment]
@kli0rf, it seems to be a regression in electron versions >2. Downgrading would probably lose other major features and wouldn't be as simple as just swapping out the version unfortunately. You can keep this issue open until it's fixed upstream, but I think you'd be better off filing an issue on the electron github.
