### ISSUE TITLE
[Mac] Tray icon displays "YakYak - Hangouts Client" text

### ISSUE THREAD

**Issue by Stanko** [yakyak/yakyak#990]
See the screenshot:

<img width="280" alt="screenshot 2018-10-28 15 00 26" src="https://user-images.githubusercontent.com/776788/47616867-7b2f2d00-dac2-11e8-8515-8b51eb97c03a.png">

YakYak icon now takes huge amount of space in tray. 

It seems this change introduced it.
https://github.com/yakyak/yakyak/commit/f666a6ec07dffd48a3eea3f8e428d30dc0e98153#diff-590c38cfd8688fbb56b04872bbe497e8R35

If there is a similar issue opened (I couldn't find one) feel free to close this one.

Thank you!

EDIT: quick hack is to edit this file:
```
/Applications/YakYak.app/Contents/Resources/app/ui/views/trayicon.js
```
comment out line 51
```js
tray.setTitle(i18n.__('title:YakYak - Hangouts Client'));
```

and restart YakYak.

Tested on HighSierra 10.13.6 and YakYak 1.5.2

**Comment by socketbox** [comment]
Odd, but this doesn't work for me; I'm on High Sierra 10.13.6. I tried killing the app and moving or removing these directories:

-  `~/Library/Application Support/yakyak`
- `/private/var/db/BootCaches/<some long guid>/app.com.github.yakyak.playlist`
- `/Users/chb/Library/Saved Application State/com.github.yakyak.savedState` 

But even though the file that you mention is altered accordingly, it still has that absurdly long title

**Comment by jessecarbon** [comment]
Bummer this didn't make it to 1.5.3

**Comment by jessejoe** [comment]
Looks like this didn't make it to 1.5.3, any reason you didn't submit a PR @Stanko? I'd be happy to if you don't.

**Comment by Stanko** [comment]
Well I thought it was added for accessibility, so I didn't want to break something else.

**Comment by jessejoe** [comment]
@averissimo any thoughts? Seems like a pretty nonstandard change, maybe it could be an option?

**Comment by averissimo** [comment]
My bad!! Did not know this had such an impact on OSX.

@Stanko can you put that on a pull request?

**Comment by averissimo** [comment]
This was not out of the blue, it was a misguided attempt as the tray icon was having 'electron' title on linux distributions.

I really believed I didn't commit this change.

**Comment by timgilbert** [comment]
Any chance of a release including this fix? It's still pretty annoying on Macs...
