### ISSUE TITLE
yakyak crash: The "url" argument must be of type string, received type object

### ISSUE THREAD

**Issue by clearscreen** [yakyak/yakyak#993]
Currently yakyak will crash irrecoverably when selecting a "bad" chat. I've narrowed this down to loading a specific group chat with 100% reproducibility. When I select the specific chat it crashes, and on each subsequent relaunch it will continue crashing until i select a different chat.

Here's what I see in the Inspector:

`url.js:150 Uncaught NodeError: The "url" argument must be of type string. Received type object`
`    at Url.parse (url.js:150:11)`
`    at Object.urlParse [as parse] (url.js:144:13)`
`    at getImageUrl (C:\Users\clear\Downloads\yakyak-1.5.2-win32-x64\yakyak-win32-x64\resources\app\ui\util.js:239:18)`
`    at formatters (C:\Users\clear\Downloads\yakyak-1.5.2-win32-x64\yakyak-win32-x64\resources\app\ui\views\messages.js:546:18)`
`    at C:\Users\clear\Downloads\yakyak-1.5.2-win32-x64\yakyak-win32-x64\resources\app\ui\views\messages.js:503:16`
`    at Array.forEach (<anonymous>)`
`    at format (C:\Users\clear\Downloads\yakyak-1.5.2-win32-x64\yakyak-win32-x64\resources\app\ui\views\messages.js:502:18)`
`    at C:\Users\clear\Downloads\yakyak-1.5.2-win32-x64\yakyak-win32-x64\resources\app\ui\views\messages.js:408:9`
`    at unnest (C:\Users\clear\Downloads\yakyak-1.5.2-win32-x64\yakyak-win32-x64\resources\app\node_modules\tagg\lib\tagg.js:89:29)`
`    at tagf (C:\Users\clear\Downloads\yakyak-1.5.2-win32-x64\yakyak-win32-x64\resources\app\node_modules\tagg\lib\tagg.js:125:9)`
`app.coffee:153 Possible fatal error on main process, YakYak could stop working as expected. Object`

**Comment by clearscreen** [comment]
The following coffeescript produces different javascript in yakyak's version 1.5.2 win x64 build.
```
isImg = (url) -> url?.match /\.(png|jpe?g|gif|svg)$/i

getImageUrl = (url="") ->
    return url if isImg url
    parsed = URL.parse url, true
    url = parsed.query.q
    return url if isImg url
    false
```

yakyak 1.5.2 util.js snippet from extracted 1.5.2 win32 x64 release
```
  isImg = function(url) {
    return url != null ? url.match(/\.(png|jpe?g|gif|svg)$/i) : void 0;
  };
  
  getImageUrl = function(url = "") {
    var parsed;
    if (isImg(url)) {
      return url;
    }
    parsed = URL.parse(url, true);
    url = parsed.query.q;
    if (isImg(url)) {
      return url;
    }
    return false;
  };

```  
yakyak 1.4.3 util.js snippet from extracted 1.4.3 win32 x64 release
```
  isImg = function(url) {
    return url != null ? url.match(/\.(png|jpe?g|gif|svg)$/i) : void 0;
  };

  getImageUrl = function(url) {
    var parsed;
    if (url == null) {
      url = "";
    }
    if (isImg(url)) {
      return url;
    }
    parsed = URL.parse(url, true);
    url = parsed.query.q;
    if (isImg(url)) {
      return url;
    }
    return false;
  };
  
```

As you can see above, version 1.4.3 has the following code which checks if the url equals null and sets it to an empty string if it does. 
```
    if (url == null) {
      url = "";
    }
```
Version 1.5.2 is missing this for some reason. I am unsure what changed in CoffeeScript but the fix probably lies in figuring that out. I guess the real fix might be making the ternary operator for isImg not return an object (void 0???), but I am unsure if that would be "correct."

For anyone reading this wanting a quick fix, in your extracted yakyak-1.5.2-win32-x64 directory open resources\app\ui\util.js and add
	` if (url == null) return false;`
after line 235 so your new getImageUrl function appears as follows

```
  getImageUrl = function(url = "") {
    var parsed;
    if (url == null) return false;
    if (isImg(url)) {
      return url;
    }
    parsed = URL.parse(url, true);
    url = parsed.query.q;
    if (isImg(url)) {
      return url;
    }
    return false;
  };
  
```
save your edit to util.js, relaunch yakyak, and you're good to go.

**Comment by averissimo** [comment]
can you create a pull request with this change?

**Comment by averissimo** [comment]
Can you test the new pre-release v1.5.3-beta-rolling to see if your suggestion fixes the issue?

Thanks
