### ISSUE TITLE
yakyak don't conect

### ISSUE THREAD

**Issue by TrinoBianco** [yakyak/yakyak#994]
new google update and yakyak don't connect 
reproduced in Ubuntu 16.04 and Windows 10 last update, Tell me how to fix it?
![1234](https://user-images.githubusercontent.com/44569236/47684954-6e532c00-dbdd-11e8-8a48-7766db28d434.JPG)
![5432](https://user-images.githubusercontent.com/44569236/47684959-73b07680-dbdd-11e8-88e8-6ef28d78a16c.JPG)

reconnecting 1
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed TypeError: Cannot read property 'length' of undefined
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error connecting TypeError: Cannot read property 'length' of undefined
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)

yakyak
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed TypeError: Cannot read property 'length' of undefined
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error connecting TypeError: Cannot read property 'length' of undefined
    at /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js:125:21
    at _fulfilled (/opt/yakyak/resources/app/node_modules/q/q.js:854:54)
    at /opt/yakyak/resources/app/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/opt/yakyak/resources/app/node_modules/q/q.js:816:13)
    at /opt/yakyak/resources/app/node_modules/q/q.js:570:49
    at runSingle (/opt/yakyak/resources/app/node_modules/q/q.js:137:13)
    at flush (/opt/yakyak/resources/app/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by maglax** [comment]
Seems like a duplicate of #988 and #991(Which itself is a duplicate of #988).

**Comment by TrinoBianco** [comment]
Deleting ~/.config/yakyak didn't work for me either. Even after a fresh deb install from root. After the authentication procedure I get the same error again.

**Comment by averissimo** [comment]
I'm not able to reproduce this, is it still happening for you guys?

**Comment by TrinoBianco** [comment]
yes  this problem is actual, I use yakyak in work, it is very lacking for monitoring alerts, would be very grateful if there is a solution how to fix it

**Comment by averissimo** [comment]
Can you replace the if statement in line 125 of file `/opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js` with:

```
if (typeof d !== "undefined" && d !== null ? d.length : void 0) {
```

And see if it fixes it

**Comment by TrinoBianco** [comment]
I replaced  125 line 
if (typeof d !== "undefined" && d !== null ? d.length : void 0) {

in my console 
-------------------------------------
:/opt/yakyak# yakyak
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connected 0
-------------------------------
passed authorization and started the program window but there is no information

![yak](https://user-images.githubusercontent.com/44569236/47798035-3ad4e680-dd30-11e8-8fa2-597399c3af87.png)

**Comment by averissimo** [comment]
Can you open the console Ctrl + Alt + I and see if there is an error

**Comment by TrinoBianco** [comment]
yes I opened the console but there are no errors

![yakyak 1](https://user-images.githubusercontent.com/44569236/47817065-5f938300-dd5d-11e8-80a9-0e95438cc78b.JPG)
![yakyak 2](https://user-images.githubusercontent.com/44569236/47817069-63bfa080-dd5d-11e8-9254-795812fdf699.JPG)

**Comment by TrinoBianco** [comment]
https://github.com/yakyak/yakyak/releases/tag/v1.5.3-beta-rolling
https://github.com/yakyak/yakyak/releases/download/v1.5.3-beta-rolling/yakyak-1.5.2-linux-amd64.deb
start with replace  
line 125 of file /opt/yakyak/resources/app/node_modules/hangupsjs/lib/init.js with:

if (typeof d !== "undefined" && d !== null ? d.length : void 0) {
from if (d.length) {
-----------------------------------------------------
running and notifications come in a pop-up window, but the program itself doesn’t display data either

**Comment by TrinoBianco** [comment]
https://github.com/yakyak/yakyak/releases

**Comment by averissimo** [comment]
Hummm, but that does not have the fix you described above.

**Comment by TrinoBianco** [comment]
and yet this version works ...
