### ISSUE TITLE
re-releasing version 1.5.2

### ISSUE THREAD

**Issue by r0bnewt0n** [yakyak/yakyak#995]
Hi,
Thanks for your work on YakYak.
I notice in the closed issues that a previously released version 1.5.2 was re-released with a patch to fix the recent problem with Google changing their API.
When I go to the Releases section I see that 1.5.2 was released 27 days ago, and there is no mention of this patch.  People waiting for a fix may assume that none is available?  Wouldn't it be better to release a new version 1.5.3 with the patch?

**Comment by eacmen** [comment]
I assumed none was available. If 1.5.2 is in fact patched that is very confusing.

**Comment by eacmen** [comment]
> I assumed none was available. If 1.5.2 is in fact patched that is very confusing.

For all that are wondering 1.5.2 is actually a patched version and was re-released recently but github still says it was released 27 days ago. Very happy to get YakYak working again, very sad that I was checking for updates every day and it was probably updated but I never knew.

**Comment by lparsons** [comment]
I noticed that the [Snap package](https://snapcraft.io/yakyak) is not yet updated. Is there some way to make that happen?

**Comment by llorllale** [comment]
wow... I had been waiting for days and never knew.

**Comment by averissimo** [comment]
We will be changing the way we release versions, with the pre-release version having a suffix to denote that is still unstable/master/nightly/something else.

And the actual stable releases being created at the release time.

Hopefully this will avoid future confusion, especially with so many community maintained packages (homebrew, snap, ...)

**Comment by r0bnewt0n** [comment]
@averissimo So with the latest google API change (31st October), when you have a patch for it, will you release a stable release called 1.5.3?  (This could be based on either 1.5.2 with the patch applied, or the unstable/master with the patch appled if you think the unstable/master is now stable enough?)

**Comment by averissimo** [comment]
Yes, it was released yesterday.

Up until now the master/unstable releases are just a temporary state waiting for enough patches to be contributed or enough time to pass until releasing as a stable release.

The current rhythm of yakyak is on maintenance mode and small increments. Not many breaking changes happening from the community. There's a redesign effort started a while ago, but no one coded for it yet :(
